package tablenames

// C is the C table backend (internal/codegen/ctable). It carries the
// widest surface of the six, and for one reason: C has no namespace to
// put a runtime in and no nested scope to hide one in, so every spelling
// the others can scope away is a unit-level name here. Everything a
// consumer never types is spelled schema_<package>_..._ instead and claims
// nothing (internal/codegen/ctable's `sym`); what is left is what a
// consumer reads and writes.
const C Backend = 1 << 5

func init() {
	define(C,
		Name{Name: "table_retain_known", What: "the C retention runtime"},
		Name{Name: "TableRetain", What: "the C retention runtime"},
		Name{Name: "TableRetainId", What: "the C retention runtime"},
		Name{Name: "TableRetainIds", What: "the C retention runtime"},
		Name{Name: "TableRetainIn", What: "the C retention runtime"},
		Name{Name: "TableRetainMessage", What: "the C retention runtime"},
		Name{Name: "TableRetainOut", What: "the C retention runtime"},
		Name{Name: "TableRetainPath", What: "the C retention runtime"},
		Name{Name: "TableRetainSaveNode", What: "the C retention runtime"},
		Name{Name: "TableRetainStep", What: "the C retention runtime"},
		Name{Name: "TableRetainWalk", What: "the C retention runtime"},
		Name{Name: "table_retain_at", What: "the C retention runtime"},
		Name{Name: "table_retain_begin", What: "the C retention runtime"},
		Name{Name: "table_retain_capture", What: "the C retention runtime"},
		Name{Name: "table_retain_clear_placed", What: "the C retention runtime"},
		Name{Name: "table_retain_commit", What: "the C retention runtime"},
		Name{Name: "table_retain_count_lost", What: "the C retention runtime"},
		Name{Name: "table_retain_discard", What: "the C retention runtime"},
		Name{Name: "table_retain_finish", What: "the C retention runtime"},
		Name{Name: "table_retain_graph_save", What: "the C retention runtime"},
		Name{Name: "table_retain_here", What: "the C retention runtime"},
		Name{Name: "table_retain_id", What: "the C retention runtime"},
		Name{Name: "table_retain_in_content", What: "the C retention runtime"},
		Name{Name: "table_retain_in_frame", What: "the C retention runtime"},
		Name{Name: "table_retain_in_payload", What: "the C retention runtime"},
		Name{Name: "table_retain_in_ref", What: "the C retention runtime"},
		Name{Name: "table_retain_index", What: "the C retention runtime"},
		Name{Name: "table_retain_leb", What: "the C retention runtime"},
		Name{Name: "table_retain_leb_bytes", What: "the C retention runtime"},
		Name{Name: "table_retain_message_capture", What: "the C retention runtime"},
		Name{Name: "table_retain_message_content", What: "the C retention runtime"},
		Name{Name: "table_retain_message_frame", What: "the C retention runtime"},
		Name{Name: "table_retain_message_opaque", What: "the C retention runtime"},
		Name{Name: "table_retain_message_payload", What: "the C retention runtime"},
		Name{Name: "table_retain_message_scalar", What: "the C retention runtime"},
		Name{Name: "table_retain_nameable", What: "the C retention runtime"},
		Name{Name: "table_retain_out_content", What: "the C retention runtime"},
		Name{Name: "table_retain_out_frame", What: "the C retention runtime"},
		Name{Name: "table_retain_out_leb", What: "the C retention runtime"},
		Name{Name: "table_retain_out_leb_read", What: "the C retention runtime"},
		Name{Name: "table_retain_out_payload", What: "the C retention runtime"},
		Name{Name: "table_retain_out_raw", What: "the C retention runtime"},
		Name{Name: "table_retain_out_ref", What: "the C retention runtime"},
		Name{Name: "table_retain_payload", What: "the C retention runtime"},
		Name{Name: "table_retain_probe", What: "the C retention runtime"},
		Name{Name: "table_retain_put32", What: "the C retention runtime"},
		Name{Name: "table_retain_put64", What: "the C retention runtime"},
		Name{Name: "table_retain_raw", What: "the C retention runtime"},
		Name{Name: "table_retain_record_measure", What: "the C retention runtime"},
		Name{Name: "table_retain_records", What: "the C retention runtime"},
		Name{Name: "table_retain_ref", What: "the C retention runtime"},
		Name{Name: "table_retain_reserved", What: "the C retention runtime"},
		Name{Name: "table_retain_reset", What: "the C retention runtime"},
		Name{Name: "table_retain_rewind", What: "the C retention runtime"},
		Name{Name: "table_retain_root", What: "the C retention runtime"},
		Name{Name: "table_retain_step", What: "the C retention runtime"},
		Name{Name: "table_retain_tail", What: "the C retention runtime"},
		Name{Name: "table_retain_truncate", What: "the C retention runtime"},
		Name{Name: "table_retain_u32", What: "the C retention runtime"},
		Name{Name: "table_retain_u64", What: "the C retention runtime"},
		Name{Name: "table_retain_under", What: "the C retention runtime"},
		Name{Name: "table_retain_width", What: "the C retention runtime"},
		Name{Name: "table_retain_writer_id", What: "the C retention runtime"},

		Name{Name: "TableBitReader", What: "the C message and announcement runtime"},
		Name{Name: "TableBitWriter", What: "the C message and announcement runtime"},
		Name{Name: "TableMessageEntry", What: "the C message and announcement runtime"},
		Name{Name: "TableMessageReader", What: "the C message and announcement runtime"},
		Name{Name: "TableMessageShapeFacts", What: "the C message and announcement runtime"},
		Name{Name: "TableVocabulary", What: "the C message and announcement runtime"},
		Name{Name: "announce", What: "the C message and announcement runtime"},
		Name{Name: "announce_measure", What: "the C message and announcement runtime"},
		Name{Name: "announce_read", What: "the C message and announcement runtime"},
		Name{Name: "kTableAnnounce", What: "the C message and announcement runtime"},
		Name{Name: "kTableAnnounceBytes", What: "the C message and announcement runtime"},
		Name{Name: "kTableMessageBatchMax", What: "the C message and announcement runtime"},
		Name{Name: "kTableMessageEntriesHere", What: "the C message and announcement runtime"},
		Name{Name: "kTableMessageRefBitsHere", What: "the C message and announcement runtime"},
		Name{Name: "table_announce_once", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_align_read", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_align_write", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_get", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_getbytes", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_has", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_put", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_putbytes", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_reader", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_skip", What: "the C message and announcement runtime"},
		Name{Name: "table_bit_writer", What: "the C message and announcement runtime"},
		Name{Name: "table_bits_required", What: "the C message and announcement runtime"},
		Name{Name: "table_message_blob_scan", What: "the C message and announcement runtime"},
		Name{Name: "table_message_close", What: "the C message and announcement runtime"},
		Name{Name: "table_message_count", What: "the C message and announcement runtime"},
		Name{Name: "table_message_dequantize", What: "the C message and announcement runtime"},
		Name{Name: "table_message_element", What: "the C message and announcement runtime"},
		Name{Name: "table_message_entry_read", What: "the C message and announcement runtime"},
		Name{Name: "table_message_fixed_kind", What: "the C message and announcement runtime"},
		Name{Name: "table_message_float", What: "the C message and announcement runtime"},
		Name{Name: "table_message_integer_kind", What: "the C message and announcement runtime"},
		Name{Name: "table_message_kind_bits", What: "the C message and announcement runtime"},
		Name{Name: "table_message_known_kind", What: "the C message and announcement runtime"},
		Name{Name: "table_message_leb", What: "the C message and announcement runtime"},
		Name{Name: "table_message_nodes_open", What: "the C message and announcement runtime"},
		Name{Name: "table_message_number", What: "the C message and announcement runtime"},
		Name{Name: "table_message_open", What: "the C message and announcement runtime"},
		Name{Name: "table_message_quantization", What: "the C message and announcement runtime"},
		Name{Name: "table_message_quantize", What: "the C message and announcement runtime"},
		Name{Name: "table_message_ref", What: "the C message and announcement runtime"},
		Name{Name: "table_message_shape_read", What: "the C message and announcement runtime"},
		Name{Name: "table_message_skip", What: "the C message and announcement runtime"},
		Name{Name: "table_message_skip_body", What: "the C message and announcement runtime"},
		Name{Name: "table_message_skip_run", What: "the C message and announcement runtime"},
		Name{Name: "table_message_value_bits", What: "the C message and announcement runtime"},
		Name{Name: "table_vocabulary", What: "the C message and announcement runtime"},

		Name{Name: "TableMapKey", What: "the C list, map and node-extent runtime"},
		Name{Name: "TableSequence", What: "the C list, map and node-extent runtime"},
		Name{Name: "TableSequenceCompare", What: "the C list, map and node-extent runtime"},
		Name{Name: "TableSequenceCursor", What: "the C list, map and node-extent runtime"},
		Name{Name: "TableSequenceFill", What: "the C list, map and node-extent runtime"},
		Name{Name: "TableSequenceHead", What: "the C list, map and node-extent runtime"},
		Name{Name: "TableSequenceOrder", What: "the C list, map and node-extent runtime"},
		Name{Name: "TableSequenceSegment", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_extent_reserve", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_json_interpret_exact", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_json_map_key_value", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_json_read_list", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_json_read_map", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_json_write_list", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_json_write_map", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_map_hash", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_map_index_slots", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_map_key", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_map_key_compare", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_add", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_cursor", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_erase", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_fill", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_fill_drop", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_fill_end", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_fill_next", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_next", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_order", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_orders_release", What: "the C list, map and node-extent runtime"},
		Name{Name: "table_sequence_sift", What: "the C list, map and node-extent runtime"},

		Name{Name: "TableAllocator", What: "the C graph, blob and text runtime"},
		Name{Name: "TableBlob", What: "the C graph, blob and text runtime"},
		Name{Name: "TableBytesView", What: "the C graph, blob and text runtime"},
		Name{Name: "TableJsonGraphEntry", What: "the C graph, blob and text runtime"},
		Name{Name: "TableJsonGraphIn", What: "the C graph, blob and text runtime"},
		Name{Name: "TableJsonGraphMap", What: "the C graph, blob and text runtime"},
		Name{Name: "TableJsonGraphOut", What: "the C graph, blob and text runtime"},
		Name{Name: "TableNodeDirEntry", What: "the C graph, blob and text runtime"},
		Name{Name: "TableNodeEntry", What: "the C graph, blob and text runtime"},
		Name{Name: "TableNodeMap", What: "the C graph, blob and text runtime"},
		Name{Name: "TableNodeScan", What: "the C graph, blob and text runtime"},
		Name{Name: "TableNodeType", What: "the C graph, blob and text runtime"},
		Name{Name: "TableNodeWork", What: "the C graph, blob and text runtime"},
		Name{Name: "TableNumbering", What: "the C graph, blob and text runtime"},
		Name{Name: "TableStringView", What: "the C graph, blob and text runtime"},
		Name{Name: "kTableBytesTypeId", What: "the C graph, blob and text runtime"},
		Name{Name: "kTableStringTypeId", What: "the C graph, blob and text runtime"},
		Name{Name: "table_allocate", What: "the C graph, blob and text runtime"},
		Name{Name: "table_arena_grab_span", What: "the C graph, blob and text runtime"},
		Name{Name: "table_arena_init_with_allocator", What: "the C graph, blob and text runtime"},
		Name{Name: "table_blob_at", What: "the C graph, blob and text runtime"},
		Name{Name: "table_blob_edges", What: "the C graph, blob and text runtime"},
		Name{Name: "table_blob_emplace", What: "the C graph, blob and text runtime"},
		Name{Name: "table_blob_save", What: "the C graph, blob and text runtime"},
		Name{Name: "table_blob_storage", What: "the C graph, blob and text runtime"},
		Name{Name: "table_bytes_at", What: "the C graph, blob and text runtime"},
		Name{Name: "table_bytes_emplace", What: "the C graph, blob and text runtime"},
		Name{Name: "table_bytes_node_type", What: "the C graph, blob and text runtime"},
		Name{Name: "table_default_allocate", What: "the C graph, blob and text runtime"},
		Name{Name: "table_default_allocator", What: "the C graph, blob and text runtime"},
		Name{Name: "table_default_release", What: "the C graph, blob and text runtime"},
		Name{Name: "table_graph_pack", What: "the C graph, blob and text runtime"},
		Name{Name: "table_graph_records", What: "the C graph, blob and text runtime"},
		Name{Name: "table_graph_save", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_emplace", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_graph_find", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_graph_reach", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_graph_slot", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_read_blob", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_read_graph", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_read_pointer", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_read_table_keys", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_scan_label", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_skipped_ampersand", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_write_fields", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_write_graph", What: "the C graph, blob and text runtime"},
		Name{Name: "table_json_write_pointer", What: "the C graph, blob and text runtime"},
		Name{Name: "table_node_resolve", What: "the C graph, blob and text runtime"},
		Name{Name: "table_node_scan_begin", What: "the C graph, blob and text runtime"},
		Name{Name: "table_node_scan_next", What: "the C graph, blob and text runtime"},
		Name{Name: "table_node_scan_open", What: "the C graph, blob and text runtime"},
		Name{Name: "table_node_scan_whole", What: "the C graph, blob and text runtime"},
		Name{Name: "table_node_storage", What: "the C graph, blob and text runtime"},
		Name{Name: "table_node_wire_storage", What: "the C graph, blob and text runtime"},
		Name{Name: "table_number_build", What: "the C graph, blob and text runtime"},
		Name{Name: "table_number_dispose", What: "the C graph, blob and text runtime"},
		Name{Name: "table_number_edge", What: "the C graph, blob and text runtime"},
		Name{Name: "table_number_find", What: "the C graph, blob and text runtime"},
		Name{Name: "table_number_grow", What: "the C graph, blob and text runtime"},
		Name{Name: "table_number_hash", What: "the C graph, blob and text runtime"},
		Name{Name: "table_number_rehash", What: "the C graph, blob and text runtime"},
		Name{Name: "table_number_slot", What: "the C graph, blob and text runtime"},
		Name{Name: "table_ref_at", What: "the C graph, blob and text runtime"},
		Name{Name: "table_release", What: "the C graph, blob and text runtime"},
		Name{Name: "table_string_at", What: "the C graph, blob and text runtime"},
		Name{Name: "table_string_emplace", What: "the C graph, blob and text runtime"},
		Name{Name: "table_string_node_type", What: "the C graph, blob and text runtime"},
		Name{Name: "table_worker_alloc", What: "the C graph, blob and text runtime"},
		Name{Name: "schema_allocate", What: "the default zeroed allocation hook"},
		Name{Name: "schema_release", What: "the default release hook"},

		Name{Name: "TableJsonInteger", What: "the text form integer conversion"},
		Name{Name: "table_json_interpret", What: "the text form integer conversion"},
		Name{Name: "table_json_integer_of", What: "the text form integer conversion"},
		Name{Name: "table_json_integer_in_domain", What: "the text form integer conversion"},
		Name{Name: "TableJsonWide", What: "the C table wide numeric and text runtime"},
		Name{Name: "TableWideRange", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_decode_utf8", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_kind_fixed", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_kind_wide", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_kind_wide_signed", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_read_wide", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_scan_unit", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_scan_w_string", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_compare", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_div", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_load", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_mul_add", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_neg", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_negative", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_shl", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_shr", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_store", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_wide_zero", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_write_w_string", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_json_write_wide", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_wire_utf16", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_wire_utf16_clamp", What: "the C table wide numeric and text runtime"},
		Name{Name: "table_wire_utf16_unit", What: "the C table wide numeric and text runtime"},

		Name{Name: "table_reader_array_header", What: "the form-1 array header reader"},
		Name{Name: "table_wire_widen_f32", What: "exact f32 widening including NaN payloads"},
		Name{Name: "table_kind_widens", What: "the form-1 file wire runtime"},
		Name{Name: "table_reader_child", What: "the form-1 file wire runtime"},
		Name{Name: "table_reader_id_at", What: "the form-1 file wire runtime"},
		Name{Name: "table_reader_leb", What: "the form-1 file wire runtime"},
		Name{Name: "table_reader_room", What: "the form-1 file wire runtime"},
		Name{Name: "table_reader_span", What: "the form-1 file wire runtime"},
		Name{Name: "table_wire_open", What: "the form-1 file wire runtime"},
		Name{Name: "table_wire_utf8", What: "the form-1 file wire runtime"},
		Name{Name: "table_wire_utf8_clamp", What: "the form-1 file wire runtime"},
		Name{Name: "table_writer_finish", What: "the form-1 file wire runtime"},
		Name{Name: "table_writer_id", What: "the form-1 file wire runtime"},
		Name{Name: "table_writer_id_at", What: "the form-1 file wire runtime's ordinal slot cache"},
		Name{Name: "table_writer_header_at", What: "the form-1 file wire runtime's paired field header"},
		Name{Name: "table_writer_leb", What: "the form-1 file wire runtime"},
		Name{Name: "table_writer_probe", What: "the form-1 file wire runtime"},
		Name{Name: "TableReport", What: "the read report — the permissive contract's ledger"},
		Name{Name: "TableWriteIds", What: "the file writer identity table"},
		Name{Name: "table_writer_rewind", What: "the file writer probe checkpoint"},
		Name{Name: "TableWriter", What: "the wire writer over the caller's buffer"},
		Name{Name: "TableReader", What: "the wire reader over the caller's buffer"},
		Name{Name: "TableTypeInfo", What: "a table's reflection descriptor"},
		Name{Name: "TableFieldInfo", What: "a field's reflection descriptor"},
		// THE SHARED EMPTY DOC (docs/SPEC-TABLES.md §8.1, §8.7): every field row
		// and every declaration row with no `///` block names this ONE
		// definition, so absence costs a unit no string data and a printer
		// concatenates doc columns with no null test. Every descriptor row a
		// VIEW FILE writes names it too, so it is claimed in EVERY unit
		// beside the descriptor primitives above (docs/SPEC-TABLES.md §8.2,
		// §11) rather than only where a table rides.
		Name{Name: "TableDocNone", What: "the one shared empty doc every unannotated descriptor row names"},
		Name{Name: "TableUnionInfo", What: "a union field's tag and its arms"},
		Name{Name: "TableUnionArmInfo", What: "one union arm's payload and descriptor"},
		Name{Name: "table_bits_to_float", What: "u32 bits -> float"},
		Name{Name: "table_float_to_bits", What: "float -> u32 bits"},
		Name{Name: "table_bits_to_double", What: "u64 bits -> double"},
		Name{Name: "table_double_to_bits", What: "double -> u64 bits"},
		Name{Name: "TableRef", What: "C++: a pointer's eight-byte reference slot; C#: a field descriptor's nested-table factory"},
		Name{Name: "TableArena", What: "the builder's segmented slab arena"},
		Name{Name: "TableWorker", What: "a builder worker's allocation front"},
		Name{Name: "TableBlockAllocator", What: "the caller's alloc/free pair, used once at build time"},
		Name{Name: "table_block_default_alloc", What: "the default allocator's alloc half"},
		Name{Name: "table_block_default_free", What: "the default allocator's free half"},
		Name{Name: "TableBlockTriple", What: "one array's (offset_of, count, stride)"},
		Name{Name: "TableBlockRefusal", What: "why Begin refused: the array, its count and its maximum"},
		Name{Name: "TableBlockRows", What: "one array's rows, iterated at the pitch the instance gives"},
		Name{Name: "TableBlockFieldInfo", What: "a block field's reflection descriptor"},
		Name{Name: "TableBlockInfo", What: "a block's reflection descriptor"},
		Name{Name: "table_block_byteswap64", What: "the byte-order check's swap"},
		Name{Name: "table_block_read64", What: "the prologue read BYTEWISE"},
		Name{Name: "table_block_align", What: "round an offset up to an alignment"},
		Name{Name: "table_cook_read64", What: "the cooked header read BYTEWISE"},
		// ---- THE C BACKEND's own spellings (internal/codegen/ctable) ----
		//
		// C has no namespace and no nested scope, so a runtime name is a unit-level
		// name whatever it is for. The list is long for that reason and for no
		// other: everything a consumer never types carries the schema_<package>_
		// prefix instead and is absent from here (ctable's `sym`), so what follows
		// is the surface a C consumer actually reads and writes, plus the text
		// form's walk — which lives in <Base>Table.c and would collide there with a
		// declaration of the same name in the unit's own header.

		// the wire reader and writer's operations. C++ spells these as member
		// functions of TableWriter and TableReader, which claim nothing; C has no
		// members, so each is a name.
		Name{Name: "table_writer_make", What: "a writer over a caller's buffer"},
		Name{Name: "table_writer_raw", What: "the writer's byte move"},
		Name{Name: "table_writer_put8", What: "the writer's u8"},
		Name{Name: "table_writer_put16", What: "the writer's little-endian u16"},
		Name{Name: "table_writer_put32", What: "the writer's little-endian u32"},
		Name{Name: "table_writer_put64", What: "the writer's little-endian u64"},
		Name{Name: "table_reader_make", What: "a reader over a caller's buffer"},
		Name{Name: "table_reader_has", What: "the reader's remaining-bytes question"},
		Name{Name: "table_reader_get8", What: "the reader's u8"},
		Name{Name: "table_reader_get16", What: "the reader's little-endian u16"},
		Name{Name: "table_reader_get32", What: "the reader's little-endian u32"},
		Name{Name: "table_reader_get64", What: "the reader's little-endian u64"},
		Name{Name: "table_reader_skip", What: "skip one payload by kind — the tolerant read's unknown-field path"},
		// the descriptors' VOCABULARY, as data. C++ spells an enum's names and wire
		// ids as captureless lambdas in the field descriptor; C has none, and a
		// named function per enum would claim a name per enum, so the same facts
		// ride as a table indexed the way enum_max bounds (§8.1).
		Name{Name: "TableVariantInfo", What: "one vocabulary entry: a variant's name and its table-wire id"},
		// the ENUM-KEYED array (docs/SPEC-TABLES.md §2.4). C's storage IS the array,
		// so there is no TableKeyed to emit; what C++ puts in operator[] — the
		// left shift and the None refusal — lives in these two.
		Name{Name: "table_keyed_slot", What: "the storage index a key names, refusing out-of-range keys in every build"},
		// the VARIABLE-LENGTH runtime's C spellings (docs/SPEC-TABLES.md §6). The
		// arena and the worker are C++'s too; everything a member function or a
		// template did there is a name here.
		Name{Name: "table_ref_null", What: "is this reference slot null (§6.3)"},
		Name{Name: "table_align_up", What: "round a u32 arena offset up to the node alignment"},
		Name{Name: "table_align_up64", What: "round an i64 region offset up to the node alignment"},
		Name{Name: "table_arena_init", What: "start one arena"},
		Name{Name: "table_arena_shutdown", What: "release one arena's segments"},
		Name{Name: "table_arena_at", What: "resolve an arena offset — one L1 load plus an add"},
		Name{Name: "table_arena_grab_slab", What: "hand one worker its next private slab"},
		Name{Name: "table_worker_make", What: "one thread's allocation front"},
		Name{Name: "table_worker_bump", What: "reserve one node's bytes in a worker's slab, untyped"},
		Name{Name: "TableCtx", What: "which encoding a walk is reading: an arena's offsets, or a region's self-relative deltas"},
		Name{Name: "TableRegionSink", What: "bump-allocation into the caller's exact region"},
		Name{Name: "TableSink", What: "where a node comes from — a region sink or a worker; C's form of the reference's Sink template parameter"},
		// the one ATOMIC the arena needs, and its spelling is FEATURE TESTED
		// because C99 has none (§6.4). The names are claimed whatever the
		// compiler picks, so a schema cannot become illegal by changing compilers.
		Name{Name: "TableAtomicU32", What: "the arena cursor's atomic u32"},
		Name{Name: "TableAtomicPtr", What: "an arena segment's atomic pointer"},
		Name{Name: "table_atomic_load32", What: "an acquire load of the cursor"},
		Name{Name: "table_atomic_store32", What: "a relaxed store of the cursor"},
		Name{Name: "table_atomic_load_ptr", What: "an acquire load of a segment"},
		Name{Name: "table_atomic_store_ptr", What: "a relaxed store of a segment"},
		Name{Name: "table_arena_cas32", What: "the slab handout's compare-exchange"},
		Name{Name: "table_arena_cas_ptr", What: "the segment publication's compare-exchange"},
		// the BLOCK form's C spellings (§19)
		Name{Name: "table_block_row_at", What: "one row of an array, at the pitch the instance gives"},
		// THE TUNING CONSTANTS, which C spells as #define and the other two as
		// typed constants inside their own scope. A macro is not scoped by
		// anything, so each is a unit-level name here (§6, §7.1, §16).
		Name{Name: "kTableAlign", What: "every arena node starts eight-aligned"},
		Name{Name: "kTableAllocFailed", What: "the arena's refusal, never a silent smaller slab"},
		Name{Name: "kTableMaxDepth", What: "the pointer-chain depth cap (§3.1)"},
		Name{Name: "kTableMaxSegments", What: "the arena's segment table"},
		Name{Name: "kTableSegmentBits", What: "the arena's segment size, as a shift"},
		Name{Name: "kTableSegmentMask", What: "the offset inside a segment"},
		Name{Name: "kTableSegmentSize", What: "the arena's segment size"},
		Name{Name: "kTableSlabBytes", What: "one worker's slab: one atomic per slab, none per node"},
		Name{Name: "table_cook_header_bytes", What: "the cooked header's 64 bytes (§7.1)"},
		Name{Name: "kTableJsonMaxDepth", What: "the text form's nesting cap"},
		Name{Name: "kTableJsonMaxKey", What: "the longest key that can name a field"},
		Name{Name: "kTableJsonMaxNumber", What: "the longest numeric token the walk converts"},
		// THE TEXT FORM'S WALK (docs/SPEC-TABLES.md §16), which C# scopes inside a
		// nested class and C++ hides in a namespace. C has neither, and the walk
		// lives in <Base>Table.c beside the unit's own header, so every one of its
		// spellings could collide with a declaration in that unit. They are one
		// family with one job, and the registry lists them rather than filtering
		// them: a scan that has to recognise a prefix is a scan that goes blind the
		// day a name leaves the family.
		Name{Name: "table_json_base64_alphabet", What: "the text form's walk"},
		Name{Name: "table_json_base64_value", What: "the text form's base64 decode lookup"},
		Name{Name: "table_json_count", What: "the text form's walk"},
		Name{Name: "table_json_decimal_point", What: "the text form's walk"},
		Name{Name: "table_json_element_shape", What: "the text form's walk"},
		Name{Name: "table_json_encode_utf8", What: "the text form's walk"},
		Name{Name: "table_json_finite", What: "the text form's walk"},
		Name{Name: "table_json_get_raw", What: "the text form's walk"},
		Name{Name: "table_json_get_signed", What: "the text form's walk"},
		Name{Name: "table_json_guard_holds", What: "the text form's walk"},
		Name{Name: "table_json_hex4", What: "the text form's walk"},
		Name{Name: "TableJsonIn", What: "the text form's walk"},
		Name{Name: "table_json_is_bytes", What: "the text form's walk"},
		Name{Name: "table_json_is_enum", What: "the text form's walk"},
		Name{Name: "table_json_is_flags", What: "the text form's walk"},
		Name{Name: "table_json_is_keyed", What: "the text form's walk"},
		Name{Name: "table_json_key_name", What: "the text form's walk"},
		Name{Name: "table_json_keyed_slot_key", What: "the text form's walk"},
		Name{Name: "table_json_keyed_slot_valid", What: "the text form's walk"},
		Name{Name: "table_json_line", What: "the text form's walk"},
		Name{Name: "table_json_literal", What: "the text form's walk"},
		Name{Name: "TableJsonOut", What: "the text form's walk"},
		Name{Name: "table_json_peek", What: "the text form's walk"},
		Name{Name: "table_json_put", What: "the text form's walk"},
		Name{Name: "table_json_raw", What: "the text form's walk"},
		Name{Name: "table_json_read", What: "the text form's walk"},
		Name{Name: "table_json_read_field", What: "the text form's walk"},
		Name{Name: "table_json_read_scalar", What: "the text form's walk"},
		Name{Name: "table_json_read_table", What: "the text form's walk"},
		Name{Name: "table_json_scan_number", What: "the text form's walk"},
		Name{Name: "table_json_scan_string", What: "the text form's walk"},
		Name{Name: "table_json_set_count", What: "the text form's walk"},
		Name{Name: "table_json_set_raw", What: "the text form's walk"},
		Name{Name: "table_json_shape", What: "the text form's walk"},
		Name{Name: "table_json_skip_container", What: "the text form's walk"},
		Name{Name: "table_json_skip_value", What: "the text form's walk"},
		Name{Name: "table_json_space", What: "the text form's walk"},
		Name{Name: "table_json_text", What: "the text form's walk"},
		Name{Name: "table_json_token_double", What: "the text form's walk"},
		Name{Name: "table_json_token_integer", What: "the text form's walk"},
		Name{Name: "table_json_utf8", What: "the text form's walk"},
		Name{Name: "table_json_value_shape", What: "the text form's walk"},
		Name{Name: "table_json_variant_name", What: "the text form's walk"},
		Name{Name: "table_json_walk_number", What: "the text form's walk"},
		Name{Name: "table_json_write", What: "the text form's walk"},
		Name{Name: "table_json_write_base64", What: "the text form's walk"},
		Name{Name: "table_json_write_field", What: "the text form's walk"},
		Name{Name: "table_json_write_float", What: "the text form's walk"},
		Name{Name: "table_json_write_scalar", What: "the text form's walk"},
		Name{Name: "table_json_write_signed", What: "the text form's walk"},
		Name{Name: "table_json_write_string", What: "the text form's walk"},
		Name{Name: "table_json_write_unsigned", What: "the text form's walk"},
		Name{Name: "table_json_write_value", What: "the text form's walk"},
		// The C spellings of names the other backends carry in PascalCase. They
		// are separate entries because they are separate SPELLINGS: C spells a
		// function and a file-scope constant snake_case, which is the convention
		// its packet half already uses, so the same runtime value is one identifier
		// in Rust and C++ and a different identifier here. Both are claimed for
		// every target, because the claim is front-end law and a unit legal under
		// one backend must be legal under all of them.
		Name{Name: "table_block_default_allocator", What: "the malloc/free pair, for a caller with none of its own"},
		Name{Name: "table_block_magic", What: "the block prologue's magic, and the byte-order check with it"},
		Name{Name: "table_block_byte_order", What: "this build's byte order, as the prologue carries it"},
		Name{Name: "TableByteOrder", What: "the C canonical cook writer"},
		Name{Name: "TableByteOrder_Little", What: "the C canonical cook writer"},
		Name{Name: "TableByteOrder_Big", What: "the C canonical cook writer"},
		Name{Name: "table_cook_put", What: "the C canonical cook writer"},
		Name{Name: "table_cook_put128", What: "the C canonical cook writer"},
		Name{Name: "table_cook_bytes", What: "the C canonical cook writer"},
		Name{Name: "table_cook_units", What: "the C canonical cook writer"},
		Name{Name: "table_cook_header", What: "the C canonical cook writer"},
		Name{Name: "table_cook_ref", What: "the C canonical cook writer"},
		Name{Name: "table_cook_layout", What: "the C canonical cook writer"},
		Name{Name: "table_graph_cook", What: "the C canonical cook writer"},
		Name{Name: "TableRefuseReason", What: "the C cook and block refusal surface"},
		Name{Name: "table_cook_refuse", What: "the C cook and block refusal surface"},
		Name{Name: "table_cook_open_ex", What: "the C cook and block refusal surface"},
		Name{Name: "TableBlockConstRows", What: "the C cook and block refusal surface"},
		Name{Name: "table_block_row_at_const", What: "the C cook and block refusal surface"},
		Name{Name: "table_block_read32", What: "the C cook and block refusal surface"},
		Name{Name: "schema_assert", What: "the C keyed accessor assertion hook"},
		Name{Name: "schema_fatal", What: "the C keyed accessor fatal hook"},
		Name{Name: "table_cook_open", What: "the cooked header's WHOLE check, shared by every <Name>Open"},
		Name{Name: "table_cook_magic", What: "the cooked header's magic, and the byte-order check with it"},
		Name{Name: "table_cook_byte_order", What: "this build's byte order, as a cooked header records it"},
		Name{Name: "table_cook_max_align", What: "the greatest region alignment a cooked header may name"},
		// THE FIXED FORM's runtime (docs/SPEC-TABLES.md §3.4). C has no namespace
		// to hide it in, so every spelling of it is a unit-level name; the two
		// MACROS it defines lead with SCHEMA_ and are reserved by internal/check
		// instead, which is where this backend's macros are claimed.
		Name{Name: "TableFixedCompiler", What: "the fixed form's plan compiler state (§3.4)"},
		Name{Name: "TableFixedDst", What: "the fixed form: MY side of a LAYOUT entry"},
		Name{Name: "TableFixedEntry", What: "the fixed form: one plan entry"},
		Name{Name: "TableFixedCheck", What: "the fixed form: the layout validation's state (§3.4)"},
		Name{Name: "TableFixedLayoutEntry", What: "the fixed form: one entry of a LAYOUT"},
		Name{Name: "TableFixedLayoutView", What: "the fixed form: a parsed LAYOUT"},
		Name{Name: "kTableFixedConst", What: "the fixed form's ops"},
		Name{Name: "kTableFixedCopy", What: "the fixed form's ops"},
		Name{Name: "kTableFixedCount", What: "the fixed form's ops"},
		Name{Name: "kTableFixedEntryBytes", What: "the fixed form: a layout entry is seventeen bytes"},
		Name{Name: "kTableFixedHashAt", What: "the fixed form's pinned header: the layout hash at offset 8 (§3)"},
		Name{Name: "kTableFixedHeaderBytes", What: "the fixed form's pinned header: sixteen bytes, the body at 16 (§3)"},
		Name{Name: "kTableFixedLayoutHeaderBytes", What: "the fixed form: the layout's u32 entry count, and nothing else"},
		Name{Name: "kTableFixedMaxDepth", What: "the fixed form: a bound on the layout WALK, not on the wire"},
		Name{Name: "kTableFixedRecordMaxBytes", What: "the fixed form: §3.4's 65536-byte record ceiling"},
		Name{Name: "kTableFixedForm", What: "the fixed form's form byte, 3"},
		Name{Name: "kTableFixedOrdinal", What: "the fixed form's ops"},
		Name{Name: "kTableFixedText", What: "the fixed form's ops"},
		Name{Name: "kTableFixedTextBytes", What: "the fixed form: a text entry's flavour"},
		Name{Name: "kTableFixedTextUtf8", What: "the fixed form: a text entry's flavour"},
		Name{Name: "kTableFixedTextWide", What: "the fixed form: a text entry's flavour"},
		Name{Name: "kTableFixedWiden", What: "the fixed form's ops"},
		Name{Name: "kTableFixedWidenF", What: "the fixed form's ops"},
		Name{Name: "table_fixed_apply", What: "the fixed form's read loop body"},
		Name{Name: "table_fixed_compile", What: "the fixed form's plan compiler"},
		Name{Name: "table_fixed_compile_entry", What: "the fixed form's plan compiler"},
		Name{Name: "table_fixed_compiler_init", What: "the fixed form's plan compiler"},
		Name{Name: "table_fixed_copy_run", What: "the fixed form's run copy"},
		Name{Name: "table_fixed_entry_at", What: "the fixed form's layout reader"},
		Name{Name: "table_fixed_entry_zero", What: "the fixed form: a zeroed plan entry, since C has no member initializer"},
		Name{Name: "table_fixed_get32", What: "the fixed form's little-endian loads"},
		Name{Name: "table_fixed_get64", What: "the fixed form's little-endian loads"},
		Name{Name: "table_fixed_check_entry", What: "the fixed form's layout validation, rule by named rule (§3.4)"},
		Name{Name: "table_fixed_fail", What: "the fixed form's layout validation: the first rule to fail names the refusal"},
		Name{Name: "table_fixed_hash_of", What: "the fixed form's layout hash"},
		Name{Name: "table_fixed_known_kind", What: "the fixed form's CLOSED kind set (§3, §3.4)"},
		Name{Name: "table_fixed_lay_table", What: "the fixed form's plan compiler"},
		Name{Name: "table_fixed_match_children", What: "the fixed form's plan compiler"},
		Name{Name: "table_fixed_push", What: "the fixed form's plan compiler"},
		Name{Name: "table_fixed_put16", What: "the fixed form's little-endian stores"},
		Name{Name: "table_fixed_put32", What: "the fixed form's little-endian stores"},
		Name{Name: "table_fixed_put64", What: "the fixed form's little-endian stores"},
		Name{Name: "table_fixed_put8", What: "the fixed form's little-endian stores"},
		Name{Name: "table_fixed_putf32", What: "the fixed form's little-endian stores"},
		Name{Name: "table_fixed_putf64", What: "the fixed form's little-endian stores"},
		Name{Name: "table_fixed_run", What: "the fixed form's ONE read loop"},
		Name{Name: "TableFixedFill", What: "the fixed form: one prefill range, the bytes a plan does not land"},
		Name{Name: "table_fixed_entry_lands", What: "the fixed form: the storage bytes one plan entry writes"},
		Name{Name: "table_fixed_fill_run", What: "the fixed form: copy the prefill's ranges from the default image"},
		Name{Name: "table_fixed_fills", What: "the fixed form: cover minus what this plan lands"},
		Name{Name: "table_fixed_lay_fills", What: "the fixed form: reserve the prefill ranges in the plan pool"},
		Name{Name: "table_fixed_signed_kind", What: "the fixed form's widening rungs"},
		Name{Name: "table_fixed_layout_entry_zero", What: "the fixed form's layout reader"},
		Name{Name: "table_fixed_layout_view_zero", What: "the fixed form's layout reader"},
		Name{Name: "table_fixed_leaf_size", What: "the fixed form's layout validation: a leaf kind's admitted sizes"},
		Name{Name: "table_fixed_ordinal_width", What: "the fixed form's layout validation: a tag or ordinal's admitted widths"},
		Name{Name: "table_fixed_parse_layout", What: "the fixed form's layout reader, and the whole of what a reader trusts a layout on"},
		Name{Name: "table_fixed_subtree", What: "the fixed form's layout reader"},
		Name{Name: "table_fixed_tag_at", What: "the fixed form: the plan guard compared at the tag's width"},
		Name{Name: "table_fixed_tag_bytes", What: "the fixed form's layout reader"},
		Name{Name: "table_fixed_union_arm_bytes", What: "the fixed form's layout reader"},
		Name{Name: "table_fixed_widens", What: "the fixed form's widening rungs"},
		Name{Name: "TableFixedKnownLayout", What: "the fixed form: one locked layout of a lineage entry — its hash, its bytes and its record size (§5.2)"},
		Name{Name: "TableFixedLineagePlan", What: "the fixed form: one lineage entry's plan, built from the lock's bytes off every load path (§5.2)"},
		Name{Name: "table_fixed_select", What: "the fixed form: the header's hash selects a known layout, or refuses (§5.3)"},
		Name{Name: "table_fixed_refuse_hash", What: "the fixed form: a refusal that carries THE FILE'S hash — layout_newer and layout_unsupported (§5.3)"},
		Name{Name: "SCHEMA_TABLE_LAYOUT_NEWER", What: "the fixed form: a hash this reader's lineage does not hold — ship the reader (§5.3)"},
		Name{Name: "SCHEMA_TABLE_LAYOUT_UNSUPPORTED", What: "the fixed form: a hash in the lineage below the floor — upgrade the client (§5.3)"},
		Name{Name: "TableFixedPlanCache", What: "the plan cache BY HASH, so a compile is paid once per peer and never once per record"},
		Name{Name: "TableFixedPlanCacheSlot", What: "one cached compiled plan: hash, plan pointer, count, record_bytes"},
		Name{Name: "kTableFixedPlanCacheCapacity", What: "the plan cache's named bound: 64, overflow is a miss"},
		Name{Name: "table_fixed_plan_cache_init", What: "bind caller-owned slot storage to a plan cache"},
	)
}
