package tablenames

// Go is the Go table backend (internal/codegen/gotable).
const Go Backend = 1 << 3

func init() {
	define(Go,
		Name{Name: "TableMap", What: "map storage, ordering, key validation and text"},
		Name{Name: "TableMapIndex", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableJsonDecimalKey", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableJsonMapInteger", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableJsonReadMap", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableJsonWriteMap", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapCursor", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapFind", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapHash", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapIndex", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapIndexFind", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapIndexMeasure", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapKey", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapKeyOrder", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapKeyValid", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapPlace", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapReadKey", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapStoreKey", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableMapStoredKey", What: "map storage, ordering, key validation and text"},
		Name{Name: "tableBuilderLoad", What: "editable file load through the builder allocator"},
		Name{Name: "tableRegionCount", What: "unclamped authoring storage count"},
		Name{Name: "tableExtentFieldEmpty", What: "unreached container refusal"},
		Name{Name: "TableList", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "TableExtentCarve", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainer", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainerAppend", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainerErase", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainerChunk", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainerCursor", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainerCursorBegin", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainerFill", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainerFillAt", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableContainerHead", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableExtentBytes", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableExtentValue", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableExtentWalk", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableJsonReadList", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableJsonWriteList", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableWireArrayExtent", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableWireExtent", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableWireNodeBytes", What: "unbounded container storage, framing and descriptor walks"},
		Name{Name: "tableWireUnionExtent", What: "unbounded container storage, framing and descriptor walks"},

		Name{Name: "TableAllocator", What: "the canonical region and graph text runtime"},
		Name{Name: "TableArena", What: "the canonical region and graph text runtime"},
		Name{Name: "TableBlob", What: "the canonical region and graph text runtime"},
		Name{Name: "TableBlobAt", What: "the canonical region and graph text runtime"},
		Name{Name: "TableBytesAt", What: "the canonical region and graph text runtime"},
		Name{Name: "TableBytesEmplace", What: "the canonical region and graph text runtime"},
		Name{Name: "TableBytesView", What: "the canonical region and graph text runtime"},
		Name{Name: "TableNodeDirEntry", What: "the canonical region and graph text runtime"},
		Name{Name: "TableNodeMap", What: "the canonical region and graph text runtime"},
		Name{Name: "TableNumbering", What: "the canonical region and graph text runtime"},
		Name{Name: "TableRef", What: "the canonical region and graph text runtime"},
		Name{Name: "TableStringAt", What: "the canonical region and graph text runtime"},
		Name{Name: "TableStringEmplace", What: "the canonical region and graph text runtime"},
		Name{Name: "TableStringView", What: "the canonical region and graph text runtime"},
		Name{Name: "TableWorker", What: "the canonical region and graph text runtime"},
		Name{Name: "tableArenaSegment", What: "the canonical region and graph text runtime"},
		Name{Name: "tableArenaSegmentBytes", What: "the canonical region and graph text runtime"},
		Name{Name: "tableArenaSegments", What: "the canonical region and graph text runtime"},
		Name{Name: "tableArenaSlabBytes", What: "the canonical region and graph text runtime"},
		Name{Name: "tableBytesTypeId", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonDropLabel", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonGraph", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonGraphNode", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonLabel", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonPointerAt", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonReadBlob", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonReadLabel", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonReadPointer", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonReadTableFields", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonWriteLabeledValue", What: "the canonical region and graph text runtime"},
		Name{Name: "tableJsonWritePointer", What: "the canonical region and graph text runtime"},
		Name{Name: "tableNodeEntry", What: "the canonical region and graph text runtime"},
		Name{Name: "tableNodeMeasure", What: "the canonical region and graph text runtime"},
		Name{Name: "tableNodeScan", What: "the canonical region and graph text runtime"},
		Name{Name: "tableNodeScanBegin", What: "the canonical region and graph text runtime"},
		Name{Name: "tableNodeStorage", What: "the canonical region and graph text runtime"},
		Name{Name: "tableNodeWrite", What: "the canonical region and graph text runtime"},
		Name{Name: "tableNumber", What: "the canonical region and graph text runtime"},
		Name{Name: "tableOptionalArena", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRefAt", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionAlign", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionEdges", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionFromJson", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionLoad", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionMeasure", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionPack", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionRound", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionSave", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionToJson", What: "the canonical region and graph text runtime"},
		Name{Name: "tableRegionValueEdges", What: "the canonical region and graph text runtime"},
		Name{Name: "tableStringTypeId", What: "the canonical region and graph text runtime"},
		Name{Name: "tableUtf16Valid", What: "wide text conversion"},
		Name{Name: "tableUtf16Clamp", What: "wide text conversion"},
		Name{Name: "tableJsonWriteWString", What: "wide text conversion"},
		Name{Name: "tableJsonWriteStringBody", What: "wide text conversion"},

		Name{Name: "tableJsonWide", What: "exact wide scalar text conversion"},
		Name{Name: "tableJsonWideSigned", What: "exact wide scalar text conversion"},
		Name{Name: "tableJsonWideLoad", What: "exact wide scalar text conversion"},
		Name{Name: "tableJsonWideStore", What: "exact wide scalar text conversion"},
		Name{Name: "tableJsonReadWide", What: "exact wide scalar text conversion"},
		Name{Name: "tableJsonWriteWide", What: "exact wide scalar text conversion"},

		Name{Name: "tableIdCapacity", What: "the form-1 wire runtime"},
		Name{Name: "tableIdBuckets", What: "the form-1 wire runtime"},
		Name{Name: "TableIds", What: "the form-1 wire runtime"},
		Name{Name: "tableLebBytes", What: "the form-1 wire runtime"},
		Name{Name: "TableOpenVerdict", What: "the form-1 wire runtime"},
		Name{Name: "TableOpenOk", What: "the form-1 wire runtime"},
		Name{Name: "TableOpenRefused", What: "the form-1 wire runtime"},
		Name{Name: "TableOpenDamaged", What: "the form-1 wire runtime"},
		Name{Name: "TableOpenBodyStopped", What: "the form-1 wire runtime"},
		Name{Name: "tableKindBytes", What: "the form-1 wire runtime"},
		Name{Name: "tableOpen", What: "the form-1 wire runtime"},
		Name{Name: "tableKindWidens", What: "the form-1 wire runtime"},
		Name{Name: "tableUtf8Valid", What: "the form-1 wire runtime"},
		Name{Name: "tableUtf8Clamp", What: "the form-1 wire runtime"},
		Name{Name: "tableWidenFloat", What: "the form-1 wire runtime"},

		Name{Name: "TableReport", What: "the read report — the permissive contract's ledger"},
		Name{Name: "TableWriter", What: "the wire writer over the caller's buffer"},
		Name{Name: "TableReader", What: "the wire reader over the caller's buffer"},
		Name{Name: "TableTypeInfo", What: "a table's reflection descriptor"},
		Name{Name: "TableFieldInfo", What: "a field's reflection descriptor"},
		// THE SHARED EMPTY DOC (docs/SPEC-TABLES.md §8.1, §8.7): every field row
		// and every declaration row with no `///` block names this ONE
		// definition, so absence costs a unit no string data and a printer
		// concatenates doc columns with no null test. Every descriptor row a
		// VIEW FILE writes names it too, so it is claimed in EVERY unit
		// beside the descriptor primitives above (docs/SPEC-TABLES.md §8.2,
		// §11) rather than only where a table rides.
		Name{Name: "TableDocNone", What: "the one shared empty doc every unannotated descriptor row names"},
		Name{Name: "TableUnionInfo", What: "a union field's tag and its arms"},
		Name{Name: "TableUnionArmInfo", What: "one union arm's payload and descriptor"},
		Name{Name: "TableEnumId", What: "an enum value -> its table-wire variant id"},
		Name{Name: "TableEnumValue", What: "a table-wire variant id -> its enum value"},
		Name{Name: "TableKeyed", What: "an enum-keyed array's slot storage"},
		Name{Name: "Table", What: "TableFieldInfo's nested-table column", Scoped: true},
		Name{Name: "TableBlockTriple", What: "one array's (offset_of, count, stride)"},
		Name{Name: "TableBlockRows", What: "one array's rows, iterated at the pitch the instance gives"},
		Name{Name: "TableBlockFieldInfo", What: "a block field's reflection descriptor"},
		Name{Name: "TableBlockInfo", What: "a block's reflection descriptor"},
		Name{Name: "TableBlockMagic", What: "the block prologue's magic, and the byte-order check with it", RustConst: true},
		Name{Name: "TableBlockByteOrder", What: "this build's byte order, as the prologue carries it", RustConst: true},
		Name{Name: "TableCookMagic", What: "the cooked header's magic, and the byte-order check with it", RustConst: true},
		Name{Name: "TableCookByteOrder", What: "this build's byte order, as a cooked header records it", RustConst: true},
		Name{Name: "TableCookMaxAlign", What: "the greatest region alignment a cooked header may name", RustConst: true},
		Name{Name: "TableCookHeaderBytes", What: "§7.1's 64-byte header. C# spells it a Schema member, which claims nothing; Rust puts it at module level, Go at package scope and JavaScript at module scope, so the claim is the UNION and the name is claimed", RustConst: true},
		Name{Name: "TableCookInfo", What: "a cooked record's reflection descriptor"},
		Name{Name: "TableCookFieldInfo", What: "a cooked field's reflection descriptor"},
		Name{Name: "TableCookStorage", What: "what a cooked slot HOLDS, which is not always what the wire carries (§7.2)"},
		// the eight MEMBERS of that vocabulary, which C# scopes inside its enum and
		// Rust inside its own type, and which GO flattens into the package
		// namespace — exactly as the Go packet emitter flattens a declared enum's
		// variants, which the checker already claims one by one. A port's spelling
		// decides the claim, and this is Go's alone.
		Name{Name: "TableCookStorageRecord", What: "a nested record, or an array of them"},
		Name{Name: "TableCookStorageReference", What: "an eight-byte signed self-relative delta slot (§6.3)"},
		Name{Name: "TableCookStorageBool", What: "a bool slot"},
		Name{Name: "TableCookStorageSigned", What: "a signed integer slot"},
		Name{Name: "TableCookStorageUnsigned", What: "an unsigned integer, an enum ordinal, a bits(N), a flags mask"},
		Name{Name: "TableCookStorageFloat", What: "a float slot"},
		Name{Name: "TableCookStorageString", What: "char[N + 1] with an int32 used length beside it"},
		Name{Name: "TableCookStorageBytes", What: "uint8[N] with an int32 used length beside it"},
		// ---- THE GO PORT'S LOWERCASE FAMILY (docs/SPEC-TABLES.md §11) ----
		//
		// Go is the first backend whose runtime puts UNEXPORTED names at package
		// scope, and unexported is not private: a Go package is one namespace, so
		// `const tableJsonMaxDepth = 5` in a schema generates a redeclaration and
		// the unit does not compile. That is precisely the defect §11 promises
		// cannot happen, so every one of these is claimed on the same terms as the
		// PascalCase surface above.
		//
		// THE THREE SLICES ARE WHY THERE ARE ONLY THREE OF THEM. A descriptor graph
		// could have taken one variable per record — `cookRecordScene`,
		// `blockInfoRenderFrameShipRow` — and each of those is a name DERIVED from
		// a declaration's own spelling, which is a name a declaration can collide
		// with and which this registry has no shape for. One fixed name per graph
		// is one claim, and the emitters index into it.
		Name{Name: "tableBlockLayoutOffset", What: "the block layout contract's offset refusal"},
		Name{Name: "tableBlockLayoutSize", What: "the block layout contract's size refusal"},
		Name{Name: "tableBlockNativeOrder", What: "this machine's byte order, read once at package initialisation"},
		Name{Name: "tableBlockRecords", What: "the unit's whole block descriptor graph, one slice"},
		Name{Name: "tableCookLayoutOffset", What: "the cook layout contract's offset refusal"},
		Name{Name: "tableCookLayoutSize", What: "the cook layout contract's size refusal"},
		Name{Name: "tableCookNativeOrder", What: "this machine's byte order, read once at package initialisation"},
		Name{Name: "tableCookRecords", What: "the unit's whole cooked-record descriptor graph, one slice"},
		Name{Name: "tableJsonBase64Alphabet", What: "the base64 alphabet a `bytes` field rides under"},
		Name{Name: "tableJsonBase64Decode", What: "the base64 decode lookup for a `bytes` field"},
		Name{Name: "tableJsonBytes", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonCount", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonElementShape", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonEncodeUtf8", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonFinite", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonGetRaw", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonGetSigned", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonGuardHolds", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonIn", What: "the text reader's cursor"},
		Name{Name: "tableJsonIsBytes", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonIsEnum", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonIsFlags", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonIsKeyed", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonKeyedSlotKey", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonKeyedSlotValid", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonMaxDepth", What: "the walk's nesting cap"},
		Name{Name: "tableJsonMaxKey", What: "the longest key the walk will place"},
		Name{Name: "tableJsonMaxNumber", What: "the longest numeric token the walk will convert"},
		Name{Name: "tableJsonNameIs", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonNamed", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonOut", What: "the text writer's sink"},
		Name{Name: "tableJsonRead", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonReadField", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonReadScalar", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonReadTable", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonSetCount", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonSetRaw", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonShape", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonText", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonTokenDouble", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonTokenInteger", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonUtf8", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWrite", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWriteBase64", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWriteField", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWriteFloat", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWriteScalar", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWriteSigned", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWriteString", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWriteUnsigned", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableJsonWriteValue", What: "one step of the text form's generic walk (§16)"},
		Name{Name: "tableUnionArms", What: "the unit's union-field shapes, one slice"},
		Name{Name: "BuildVersion", What: "the unit's build version (docs/SPEC-TABLES.md §20). C# spells it a member of Schema, which claims nothing; C++, Go, Rust, Java, Elixir and JavaScript put it at unit scope — Java in a file of its own name, Elixir as a module, JavaScript as a module-scope export — so the claim is the union. C does NOT emit this spelling: an object-like macro carrying a common PascalCase identifier rewrites it everywhere in the consumer's own translation unit, which no front end can refuse, so the C backend spells the value SCHEMA_<PKG>_BUILD_VERSION_VALUE under the reserved prefix (internal/check's cReservedMacros)", RustConst: true},
	)
}
