// Generated by the schema compiler from Types.schema. DO NOT EDIT.
// package example — protocol id 0xaacab4aa04d2189b
// The TABLE wire (evolution-tolerant, notes/table-wire.md).

package example

import "math"

// TableWriteVec3 appends value's table-wire encoding and returns the buffer.
func TableWriteVec3(value *Vec3) []byte {
	w := &tableWriter{}
	tableWriteVec3(w, value)
	return w.buf
}

func tableWriteVec3(w *tableWriter, value *Vec3) {
	if value.X != 0 {
		w.u16(0xad8b) // x
		w.u8(11)
		w.u64(math.Float64bits(value.X))
	}
	if value.Y != 0 {
		w.u16(0xb2f8) // y
		w.u8(11)
		w.u64(math.Float64bits(value.Y))
	}
	if value.Z != 0 {
		w.u16(0xaca1) // z
		w.u8(11)
		w.u64(math.Float64bits(value.Z))
	}
	w.u16(0) // terminator
}

// TableReadVec3 decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadVec3(data []byte, value *Vec3, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadVec3(r, value)
}

func tableReadVec3(r *tableReader, value *Vec3) bool {
	*value = Vec3{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0xad8b: // x
			if kind != 11 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			value.X = math.Float64frombits(r.get64())
		case 0xb2f8: // y
			if kind != 11 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			value.Y = math.Float64frombits(r.get64())
		case 0xaca1: // z
			if kind != 11 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			value.Z = math.Float64frombits(r.get64())
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteQuat appends value's table-wire encoding and returns the buffer.
func TableWriteQuat(value *Quat) []byte {
	w := &tableWriter{}
	tableWriteQuat(w, value)
	return w.buf
}

func tableWriteQuat(w *tableWriter, value *Quat) {
	if value.X != 0 {
		w.u16(0xad8b) // x
		w.u8(11)
		w.u64(math.Float64bits(value.X))
	}
	if value.Y != 0 {
		w.u16(0xb2f8) // y
		w.u8(11)
		w.u64(math.Float64bits(value.Y))
	}
	if value.Z != 0 {
		w.u16(0xaca1) // z
		w.u8(11)
		w.u64(math.Float64bits(value.Z))
	}
	if value.W != 0 {
		w.u16(0xcd3a) // w
		w.u8(11)
		w.u64(math.Float64bits(value.W))
	}
	w.u16(0) // terminator
}

// TableReadQuat decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadQuat(data []byte, value *Quat, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadQuat(r, value)
}

func tableReadQuat(r *tableReader, value *Quat) bool {
	*value = Quat{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0xad8b: // x
			if kind != 11 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			value.X = math.Float64frombits(r.get64())
		case 0xb2f8: // y
			if kind != 11 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			value.Y = math.Float64frombits(r.get64())
		case 0xaca1: // z
			if kind != 11 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			value.Z = math.Float64frombits(r.get64())
		case 0xcd3a: // w
			if kind != 11 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			value.W = math.Float64frombits(r.get64())
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteHandle appends value's table-wire encoding and returns the buffer.
func TableWriteHandle(value *Handle) []byte {
	w := &tableWriter{}
	tableWriteHandle(w, value)
	return w.buf
}

func tableWriteHandle(w *tableWriter, value *Handle) {
	if value.ObjectId != 0 {
		w.u16(0xdc71) // object_id
		w.u8(4)
		w.u32(uint32(value.ObjectId))
	}
	if value.ObjectSequence != 0 {
		w.u16(0x57ee) // object_sequence
		w.u8(6)
		w.u8(uint8(value.ObjectSequence))
	}
	w.u16(0) // terminator
}

// TableReadHandle decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadHandle(data []byte, value *Handle, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadHandle(r, value)
}

func tableReadHandle(r *tableReader, value *Handle) bool {
	*value = Handle{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0xdc71: // object_id
			if kind != 4 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			decoded := int32(r.get32())
			if decoded < 0 {
				decoded = 0
				r.rep.Clamped++
			} else if decoded > 9999 {
				decoded = 9999
				r.rep.Clamped++
			}
			value.ObjectId = int32(decoded)
		case 0x57ee: // object_sequence
			if kind != 6 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			decoded := r.get8()
			value.ObjectSequence = uint8(decoded)
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteQuantizedPosition appends value's table-wire encoding and returns the buffer.
func TableWriteQuantizedPosition(value *QuantizedPosition) []byte {
	w := &tableWriter{}
	tableWriteQuantizedPosition(w, value)
	return w.buf
}

func tableWriteQuantizedPosition(w *tableWriter, value *QuantizedPosition) {
	if value.X != 0 {
		w.u16(0xad8b) // x
		w.u8(4)
		w.u32(uint32(value.X))
	}
	if value.Y != 0 {
		w.u16(0xb2f8) // y
		w.u8(4)
		w.u32(uint32(value.Y))
	}
	if value.Z != 0 {
		w.u16(0xaca1) // z
		w.u8(4)
		w.u32(uint32(value.Z))
	}
	w.u16(0) // terminator
}

// TableReadQuantizedPosition decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadQuantizedPosition(data []byte, value *QuantizedPosition, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadQuantizedPosition(r, value)
}

func tableReadQuantizedPosition(r *tableReader, value *QuantizedPosition) bool {
	*value = QuantizedPosition{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0xad8b: // x
			if kind != 4 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			decoded := int32(r.get32())
			if decoded < -8388608 {
				decoded = -8388608
				r.rep.Clamped++
			} else if decoded > 8388608 {
				decoded = 8388608
				r.rep.Clamped++
			}
			value.X = int32(decoded)
		case 0xb2f8: // y
			if kind != 4 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			decoded := int32(r.get32())
			if decoded < -8388608 {
				decoded = -8388608
				r.rep.Clamped++
			} else if decoded > 8388608 {
				decoded = 8388608
				r.rep.Clamped++
			}
			value.Y = int32(decoded)
		case 0xaca1: // z
			if kind != 4 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			decoded := int32(r.get32())
			if decoded < -8388608 {
				decoded = -8388608
				r.rep.Clamped++
			} else if decoded > 8388608 {
				decoded = 8388608
				r.rep.Clamped++
			}
			value.Z = int32(decoded)
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteQuantizedVelocity appends value's table-wire encoding and returns the buffer.
func TableWriteQuantizedVelocity(value *QuantizedVelocity) []byte {
	w := &tableWriter{}
	tableWriteQuantizedVelocity(w, value)
	return w.buf
}

func tableWriteQuantizedVelocity(w *tableWriter, value *QuantizedVelocity) {
	if value.X != 0 {
		w.u16(0xad8b) // x
		w.u8(4)
		w.u32(uint32(value.X))
	}
	if value.Y != 0 {
		w.u16(0xb2f8) // y
		w.u8(4)
		w.u32(uint32(value.Y))
	}
	if value.Z != 0 {
		w.u16(0xaca1) // z
		w.u8(4)
		w.u32(uint32(value.Z))
	}
	w.u16(0) // terminator
}

// TableReadQuantizedVelocity decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadQuantizedVelocity(data []byte, value *QuantizedVelocity, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadQuantizedVelocity(r, value)
}

func tableReadQuantizedVelocity(r *tableReader, value *QuantizedVelocity) bool {
	*value = QuantizedVelocity{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0xad8b: // x
			if kind != 4 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			decoded := int32(r.get32())
			if decoded < -2097152 {
				decoded = -2097152
				r.rep.Clamped++
			} else if decoded > 2097152 {
				decoded = 2097152
				r.rep.Clamped++
			}
			value.X = int32(decoded)
		case 0xb2f8: // y
			if kind != 4 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			decoded := int32(r.get32())
			if decoded < -2097152 {
				decoded = -2097152
				r.rep.Clamped++
			} else if decoded > 2097152 {
				decoded = 2097152
				r.rep.Clamped++
			}
			value.Y = int32(decoded)
		case 0xaca1: // z
			if kind != 4 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			decoded := int32(r.get32())
			if decoded < -2097152 {
				decoded = -2097152
				r.rep.Clamped++
			} else if decoded > 2097152 {
				decoded = 2097152
				r.rep.Clamped++
			}
			value.Z = int32(decoded)
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteQuantizedRotation appends value's table-wire encoding and returns the buffer.
func TableWriteQuantizedRotation(value *QuantizedRotation) []byte {
	w := &tableWriter{}
	tableWriteQuantizedRotation(w, value)
	return w.buf
}

func tableWriteQuantizedRotation(w *tableWriter, value *QuantizedRotation) {
	if value.X != 0 {
		w.u16(0xad8b) // x
		w.u8(3)
		w.u16(uint16(value.X))
	}
	if value.Y != 0 {
		w.u16(0xb2f8) // y
		w.u8(3)
		w.u16(uint16(value.Y))
	}
	if value.Z != 0 {
		w.u16(0xaca1) // z
		w.u8(3)
		w.u16(uint16(value.Z))
	}
	if value.W != 0 {
		w.u16(0xcd3a) // w
		w.u8(3)
		w.u16(uint16(value.W))
	}
	w.u16(0) // terminator
}

// TableReadQuantizedRotation decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadQuantizedRotation(data []byte, value *QuantizedRotation, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadQuantizedRotation(r, value)
}

func tableReadQuantizedRotation(r *tableReader, value *QuantizedRotation) bool {
	*value = QuantizedRotation{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0xad8b: // x
			if kind != 3 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(2) {
				r.rep.Malformed = true
				return false
			}
			decoded := int16(r.get16())
			if decoded < -1024 {
				decoded = -1024
				r.rep.Clamped++
			} else if decoded > 1024 {
				decoded = 1024
				r.rep.Clamped++
			}
			value.X = int16(decoded)
		case 0xb2f8: // y
			if kind != 3 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(2) {
				r.rep.Malformed = true
				return false
			}
			decoded := int16(r.get16())
			if decoded < -1024 {
				decoded = -1024
				r.rep.Clamped++
			} else if decoded > 1024 {
				decoded = 1024
				r.rep.Clamped++
			}
			value.Y = int16(decoded)
		case 0xaca1: // z
			if kind != 3 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(2) {
				r.rep.Malformed = true
				return false
			}
			decoded := int16(r.get16())
			if decoded < -1024 {
				decoded = -1024
				r.rep.Clamped++
			} else if decoded > 1024 {
				decoded = 1024
				r.rep.Clamped++
			}
			value.Z = int16(decoded)
		case 0xcd3a: // w
			if kind != 3 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(2) {
				r.rep.Malformed = true
				return false
			}
			decoded := int16(r.get16())
			if decoded < -1024 {
				decoded = -1024
				r.rep.Clamped++
			} else if decoded > 1024 {
				decoded = 1024
				r.rep.Clamped++
			}
			value.W = int16(decoded)
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteRigidBody appends value's table-wire encoding and returns the buffer.
func TableWriteRigidBody(value *RigidBody) []byte {
	w := &tableWriter{}
	tableWriteRigidBody(w, value)
	return w.buf
}

func tableWriteRigidBody(w *tableWriter, value *RigidBody) {
	{
		fieldAt := len(w.buf)
		w.u16(0xdd45) // position
		w.u8(13)
		lenAt := len(w.buf)
		w.u32(0)
		tableWriteVec3(w, &value.Position)
		if len(w.buf)-lenAt-4 <= 2 {
			w.buf = w.buf[:fieldAt] // all-default nested elides
		} else {
			w.patch32(lenAt, uint32(len(w.buf)-lenAt-4))
		}
	}
	{
		fieldAt := len(w.buf)
		w.u16(0x7964) // orientation
		w.u8(13)
		lenAt := len(w.buf)
		w.u32(0)
		tableWriteQuat(w, &value.Orientation)
		if len(w.buf)-lenAt-4 <= 2 {
			w.buf = w.buf[:fieldAt] // all-default nested elides
		} else {
			w.patch32(lenAt, uint32(len(w.buf)-lenAt-4))
		}
	}
	if value.AtRest != false {
		w.u16(0xf9eb) // at_rest
		w.u8(1)
		if value.AtRest {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if !value.AtRest {
		{
			fieldAt := len(w.buf)
			w.u16(0x0637) // linear_velocity
			w.u8(13)
			lenAt := len(w.buf)
			w.u32(0)
			tableWriteVec3(w, &value.LinearVelocity)
			if len(w.buf)-lenAt-4 <= 2 {
				w.buf = w.buf[:fieldAt] // all-default nested elides
			} else {
				w.patch32(lenAt, uint32(len(w.buf)-lenAt-4))
			}
		}
	}
	if !value.AtRest {
		{
			fieldAt := len(w.buf)
			w.u16(0x01a7) // angular_velocity
			w.u8(13)
			lenAt := len(w.buf)
			w.u32(0)
			tableWriteVec3(w, &value.AngularVelocity)
			if len(w.buf)-lenAt-4 <= 2 {
				w.buf = w.buf[:fieldAt] // all-default nested elides
			} else {
				w.patch32(lenAt, uint32(len(w.buf)-lenAt-4))
			}
		}
	}
	w.u16(0) // terminator
}

// TableReadRigidBody decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadRigidBody(data []byte, value *RigidBody, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadRigidBody(r, value)
}

func tableReadRigidBody(r *tableReader, value *RigidBody) bool {
	*value = RigidBody{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0xdd45: // position
			if kind != 13 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			bodyLen := int(r.get32())
			if !r.has(bodyLen) {
				r.rep.Malformed = true
				return false
			}
			sub := &tableReader{buf: r.buf[r.off : r.off+bodyLen], rep: r.rep}
			tableReadVec3(sub, &value.Position)
			r.off += bodyLen
		case 0x7964: // orientation
			if kind != 13 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			bodyLen := int(r.get32())
			if !r.has(bodyLen) {
				r.rep.Malformed = true
				return false
			}
			sub := &tableReader{buf: r.buf[r.off : r.off+bodyLen], rep: r.rep}
			tableReadQuat(sub, &value.Orientation)
			r.off += bodyLen
		case 0xf9eb: // at_rest
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.AtRest = r.get8() != 0
		case 0x0637: // linear_velocity
			if kind != 13 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			bodyLen := int(r.get32())
			if !r.has(bodyLen) {
				r.rep.Malformed = true
				return false
			}
			sub := &tableReader{buf: r.buf[r.off : r.off+bodyLen], rep: r.rep}
			tableReadVec3(sub, &value.LinearVelocity)
			r.off += bodyLen
		case 0x01a7: // angular_velocity
			if kind != 13 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			bodyLen := int(r.get32())
			if !r.has(bodyLen) {
				r.rep.Malformed = true
				return false
			}
			sub := &tableReader{buf: r.buf[r.off : r.off+bodyLen], rep: r.rep}
			tableReadVec3(sub, &value.AngularVelocity)
			r.off += bodyLen
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteInput appends value's table-wire encoding and returns the buffer.
func TableWriteInput(value *Input) []byte {
	w := &tableWriter{}
	tableWriteInput(w, value)
	return w.buf
}

func tableWriteInput(w *tableWriter, value *Input) {
	if value.StickX != 0 {
		w.u16(0x5c38) // stick_x
		w.u8(10)
		w.u32(math.Float32bits(value.StickX))
	}
	if value.StickY != 0 {
		w.u16(0x5c8b) // stick_y
		w.u8(10)
		w.u32(math.Float32bits(value.StickY))
	}
	if value.Throttle != 0 {
		w.u16(0x0552) // throttle
		w.u8(10)
		w.u32(math.Float32bits(value.Throttle))
	}
	if value.Yaw != 0 {
		w.u16(0x80c1) // yaw
		w.u8(10)
		w.u32(math.Float32bits(value.Yaw))
	}
	if value.Pitch != 0 {
		w.u16(0xf783) // pitch
		w.u8(10)
		w.u32(math.Float32bits(value.Pitch))
	}
	if value.Fire != false {
		w.u16(0x9872) // fire
		w.u8(1)
		if value.Fire {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if value.AltFire != false {
		w.u16(0x048a) // alt_fire
		w.u8(1)
		if value.AltFire {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if value.Boost != false {
		w.u16(0xdcc5) // boost
		w.u8(1)
		if value.Boost {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if value.Brake != false {
		w.u16(0xa81d) // brake
		w.u8(1)
		if value.Brake {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if value.Aim != false {
		w.u16(0x69c4) // aim
		w.u8(1)
		if value.Aim {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if value.LockOn != false {
		w.u16(0x21cc) // lock_on
		w.u8(1)
		if value.LockOn {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if value.Zoom != false {
		w.u16(0x3da0) // zoom
		w.u8(1)
		if value.Zoom {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if value.Ping != false {
		w.u16(0xe6d4) // ping
		w.u8(1)
		if value.Ping {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	w.u16(0) // terminator
}

// TableReadInput decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadInput(data []byte, value *Input, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadInput(r, value)
}

func tableReadInput(r *tableReader, value *Input) bool {
	*value = Input{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0x5c38: // stick_x
			if kind != 10 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			value.StickX = math.Float32frombits(r.get32())
		case 0x5c8b: // stick_y
			if kind != 10 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			value.StickY = math.Float32frombits(r.get32())
		case 0x0552: // throttle
			if kind != 10 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			value.Throttle = math.Float32frombits(r.get32())
		case 0x80c1: // yaw
			if kind != 10 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			value.Yaw = math.Float32frombits(r.get32())
		case 0xf783: // pitch
			if kind != 10 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			value.Pitch = math.Float32frombits(r.get32())
		case 0x9872: // fire
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.Fire = r.get8() != 0
		case 0x048a: // alt_fire
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.AltFire = r.get8() != 0
		case 0xdcc5: // boost
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.Boost = r.get8() != 0
		case 0xa81d: // brake
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.Brake = r.get8() != 0
		case 0x69c4: // aim
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.Aim = r.get8() != 0
		case 0x21cc: // lock_on
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.LockOn = r.get8() != 0
		case 0x3da0: // zoom
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.Zoom = r.get8() != 0
		case 0xe6d4: // ping
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.Ping = r.get8() != 0
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteInputPacket appends value's table-wire encoding and returns the buffer.
func TableWriteInputPacket(value *InputPacket) []byte {
	w := &tableWriter{}
	tableWriteInputPacket(w, value)
	return w.buf
}

func tableWriteInputPacket(w *tableWriter, value *InputPacket) {
	if value.SynchronizeSequence != 0 {
		w.u16(0x44ed) // synchronize_sequence
		w.u8(7)
		w.u16(uint16(value.SynchronizeSequence))
	}
	if value.CurrentFrame != 0 {
		w.u16(0xc9ce) // current_frame
		w.u8(9)
		w.u64(uint64(value.CurrentFrame))
	}
	if value.StartFrame != 0 {
		w.u16(0x3d37) // start_frame
		w.u8(9)
		w.u64(uint64(value.StartFrame))
	}
	if value.InputsCount > 0 {
		w.u16(0x9e2e) // inputs
		w.u8(14)
		lenAt := len(w.buf)
		w.u32(0)
		w.u8(13)
		w.u16(uint16(value.InputsCount))
		for i := int32(0); i < value.InputsCount; i++ {
			elemLenAt := len(w.buf)
			w.u32(0)
			tableWriteInput(w, &value.Inputs[i])
			w.patch32(elemLenAt, uint32(len(w.buf)-elemLenAt-4))
		}
		w.patch32(lenAt, uint32(len(w.buf)-lenAt-4))
	}
	w.u16(0) // terminator
}

// TableReadInputPacket decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadInputPacket(data []byte, value *InputPacket, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadInputPacket(r, value)
}

func tableReadInputPacket(r *tableReader, value *InputPacket) bool {
	*value = InputPacket{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0x44ed: // synchronize_sequence
			if kind != 7 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(2) {
				r.rep.Malformed = true
				return false
			}
			decoded := r.get16()
			value.SynchronizeSequence = uint16(decoded)
		case 0xc9ce: // current_frame
			if kind != 9 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			decoded := r.get64()
			value.CurrentFrame = uint64(decoded)
		case 0x3d37: // start_frame
			if kind != 9 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			decoded := r.get64()
			value.StartFrame = uint64(decoded)
		case 0x9e2e: // inputs
			if kind != 14 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			bodyLen := int(r.get32())
			if !r.has(bodyLen) {
				r.rep.Malformed = true
				return false
			}
			bodyEnd := r.off + bodyLen
			if bodyLen >= 3 {
				elemKind := r.get8()
				count := int(r.get16())
				if elemKind != 13 {
					r.rep.KindMismatch++
					r.off = bodyEnd
					break
				}
				keep := count
				if keep > 16 {
					keep = 16
					r.rep.Clamped++
				}
				for i := 0; i < keep; i++ {
					if !r.has(4) {
						r.rep.Malformed = true
						return false
					}
					elemLen := int(r.get32())
					if !r.has(elemLen) {
						r.rep.Malformed = true
						return false
					}
					sub := &tableReader{buf: r.buf[r.off : r.off+elemLen], rep: r.rep}
					tableReadInput(sub, &value.Inputs[i])
					r.off += elemLen
				}
				value.InputsCount = int32(keep)
			}
			r.off = bodyEnd // excess elements and slack skip via the length
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}

// TableWriteShipCreate appends value's table-wire encoding and returns the buffer.
func TableWriteShipCreate(value *ShipCreate) []byte {
	w := &tableWriter{}
	tableWriteShipCreate(w, value)
	return w.buf
}

func tableWriteShipCreate(w *tableWriter, value *ShipCreate) {
	if value.ShipType != ShipTypeNone {
		w.u16(0x38e9) // ship_type
		w.u8(6)
		w.u8(uint8(value.ShipType))
	}
	{
		fieldAt := len(w.buf)
		w.u16(0xdd45) // position
		w.u8(13)
		lenAt := len(w.buf)
		w.u32(0)
		tableWriteQuantizedPosition(w, &value.Position)
		if len(w.buf)-lenAt-4 <= 2 {
			w.buf = w.buf[:fieldAt] // all-default nested elides
		} else {
			w.patch32(lenAt, uint32(len(w.buf)-lenAt-4))
		}
	}
	{
		fieldAt := len(w.buf)
		w.u16(0x60f3) // rotation
		w.u8(13)
		lenAt := len(w.buf)
		w.u32(0)
		tableWriteQuantizedRotation(w, &value.Rotation)
		if len(w.buf)-lenAt-4 <= 2 {
			w.buf = w.buf[:fieldAt] // all-default nested elides
		} else {
			w.patch32(lenAt, uint32(len(w.buf)-lenAt-4))
		}
	}
	{
		fieldAt := len(w.buf)
		w.u16(0x0637) // linear_velocity
		w.u8(13)
		lenAt := len(w.buf)
		w.u32(0)
		tableWriteQuantizedVelocity(w, &value.LinearVelocity)
		if len(w.buf)-lenAt-4 <= 2 {
			w.buf = w.buf[:fieldAt] // all-default nested elides
		} else {
			w.patch32(lenAt, uint32(len(w.buf)-lenAt-4))
		}
	}
	if value.HasFlags != false {
		w.u16(0xaa8d) // has_flags
		w.u8(1)
		if value.HasFlags {
			w.u8(1)
		} else {
			w.u8(0)
		}
	}
	if value.HasFlags {
		if value.Flags != 0 {
			w.u16(0xe64b) // flags
			w.u8(9)
			w.u64(uint64(value.Flags))
		}
	}
	if value.Team != TeamNone {
		w.u16(0xdff1) // team
		w.u8(6)
		w.u8(uint8(value.Team))
	}
	if value.Health != 0 {
		w.u16(0x8617) // health
		w.u8(3)
		w.u16(uint16(value.Health))
	}
	if value.Thrust != 0 {
		w.u16(0x9e51) // thrust
		w.u8(2)
		w.u8(uint8(value.Thrust))
	}
	w.u16(0) // terminator
}

// TableReadShipCreate decodes a table-wire buffer under the permissive contract:
// declared defaults prefill, known fields overlay, unknown ids and kind
// mismatches skip and count, out-of-range values clamp and count. false
// means malformed — the partial decode up to that point is kept.
func TableReadShipCreate(data []byte, value *ShipCreate, report *TableReport) bool {
	r := &tableReader{buf: data, rep: report}
	return tableReadShipCreate(r, value)
}

func tableReadShipCreate(r *tableReader, value *ShipCreate) bool {
	*value = ShipCreate{} // prefill (all-zero defaults), then overlay
	for {
		if !r.has(2) {
			r.rep.Malformed = true
			return false
		}
		fieldId := r.get16()
		if fieldId == 0 {
			return true
		}
		if !r.has(1) {
			r.rep.Malformed = true
			return false
		}
		kind := r.get8()
		switch fieldId {
		case 0x38e9: // ship_type
			if kind != 6 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			raw := r.get8()
			if raw > 5 {
				raw = 0 // out-of-set -> None
				r.rep.Clamped++
			}
			value.ShipType = ShipType(raw)
		case 0xdd45: // position
			if kind != 13 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			bodyLen := int(r.get32())
			if !r.has(bodyLen) {
				r.rep.Malformed = true
				return false
			}
			sub := &tableReader{buf: r.buf[r.off : r.off+bodyLen], rep: r.rep}
			tableReadQuantizedPosition(sub, &value.Position)
			r.off += bodyLen
		case 0x60f3: // rotation
			if kind != 13 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			bodyLen := int(r.get32())
			if !r.has(bodyLen) {
				r.rep.Malformed = true
				return false
			}
			sub := &tableReader{buf: r.buf[r.off : r.off+bodyLen], rep: r.rep}
			tableReadQuantizedRotation(sub, &value.Rotation)
			r.off += bodyLen
		case 0x0637: // linear_velocity
			if kind != 13 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(4) {
				r.rep.Malformed = true
				return false
			}
			bodyLen := int(r.get32())
			if !r.has(bodyLen) {
				r.rep.Malformed = true
				return false
			}
			sub := &tableReader{buf: r.buf[r.off : r.off+bodyLen], rep: r.rep}
			tableReadQuantizedVelocity(sub, &value.LinearVelocity)
			r.off += bodyLen
		case 0xaa8d: // has_flags
			if kind != 1 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			value.HasFlags = r.get8() != 0
		case 0xe64b: // flags
			if kind != 9 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(8) {
				r.rep.Malformed = true
				return false
			}
			value.Flags = ShipFlags(r.get64())
		case 0xdff1: // team
			if kind != 6 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			raw := r.get8()
			if raw > 2 {
				raw = 0 // out-of-set -> None
				r.rep.Clamped++
			}
			value.Team = Team(raw)
		case 0x8617: // health
			if kind != 3 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(2) {
				r.rep.Malformed = true
				return false
			}
			decoded := int16(r.get16())
			if decoded < 0 {
				decoded = 0
				r.rep.Clamped++
			} else if decoded > 1000 {
				decoded = 1000
				r.rep.Clamped++
			}
			value.Health = int16(decoded)
		case 0x9e51: // thrust
			if kind != 2 {
				r.rep.KindMismatch++
				if !r.skip(kind) {
					r.rep.Malformed = true
					return false
				}
				break
			}
			if !r.has(1) {
				r.rep.Malformed = true
				return false
			}
			decoded := int8(r.get8())
			if decoded < 0 {
				decoded = 0
				r.rep.Clamped++
			} else if decoded > 100 {
				decoded = 100
				r.rep.Clamped++
			}
			value.Thrust = int8(decoded)
		default:
			r.rep.Unknown++
			if !r.skip(kind) {
				r.rep.Malformed = true
				return false
			}
		}
	}
}
