// The fixed-point + 128-bit corpus unit's test binary (examples128/ ->
// generated/cpp/ludicrous). Round-trips the new wire families through the
// classic serialize runtime's fixed-point surface and byte-compares against
// EXPECTED ARRAYS DERIVED INDEPENDENTLY FROM STANDARD.md — the derivation
// implements the wire law by hand (bit i of the stream lives in byte i/8 at
// bit position i%8; ranged values are value - min in bit-length-of-range
// bits; fixed is the raw scaled offset in bitlen(max - min) + F bits;
// uint128 is 128 raw bits low qword first), never by calling serialize. The
// golden .bin files under testdata/wire/ were written FROM that derivation,
// so the C++ run asserts generated bytes == derived bytes both in-source and
// on disk. A mismatch is stop-the-line (SPEC §3.1, §7.2 gate 7).

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "LudicrousWire.h"
#include "LudicrousTable.h" // every type here is table-tainted (int128/fixed); the header must still compile

#define check( condition )                                                    \
    do                                                                        \
    {                                                                         \
        if ( !( condition ) )                                                 \
        {                                                                     \
            printf( "FAILED: %s (%s:%d)\n", #condition, __FILE__, __LINE__ ); \
            return 1;                                                         \
        }                                                                     \
    } while ( 0 )

// Golden wire bytes (SPEC §7.2 gate 7) — same contract as test/main.cpp.
static bool golden_wire( const char * name, const uint8_t * data, int64_t bytes )
{
    char path[256];
    snprintf( path, sizeof( path ), "testdata/wire/%s.bin", name );
    if ( std::getenv( "SCHEMA_UPDATE_WIRE_GOLDENS" ) )
    {
        FILE * f = fopen( path, "wb" );
        if ( !f )
        {
            printf( "cannot write %s\n", path );
            return false;
        }
        fwrite( data, 1, (size_t) bytes, f );
        fclose( f );
        return true;
    }
    FILE * f = fopen( path, "rb" );
    if ( !f )
    {
        printf( "missing wire golden %s (run: make update-goldens)\n", path );
        return false;
    }
    static uint8_t expected[4096];
    size_t n = fread( expected, 1, sizeof( expected ), f );
    fclose( f );
    if ( (int64_t) n != bytes || std::memcmp( expected, data, (size_t) bytes ) != 0 )
    {
        printf( "WIRE GOLDEN MISMATCH: %s (%lld golden vs %lld actual bytes) — stop-the-line (SPEC §3.1, §7.2 gate 7)\n",
                name, (long long) n, (long long) bytes );
        return false;
    }
    return true;
}

// set_bits forces bits [pos, pos + n) of the stream image to 1 — the hostile
// reader's tool: smuggling an offset into the range's bit headroom, which a
// read must REJECT, never clamp (STANDARD.md).
static void set_bits( uint8_t * data, int pos, int n )
{
    for ( int i = pos; i < pos + n; i++ )
    {
        data[i / 8] = (uint8_t) ( data[i / 8] | ( 1 << ( i % 8 ) ) );
    }
}

// put_bits writes value's low n bits into bits [pos, pos + n) of the image —
// the STANDARD.md wire law implemented directly (bit i of the stream lives in
// byte i/8 at bit position i%8), never by calling serialize. The NarrowBody
// expected images are DERIVED with this at run time, same independence
// contract as the static arrays above.
static void put_bits( uint8_t * data, int pos, int n, uint64_t value )
{
    for ( int i = 0; i < n; i++ )
    {
        if ( ( value >> i ) & 1 )
        {
            data[( pos + i ) / 8] = (uint8_t) ( data[( pos + i ) / 8] | ( 1 << ( ( pos + i ) % 8 ) ) );
        }
    }
}

// The STANDARD.md-derived images (see tools note at top). Field derivation,
// in wire order — offsets are value - min in the unsigned domain:
//   mode      enum [0,3]                 = 3                    ->   3 in  2 bits
//   angle     fixed(16,16)  [-180,180]   = raw +45.5 * 2^16     ->  14778368 in 25 bits   (bitlen(360)+16)
//   position  fixed(48,16)  [-30000,30000] = raw -12346.1875*2^16 -> 1156960256 in 32 bits (bitlen(60000)+16)
//   reach     fixed(112,16) [-1e6,1e6]   = raw_max - 1          ->  131071999999 in 37 bits (bitlen(2e6)+16)
//   ticks     fixed(32,0)   [0,1e6]      = 777777               ->  777777 in 20 bits     (bitlen(1e6)+0)
//   samples0  fixed(16,16)  [-8,8]       = raw_min              ->  0 in 21 bits          (bitlen(16)+16)
//   samples1  fixed(16,16)  [-8,8]       = raw_max              ->  1048576 in 21 bits
//   entity_id uint128 = 0x0123456789ABCDEF_FEDCBA9876543210     ->  lo 64 bits, hi 64 bits
//   energy    int128 [-5e9,5e9]          = 4999999999           ->  9999999999 in 34 bits (bitlen(1e10))
//   flux      int128 [-2^100,2^100]      = 2^99 + 7             ->  2^100 + 2^99 + 7 in 102 bits
//   bias      int128 [-1000,1000]        = -250 (its DEFAULT)   ->  750 in 11 bits
//   seed      uint128                    = 2^65 (its DEFAULT)   ->  128 bits
//   keys      [<= 4]uint128 count = 2                           ->  2 in 3 bits, then 2 x 128 bits
//   has_target bool                                             ->  1 bit
//   target_id uint128 = 42 (taken branch only)                  ->  128 bits
// Totals: 949 bits = 119 bytes taken, 821 bits = 103 bytes untaken.
static const uint8_t expected_ludicrous_state[119] =
{
    0x03, 0x00, 0x86, 0x03, 0x80, 0xAE, 0x27, 0xFA, 0xFF, 0xFF, 0x23, 0xF4,
    0x31, 0xDE, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x20, 0x84, 0x0C, 0x95, 0x1D,
    0xA6, 0x2E, 0xB7, 0xFF, 0x7B, 0xF3, 0x6A, 0xE2, 0x59, 0xD1, 0x48, 0xC0,
    0xFF, 0xF8, 0x02, 0x95, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x98, 0xBB, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x58, 0x05, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t expected_ludicrous_state_untargeted[103] =
{
    0x03, 0x00, 0x86, 0x03, 0x80, 0xAE, 0x27, 0xFA, 0xFF, 0xFF, 0x23, 0xF4,
    0x31, 0xDE, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x20, 0x84, 0x0C, 0x95, 0x1D,
    0xA6, 0x2E, 0xB7, 0xFF, 0x7B, 0xF3, 0x6A, 0xE2, 0x59, 0xD1, 0x48, 0xC0,
    0xFF, 0xF8, 0x02, 0x95, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x98, 0xBB, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08,
};

static ludicrous::LudicrousState make_state()
{
    using namespace ludicrous;
    LudicrousState in;
    in.mode = DriveMode::Ludicrous;
    in.probe.angle = 2981888;                                   // +45.5 * 2^16
    in.probe.position = -809119744ll;                           // -12346.1875 * 2^16
    in.probe.reach = serialize::int128_t( 65536000000ll - 1 );  // raw_max - 1
    in.probe.ticks = 777777;
    in.probe.samples[0] = -524288;                              // raw_min
    in.probe.samples[1] = 524288;                               // raw_max
    in.wide.entity_id = ( serialize::uint128_t( 0x0123456789ABCDEFull ) << 64 )
                      | serialize::uint128_t( 0xFEDCBA9876543210ull );
    in.wide.energy = serialize::int128_t( 4999999999ll );
    in.wide.flux = ( serialize::int128_t( 1 ) << 99 ) + serialize::int128_t( 7 );
    // wide.bias and wide.seed stay at their SPECIFIED DEFAULTS (-250 and
    // 2^65) — construction installs them, and they ride the wire as written
    in.keys_count = 2;
    in.keys[0] = serialize::uint128_t( 1 );
    in.keys[1] = serialize::uint128_t( 1 ) << 127;
    in.has_target = true;
    in.target_id = serialize::uint128_t( 42 );
    return in;
}

int main()
{
    using namespace ludicrous;

    // worst-case bounds, hand-derived (SPEC §6.1 item 4):
    //   FixedProbe    25 + 32 + 37 + 20 + 2*21               = 156
    //   WideProbe     128 + 34 + 102 + 11 + 128              = 403
    //   LudicrousState 2 + 156 + 403 + (3 + 4*128) + 1 + 128 = 1205
    //   Message       tag [0,1] = 1 bit + 1205               = 1206
    static_assert(FixedProbeMaxBits == 156, "FixedProbe worst case");
    static_assert(WideProbeMaxBits == 403, "WideProbe worst case");
    static_assert(LudicrousStateMaxBits == 1205, "LudicrousState worst case");
    static_assert(MessageMaxBits == 1206, "message-level bound");
    static_assert(ProtocolId != 0, "the unit has a protocol id");

    // zero initialization with specified defaults (SPEC §4.2), sentinel-zero
    // composition: a fresh state starts at DriveMode::None — the null rides
    // in-band — and the two defaulted 128-bit fields construct to their
    // declared values, one of which no int64 literal can spell
    {
        LudicrousState zero;
        check( zero.mode == DriveMode::None );
        check( zero.probe.reach == serialize::int128_t( 0 ) );
        check( zero.wide.entity_id == serialize::uint128_t( 0 ) );
        check( zero.wide.bias == serialize::int128_t( -250 ) );
        check( zero.wide.seed == serialize::uint128_t( 1 ) << 65 );
        check( zero.keys_count == 0 );
        check( zero.target_id == serialize::uint128_t( 0 ) );
    }

    alignas( 8 ) uint8_t buffer[256];

    // ---- the taken-branch wire: generated bytes == STANDARD.md-derived ----
    {
        LudicrousState in = make_state();
        serialize::WriteStream ws( buffer, sizeof( buffer ) );
        check( WriteLudicrousState( ws, in ) );
        ws.Flush();
        check( ws.GetBytesProcessed() == (int) sizeof( expected_ludicrous_state ) );
        check( std::memcmp( buffer, expected_ludicrous_state, sizeof( expected_ludicrous_state ) ) == 0 );
        check( golden_wire( "ludicrous_state", buffer, ws.GetBytesProcessed() ) );

        LudicrousState out;
        serialize::ReadStream rs( buffer, ws.GetBytesProcessed() );
        check( ReadLudicrousState( rs, out ) );
        check( out.mode == DriveMode::Ludicrous );
        check( out.probe.angle == in.probe.angle );
        check( out.probe.position == in.probe.position );
        check( out.probe.reach == in.probe.reach );
        check( out.probe.ticks == in.probe.ticks );
        check( out.probe.samples[0] == in.probe.samples[0] );
        check( out.probe.samples[1] == in.probe.samples[1] );
        check( out.wide.entity_id == in.wide.entity_id );
        check( out.wide.energy == in.wide.energy );
        check( out.wide.flux == in.wide.flux );
        check( out.wide.bias == serialize::int128_t( -250 ) );
        check( out.wide.seed == serialize::uint128_t( 1 ) << 65 );
        check( out.keys_count == 2 );
        check( out.keys[0] == in.keys[0] );
        check( out.keys[1] == in.keys[1] );
        check( out.has_target && out.target_id == serialize::uint128_t( 42 ) );
    }

    // ---- the untaken branch: identical prefix, and the 128-bit field under
    // it reads back ZERO into a dirty object (SPEC §5) ----
    {
        LudicrousState in = make_state();
        in.has_target = false;
        serialize::WriteStream ws( buffer, sizeof( buffer ) );
        check( WriteLudicrousState( ws, in ) );
        ws.Flush();
        check( ws.GetBytesProcessed() == (int) sizeof( expected_ludicrous_state_untargeted ) );
        check( std::memcmp( buffer, expected_ludicrous_state_untargeted, sizeof( expected_ludicrous_state_untargeted ) ) == 0 );
        check( golden_wire( "ludicrous_state_untargeted", buffer, ws.GetBytesProcessed() ) );

        LudicrousState out;
        out.target_id = serialize::uint128_t( 0xDEAD ); // dirty — the read must zero it
        serialize::ReadStream rs( buffer, ws.GetBytesProcessed() );
        check( ReadLudicrousState( rs, out ) );
        check( !out.has_target );
        check( out.target_id == serialize::uint128_t( 0 ) );
    }

    // ---- hostile reads REJECT, never clamp (STANDARD.md, SPEC §5) ----
    {
        // fixed: angle's 25 offset bits start at bit 2; all-ones = 33554431,
        // above the raw range 360 * 2^16 = 23592960
        uint8_t hostile[sizeof( expected_ludicrous_state )];
        std::memcpy( hostile, expected_ludicrous_state, sizeof( hostile ) );
        set_bits( hostile, 2, 25 );
        LudicrousState out;
        serialize::ReadStream rs( hostile, sizeof( hostile ) );
        check( !ReadLudicrousState( rs, out ) );
    }
    {
        // int128: energy's 34 offset bits start at bit 286 (2+156+128);
        // all-ones = 2^34 - 1 = 17179869183, above the range 10^10
        uint8_t hostile[sizeof( expected_ludicrous_state )];
        std::memcpy( hostile, expected_ludicrous_state, sizeof( hostile ) );
        set_bits( hostile, 286, 34 );
        LudicrousState out;
        serialize::ReadStream rs( hostile, sizeof( hostile ) );
        check( !ReadLudicrousState( rs, out ) );
    }
    {
        // truncation: running out of input mid-read is a read failure (SPEC §5)
        LudicrousState out;
        serialize::ReadStream rs( buffer, 4 );
        check( !ReadLudicrousState( rs, out ) );
    }

    // ---- NarrowBody: the narrowed fixed shallow (SPEC §4.8 rule 2b) ----
    // The Quantize/Unquantize pair RETURNS as round-to-nearest arithmetic
    // shifts (ties toward +infinity — the ( raw + half ) >> drop form), the
    // shallow wire carries the narrowed per-component ints, and the deep
    // wire stays full precision. Derivation, in wire order:
    //   shallow: position 3 x 26 bits ([-100000, 100000] x 256), rotation
    //            4 x 12 bits ([-1, 1] x 1024), velocity 3 x 34 bits (full
    //            Q48.16 over [-100000, 100000]) = 228 bits = 29 bytes
    //   deep:    position/velocity 3 x 34, rotation 4 x 32 = 332 bits = 42 bytes
    {
        static_assert( NarrowBodyData_ShallowMaxBits == 228, "narrowed shallow worst case" );
        static_assert( NarrowBodyData_DeepMaxBits == 332, "narrow deep worst case" );

        NarrowBodyData_Interpolate in;
        in.position.x = 384;                                    // +1.5 eighths: tie, rounds UP to 2
        in.position.y = -384;                                   // -1.5 eighths: tie, rounds toward +inf to -1
        in.position.z = -6586368ll;                             // -100.5 * 2^16, exact in 8 kept bits
        in.rotation.x = 0;                                      // identity...
        in.rotation.y = 0;
        in.rotation.z = 0;
        in.rotation.w = 1 << 30;                                // ...w = 1.0, hits the +1024 bound exactly
        in.velocity.x = 1;                                      // one raw ulp survives full precision
        in.velocity.y = -1;
        in.velocity.z = 123456789ll;

        // the pair is pure integer shifts — pin the tie semantics in source
        NarrowBodyData_Shallow sh;
        QuantizeNarrowBody( in, sh );
        check( sh.position_x == 2 );
        check( sh.position_y == -1 );                           // half-away would say -2 — the shift form is pinned
        check( sh.position_z == -25728 );
        check( sh.rotation_x == 0 && sh.rotation_y == 0 && sh.rotation_z == 0 );
        check( sh.rotation_w == 1024 );
        check( sh.velocity.x == 1 && sh.velocity.y == -1 && sh.velocity.z == 123456789ll );

        NarrowBodyData_Interpolate back;
        UnquantizeNarrowBody( sh, back );
        check( back.position.x == 512 );                        // narrowing loss, 384 -> 2 -> 512
        check( back.position.y == -256 );
        check( back.position.z == -6586368ll );                 // exact multiple of 2^8 restores exactly
        check( back.rotation.w == 1 << 30 );                    // the identity survives the round trip
        check( back.velocity.z == 123456789ll );

        // shallow wire: generated bytes == wire-law-derived bytes
        uint8_t expected_shallow[29] = { 0 };
        {
            int pos = 0;
            put_bits( expected_shallow, pos, 26, uint64_t( 2 + 25600000 ) ); pos += 26;
            put_bits( expected_shallow, pos, 26, uint64_t( -1 + 25600000 ) ); pos += 26;
            put_bits( expected_shallow, pos, 26, uint64_t( -25728 + 25600000 ) ); pos += 26;
            put_bits( expected_shallow, pos, 12, uint64_t( 0 + 1024 ) ); pos += 12;
            put_bits( expected_shallow, pos, 12, uint64_t( 0 + 1024 ) ); pos += 12;
            put_bits( expected_shallow, pos, 12, uint64_t( 0 + 1024 ) ); pos += 12;
            put_bits( expected_shallow, pos, 12, uint64_t( 1024 + 1024 ) ); pos += 12;
            put_bits( expected_shallow, pos, 34, uint64_t( 1ll + 6553600000ll ) ); pos += 34;
            put_bits( expected_shallow, pos, 34, uint64_t( -1ll + 6553600000ll ) ); pos += 34;
            put_bits( expected_shallow, pos, 34, uint64_t( 123456789ll + 6553600000ll ) ); pos += 34;
        }
        serialize::WriteStream ws( buffer, sizeof( buffer ) );
        check( WriteNarrowBodyData_Shallow( ws, sh ) );
        ws.Flush();
        check( ws.GetBytesProcessed() == (int) sizeof( expected_shallow ) );
        check( std::memcmp( buffer, expected_shallow, sizeof( expected_shallow ) ) == 0 );
        check( golden_wire( "narrow_body_shallow", buffer, ws.GetBytesProcessed() ) );

        NarrowBodyData_Shallow shOut;
        serialize::ReadStream rs( buffer, ws.GetBytesProcessed() );
        check( ReadNarrowBodyData_Shallow( rs, shOut ) );
        check( shOut.position_x == 2 && shOut.position_y == -1 && shOut.position_z == -25728 );
        check( shOut.rotation_w == 1024 );
        check( shOut.velocity.z == 123456789ll );

        // deep wire: full precision, byte-pinned the same way
        NarrowBodyData_Deep deep;
        deep.position = in.position;
        deep.rotation = in.rotation;
        deep.velocity = in.velocity;
        uint8_t expected_deep[42] = { 0 };
        {
            int pos = 0;
            put_bits( expected_deep, pos, 34, uint64_t( 384ll + 6553600000ll ) ); pos += 34;
            put_bits( expected_deep, pos, 34, uint64_t( -384ll + 6553600000ll ) ); pos += 34;
            put_bits( expected_deep, pos, 34, uint64_t( -6586368ll + 6553600000ll ) ); pos += 34;
            put_bits( expected_deep, pos, 32, uint64_t( 0 + ( 1ll << 30 ) ) ); pos += 32;
            put_bits( expected_deep, pos, 32, uint64_t( 0 + ( 1ll << 30 ) ) ); pos += 32;
            put_bits( expected_deep, pos, 32, uint64_t( 0 + ( 1ll << 30 ) ) ); pos += 32;
            put_bits( expected_deep, pos, 32, uint64_t( ( 1ll << 30 ) + ( 1ll << 30 ) ) ); pos += 32;
            put_bits( expected_deep, pos, 34, uint64_t( 1ll + 6553600000ll ) ); pos += 34;
            put_bits( expected_deep, pos, 34, uint64_t( -1ll + 6553600000ll ) ); pos += 34;
            put_bits( expected_deep, pos, 34, uint64_t( 123456789ll + 6553600000ll ) ); pos += 34;
        }
        serialize::WriteStream wsd( buffer, sizeof( buffer ) );
        check( WriteNarrowBodyData_Deep( wsd, deep ) );
        wsd.Flush();
        check( wsd.GetBytesProcessed() == (int) sizeof( expected_deep ) );
        check( std::memcmp( buffer, expected_deep, sizeof( expected_deep ) ) == 0 );
        check( golden_wire( "narrow_body_deep", buffer, wsd.GetBytesProcessed() ) );

        NarrowBodyData_Deep deepOut;
        serialize::ReadStream rsd( buffer, wsd.GetBytesProcessed() );
        check( ReadNarrowBodyData_Deep( rsd, deepOut ) );
        check( deepOut.position.x == 384 && deepOut.position.y == -384 && deepOut.position.z == -6586368ll );
        check( deepOut.rotation.w == 1 << 30 );
        check( deepOut.velocity.z == 123456789ll );

        // hostile shallow read: position_x's 26 offset bits all-ones =
        // 67108863, above the range size 51200000 — reject, never clamp
        uint8_t hostile[sizeof( expected_shallow )];
        std::memcpy( hostile, expected_shallow, sizeof( hostile ) );
        set_bits( hostile, 0, 26 );
        NarrowBodyData_Shallow hOut;
        serialize::ReadStream hrs( hostile, sizeof( hostile ) );
        check( !ReadNarrowBodyData_Shallow( hrs, hOut ) );
    }

    // ---- the message dispatch surface over the new unit ----
    {
        Message m;
        check( m.type == MessageType::None );
        m.type = MessageType::LudicrousState;
        m.ludicrous_state = make_state();

        serialize::WriteStream ws( buffer, sizeof( buffer ) );
        check( WriteMessage( ws, m ) );
        ws.Flush();

        Message out;
        serialize::ReadStream rs( buffer, ws.GetBytesProcessed() );
        check( ReadMessage( rs, out ) );
        check( GetMessageType( out ) == MessageType::LudicrousState );
        check( out.ludicrous_state.wide.flux == m.ludicrous_state.wide.flux );
        check( out.ludicrous_state.probe.angle == 2981888 );
    }

    printf( "OK\n" );
    return 0;
}
