// Code generated by the schema compiler from WideText.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package wide — protocol id 0x53835dbf9f05e4d9

use serialize::{ReadStream, Stream, WriteStream};

// The unit's protocol id — the hash of its wire shape (SPEC §3.1). Two
// sides at the same id speak identical bits; there is no other versioning.
pub const PROTOCOL_ID: u64 = 0x53835dbf9f05e4d9;

/// The generated crate's error: the runtime's own errors pass through;
/// Validation is a read rejecting the wire (SPEC §4.3, §4.7).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Error {
    Stream(serialize::Error),
    Validation,
}

impl From<serialize::Error> for Error {
    fn from(e: serialize::Error) -> Error {
        Error::Stream(e)
    }
}

// serialize.rs 2.0.0 writes are infallible: their Result carries an
// uninhabited error, and `?` on one needs this vacuous conversion.
impl From<core::convert::Infallible> for Error {
    fn from(e: core::convert::Infallible) -> Error {
        match e {}
    }
}

pub type Result<T = ()> = core::result::Result<T, Error>;

// type WideSeven
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct WideSeven {
    pub text: [u16; 7], // UTF-16 code units (SPEC §4.12)
    pub text_length: i32,
}

// The zero form (SPEC §5): specified defaults live only in new(), never here.
impl Default for WideSeven {
    fn default() -> Self {
        WideSeven {
            text: [0; 7],
            text_length: 0,
        }
    }
}

// WIDE_SEVEN_MAX_BITS is the longest wire path; align pads at worst case (SPEC §6.1).
// WIDE_SEVEN_MAX_BYTES is rounded up to the 8-byte write-buffer granularity.
pub const WIDE_SEVEN_MAX_BITS: u64 = 227;
pub const WIDE_SEVEN_MAX_BYTES: usize = 32;

#[inline(always)]
pub fn write_wide_seven(stream: &mut WriteStream<'_>, value: &WideSeven) -> Result {
    {
        let mut length = value.text_length;
        if length < 0 || length > 7 {
            return Err(Error::Stream(serialize::Error::ValueOutOfRange));
        }
        stream.serialize_int(&mut length, 0, 7)?;
        for &unit in &value.text[..length as usize] {
            if unit == 0 { return Err(Error::Validation); }
            let mut group = u32::from(unit);
            stream.serialize_bits(&mut group, 32)?;
        }
    }
    Ok(())
}

#[inline]
pub fn read_wide_seven(stream: &mut ReadStream<'_>, value: &mut WideSeven) -> Result {
    stream.serialize_int(&mut value.text_length, 0, 7)?;
    {
        let mut expect_low = false;
        for unit in &mut value.text[..value.text_length as usize] {
            let mut group = 0u32;
            stream.serialize_bits(&mut group, 32)?;
            if group == 0 || group > 0xFFFF { return Err(Error::Validation); }
            let high = (0xD800..=0xDBFF).contains(&group);
            let low = (0xDC00..=0xDFFF).contains(&group);
            if low != expect_low { return Err(Error::Validation); }
            expect_low = high;
            *unit = group as u16;
        }
        if expect_low { return Err(Error::Validation); }
    }
    Ok(())
}

// type WideFour
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct WideFour {
    pub text: [u16; 4], // UTF-16 code units (SPEC §4.12)
    pub text_length: i32,
}

// The zero form (SPEC §5): specified defaults live only in new(), never here.
impl Default for WideFour {
    fn default() -> Self {
        WideFour {
            text: [0; 4],
            text_length: 0,
        }
    }
}

// WIDE_FOUR_MAX_BITS is the longest wire path; align pads at worst case (SPEC §6.1).
// WIDE_FOUR_MAX_BYTES is rounded up to the 8-byte write-buffer granularity.
pub const WIDE_FOUR_MAX_BITS: u64 = 131;
pub const WIDE_FOUR_MAX_BYTES: usize = 24;

#[inline(always)]
pub fn write_wide_four(stream: &mut WriteStream<'_>, value: &WideFour) -> Result {
    {
        let mut length = value.text_length;
        if length < 0 || length > 4 {
            return Err(Error::Stream(serialize::Error::ValueOutOfRange));
        }
        stream.serialize_int(&mut length, 0, 4)?;
        for &unit in &value.text[..length as usize] {
            if unit == 0 { return Err(Error::Validation); }
            let mut group = u32::from(unit);
            stream.serialize_bits(&mut group, 32)?;
        }
    }
    Ok(())
}

#[inline]
pub fn read_wide_four(stream: &mut ReadStream<'_>, value: &mut WideFour) -> Result {
    stream.serialize_int(&mut value.text_length, 0, 4)?;
    {
        let mut expect_low = false;
        for unit in &mut value.text[..value.text_length as usize] {
            let mut group = 0u32;
            stream.serialize_bits(&mut group, 32)?;
            if group == 0 || group > 0xFFFF { return Err(Error::Validation); }
            let high = (0xD800..=0xDBFF).contains(&group);
            let low = (0xDC00..=0xDFFF).contains(&group);
            if low != expect_low { return Err(Error::Validation); }
            expect_low = high;
            *unit = group as u16;
        }
        if expect_low { return Err(Error::Validation); }
    }
    Ok(())
}

// type NarrowFifteen
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct NarrowFifteen {
    pub text: [u8; 15], // string(15): max length, used length beside it (SPEC §4.7)
    pub text_length: i32,
}

// The zero form (SPEC §5): specified defaults live only in new(), never here.
impl Default for NarrowFifteen {
    fn default() -> Self {
        NarrowFifteen {
            text: [0; 15],
            text_length: 0,
        }
    }
}

// NARROW_FIFTEEN_MAX_BITS is the longest wire path; align pads at worst case (SPEC §6.1).
// NARROW_FIFTEEN_MAX_BYTES is rounded up to the 8-byte write-buffer granularity.
pub const NARROW_FIFTEEN_MAX_BITS: u64 = 131;
pub const NARROW_FIFTEEN_MAX_BYTES: usize = 24;

#[inline(always)]
pub fn write_narrow_fifteen(stream: &mut WriteStream<'_>, value: &NarrowFifteen) -> Result {
    if value.text_length < 0 || value.text_length > 15 {
        return Err(Error::Stream(serialize::Error::ValueOutOfRange));
    }
    {
        let mut offset_value = value.text_length as u32;
        stream.serialize_bits(&mut offset_value, 4)?; // the length guards the slice (§6.3)
    }
    stream.write_bytes(&value.text[..value.text_length as usize]); // borrowed in place: the write side never mutates (infallible: returns () in serialize.rs 2.0.0)
    Ok(())
}

#[inline]
pub fn read_narrow_fifteen(stream: &mut ReadStream<'_>, value: &mut NarrowFifteen) -> Result {
    stream.serialize_int(&mut value.text_length, 0, 15)?; // the length guards the slice (§6.3)
    stream.serialize_bytes(&mut value.text[..value.text_length as usize])?;
    if std::str::from_utf8(&value.text[..value.text_length as usize]).is_err() {
        return Err(Error::Validation); // malformed UTF-8 (SPEC §4.7)
    }
    for i in 0..value.text_length as usize {
        if value.text[i] == 0 {
            return Err(Error::Validation);
        }
    }
    Ok(())
}

// type WideInterop
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct WideInterop {
    pub caption: [u16; 7], // UTF-16 code units (SPEC §4.12)
    pub caption_length: i32,
}

// The zero form (SPEC §5): specified defaults live only in new(), never here.
impl Default for WideInterop {
    fn default() -> Self {
        WideInterop {
            caption: [0; 7],
            caption_length: 0,
        }
    }
}

// WIDE_INTEROP_MAX_BITS is the longest wire path; align pads at worst case (SPEC §6.1).
// WIDE_INTEROP_MAX_BYTES is rounded up to the 8-byte write-buffer granularity.
pub const WIDE_INTEROP_MAX_BITS: u64 = 227;
pub const WIDE_INTEROP_MAX_BYTES: usize = 32;

#[inline(always)]
pub fn write_wide_interop(stream: &mut WriteStream<'_>, value: &WideInterop) -> Result {
    {
        let mut length = value.caption_length;
        if length < 0 || length > 7 {
            return Err(Error::Stream(serialize::Error::ValueOutOfRange));
        }
        stream.serialize_int(&mut length, 0, 7)?;
        for &unit in &value.caption[..length as usize] {
            if unit == 0 { return Err(Error::Validation); }
            let mut group = u32::from(unit);
            stream.serialize_bits(&mut group, 32)?;
        }
    }
    Ok(())
}

#[inline]
pub fn read_wide_interop(stream: &mut ReadStream<'_>, value: &mut WideInterop) -> Result {
    stream.serialize_int(&mut value.caption_length, 0, 7)?;
    {
        let mut expect_low = false;
        for unit in &mut value.caption[..value.caption_length as usize] {
            let mut group = 0u32;
            stream.serialize_bits(&mut group, 32)?;
            if group == 0 || group > 0xFFFF { return Err(Error::Validation); }
            let high = (0xD800..=0xDBFF).contains(&group);
            let low = (0xDC00..=0xDFFF).contains(&group);
            if low != expect_low { return Err(Error::Validation); }
            expect_low = high;
            *unit = group as u16;
        }
        if expect_low { return Err(Error::Validation); }
    }
    Ok(())
}

