// The Rust cross-language wire test for the fixed-point + 128-bit unit
// (examples128/): the generated Rust crate writes the SAME pinned instance
// test/ludicrous_main.cpp pins in testdata/wire/ludicrous_state*.bin and
// byte-compares against those files — cross-language wire identity for the
// serialize-phase-1 families (fixed(I, F), int128, uint128) is the §7.2 gate
// this binary carries. Plus round-trips through the Rust reader, the §5
// branch-zeroing check over a 128-bit field, the specified-defaults checks
// (native i128/u128 literals here — no pair composition), and the
// hostile-read rejections the C++ test carries (reject, never clamp —
// STANDARD.md).
//
// Prints OK and exits 0, exactly like its C++ and Go twins. Run from
// test/rust-ludicrous (the Makefile does): the wire goldens are at
// ../../testdata/wire.
//
// Mirrors test/ludicrous_main.cpp block for block.

// Instances are built field-by-field from new() exactly like the Go test
// (the files stay diffable side by side), so clippy's initializer-style
// suggestion is silenced for the whole binary.
#![allow(clippy::field_reassign_with_default)]

use std::sync::atomic::{AtomicBool, Ordering};

use ludicrous::*;
use serialize::{ReadStream, Stream, WriteStream};

static FAILED: AtomicBool = AtomicBool::new(false);

fn check(ok: bool, what: &str) {
    if !ok {
        println!("FAILED: {what}");
        FAILED.store(true, Ordering::Relaxed);
    }
}

fn check_err(result: ludicrous::Result, what: &str) {
    if let Err(e) = result {
        println!("FAILED: {what}: {e:?}");
        FAILED.store(true, Ordering::Relaxed);
    }
}

// golden_wire byte-compares written wire against the C++-pinned golden.
fn golden_wire(name: &str, data: &[u8]) {
    match std::fs::read(format!("../../testdata/wire/{name}.bin")) {
        Ok(golden) => check(
            data == golden.as_slice(),
            &format!("wire golden {name} — Rust bytes must equal the C++-pinned bytes"),
        ),
        Err(e) => {
            println!("FAILED: read wire golden {name}: {e}");
            FAILED.store(true, Ordering::Relaxed);
        }
    }
}

// set_bits forces bits [pos, pos + n) of the stream image to 1 — the hostile
// reader's tool: smuggling an offset into the range's bit headroom, which a
// read must REJECT, never clamp (STANDARD.md).
fn set_bits(data: &mut [u8], pos: usize, n: usize) {
    for i in pos..pos + n {
        data[i / 8] |= 1 << (i % 8);
    }
}

// make_state is test/ludicrous_main.cpp's make_state — the values must stay
// mirrored on both sides.
fn make_state() -> LudicrousState {
    let mut input = LudicrousState::new();
    input.mode = DriveMode::LUDICROUS;
    input.probe.angle = 2981888; // +45.5 * 2^16
    input.probe.position = -809119744; // -12346.1875 * 2^16
    input.probe.reach = 65536000000 - 1; // raw_max - 1
    input.probe.ticks = 777777;
    input.probe.samples[0] = -524288; // raw_min
    input.probe.samples[1] = 524288; // raw_max
    input.wide.entity_id = 0x0123456789ABCDEF_FEDCBA9876543210;
    input.wide.energy = 4999999999;
    input.wide.flux = (1i128 << 99) + 7;
    // wide.bias and wide.seed stay at their SPECIFIED DEFAULTS (-250 and
    // 2^65) — new() installs them, and they ride the wire as written
    input.keys_count = 2;
    input.keys[0] = 1;
    input.keys[1] = 1u128 << 127;
    input.has_target = true;
    input.target_id = 42;
    input
}

fn main() {
    // worst-case bounds, hand-derived (SPEC §6.1 item 4) — the same numbers
    // test/ludicrous_main.cpp static_asserts
    check(FIXED_PROBE_MAX_BITS == 156, "FixedProbe worst case");
    check(WIDE_PROBE_MAX_BITS == 403, "WideProbe worst case");
    check(LUDICROUS_STATE_MAX_BITS == 1205, "LudicrousState worst case");
    check(PROTOCOL_ID != 0, "the unit has a protocol id");

    // zero initialization with specified defaults (SPEC §4.2), sentinel-zero
    // composition: new() starts at DriveMode::NONE — the null rides in-band —
    // and the two defaulted 128-bit fields construct to their declared
    // values, one of which no i64 literal can spell
    {
        let zero = LudicrousState::new();
        check(zero.mode == DriveMode::NONE, "a fresh state starts at DriveMode None");
        check(zero.probe.reach == 0, "reach starts zero");
        check(zero.wide.entity_id == 0, "entity_id starts zero");
        check(zero.wide.bias == -250, "bias defaults -250");
        check(zero.wide.seed == 1u128 << 65, "seed defaults 2^65");
        check(zero.keys_count == 0, "keys start empty");
        check(zero.target_id == 0, "target_id starts zero");
        // Rust keeps the §5 zero form on Default; new() alone installs the
        // defaults (SPEC §4.2, the Rust column)
        check(LudicrousState::default().wide.bias == 0, "the plain zero value stays zero");
    }

    let mut taken_wire = [0u8; 256];
    let taken_len: usize;

    // ---- the taken-branch wire: generated bytes == the C++-pinned golden ----
    {
        let input = make_state();
        let mut buffer = [0u8; 256];
        let mut ws = WriteStream::new(&mut buffer);
        check_err(write_ludicrous_state(&mut ws, &input), "write LudicrousState");
        ws.flush();
        taken_len = ws.bytes_processed() as usize;
        taken_wire[..taken_len].copy_from_slice(&buffer[..taken_len]);
        golden_wire("ludicrous_state", &taken_wire[..taken_len]);

        let mut out = LudicrousState::default();
        let mut rs = ReadStream::new(&taken_wire, taken_len);
        check_err(read_ludicrous_state(&mut rs, &mut out), "read LudicrousState");
        check(out.mode == DriveMode::LUDICROUS, "mode round-trips");
        check(out.probe.angle == input.probe.angle, "angle round-trips");
        check(out.probe.position == input.probe.position, "position round-trips");
        check(out.probe.reach == input.probe.reach, "reach round-trips");
        check(out.probe.ticks == input.probe.ticks, "ticks round-trips");
        check(out.probe.samples == input.probe.samples, "samples round-trip");
        check(out.wide.entity_id == input.wide.entity_id, "entity_id round-trips");
        check(out.wide.energy == input.wide.energy, "energy round-trips");
        check(out.wide.flux == input.wide.flux, "flux round-trips");
        check(out.wide.bias == -250, "the bias default rides the wire");
        check(out.wide.seed == 1u128 << 65, "the seed default rides the wire");
        check(out.keys_count == 2, "keys_count round-trips");
        check(
            out.keys[0] == input.keys[0] && out.keys[1] == input.keys[1],
            "keys round-trip",
        );
        check(out.has_target && out.target_id == 42, "the taken branch round-trips");
    }

    // ---- the untaken branch: identical prefix, and the 128-bit field under
    // it reads back ZERO into a dirty object (SPEC §5) ----
    {
        let mut input = make_state();
        input.has_target = false;
        let mut buffer = [0u8; 256];
        let mut ws = WriteStream::new(&mut buffer);
        check_err(
            write_ludicrous_state(&mut ws, &input),
            "write LudicrousState untargeted",
        );
        ws.flush();
        let n = ws.bytes_processed() as usize;
        golden_wire("ludicrous_state_untargeted", &buffer[..n]);

        let mut out = LudicrousState::default();
        out.target_id = 0xDEAD; // dirty — the read must zero it
        let mut rs = ReadStream::new(&buffer, n);
        check_err(
            read_ludicrous_state(&mut rs, &mut out),
            "read LudicrousState untargeted",
        );
        check(!out.has_target, "has_target reads false");
        check(out.target_id == 0, "the untaken 128-bit field reads as zero (SPEC §5)");
    }

    // ---- hostile reads REJECT, never clamp (STANDARD.md, SPEC §5) ----
    {
        // fixed: angle's 25 offset bits start at bit 2; all-ones = 33554431,
        // above the raw range 360 * 2^16 = 23592960
        let mut hostile = [0u8; 256];
        hostile[..taken_len].copy_from_slice(&taken_wire[..taken_len]);
        set_bits(&mut hostile, 2, 25);
        let mut out = LudicrousState::default();
        let mut rs = ReadStream::new(&hostile, taken_len);
        check(
            read_ludicrous_state(&mut rs, &mut out).is_err(),
            "a smuggled fixed offset is REJECTED",
        );
    }
    {
        // int128: energy's 34 offset bits start at bit 286 (2+156+128);
        // all-ones = 2^34 - 1 = 17179869183, above the range 10^10
        let mut hostile = [0u8; 256];
        hostile[..taken_len].copy_from_slice(&taken_wire[..taken_len]);
        set_bits(&mut hostile, 286, 34);
        let mut out = LudicrousState::default();
        let mut rs = ReadStream::new(&hostile, taken_len);
        check(
            read_ludicrous_state(&mut rs, &mut out).is_err(),
            "a smuggled int128 offset is REJECTED",
        );
    }
    {
        // truncation: running out of input mid-read is a read failure (SPEC §5)
        let mut out = LudicrousState::default();
        let mut rs = ReadStream::new(&taken_wire, 4);
        check(
            read_ludicrous_state(&mut rs, &mut out).is_err(),
            "a truncated stream is a read failure",
        );
    }

    // ---- DegenerateProbe: min == max costs ZERO bits (SPEC §4.6) ----
    // The whole wire is the tail byte; a port that emits ANY bits for a
    // degenerate range shifts it and fails the golden compare.
    {
        check(DEGENERATE_PROBE_MAX_BITS == 8, "three degenerate fields cost zero bits");

        let mut input = DegenerateProbe::default();
        input.locked_fixed = -196608; // -3 * 2^16, the ONE legal raw
        input.locked_int = 7;
        input.locked_wide = -12345678901234;
        input.tail = 0xA5;

        let mut buffer = [0u8; 64];
        let mut ws = WriteStream::new(&mut buffer);
        check_err(write_degenerate_probe(&mut ws, &input), "write DegenerateProbe");
        ws.flush();
        let n = ws.bytes_processed() as usize;
        golden_wire("degenerate_probe", &buffer[..n]);

        let mut out = DegenerateProbe::default();
        let mut rs = ReadStream::new(&buffer, n);
        check_err(read_degenerate_probe(&mut rs, &mut out), "read DegenerateProbe");
        check(out == input, "DegenerateProbe round-trips — every value materialized from its range");
    }

    // ---- UnsignedProbe: ufixed(I, F), the unsigned sibling (SPEC §4.3;
    //) ----
    // span's raw value fills u64's HIGH HALF (above 2^63) — native unsigned
    // storage here, and the C++-pinned golden is the gate. Values mirror
    // test/ludicrous_main.cpp block for block.
    {
        check(UNSIGNED_PROBE_MAX_BITS == 196, "UnsignedProbe worst case");

        let mut input = UnsignedProbe::default();
        input.angle = 2981888; // +45.5 * 2^16
        input.span = 0xFFFF_FFFF_FFFF_0000; // raw_max — the u64 HIGH HALF
        input.reach = 131071999999; // raw_max - 1
        input.ticks = 777777;
        input.samples[0] = 0; // raw_min
        input.samples[1] = 1048576; // raw_max
        input.locked = 196608; // 3 * 2^16, the ONE legal raw
        input.tail = 0xA5;

        let mut buffer = [0u8; 64];
        let mut ws = WriteStream::new(&mut buffer);
        check_err(write_unsigned_probe(&mut ws, &input), "write UnsignedProbe");
        ws.flush();
        let n = ws.bytes_processed() as usize;
        golden_wire("unsigned_probe", &buffer[..n]);

        let mut out = UnsignedProbe::default();
        let mut rs = ReadStream::new(&buffer, n);
        check_err(read_unsigned_probe(&mut rs, &mut out), "read UnsignedProbe");
        check(out == input, "UnsignedProbe round-trips — the u64 high half bit-exact");

        // the write-side degenerate refusal: any raw but 3 * 2^16 is refused
        // before a single bit is written
        let mut bad = input;
        bad.locked = 196609;
        let mut bad_buffer = [0u8; 64];
        let mut bad_ws = WriteStream::new(&mut bad_buffer);
        check(
            write_unsigned_probe(&mut bad_ws, &bad).is_err(),
            "a wrong degenerate ufixed raw is REFUSED on write",
        );

        // hostile: span's 64 offset bits (starting at bit 25) all-ones =
        // 2^64 - 1, above the raw range 0xFFFFFFFFFFFF0000 — the headroom is
        // exactly the low 16 bits, and the reject must fire in the UNSIGNED
        // domain (a signed compare would call the smuggled value negative)
        let mut hostile = [0u8; 25];
        hostile.copy_from_slice(&buffer[..n]);
        set_bits(&mut hostile, 25, 64);
        let mut h_out = UnsignedProbe::default();
        let mut h_rs = ReadStream::new(&hostile, n);
        check(
            read_unsigned_probe(&mut h_rs, &mut h_out).is_err(),
            "a smuggled ufixed high-half offset is REJECTED",
        );
    }

    if FAILED.load(Ordering::Relaxed) {
        std::process::exit(1);
    }
    println!("OK");
}
