/* Generated by the schema compiler from Enums.schema. DO NOT EDIT.
   SPDX-License-Identifier: NONE — this generated output is yours, under terms of
   your choice. See the LICENSE exception in the schema compiler; the compiler is
   AGPL-3.0, its output is not.
   package example — protocol id 0xb6a0276149f6577e */

#ifndef SCHEMA_EXAMPLE_ENUMS_H
#define SCHEMA_EXAMPLE_ENUMS_H

#include <stdint.h>
#include <string.h>   /* memset — the zero form (SPEC §4.2) */
#include <math.h>     /* floor — the quantize pair */

#ifndef SCHEMA_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define SCHEMA_UNUSED __attribute__((unused))
#else
#define SCHEMA_UNUSED
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* enum Team — None = 0 implicit, variants dense from 1, wire range [0, 2]
   (SPEC §4.2). A fixed-width typedef rather than a C enum: an enum's underlying
   type is implementation-defined, and [max = K] headroom makes non-variant
   values wire-legal, which a C enum cannot hold honestly. */
typedef uint8_t Team;
#define TEAM_NONE 0
#define TEAM_RED 1
#define TEAM_BLUE 2
#define TEAM_MAX 2

/* Debug/log name for any Team value, out-of-set included. */
static SCHEMA_UNUSED const char * enum_name_team( Team value )
{
    switch ( value )
    {
        case TEAM_NONE: return "None";
        case 1: return "Red";
        case 2: return "Blue";
        default: return "???";
    }
}


/* enum ShipType — None = 0 implicit, variants dense from 1, wire range [0, 5]
   (SPEC §4.2). A fixed-width typedef rather than a C enum: an enum's underlying
   type is implementation-defined, and [max = K] headroom makes non-variant
   values wire-legal, which a C enum cannot hold honestly. */
typedef uint8_t ShipType;
#define SHIP_TYPE_NONE 0
#define SHIP_TYPE_FIGHTER 1
#define SHIP_TYPE_CORVETTE 2
#define SHIP_TYPE_BOMBER 3
#define SHIP_TYPE_DESTROYER 4
#define SHIP_TYPE_CARRIER 5
#define SHIP_TYPE_MAX 5

/* Debug/log name for any ShipType value, out-of-set included. */
static SCHEMA_UNUSED const char * enum_name_ship_type( ShipType value )
{
    switch ( value )
    {
        case SHIP_TYPE_NONE: return "None";
        case 1: return "Fighter";
        case 2: return "Corvette";
        case 3: return "Bomber";
        case 4: return "Destroyer";
        case 5: return "Carrier";
        default: return "???";
    }
}


/* enum MissileType — None = 0 implicit, variants dense from 1, wire range [0, 3]
   (SPEC §4.2). A fixed-width typedef rather than a C enum: an enum's underlying
   type is implementation-defined, and [max = K] headroom makes non-variant
   values wire-legal, which a C enum cannot hold honestly. */
typedef uint8_t MissileType;
#define MISSILE_TYPE_NONE 0
#define MISSILE_TYPE_HEATSEEKER 1
#define MISSILE_TYPE_TORPEDO 2
#define MISSILE_TYPE_NUKE 3
#define MISSILE_TYPE_MAX 3

/* Debug/log name for any MissileType value, out-of-set included. */
static SCHEMA_UNUSED const char * enum_name_missile_type( MissileType value )
{
    switch ( value )
    {
        case MISSILE_TYPE_NONE: return "None";
        case 1: return "Heatseeker";
        case 2: return "Torpedo";
        case 3: return "Nuke";
        default: return "???";
    }
}


/* enum PropType — None = 0 implicit, variants dense from 1, wire range [0, 6]
   (SPEC §4.2). A fixed-width typedef rather than a C enum: an enum's underlying
   type is implementation-defined, and [max = K] headroom makes non-variant
   values wire-legal, which a C enum cannot hold honestly. */
typedef uint8_t PropType;
#define PROP_TYPE_NONE 0
#define PROP_TYPE_ASTEROID 1
#define PROP_TYPE_CHUNK 2
#define PROP_TYPE_FRAGMENT 3
#define PROP_TYPE_SPHERE 4
#define PROP_TYPE_BLACK_HOLE 5
#define PROP_TYPE_DYSON_PANEL 6
#define PROP_TYPE_MAX 6

/* Debug/log name for any PropType value, out-of-set included. */
static SCHEMA_UNUSED const char * enum_name_prop_type( PropType value )
{
    switch ( value )
    {
        case PROP_TYPE_NONE: return "None";
        case 1: return "Asteroid";
        case 2: return "Chunk";
        case 3: return "Fragment";
        case 4: return "Sphere";
        case 5: return "BlackHole";
        case 6: return "DysonPanel";
        default: return "???";
    }
}


/* enum Pending — None = 0 implicit, variants dense from 1, wire range [0, 0]
   (SPEC §4.2). A fixed-width typedef rather than a C enum: an enum's underlying
   type is implementation-defined, and [max = K] headroom makes non-variant
   values wire-legal, which a C enum cannot hold honestly. */
typedef uint8_t Pending;
#define PENDING_NONE 0
#define PENDING_MAX 0

/* Debug/log name for any Pending value, out-of-set included. */
static SCHEMA_UNUSED const char * enum_name_pending( Pending value )
{
    switch ( value )
    {
        case PENDING_NONE: return "None";
        default: return "???";
    }
}


/* flags ShipFlags — one bit per variant, consumed as masks; storage uint64 in every
   target, wire 4 bits (SPEC §4.2) */
typedef uint64_t ShipFlags;
#define SHIP_FLAGS_FIRING_LASER (1ULL << 0)
#define SHIP_FLAGS_BOOSTING (1ULL << 1)
#define SHIP_FLAGS_BRAKING (1ULL << 2)
#define SHIP_FLAGS_AIMING (1ULL << 3)

#ifdef __cplusplus
}
#endif

#endif /* SCHEMA_EXAMPLE_ENUMS_H */
