/* Generated by the schema compiler from Wire.schema. DO NOT EDIT.
   SPDX-License-Identifier: NONE — this generated output is yours, under terms of
   your choice. See the LICENSE exception in the schema compiler; the compiler is
   AGPL-3.0, its output is not.
   package example — protocol id 0xb6a0276149f6577e */

#ifndef SCHEMA_EXAMPLE_WIRE_H
#define SCHEMA_EXAMPLE_WIRE_H

#include <stdint.h>

#ifndef SCHEMA_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define SCHEMA_UNUSED __attribute__((unused))
#else
#define SCHEMA_UNUSED
#endif
#endif
#include "Messages.h"

#ifdef __cplusplus
extern "C" {
#endif

#define PROBE_ID (244837814094590)
#define HALF_TURN 180.0
#define TICK_RATE 60.0

/* enum Weapon — None = 0 implicit, variants dense from 1, wire range [0, 15]
   (SPEC §4.2). A fixed-width typedef rather than a C enum: an enum's underlying
   type is implementation-defined, and [max = K] headroom makes non-variant
   values wire-legal, which a C enum cannot hold honestly. */
typedef uint8_t Weapon;
#define WEAPON_NONE 0
#define WEAPON_LASER 1
#define WEAPON_MISSILE 2
#define WEAPON_RAILGUN 3
#define WEAPON_MAX 15

/* Debug/log name for any Weapon value, out-of-set included. */
static SCHEMA_UNUSED const char * enum_name_weapon( Weapon value )
{
    switch ( value )
    {
        case WEAPON_NONE: return "None";
        case 1: return "Laser";
        case 2: return "Missile";
        case 3: return "Railgun";
        default: return "???";
    }
}


/* flags ProbeFlags — one bit per variant, consumed as masks; storage uint64 in every
   target, wire 8 bits (SPEC §4.2) */
typedef uint64_t ProbeFlags;
#define PROBE_FLAGS_ARMED (1ULL << 0)
#define PROBE_FLAGS_CLOAKED (1ULL << 1)
#define PROBE_FLAGS_DAMAGED (1ULL << 2)


/* type ProbeHeader */
typedef struct ProbeHeader {
    uint32_t version;
    uint64_t probe_id;
} ProbeHeader;


/* type ProbeBits */
typedef struct ProbeBits {
    uint32_t small;
    uint64_t boundary;
    uint64_t wide;
    uint32_t sensor;
    uint64_t nonce;
} ProbeBits;


/* type ProbeSample */
typedef struct ProbeSample {
    int active;
    float orientation;
    int32_t raw_delta;
    int64_t big_delta;
    Weapon weapon;
    int has_target;
    uint16_t target_id;
    uint32_t idle_ticks;
    uint16_t samples[8];
    int32_t samples_count;
} ProbeSample;


/* type ProbeConfig */
typedef struct ProbeConfig {
    int32_t retries;
    Weapon preferred;
} ProbeConfig;


/* type ProbeArray */
typedef struct ProbeArray {
    ProbeSample samples[2];
    ProbeConfig config;
} ProbeArray;


/* type ProbeReport */
typedef struct ProbeReport {
    ProbeHeader header;
    ProbeFlags flags;
    Test echo;
} ProbeReport;


/* type TestData */
typedef struct TestData {
    int32_t a;
    int32_t b;
    int32_t c;
    uint32_t d;
    uint32_t e;
    uint32_t f;
    int g;
    int32_t items[16];
    int32_t items_count;
    float float_value;
    float compressed_float_value;
    double double_value;
    int8_t int8_value;
    int16_t int16_value;
    uint8_t uint8_value;
    uint16_t uint16_value;
    uint32_t uint32_value;
    uint64_t uint64_value;
    int64_t int64_full;
    int64_t int64_range;
    uint8_t fixed_bytes[17];
    char text[255];
    int32_t text_length;
} TestData;

#ifdef __cplusplus
}
#endif

#endif /* SCHEMA_EXAMPLE_WIRE_H */
