(:id "java/F4" :state :done :evidence ("internal/codegen/javatable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/java/F4") :tested-revision "dc9231ae")
(:id "java/F7" :state :done :evidence ("internal/codegen/javatable/fixedform_under_20_bytes_test.go: TestFixedFormUnder20Bytes") :tested-revision "32a0e3c2")
(:id "java/F8" :state :done :evidence ("internal/codegen/javatable/fixedform_ragged_tail_test.go: TestFixedFormRaggedTail") :tested-revision "32a0e3c2")
(:id "java/F12" :state :done :evidence ("internal/codegen/javatable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/java/F12") :tested-revision "dc9231ae")
(:id "java/F10" :state :done :evidence ("internal/codegen/javatable/fixedversioning_refuse_writes_nothing_test.go: TestFixedVersioningRefuseWritesNothing") :tested-revision "32a0e3c2")
(:id "java/R7" :state :done :evidence ("internal/codegen/javatable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/java/R7") :tested-revision "32a0e3c2")
(:id "java/R8" :state :done :evidence ("internal/codegen/javatable/fixedversioning_test.go: TestFixedVersioningHash" "internal/codegen/javatable/fixedversioning_test.go: TestFixedVersioningRows") :tested-revision "32a0e3c2")
(:id "java/R9" :state :done :evidence ("internal/codegen/javatable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/java/R9") :tested-revision "32a0e3c2")
(:id "java/R13" :state :done :evidence ("internal/codegen/javatable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/java/R13") :tested-revision "32a0e3c2")
