(:id "go/F4" :state :done :evidence ("internal/codegen/gotable/fixedform_test.go: TestFixedFormLayoutMalformedTruncated") :tested-revision "624da009")
(:id "go/F7" :state :done :evidence ("internal/codegen/gotable/fixedform_under_20_bytes_test.go: TestFixedFormUnder20Bytes") :tested-revision "624da009")
(:id "go/F8" :state :done :evidence ("internal/codegen/gotable/fixedform_ragged_tail_test.go: TestFixedFormRaggedTail") :tested-revision "624da009")
(:id "go/F12" :state :unknown :note "the second-layout-for-a-held-hash refusal has no name on the page (SPEC-TABLES §3.4 and FIXED-FORM-ALGORITHM §2 say only \"refused by name\") and the go leg has no stream or layout announcement for a second layout to arrive on (the fixed carrier is planned); nothing to assert or implement without deciding the name and the surface")
(:id "go/F9" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/F9") :tested-revision "624da009")
(:id "go/F10" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/F10") :tested-revision "624da009")
(:id "go/R7" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/R7") :tested-revision "624da009")
(:id "go/R8" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/R8") :tested-revision "624da009")
(:id "go/R9" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/R9") :tested-revision "624da009")
(:id "go/R13" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/R13") :tested-revision "624da009")
(:id "go/R1" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/R1") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/R2" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/R2") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/R23" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/R23") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/R25" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/R25") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/R26" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/R26") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/W14" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/W14") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/R4" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/R4" "internal/codegen/gotable/fixedform_test.go: TestHashIncludesTheCountWord" "internal/codegen/gotable/fixedform_test.go: TestGoFixedFormLayoutAndHashAreIrsByteForByte") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/R5" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/R5") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/W11" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/W11" "internal/codegen/gotable/fixedform_test.go: TestFixedFormBytesIsLayoutKind14") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/W12" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t02_test.go: TestFixedRoadmapGoT02Plans/go/W12" "internal/codegen/gotable/fixedform_test.go: TestHashIncludesTheCountWord") :tested-revision "8319e63e090c593e5d946ecafac48477fe58abc3")
(:id "go/E5" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t04_test.go: TestFixedRoadmapGoT04VersionsEvolution/go/E5") :tested-revision "13946c5ec")
(:id "go/W2" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t04_test.go: TestFixedRoadmapGoT04VersionsEvolution/go/W2") :tested-revision "13946c5ec")
(:id "go/E6" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t04_test.go: TestFixedRoadmapGoT04VersionsEvolution/go/E6") :tested-revision "7cf6c443c")
(:id "go/E8" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t04_test.go: TestFixedRoadmapGoT04VersionsEvolution/go/E8") :tested-revision "7cf6c443c")
(:id "go/R19" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t04_test.go: TestFixedRoadmapGoT04VersionsEvolution/go/R19") :tested-revision "7cf6c443c")
(:id "go/E9" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t04_test.go: TestFixedRoadmapGoT04VersionsEvolution/go/E9") :tested-revision "1b024de44")
(:id "go/R16" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t04_test.go: TestFixedRoadmapGoT04VersionsEvolution/go/R16") :tested-revision "1b024de44")
(:id "go/R18" :state :unknown :note "\"a clamp that cannot fire is not emitted\": the ranged-scalar end on its width's limit and a bits(N) below its storage width are elided and asserted, but a full-width enum/union ordinal clamp (255 variants in a byte) IS emitted as the tautology docs/FIXED-FORM-ALGORITHM.md §5.4 calls \"still conforming\", so the ordinal half of the clause is not held on this leg")
