(:id "js/F4" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/js/F4") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/F7" :state :done :evidence ("internal/codegen/jstable/fixedform_under_20_bytes_test.go: TestJSFixedFormUnder20Bytes") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/F8" :state :done :evidence ("internal/codegen/jstable/fixedform_ragged_tail_test.go: TestJSFixedFormRaggedTail") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/F12" :state :unknown :note "the second-layout-for-a-held-hash refusal is specified only for the message form's announcement (SPEC-TABLES §3.4, ALGORITHM §3 \"refused by name\"), which names no refusal, and the js leg carries no fixed message-form announcement machinery to assert against; the page does not settle the name, so it is not decided here")
(:id "js/F9" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/js/F9") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/F10" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/js/F10" "internal/codegen/jstable/fixedversioning_refuse_writes_nothing_test.go: TestJSFixedVersioningRefuseWritesNothing") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/R7" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/js/R7") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/R8" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/js/R8" "internal/codegen/jstable/fixedversioning_test.go: TestJSFixedVersioningOldRefusesNew") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/R9" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/js/R9") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/R13" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/js/R13" "internal/codegen/jstable/fixedversioning_refuse_writes_nothing_test.go: TestJSFixedVersioningRefuseWritesNothing") :tested-revision "4e8420ab4a59c4a4bea96cd6e7e46e5e543a2c18")
(:id "js/R1" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/R1") :tested-revision "195c9a1d")
(:id "js/R2" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/R2") :tested-revision "195c9a1d")
(:id "js/R23" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/R23") :tested-revision "195c9a1d")
(:id "js/R25" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/R25") :tested-revision "195c9a1d")
(:id "js/R26" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/R26") :tested-revision "195c9a1d")
(:id "js/W14" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/W14") :tested-revision "195c9a1d")
(:id "js/R4" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/R4") :tested-revision "5fec7095")
(:id "js/R5" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/R5") :tested-revision "5fec7095")
(:id "js/W11" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/W11") :tested-revision "5fec7095")
(:id "js/W12" :state :done :evidence ("internal/codegen/jstable/fixedroadmap_t02_test.go: TestFixedRoadmapT02Plans/js/W12") :tested-revision "5fec7095")
