(:id "go/F4" :state :done :evidence ("internal/codegen/gotable/fixedform_test.go: TestFixedFormLayoutMalformedTruncated") :tested-revision "624da009")
(:id "go/F7" :state :done :evidence ("internal/codegen/gotable/fixedform_under_20_bytes_test.go: TestFixedFormUnder20Bytes") :tested-revision "624da009")
(:id "go/F8" :state :done :evidence ("internal/codegen/gotable/fixedform_ragged_tail_test.go: TestFixedFormRaggedTail") :tested-revision "624da009")
(:id "go/F12" :state :unknown :note "the second-layout-for-a-held-hash refusal has no name on the page (SPEC-TABLES §3.4 and FIXED-FORM-ALGORITHM §2 say only \"refused by name\") and the go leg has no stream or layout announcement for a second layout to arrive on (the fixed carrier is planned); nothing to assert or implement without deciding the name and the surface")
(:id "go/F9" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/F9") :tested-revision "624da009")
(:id "go/F10" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/F10") :tested-revision "624da009")
(:id "go/R7" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/R7") :tested-revision "624da009")
(:id "go/R8" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/R8") :tested-revision "624da009")
(:id "go/R9" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/R9") :tested-revision "624da009")
(:id "go/R13" :state :done :evidence ("internal/codegen/gotable/fixedroadmap_t01_test.go: TestFixedRoadmapT01Framing/go/R13") :tested-revision "624da009")
