// Code generated by the schema compiler from Data.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package blockhome — protocol id 0x0fc1a1667e54b144 (packets only: tables version by field id, not by protocol id)
// The TABLE wire (evolution-tolerant, docs/SPEC-TABLES.md): no serialize
// dependency — includable from any TU.

#pragma once

#include <stdint.h>
#include <string.h> // the prefill's scalar-array fills
#include <stddef.h> // offsetof, for the reflection descriptors

#include "Data.h"

#ifndef BLOCKHOME_SCHEMA_TABLE_PRIMITIVES
#define BLOCKHOME_SCHEMA_TABLE_PRIMITIVES

// THE CODEC DOES NOT DEPEND ON THE COMPILER'S INLINING BUDGET. A table of a
// realistic field count emits one large body per type, and the cursor a body
// writes through lives in the caller's `TableWriter`: across a call boundary
// that cursor round-trips through memory, and a `uint8_t *` store may alias the
// writer itself, so every put reloads it. When a budget runs out mid-body the
// codec silently degrades to that shape. Forcing the primitives and the
// fixed-class bodies inline is what keeps the cursor in registers and lets
// adjacent constant framing bytes merge into one store.
#if defined( _MSC_VER )
#define BLOCKHOME_TABLE_INLINE __forceinline
#elif defined( __GNUC__ ) || defined( __clang__ )
#define BLOCKHOME_TABLE_INLINE inline __attribute__(( always_inline ))
#else
#define BLOCKHOME_TABLE_INLINE inline
#endif

namespace blockhome {

// The table-wire read report — the permissive contract's ledger. Silence
// (all zero) means the data matched this reader's schema exactly.
struct TableReport
{
    int32_t unknown = 0;       // unknown field ids skipped (newer data)
    int32_t kind_mismatch = 0; // known id, changed type — skipped, never misdecoded
    int32_t clamped = 0;       // out-of-range values clamped to declared bounds
    // a key the TEXT form saw twice: last wins, and the repeat is counted
    // (docs/SPEC-TABLES.md §16.2). The wire never raises it — a body carrying an
    // id twice is legal input whose last occurrence wins, silently (§3).
    int32_t duplicate = 0;
    bool malformed = false;    // framing damage; decode stopped, partial result kept
    // THE REFUSAL VERDICT, which is not one of §4's events and moves no counter
    // (docs/SPEC-TABLES.md §3): a FORM BYTE this reader does not carry. Five
    // zero counters and a false flag are what a clean read prints too, so the
    // verdict is what tells the two apart.
    bool refused = false;
};

// ---- reflection (tables only, docs/SPEC-TABLES.md) ----
//
// Static field descriptors for every type in the table closure: name, wire
// id/kind, storage offset, bounds, ranges, enum names and branch guards —
// enough to walk, print, diff, edit or bind any table value at runtime with
// no RTTI and no schema files. TableType<X>() returns X's descriptor.

struct TableTypeInfo;

// One arm of a union field: where its payload sits inside the union's storage
// and what its payload looks like. The arm's NAME and its table-wire id come
// from the field's enum_name/variant_id functions at the same tag, so nothing
// is spelled twice (docs/SPEC-TABLES.md §8).
struct TableFieldInfo;

struct TableUnionArmInfo
{
    uint32_t offset;             // offsetof the arm's payload within the union storage
    const TableTypeInfo * table; // the arm payload's descriptor, or NULL
    // AN ARM IS A FIELD LINE (docs/SPEC-TABLES.md §2.6): an arm that names no
    // declared type or table carries the FIELD descriptor a field of that
    // type would carry instead — offsets taken within the union storage — so
    // a generic walk meets an arm's kind, width, bounds and companions where
    // it meets a field's. Exactly one of the two is non-NULL on a set arm.
    const TableFieldInfo * field;
    uint32_t size;               // the arm's whole storage, which selection zero-establishes
};

// A union field's shape: the tag, and the arms indexed by it. Arms run
// [0, enum_max]; index 0 is the EMPTY arm and carries no payload.
struct TableUnionInfo
{
    uint32_t tag_offset; // offsetof the tag within the union storage
    uint32_t tag_size;   // sizeof the tag
    const TableUnionArmInfo * arms;
};

// The exact raw range of a wide-kind field (docs/SPEC-TABLES.md §8.2): two 128-bit
// values as 64-bit lanes, low lane first, two's complement for the signed kinds.
struct TableWideRange
{
    uint64_t lo[2];
    uint64_t hi[2];
};

struct TableFieldInfo
{
    const char * name;      // schema field name, e.g. "health"
    const char * json;      // the TEXT form's key: the json = "key" attribute, else name (§16.3)
    const char * type_name; // schema type name, e.g. "float32", "Grade"
    uint64_t id;            // table-wire field id: fnv1a64 of the name, of the was alias after a rename (§5)
    uint8_t kind;           // table-wire kind; for arrays/strings/bytes, the ELEMENT kind
    bool is_array;          // fixed or counted array (bytes included)
    bool counted;           // a _count/_length int32 companion exists (counted arrays, strings, bytes)
    bool optional;          // a ?T field: a _present bool companion decides whether it rides
    int32_t array_bound;    // array capacity / string max length; 0 for plain scalars
    uint32_t offset;        // offsetof the storage member
    uint32_t elem_size;     // sizeof the member (element size for arrays)
    uint32_t count_offset;  // offsetof the _count/_length companion, or 0xffffffff
    uint32_t present_offset; // offsetof the _present companion, or 0xffffffff
    const TableTypeInfo * table; // nested table's descriptor, or NULL
    bool has_range;         // a declared [min, max] (int or float)
    double range_min;       // NOTE: int64 ranges beyond 2^53 lose precision here
    double range_max;
    // the WIDE kinds (18-29, docs/SPEC-TABLES.md §3, §8.2): frac_bits is a fixed
    // field's F — its storage holds units × 2^F — and wide is the declared
    // range on that RAW scale, exact, as two 128-bit two's-complement values
    // in 64-bit lanes (low lane first). NULL where the declaration bounds
    // nothing (a bare uint128) and for every other kind; frac_bits is 0 for
    // every kind that is not fixed-point. range_min/range_max still carry
    // the declared bounds as doubles — whole units for a fixed field — for
    // a walker that only shows them.
    uint8_t frac_bits;
    const TableWideRange * wide;
    int64_t enum_max;       // enums: highest valid value (None = 0 always valid);
                            // unions: the arm count (tag range [0, enum_max]);
                            // flags: the highest declared BIT INDEX; else -1
    // the vocabulary's names, indexed the same way enum_max bounds: an enum's
    // value -> name, a union's tag -> arm name, a FLAGS field's bit index ->
    // variant name. NULL for every other kind.
    const char * (*enum_name)( uint64_t value );
    // the TABLE-WIRE id of one variant (docs/SPEC-TABLES.md §5): for an enum, the
    // hash of the variant's name; for a union, the hash of the arm's name.
    // 0 is the reserved id — an enum's None, a union's empty. NULL for every
    // other kind — a FLAGS field's variants have no per-variant wire id (§4),
    // so a NULL here beside a non-NULL enum_name is what says "flags".
    // Walk [0, enum_max] to enumerate a vocabulary and its ids.
    uint64_t (*variant_id)( uint64_t value );
    // an ENUM-KEYED array (docs/SPEC-TABLES.md §2.4): the array has one slot per
    // variant of key_type_name, indexed by the variant's value, and its slots
    // ride under variant ids rather than positions. key_name and key_id are
    // the key's vocabulary — walk [0, array_bound) to print slots by name.
    // NULL on every other field.
    const char * key_type_name;
    const char * (*key_name)( uint64_t value );
    uint64_t (*key_id)( uint64_t value );
    // union fields: the tag and its arms, behind a function so the whole
    // descriptor stays CONSTANT-INITIALISED (a captureless lambda converts to
    // a function pointer at compile time; the arms themselves are a static
    // inside it). NULL for every other kind.
    const TableUnionInfo * (*arms)();
    const char * guard;     // branch guard, e.g. "at_rest" or "!at_rest"; "" if unguarded
};

struct TableTypeInfo
{
    const char * name;   // schema type name
    uint32_t size;       // sizeof the storage struct
    int32_t num_fields;
    const TableFieldInfo * fields;
    // put one instance back at its declared defaults, in place. A generic
    // walker that fills a value has to be able to establish the defaults an
    // absent field takes, and it holds no type to spell — this is the one
    // thing the descriptors could not express without it. Placement-new
    // value-init, exactly what the wire's read path does, and no temporary.
    void (*reset)( void * storage );
};

struct TableWriter
{
    uint8_t * buffer;
    int64_t capacity;
    int64_t offset = 0;
    bool overflow = false;

    // the parameters do not repeat the member names: a parameter that hides a
    // member is a warning the estate's compilers disagree about (gcc's
    // -Wshadow and cl's C4458 refuse it, clang's -Wshadow does not), and this
    // is a header a consumer compiles under its OWN flags
    TableWriter( uint8_t * to_buffer, int64_t to_capacity ) : buffer( to_buffer ), capacity( to_capacity ) {}

    BLOCKHOME_TABLE_INLINE void raw( const void * data, int64_t bytes )
    {
        if ( offset + bytes > capacity ) { overflow = true; return; }
        memcpy( buffer + offset, data, (size_t) bytes );
        offset += bytes;
    }
    BLOCKHOME_TABLE_INLINE void put8( uint8_t v )   { raw( &v, 1 ); }
    BLOCKHOME_TABLE_INLINE void put16( uint16_t v ) { uint8_t b[2] = { uint8_t( v ), uint8_t( v >> 8 ) }; raw( b, 2 ); }
    BLOCKHOME_TABLE_INLINE void put32( uint32_t v ) { uint8_t b[4] = { uint8_t( v ), uint8_t( v >> 8 ), uint8_t( v >> 16 ), uint8_t( v >> 24 ) }; raw( b, 4 ); }
    BLOCKHOME_TABLE_INLINE void put64( uint64_t v ) { put32( uint32_t( v ) ); put32( uint32_t( v >> 32 ) ); }
    // a 128-bit value as two lanes, the low half first (docs/SPEC-TABLES.md §3)
    BLOCKHOME_TABLE_INLINE void put128( uint64_t lo, uint64_t hi ) { put64( lo ); put64( hi ); }
    // EVERY LENGTH, COUNT, INDEX AND ID REFERENCE IS ONE CANONICAL UNSIGNED
    // LEB128 (docs/SPEC-TABLES.md §3): seven value bits a byte, the lowest
    // group first, the high bit set on every byte but the last. One value has
    // one spelling, so two conforming writers agree byte for byte.
    BLOCKHOME_TABLE_INLINE void putleb( uint64_t v )
    {
        while ( v >= 0x80 ) { put8( uint8_t( v ) | 0x80 ); v >>= 7; }
        put8( uint8_t( v ) );
    }
};

// TableLebBytes is one value's spelling length, which a MEASURE needs before
// the bytes exist — the length of a body has to be known before it is written,
// because a length whose own width moves cannot be patched in place.
inline int64_t TableLebBytes( uint64_t v )
{
    int64_t n = 1;
    while ( v >= 0x80 ) { v >>= 7; n++; }
    return n;
}

// THE ID TABLE, WRITER SIDE (docs/SPEC-TABLES.md §3). It holds every id the
// body used, once each, in FIRST-USE order over the whole wire, and the body
// names them by position: reference k is the kth entry, counted from 1, and
// reference 0 names NO ID.
//
// Its capacity is a COMPILE-TIME fact of the unit — the distinct names its
// table closure can spell — so a save allocates nothing: the table is a local
// of Measure and of Save. The bucket chain makes ref constant time and makes
// truncate constant time too, which is what an ELIDED field needs: a field
// that turns out not to ride costs nothing in the id table either, so the walk
// interns its id, builds the payload that decides, and undoes the entry when
// nothing rides.
struct TableIds
{
    static const int32_t kCapacity = 28;
    static const int32_t kBuckets = 64;

    uint64_t ids[ kCapacity ];
    int32_t chain[ kCapacity ];
    int32_t head[ kBuckets ];
    int32_t count;
    bool overflow;

    TableIds() : count( 0 ), overflow( false )
    {
        for ( int32_t i = 0; i < kBuckets; i++ ) { head[i] = -1; }
    }

    static BLOCKHOME_TABLE_INLINE uint32_t bucket_of( uint64_t id )
    {
        return uint32_t( ( id * 0x9E3779B97F4A7C15ull ) >> 58 ) & uint32_t( kBuckets - 1 );
    }

    // the reference an id takes, appending it on first use
    uint64_t ref( uint64_t id )
    {
        const uint32_t b = bucket_of( id );
        for ( int32_t i = head[b]; i >= 0; i = chain[i] )
        {
            if ( ids[i] == id ) { return uint64_t( i ) + 1; }
        }
        if ( count >= kCapacity ) { overflow = true; return 1; }
        ids[count] = id; chain[count] = head[b]; head[b] = count; count++;
        return uint64_t( count );
    }

    // undo every entry appended since mark. An entry removed is the most
    // recent one in its bucket, so it sits at that bucket's head.
    void truncate( int32_t mark )
    {
        while ( count > mark )
        {
            count--;
            head[ bucket_of( ids[count] ) ] = chain[count];
        }
    }
};

// TableIdsBytes is the trailer's own size: the entries, each a fixed
// little-endian u64, and the ENTRY COUNT, the one fixed-width number on the
// wire (docs/SPEC-TABLES.md §3).
inline int64_t TableIdsBytes( const TableIds & ids ) { return int64_t( ids.count ) * 8 + 8; }

// TableIdsWrite puts the trailer where the walk ended: a writer never patches,
// because first-use order is known only when the walk ends.
inline void TableIdsWrite( TableWriter & w, const TableIds & ids )
{
    for ( int32_t i = 0; i < ids.count; i++ ) { w.put64( ids.ids[i] ); }
    w.put64( uint64_t( ids.count ) );
}

// THE ID TABLE, READER SIDE (docs/SPEC-TABLES.md §3). A reader locates it from
// the END of the wire and resolves it ONCE, at open: the entries are eight
// bytes each and a body names them by position, so every field dispatches
// through an index rather than through a search over hashes.
struct TableIdTable
{
    const uint8_t * entries = NULL;
    int64_t count = 0;

    // the id a reference names. ref is 1-based and bounds-checked by the
    // caller: a reference ABOVE the entry count is framing damage on the body
    // that carries it, and 0 names no id at all.
    uint64_t at( uint64_t ref ) const
    {
        const uint8_t * e = entries + ( ref - 1 ) * 8;
        uint64_t lo = uint64_t( e[0] ) | uint64_t( e[1] ) << 8 | uint64_t( e[2] ) << 16 | uint64_t( e[3] ) << 24;
        uint64_t hi = uint64_t( e[4] ) | uint64_t( e[5] ) << 8 | uint64_t( e[6] ) << 16 | uint64_t( e[7] ) << 24;
        return lo | ( hi << 32 );
    }
};

struct TableReader
{
    const uint8_t * buffer;
    int64_t size;
    int64_t offset = 0;
    TableReport * report;
    const TableIdTable * ids = NULL;
    // ONLY THE ROOT BODY CARRIES THE NODE TABLE (docs/SPEC-TABLES.md §3.1), so
    // a body has to know which it is: the reserved id inside a NESTED body is
    // malformed, because a second numbering cannot exist. Every reader made
    // for a payload is nested; the two the wire surfaces make for a root say so.
    bool nested = true;

    TableReader( const uint8_t * from_buffer, int64_t from_size, TableReport * to_report )
        : buffer( from_buffer ), size( from_size ), report( to_report ) {}

    TableReader( const uint8_t * from_buffer, int64_t from_size, TableReport * to_report, const TableIdTable * to_ids )
        : buffer( from_buffer ), size( from_size ), report( to_report ), ids( to_ids ) {}

    BLOCKHOME_TABLE_INLINE bool has( int64_t bytes ) const { return offset + bytes <= size; }
    // A LENGTH IS A 64-BIT NUMBER AND A BUFFER IS NOT (docs/SPEC-TABLES.md
    // §3): every length, count and index on this wire has sixty-four bits of
    // capability, so one past what remains must be compared UNSIGNED. Casting
    // it to int64 first turns 0xFFFFFFFFFFFFFFFF into -1, and a negative
    // length looks like room.
    BLOCKHOME_TABLE_INLINE bool room( uint64_t bytes ) const { return bytes <= (uint64_t) ( size - offset ); }
    BLOCKHOME_TABLE_INLINE uint8_t get8()   { return buffer[offset++]; }
    BLOCKHOME_TABLE_INLINE uint16_t get16() { uint16_t v = uint16_t( buffer[offset] ) | uint16_t( buffer[offset+1] ) << 8; offset += 2; return v; }
    BLOCKHOME_TABLE_INLINE uint32_t get32() { uint32_t v = uint32_t( buffer[offset] ) | uint32_t( buffer[offset+1] ) << 8 | uint32_t( buffer[offset+2] ) << 16 | uint32_t( buffer[offset+3] ) << 24; offset += 4; return v; }
    BLOCKHOME_TABLE_INLINE uint64_t get64() { uint64_t lo = get32(); uint64_t hi = get32(); return lo | ( hi << 32 ); }
    BLOCKHOME_TABLE_INLINE void get128( uint64_t & lo, uint64_t & hi ) { lo = get64(); hi = get64(); }

    // ONE CANONICAL UNSIGNED LEB128 (docs/SPEC-TABLES.md §3), and a
    // non-minimal spelling is MALFORMED: 0x80 0x00 and 0x00 both spell zero,
    // and only the second is legal input. An encoding past ten bytes, or a
    // tenth byte with a bit above the 64th value bit, is malformed on the same
    // rule. false = framing damage on the body carrying it.
    bool getleb( uint64_t & value )
    {
        // A NUMBER THIS READER REFUSES LEAVES THE CURSOR WHERE IT WAS. The
        // caller's next question is often "did this body end exactly at its
        // L", and a rejected number that had moved the cursor would answer
        // that question with the damage already stepped over.
        const int64_t at = offset;
        value = 0;
        uint32_t shift = 0;
        for ( int32_t i = 0; i < 10; i++ )
        {
            if ( !has( 1 ) ) { offset = at; return false; }
            const uint8_t b = get8();
            if ( i == 9 && b > 1 ) { offset = at; return false; }
            value |= uint64_t( b & 0x7F ) << shift;
            if ( ( b & 0x80 ) == 0 )
            {
                if ( i > 0 && b == 0 ) { offset = at; return false; } // a redundant continuation
                return true;
            }
            shift += 7;
        }
        offset = at;
        return false;
    }

    // resolve one id reference against the file's table. false = a reference
    // ABOVE the entry count, or a 0 where an id is required, both of which
    // are framing damage on the body that carries it.
    bool getid( uint64_t & id )
    {
        uint64_t ref = 0;
        if ( !getleb( ref ) ) { return false; }
        if ( ref == 0 || ids == NULL || ref > (uint64_t) ids->count ) { return false; }
        id = ids->at( ref );
        return true;
    }

    // skip one payload by kind; false = framing damage. FOUR RULES COVER THE
    // SET (docs/SPEC-TABLES.md §3), and a kind outside it is not skippable —
    // which is why the set is closed and why kind 31 exists.
    bool skip( uint8_t kind )
    {
        switch ( kind )
        {
            // the fixed-width kinds, each by its width: 18-29 are the 128-bit integers and
            // the fixed-point family at every storage width (docs/SPEC-TABLES.md §3)
            case 1: case 2: case 6: case 20: case 25: return has( 1 ) ? ( offset += 1, true ) : false;
            case 3: case 7: case 21: case 26:         return has( 2 ) ? ( offset += 2, true ) : false;
            case 4: case 8: case 10: case 22: case 27: return has( 4 ) ? ( offset += 4, true ) : false;
            case 5: case 9: case 11: case 23: case 28: return has( 8 ) ? ( offset += 8, true ) : false;
            case 18: case 19: case 24: case 29: return has( 16 ) ? ( offset += 16, true ) : false;
            case 17: case 30: // a NODE INDEX (§3.1) and an ENUM's variant reference: one LEB128 and stop
            {
                uint64_t ignored = 0;
                return getleb( ignored );
            }
            case 12: case 13: case 14: case 16: case 31: case 32: // 31 is the ESCAPE, 32 the payload-free kind
            {
                uint64_t n = 0;
                if ( !getleb( n ) ) return false;
                return room( n ) ? ( offset += (int64_t) n, true ) : false;
            }
            case 15: // union: the arm id reference, then its kind, its L and its payload (reference 0 = empty)
            {
                uint64_t arm = 0;
                if ( !getleb( arm ) ) return false;
                if ( arm == 0 ) return true;
                if ( !has( 1 ) ) return false;
                offset += 1; // the arm's kind byte
                uint64_t n = 0;
                if ( !getleb( n ) ) return false;
                return room( n ) ? ( offset += (int64_t) n, true ) : false;
            }
        }
        return false;
    }
};

// The RESERVED node-table id, the one id the language holds back
// (docs/SPEC-TABLES.md §3.1, §5). It rides in every unit, pointered or not,
// because every body has to know that a NESTED body claiming one is damaged.
static const uint64_t kTableNodeTableFieldId = 0xFFFFFFFFFFFFFFFFull;

// TableWireForm is the FORM BYTE, and it is the whole header
// (docs/SPEC-TABLES.md §3). A reader that meets a byte it does not know
// refuses the wire by name and never reports damage.
const uint8_t kTableWireForm = 1;

// TableOpen reads the form byte and the trailer, in that order, and hands back
// the ROOT BODY. It answers one of three verdicts, because five zero counters
// and a false flag are what a clean read prints too:
//
//   TableOpenOk       the form is known and the table read whole
//   TableOpenRefused  a FORM BYTE this reader does not carry: nothing is
//                     decoded, nothing is counted, and no damage is reported
//   TableOpenDamaged  a table that cannot be read whole — fewer than eight
//                     bytes, a count whose entries run past the front of the
//                     file, a count that leaves no room for the form byte, or
//                     ONE ID IN TWO ENTRIES. The whole wire is malformed,
//                     nothing is decoded, and one event is counted.
//   TableOpenBodyStopped  the form and the table were good and the ROOT BODY
//                     could not be walked to its own terminator. What it
//                     decoded before that is kept, as everywhere on this wire.
enum TableOpenVerdict { TableOpenOk, TableOpenRefused, TableOpenDamaged, TableOpenBodyStopped };

inline TableOpenVerdict TableOpen( const uint8_t * buffer, int64_t bytes, TableIdTable & table, int64_t & body_bytes )
{
    if ( bytes < 1 ) { return TableOpenDamaged; }
    if ( buffer[0] != kTableWireForm ) { return TableOpenRefused; }
    if ( bytes < 9 ) { return TableOpenDamaged; }
    const uint8_t * tail = buffer + bytes - 8;
    uint64_t lo = uint64_t( tail[0] ) | uint64_t( tail[1] ) << 8 | uint64_t( tail[2] ) << 16 | uint64_t( tail[3] ) << 24;
    uint64_t hi = uint64_t( tail[4] ) | uint64_t( tail[5] ) << 8 | uint64_t( tail[6] ) << 16 | uint64_t( tail[7] ) << 24;
    uint64_t count = lo | ( hi << 32 );
    if ( count > (uint64_t) ( bytes / 8 ) ) { return TableOpenDamaged; }
    const int64_t span = (int64_t) count * 8 + 8;
    if ( span + 1 > bytes ) { return TableOpenDamaged; }
    table.entries = buffer + bytes - span;
    table.count = (int64_t) count;
    // THE ENTRIES ARE DISTINCT: a table that carries one id twice is malformed
    // for the whole wire, because no wire this schema writes carries a repeat
    // and it would leave one more shape of table for a hostile writer to aim
    // at (docs/SPEC-TABLES.md §3).
    for ( int64_t i = 1; i < table.count; i++ )
    {
        const uint64_t id = table.at( uint64_t( i ) + 1 );
        for ( int64_t j = 0; j < i; j++ )
        {
            if ( table.at( uint64_t( j ) + 1 ) == id ) { return TableOpenDamaged; }
        }
    }
    body_bytes = bytes - span - 1;
    return TableOpenOk;
}

// TableBodyExtent walks a body's framing to the zero reference that ends it,
// so a reader can tell a body that ENDED EARLY — leaving bytes no field claims
// — from one that is merely damaged. ANY BYTE BETWEEN THE ROOT'S TERMINATOR
// AND THE TABLE'S FIRST ENTRY IS MALFORMED, because no field claims it and the
// two ends of the file have met (docs/SPEC-TABLES.md §3).
inline bool TableBodyEndsEarly( const uint8_t * body, int64_t bytes, const TableIdTable & table )
{
    TableReport ignored;
    TableReader r( body, bytes, &ignored, &table );
    for ( ;; )
    {
        uint64_t ref = 0;
        if ( !r.getleb( ref ) ) { return false; }
        if ( ref == 0 ) { return r.offset != bytes; }
        if ( ref > (uint64_t) table.count ) { return false; }
        if ( !r.has( 1 ) ) { return false; }
        if ( !r.skip( r.get8() ) ) { return false; }
    }
}

inline float table_bits_to_float( uint32_t bits ) { float f; memcpy( &f, &bits, 4 ); return f; }
inline uint32_t table_float_to_bits( float f ) { uint32_t b; memcpy( &b, &f, 4 ); return b; }
inline double table_bits_to_double( uint64_t bits ) { double d; memcpy( &d, &bits, 8 ); return d; }
inline uint64_t table_double_to_bits( double d ) { uint64_t b; memcpy( &b, &d, 8 ); return b; }

} // namespace blockhome

#endif // BLOCKHOME_SCHEMA_TABLE_PRIMITIVES

#ifndef BLOCKHOME_SCHEMA_BUILD_VERSION
#define BLOCKHOME_SCHEMA_BUILD_VERSION

namespace blockhome {

// THE BUILD VERSION (docs/SPEC-TABLES.md §20): one digest over every fact the bytes
// this build produces depend on — the type wire's protocol id, every record's
// layout as the compiler's own C ABI model computes it, and the facts that
// decide what a load PUTS in those slots. It is the number a cook's header
// carries and the number Open compares, and the number a block's prologue
// carries and BlockOpen compares: a build version answers "which build?" and
// not "which form?", and what separates the two forms is their MAGIC.
//
// There are TWO ids in the design and they are not interchangeable: the
// PROTOCOL ID is the type wire's and nothing else, and the BUILD VERSION is
// what everything cooked or blocked is keyed by. A table edit moves this and
// never the protocol id; a type edit moves both.
static const uint64_t BuildVersion = 0xad75fcea740d7640ull;

} // namespace blockhome

#endif // BLOCKHOME_SCHEMA_BUILD_VERSION

#ifndef BLOCKHOME_SCHEMA_TABLE_COOK
#define BLOCKHOME_SCHEMA_TABLE_COOK

namespace blockhome {

// ---- the cooked form (docs/SPEC-TABLES.md §7) ----
//
// A cooked file is a HEADER, a DATA part and an ATTRIBUTION part, in that
// order. Every word of the header is a u64 written in the byte order the cook
// was produced in, and the header is 64 bytes:
//
//     0  magic               0x4b4f4f434d484353, read BYTEWISE before anything else
//     8  build_version       the unit's id (docs/SPEC-TABLES.md §20)
//    16  byte_order          1 little, 2 big — the order that WROTE the file
//    24  data_length         the region's bytes, rounded up to alignment
//    32  attribution_length  the directory's bytes, or 0
//    40  alignment           the region's alignment, never below eight
//    48  reserved            zero
//    56  reserved            zero
//
// The DATA part is Lock's region written verbatim (§7.2) — the root at its
// base — and it is what a runtime points at. The ATTRIBUTION part is the node
// directory (§6.3), and NOTHING THAT READS THE STRUCTURE TOUCHES IT: it is
// written beside the data for schema cook-check, so a build that ships no
// tooling need not carry it at all.
static const int64_t kTableCookHeaderBytes = 64;

// THE MAGIC'S VALUE, and a consumer written from the page needs the constant
// rather than a description of one. It is "SCHMCOOK" read as ASCII in the byte
// order a little-endian store produces — the same shape the block form's
// SCHMABLK takes, so a hex dump of a little-endian cook is legible and the two
// accelerators sit in one vocabulary.
//
// IT IS STORED IN THE PRODUCER'S ORDER, which is what makes it the byte-order
// check as well as the form check: a consumer reads back this build's
// constant, or that constant byte-reversed — which identifies a cook of the
// OTHER order — or something that is not a cook. All three answers but the
// first refuse, and a cook and a BLOCK are separated here too, because a
// form's identity belongs in its magic rather than in a second digest.
static const uint64_t TableCookMagic = 0x4b4f4f434d484353ull;

// THIS BUILD's byte order, as the header's own word carries it. The magic is
// what REFUSES a foreign order; this word is what RECORDS which order wrote
// the file, so a refusal names the order rather than inferring it and a tool
// dumping a cook reads the fact. A file whose magic matched and whose order
// word did not is corrupt, and there is no reading that recovers it.
//
// The BUILD VERSION cannot do either job: §20.1 digests byteorder as a
// GENERATION input, little for every target schema generates for today, so
// two builds of one schema for two orders emit the same id.
#if defined( __BYTE_ORDER__ ) && defined( __ORDER_BIG_ENDIAN__ ) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
static const uint64_t TableCookByteOrder = 2; // big
#else
static const uint64_t TableCookByteOrder = 1; // little
#endif

// The greatest region alignment a cooked file may name. The DATA part begins
// at align_up( 64, alignment ), which is 64 for every unit this language can
// declare — the largest alignment it has is sixteen — so a word past this cap
// describes a file no build of this schema wrote (docs/SPEC-TABLES.md §7.1).
static const uint64_t TableCookMaxAlign = 64;

// The header read, BYTEWISE. memcpy is the portable spelling of "these eight
// bytes, in this machine's order"; every compiler this repo builds under folds
// it to one load, and it is the only read in the whole of Open that is not a
// comparison.
inline uint64_t table_cook_read64( const uint8_t * p )
{
    uint64_t v;
    memcpy( &v, p, sizeof( v ) );
    return v;
}

// TableCookOpen: THE WHOLE CHECK, in one place, because §7 states the
// enumeration once and every generated <Name>Open is that one enumeration plus
// its own root's two layout facts.
//
// THE CHECK, in order: the magic read bytewise, the byte order it establishes,
// the build version against this build's own, both RESERVED words zero, the
// region alignment the header names, the two part lengths against the length
// the caller passed — a truncated file and a file with trailing bytes are the
// same refusal — the root's own storage inside the data part, and the
// alignment of the base.
//
// AND THAT IS ALL OF IT. On a match the bytes ARE what this build wrote, in
// this build's layout and this build's byte order, so there is nothing to
// validate and nothing to fix up: the caller gets the root. Nothing per node
// happens here, which is what makes open O(1) in the file's size; a walk of
// any shape would forfeit that, and validating an untrusted file is schema
// cook-check's job and a person's decision (§7.4).
//
// EVERY NUMBER BELOW COMES OUT OF THE FILE, so the arithmetic is unsigned and
// each term is BOUNDED BEFORE IT IS ADDED: a forged length near 2^64 must
// refuse, and an addition that wrapped would be the defect the comparison
// after it was supposed to catch. Nothing past length is read on any path,
// including every refusing one.
inline const uint8_t * TableCookOpen( const void * bytes, uint64_t length, uint64_t root_size, uint64_t root_align )
{
    if ( bytes == NULL ) { return NULL; }
    if ( length < (uint64_t) kTableCookHeaderBytes ) { return NULL; }
    const uint8_t * raw = (const uint8_t *) bytes;
    // the MAGIC, bytewise and first: it is what establishes the byte order
    // every other header word is read in, so nothing else may be read before
    // it. A byte-reversed constant is a cook of the other order and refuses
    // here, which is why the order never reaches a fix-up pass.
    if ( table_cook_read64( raw ) != TableCookMagic ) { return NULL; }
    if ( table_cook_read64( raw + 16 ) != TableCookByteOrder ) { return NULL; }
    if ( table_cook_read64( raw + 8 ) != BuildVersion ) { return NULL; }
    // the RESERVED words: a non-zero one means a writer used a form this build
    // does not understand, and Open refuses rather than ignoring it.
    if ( table_cook_read64( raw + 48 ) != 0 ) { return NULL; }
    if ( table_cook_read64( raw + 56 ) != 0 ) { return NULL; }
    const uint64_t data_length = table_cook_read64( raw + 24 );
    const uint64_t attribution_length = table_cook_read64( raw + 32 );
    const uint64_t alignment = table_cook_read64( raw + 40 );
    // THE ALIGNMENT WORD IS DATA, and it is the one header field the rest of
    // the check does arithmetic WITH rather than only comparison against. A
    // region's alignment is a power of two, never below eight (the floor that
    // puts the attribution part on an eight-byte boundary without a second
    // padding rule) and never past the cap above; a word that is none of those
    // rounds nothing and aligns nothing, so it is refused before it is used.
    if ( alignment < 8 || alignment > TableCookMaxAlign ) { return NULL; }
    if ( ( alignment & ( alignment - 1 ) ) != 0 ) { return NULL; }
    // and it must be an alignment THE ROOT CAN SIT AT, since the root is at
    // the region's base: both are powers of two, so "at least the root's"
    // is one division.
    if ( ( alignment % root_align ) != 0 ) { return NULL; }
    // The DATA part begins at align_up( 64, alignment ). It is DERIVED and not
    // a header field, because a fact a reader computes is a fact two writers
    // cannot disagree about.
    const uint64_t data_offset = ( (uint64_t) kTableCookHeaderBytes + alignment - 1 ) & ~( alignment - 1 );
    if ( length < data_offset ) { return NULL; }
    // the two part lengths against the length the caller passed. The whole
    // file is data_offset + data_length + attribution_length, and a length
    // that is not EXACTLY that refuses — truncation and trailing bytes are one
    // refusal, and both terms are subtracted rather than added so no sum can
    // carry.
    if ( data_length > length - data_offset ) { return NULL; }
    if ( attribution_length != length - data_offset - data_length ) { return NULL; }
    // the ROOT sits at the region's base, so the region has to hold it: a
    // shorter data part describes a root partly outside the file, which is the
    // one way a match-and-point reader could hand back storage it never
    // received.
    if ( data_length < root_size ) { return NULL; }
    const uint8_t * base = raw + data_offset;
    // the alignment of the BASE. The header pads the data part to the region's
    // alignment, so a base an allocator or mmap gave you is already aligned —
    // mmap gives page alignment for free — and a base that is not is a caller's
    // buffer this form cannot be read out of.
    if ( ( (uintptr_t) base % (uintptr_t) alignment ) != 0 ) { return NULL; }
    return base;
}

// ---- the cooked form, the WRITE side (docs/SPEC-TABLES.md §7.6) ----
//
// THE BYTE ORDER IS THE TARGET'S, NOT THE HOST'S. A cook is produced in the
// byte order of the build that will read it (§7), so the fixing happens here —
// offline, once, on the writing side — and never at Open. Passing
// TableByteOrder::Big on a little-endian machine produces a big-endian build's
// file, and nothing about the writing host reaches the bytes.
enum class TableByteOrder
{
    Little = 1, // the header's byte_order word, and the order every scalar is written in
    Big = 2,
};

// One store, width as an argument. Every call site passes a literal width, so
// the loop folds to a store (and a byte swap on the foreign order); a name per
// width would claim four §11 names to save nothing.
inline void table_cook_put( uint8_t * at, uint64_t value, int32_t width, TableByteOrder order )
{
    if ( order == TableByteOrder::Little )
    {
        for ( int32_t i = 0; i < width; i++ ) { at[i] = (uint8_t) ( value >> ( 8 * i ) ); }
    }
    else
    {
        for ( int32_t i = 0; i < width; i++ ) { at[i] = (uint8_t) ( value >> ( 8 * ( width - 1 - i ) ) ); }
    }
}

// A 128-bit store as two lanes: sixteen bytes, the low lane first in the
// little order and the high lane first — each lane big-endian — in the big
// order, exactly as a u64 is one lane of eight (docs/SPEC-TABLES.md §7.2).
inline void table_cook_put128( uint8_t * at, uint64_t lo, uint64_t hi, TableByteOrder order )
{
    if ( order == TableByteOrder::Little ) { table_cook_put( at, lo, 8, order ); table_cook_put( at + 8, hi, 8, order ); }
    else { table_cook_put( at, hi, 8, order ); table_cook_put( at + 8, lo, 8, order ); }
}

// A buffer piece: the USED bytes and nothing else. The tail is already zero —
// the whole extent was zeroed before any field was written — so this copies the
// used prefix and leaves the rest, which is what makes a string's unused tail a
// consequence of one memset rather than a rule per buffer. A used length past
// the buffer, or below zero, is a value no reader could have produced and it is
// clamped rather than trusted: this writes inside the caller's buffer on every
// input.
inline void table_cook_bytes( uint8_t * at, const void * source, int64_t used, int64_t capacity )
{
    if ( used <= 0 ) { return; }
    const int64_t n = used < capacity ? used : capacity;
    memcpy( at, source, (size_t) n );
}

} // namespace blockhome

#endif // BLOCKHOME_SCHEMA_TABLE_COOK

namespace blockhome {

// ---- prefill: the declared defaults, in place (docs/SPEC-TABLES.md) ----

inline void ArmorPlateReset( ArmorPlate & value );
inline void ArmorConfigReset( ArmorConfig & value );
inline void FiringGroupReset( FiringGroup & value );
inline void GunnerSettingsReset( GunnerSettings & value );

inline void ArmorPlateReset( ArmorPlate & value ) { value = ArmorPlate(); }

inline void ArmorConfigReset( ArmorConfig & value ) { value = ArmorConfig(); }

inline void FiringGroupReset( FiringGroup & value ) { value = FiringGroup(); }

inline void GunnerSettingsReset( GunnerSettings & value ) { value = GunnerSettings(); }

// ---- codecs: measure/save/load per closure member ----

inline int64_t ArmorPlateMeasureBody( TableIds & ids, const ArmorPlate & value );
BLOCKHOME_TABLE_INLINE bool ArmorPlateSaveBody( TableWriter & w, TableIds & ids, const ArmorPlate & value );
BLOCKHOME_TABLE_INLINE bool ArmorPlateLoadBody( TableReader & r, ArmorPlate & value );
inline int64_t ArmorConfigMeasureBody( TableIds & ids, const ArmorConfig & value );
BLOCKHOME_TABLE_INLINE bool ArmorConfigSaveBody( TableWriter & w, TableIds & ids, const ArmorConfig & value );
BLOCKHOME_TABLE_INLINE bool ArmorConfigLoadBody( TableReader & r, ArmorConfig & value );
inline int64_t FiringGroupMeasureBody( TableIds & ids, const FiringGroup & value );
BLOCKHOME_TABLE_INLINE bool FiringGroupSaveBody( TableWriter & w, TableIds & ids, const FiringGroup & value );
BLOCKHOME_TABLE_INLINE bool FiringGroupLoadBody( TableReader & r, FiringGroup & value );
inline int64_t GunnerSettingsMeasureBody( TableIds & ids, const GunnerSettings & value );
BLOCKHOME_TABLE_INLINE bool GunnerSettingsSaveBody( TableWriter & w, TableIds & ids, const GunnerSettings & value );
BLOCKHOME_TABLE_INLINE bool GunnerSettingsLoadBody( TableReader & r, GunnerSettings & value );

inline int64_t ArmorPlateMeasureBody( TableIds & ids, const ArmorPlate & value )
{
    int64_t bytes = 1; // the ZERO REFERENCE that ends the body
    if ( value.thickness != 0.0 ) { bytes += TableLebBytes( ids.ref( 0xdbae65ca25b4f315ull ) ) + 1 + 8; } // thickness
    if ( value.material != 0 ) { bytes += TableLebBytes( ids.ref( 0x026f7568983161e0ull ) ) + 1 + 4; } // material
    if ( value.layer != 0 ) { bytes += TableLebBytes( ids.ref( 0x84e39fec29768c56ull ) ) + 1 + 1; } // layer
    return bytes;
}

inline int64_t ArmorPlateMeasure( const ArmorPlate & value )
{
    TableIds ids;
    const int64_t body = ArmorPlateMeasureBody( ids, value );
    if ( body < 0 || ids.overflow ) { return -1; }
    return 1 + body + TableIdsBytes( ids );
}

BLOCKHOME_TABLE_INLINE bool ArmorPlateSaveBody( TableWriter & w, TableIds & ids, const ArmorPlate & value )
{
    if ( value.thickness != 0.0 )
    {
        w.putleb( ids.ref( 0xdbae65ca25b4f315ull ) ); w.put8( 11 ); // thickness
        w.put64( table_double_to_bits( value.thickness ) );
    }
    if ( value.material != 0 )
    {
        w.putleb( ids.ref( 0x026f7568983161e0ull ) ); w.put8( 8 ); // material
        w.put32( uint32_t( value.material ) );
    }
    if ( value.layer != 0 )
    {
        w.putleb( ids.ref( 0x84e39fec29768c56ull ) ); w.put8( 6 ); // layer
        w.put8( uint8_t( value.layer ) );
    }
    w.put8( 0 ); // the ZERO REFERENCE that ends the body
    return !w.overflow;
}

inline int64_t ArmorPlateSave( const ArmorPlate & value, uint8_t * buffer, int64_t capacity )
{
    TableWriter w( buffer, capacity );
    TableIds ids;
    w.put8( kTableWireForm ); // the FORM BYTE is the whole header (§3)
    if ( !ArmorPlateSaveBody( w, ids, value ) || ids.overflow ) { return -1; }
    TableIdsWrite( w, ids ); // the ID TABLE is the last thing in the file
    if ( w.overflow ) { return -1; }
    return w.offset; // == ArmorPlateMeasure( value )
}

BLOCKHOME_TABLE_INLINE bool ArmorPlateLoadBody( TableReader & r, ArmorPlate & value )
{
    ArmorPlateReset( value ); // prefill declared defaults in place, then overlay
    for ( ;; )
    {
        uint64_t field_ref = 0;
        if ( !r.getleb( field_ref ) ) { r.report->malformed = true; return false; }
        if ( field_ref == 0 ) return true; // the body ENDS AT ITS OWN ZERO REFERENCE
        if ( r.ids == NULL || field_ref > (uint64_t) r.ids->count ) { r.report->malformed = true; return false; } // a reference ABOVE the entry count
        const uint64_t field_id = r.ids->at( field_ref );
        if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
        uint8_t kind = r.get8();
        if ( field_id == kTableNodeTableFieldId && r.nested )
        {
            // THE RESERVED ID INSIDE A NESTED BODY IS MALFORMED
            // (docs/SPEC-TABLES.md §3.1), on the numbering's own rule: a
            // second numbering cannot exist, so a body claiming one is
            // damaged — that body stops and the parent reads on past its L.
            r.report->malformed = true;
            return false;
        }
        switch ( field_id )
        {
            case 0xdbae65ca25b4f315ull: // thickness
            {
                if ( kind != 11 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 8 ) ) { r.report->malformed = true; return false; }
                value.thickness = table_bits_to_double( r.get64() );
                break;
            }
            case 0x026f7568983161e0ull: // material
            {
                if ( kind != 8 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                uint32_t decoded_v = uint32_t( r.get32( ) );
                value.material = decoded_v;
                break;
            }
            case 0x84e39fec29768c56ull: // layer
            {
                if ( kind != 6 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
                uint8_t decoded_v = uint8_t( r.get8( ) );
                value.layer = decoded_v;
                break;
            }
            default:
            {
                r.report->unknown++;
                if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                break;
            }
        }
    }
}

// THE FORM BYTE IS READ FIRST, before the trailer and before any body, so a
// file that is both a newer form and damaged is a REFUSAL and never damage.
// A refusal moves none of the report's five counters, because nothing was
// decoded and there is nothing to count (docs/SPEC-TABLES.md §3).
inline TableOpenVerdict ArmorPlateLoadVerdict( ArmorPlate & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    TableReport ignored;
    TableReport * to = report != NULL ? report : &ignored;
    TableIdTable table;
    int64_t body_bytes = 0;
    const TableOpenVerdict verdict = TableOpen( buffer, bytes, table, body_bytes );
    if ( verdict != TableOpenOk )
    {
        ArmorPlateReset( value );
        if ( verdict == TableOpenDamaged ) { to->malformed = true; }
        else { to->refused = true; }
        return verdict;
    }
    // ANY BYTE BETWEEN THE ROOT'S TERMINATOR AND THE TABLE'S FIRST ENTRY IS
    // MALFORMED, because no field claims it and the two ends of the file
    // have met: nothing is decoded and one event is counted (§3).
    if ( TableBodyEndsEarly( buffer + 1, body_bytes, table ) )
    {
        ArmorPlateReset( value );
        to->malformed = true;
        return TableOpenDamaged;
    }
    TableReader r( buffer + 1, body_bytes, to, &table );
    r.nested = false; // the ROOT body, the one that may carry a node table
    if ( !ArmorPlateLoadBody( r, value ) ) { return TableOpenBodyStopped; }
    return TableOpenOk;
}

// The bool is the BODY reaching its own terminator, and it is what it has
// always been: framing damage inside a field keeps what it decoded, flags
// the report and reads on, so this answers true (docs/SPEC-TABLES.md §4).
// False is a wire nothing could be decoded from: a refusal, a table that
// cannot be read whole, or a root body the walk could not finish.
inline bool ArmorPlateLoad( ArmorPlate & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    return ArmorPlateLoadVerdict( value, buffer, bytes, report ) == TableOpenOk;
}

inline int64_t ArmorConfigMeasureBody( TableIds & ids, const ArmorConfig & value )
{
    int64_t bytes = 1; // the ZERO REFERENCE that ends the body
    {
        const int32_t mark_front = ids.count;
        const uint64_t ref_front = ids.ref( 0x538b8c566e9e4b38ull );
        const int64_t body_front = ArmorPlateMeasureBody( ids, value.front );
        if ( body_front < 0 ) { return -1; }
        if ( body_front > 1 ) { bytes += TableLebBytes( ref_front ) + 1 + TableLebBytes( (uint64_t) ( body_front ) ) + ( body_front ); } // front
        else { ids.truncate( mark_front ); } // an all-default nested table elides, and costs no entry
    }
    {
        const int32_t mark_rear = ids.count;
        const uint64_t ref_rear = ids.ref( 0x4ce65d1fbfdde703ull );
        const int64_t body_rear = ArmorPlateMeasureBody( ids, value.rear );
        if ( body_rear < 0 ) { return -1; }
        if ( body_rear > 1 ) { bytes += TableLebBytes( ref_rear ) + 1 + TableLebBytes( (uint64_t) ( body_rear ) ) + ( body_rear ); } // rear
        else { ids.truncate( mark_rear ); } // an all-default nested table elides, and costs no entry
    }
    if ( value.rating != 0.0f ) { bytes += TableLebBytes( ids.ref( 0x4e79ecbefe5ff4d0ull ) ) + 1 + 4; } // rating
    if ( value.tier != 0 ) { bytes += TableLebBytes( ids.ref( 0x1e6f84ef2eb65989ull ) ) + 1 + 1; } // tier
    return bytes;
}

inline int64_t ArmorConfigMeasure( const ArmorConfig & value )
{
    TableIds ids;
    const int64_t body = ArmorConfigMeasureBody( ids, value );
    if ( body < 0 || ids.overflow ) { return -1; }
    return 1 + body + TableIdsBytes( ids );
}

BLOCKHOME_TABLE_INLINE bool ArmorConfigSaveBody( TableWriter & w, TableIds & ids, const ArmorConfig & value )
{
    {
        const int32_t mark_front = ids.count;
        const uint64_t ref_front = ids.ref( 0x538b8c566e9e4b38ull );
        const int64_t body_front = ArmorPlateMeasureBody( ids, value.front );
        if ( body_front < 0 ) return false; // storage invariant, refused as measure refuses it
        if ( body_front > 1 ) // all-default nested elides
        {
            w.putleb( ref_front ); w.put8( 13 ); w.putleb( (uint64_t) body_front ); // front
            if ( !ArmorPlateSaveBody( w, ids, value.front ) ) return false;
        }
        else { ids.truncate( mark_front ); }
    }
    {
        const int32_t mark_rear = ids.count;
        const uint64_t ref_rear = ids.ref( 0x4ce65d1fbfdde703ull );
        const int64_t body_rear = ArmorPlateMeasureBody( ids, value.rear );
        if ( body_rear < 0 ) return false; // storage invariant, refused as measure refuses it
        if ( body_rear > 1 ) // all-default nested elides
        {
            w.putleb( ref_rear ); w.put8( 13 ); w.putleb( (uint64_t) body_rear ); // rear
            if ( !ArmorPlateSaveBody( w, ids, value.rear ) ) return false;
        }
        else { ids.truncate( mark_rear ); }
    }
    if ( value.rating != 0.0f )
    {
        w.putleb( ids.ref( 0x4e79ecbefe5ff4d0ull ) ); w.put8( 10 ); // rating
        w.put32( table_float_to_bits( value.rating ) );
    }
    if ( value.tier != 0 )
    {
        w.putleb( ids.ref( 0x1e6f84ef2eb65989ull ) ); w.put8( 6 ); // tier
        w.put8( uint8_t( value.tier ) );
    }
    w.put8( 0 ); // the ZERO REFERENCE that ends the body
    return !w.overflow;
}

inline int64_t ArmorConfigSave( const ArmorConfig & value, uint8_t * buffer, int64_t capacity )
{
    TableWriter w( buffer, capacity );
    TableIds ids;
    w.put8( kTableWireForm ); // the FORM BYTE is the whole header (§3)
    if ( !ArmorConfigSaveBody( w, ids, value ) || ids.overflow ) { return -1; }
    TableIdsWrite( w, ids ); // the ID TABLE is the last thing in the file
    if ( w.overflow ) { return -1; }
    return w.offset; // == ArmorConfigMeasure( value )
}

BLOCKHOME_TABLE_INLINE bool ArmorConfigLoadBody( TableReader & r, ArmorConfig & value )
{
    ArmorConfigReset( value ); // prefill declared defaults in place, then overlay
    for ( ;; )
    {
        uint64_t field_ref = 0;
        if ( !r.getleb( field_ref ) ) { r.report->malformed = true; return false; }
        if ( field_ref == 0 ) return true; // the body ENDS AT ITS OWN ZERO REFERENCE
        if ( r.ids == NULL || field_ref > (uint64_t) r.ids->count ) { r.report->malformed = true; return false; } // a reference ABOVE the entry count
        const uint64_t field_id = r.ids->at( field_ref );
        if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
        uint8_t kind = r.get8();
        if ( field_id == kTableNodeTableFieldId && r.nested )
        {
            // THE RESERVED ID INSIDE A NESTED BODY IS MALFORMED
            // (docs/SPEC-TABLES.md §3.1), on the numbering's own rule: a
            // second numbering cannot exist, so a body claiming one is
            // damaged — that body stops and the parent reads on past its L.
            r.report->malformed = true;
            return false;
        }
        switch ( field_id )
        {
            case 0x538b8c566e9e4b38ull: // front
            {
                if ( kind != 13 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                uint64_t body_len = 0;
                if ( !r.getleb( body_len ) || !r.room( body_len ) ) { r.report->malformed = true; return false; }
                {
                    TableReader sub( r.buffer + r.offset, (int64_t) body_len, r.report, r.ids );
                    ArmorPlateLoadBody( sub, value.front );
                    if ( sub.offset != sub.size )
                    {
                        r.report->malformed = true;
                        ArmorPlateReset( value.front );
                    }
                }
                r.offset += (int64_t) body_len;
                break;
            }
            case 0x4ce65d1fbfdde703ull: // rear
            {
                if ( kind != 13 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                uint64_t body_len = 0;
                if ( !r.getleb( body_len ) || !r.room( body_len ) ) { r.report->malformed = true; return false; }
                {
                    TableReader sub( r.buffer + r.offset, (int64_t) body_len, r.report, r.ids );
                    ArmorPlateLoadBody( sub, value.rear );
                    if ( sub.offset != sub.size )
                    {
                        r.report->malformed = true;
                        ArmorPlateReset( value.rear );
                    }
                }
                r.offset += (int64_t) body_len;
                break;
            }
            case 0x4e79ecbefe5ff4d0ull: // rating
            {
                if ( kind != 10 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                value.rating = table_bits_to_float( r.get32() );
                break;
            }
            case 0x1e6f84ef2eb65989ull: // tier
            {
                if ( kind != 6 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
                uint8_t decoded_v = uint8_t( r.get8( ) );
                value.tier = decoded_v;
                break;
            }
            default:
            {
                r.report->unknown++;
                if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                break;
            }
        }
    }
}

// THE FORM BYTE IS READ FIRST, before the trailer and before any body, so a
// file that is both a newer form and damaged is a REFUSAL and never damage.
// A refusal moves none of the report's five counters, because nothing was
// decoded and there is nothing to count (docs/SPEC-TABLES.md §3).
inline TableOpenVerdict ArmorConfigLoadVerdict( ArmorConfig & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    TableReport ignored;
    TableReport * to = report != NULL ? report : &ignored;
    TableIdTable table;
    int64_t body_bytes = 0;
    const TableOpenVerdict verdict = TableOpen( buffer, bytes, table, body_bytes );
    if ( verdict != TableOpenOk )
    {
        ArmorConfigReset( value );
        if ( verdict == TableOpenDamaged ) { to->malformed = true; }
        else { to->refused = true; }
        return verdict;
    }
    // ANY BYTE BETWEEN THE ROOT'S TERMINATOR AND THE TABLE'S FIRST ENTRY IS
    // MALFORMED, because no field claims it and the two ends of the file
    // have met: nothing is decoded and one event is counted (§3).
    if ( TableBodyEndsEarly( buffer + 1, body_bytes, table ) )
    {
        ArmorConfigReset( value );
        to->malformed = true;
        return TableOpenDamaged;
    }
    TableReader r( buffer + 1, body_bytes, to, &table );
    r.nested = false; // the ROOT body, the one that may carry a node table
    if ( !ArmorConfigLoadBody( r, value ) ) { return TableOpenBodyStopped; }
    return TableOpenOk;
}

// The bool is the BODY reaching its own terminator, and it is what it has
// always been: framing damage inside a field keeps what it decoded, flags
// the report and reads on, so this answers true (docs/SPEC-TABLES.md §4).
// False is a wire nothing could be decoded from: a refusal, a table that
// cannot be read whole, or a root body the walk could not finish.
inline bool ArmorConfigLoad( ArmorConfig & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    return ArmorConfigLoadVerdict( value, buffer, bytes, report ) == TableOpenOk;
}

inline int64_t FiringGroupMeasureBody( TableIds & ids, const FiringGroup & value )
{
    int64_t bytes = 1; // the ZERO REFERENCE that ends the body
    if ( value.barrel != 0 ) { bytes += TableLebBytes( ids.ref( 0x8ece059ad360b651ull ) ) + 1 + 4; } // barrel
    if ( value.cooldown != 0.0f ) { bytes += TableLebBytes( ids.ref( 0xdc2cbe6953343d48ull ) ) + 1 + 4; } // cooldown
    return bytes;
}

inline int64_t FiringGroupMeasure( const FiringGroup & value )
{
    TableIds ids;
    const int64_t body = FiringGroupMeasureBody( ids, value );
    if ( body < 0 || ids.overflow ) { return -1; }
    return 1 + body + TableIdsBytes( ids );
}

BLOCKHOME_TABLE_INLINE bool FiringGroupSaveBody( TableWriter & w, TableIds & ids, const FiringGroup & value )
{
    if ( value.barrel != 0 )
    {
        w.putleb( ids.ref( 0x8ece059ad360b651ull ) ); w.put8( 8 ); // barrel
        w.put32( uint32_t( value.barrel ) );
    }
    if ( value.cooldown != 0.0f )
    {
        w.putleb( ids.ref( 0xdc2cbe6953343d48ull ) ); w.put8( 10 ); // cooldown
        w.put32( table_float_to_bits( value.cooldown ) );
    }
    w.put8( 0 ); // the ZERO REFERENCE that ends the body
    return !w.overflow;
}

inline int64_t FiringGroupSave( const FiringGroup & value, uint8_t * buffer, int64_t capacity )
{
    TableWriter w( buffer, capacity );
    TableIds ids;
    w.put8( kTableWireForm ); // the FORM BYTE is the whole header (§3)
    if ( !FiringGroupSaveBody( w, ids, value ) || ids.overflow ) { return -1; }
    TableIdsWrite( w, ids ); // the ID TABLE is the last thing in the file
    if ( w.overflow ) { return -1; }
    return w.offset; // == FiringGroupMeasure( value )
}

BLOCKHOME_TABLE_INLINE bool FiringGroupLoadBody( TableReader & r, FiringGroup & value )
{
    FiringGroupReset( value ); // prefill declared defaults in place, then overlay
    for ( ;; )
    {
        uint64_t field_ref = 0;
        if ( !r.getleb( field_ref ) ) { r.report->malformed = true; return false; }
        if ( field_ref == 0 ) return true; // the body ENDS AT ITS OWN ZERO REFERENCE
        if ( r.ids == NULL || field_ref > (uint64_t) r.ids->count ) { r.report->malformed = true; return false; } // a reference ABOVE the entry count
        const uint64_t field_id = r.ids->at( field_ref );
        if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
        uint8_t kind = r.get8();
        if ( field_id == kTableNodeTableFieldId && r.nested )
        {
            // THE RESERVED ID INSIDE A NESTED BODY IS MALFORMED
            // (docs/SPEC-TABLES.md §3.1), on the numbering's own rule: a
            // second numbering cannot exist, so a body claiming one is
            // damaged — that body stops and the parent reads on past its L.
            r.report->malformed = true;
            return false;
        }
        switch ( field_id )
        {
            case 0x8ece059ad360b651ull: // barrel
            {
                if ( kind != 8 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                uint32_t decoded_v = uint32_t( r.get32( ) );
                value.barrel = decoded_v;
                break;
            }
            case 0xdc2cbe6953343d48ull: // cooldown
            {
                if ( kind != 10 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                value.cooldown = table_bits_to_float( r.get32() );
                break;
            }
            default:
            {
                r.report->unknown++;
                if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                break;
            }
        }
    }
}

// THE FORM BYTE IS READ FIRST, before the trailer and before any body, so a
// file that is both a newer form and damaged is a REFUSAL and never damage.
// A refusal moves none of the report's five counters, because nothing was
// decoded and there is nothing to count (docs/SPEC-TABLES.md §3).
inline TableOpenVerdict FiringGroupLoadVerdict( FiringGroup & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    TableReport ignored;
    TableReport * to = report != NULL ? report : &ignored;
    TableIdTable table;
    int64_t body_bytes = 0;
    const TableOpenVerdict verdict = TableOpen( buffer, bytes, table, body_bytes );
    if ( verdict != TableOpenOk )
    {
        FiringGroupReset( value );
        if ( verdict == TableOpenDamaged ) { to->malformed = true; }
        else { to->refused = true; }
        return verdict;
    }
    // ANY BYTE BETWEEN THE ROOT'S TERMINATOR AND THE TABLE'S FIRST ENTRY IS
    // MALFORMED, because no field claims it and the two ends of the file
    // have met: nothing is decoded and one event is counted (§3).
    if ( TableBodyEndsEarly( buffer + 1, body_bytes, table ) )
    {
        FiringGroupReset( value );
        to->malformed = true;
        return TableOpenDamaged;
    }
    TableReader r( buffer + 1, body_bytes, to, &table );
    r.nested = false; // the ROOT body, the one that may carry a node table
    if ( !FiringGroupLoadBody( r, value ) ) { return TableOpenBodyStopped; }
    return TableOpenOk;
}

// The bool is the BODY reaching its own terminator, and it is what it has
// always been: framing damage inside a field keeps what it decoded, flags
// the report and reads on, so this answers true (docs/SPEC-TABLES.md §4).
// False is a wire nothing could be decoded from: a refusal, a table that
// cannot be read whole, or a root body the walk could not finish.
inline bool FiringGroupLoad( FiringGroup & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    return FiringGroupLoadVerdict( value, buffer, bytes, report ) == TableOpenOk;
}

inline int64_t GunnerSettingsMeasureBody( TableIds & ids, const GunnerSettings & value )
{
    int64_t bytes = 1; // the ZERO REFERENCE that ends the body
    if ( value.firing_groups_count < 0 || value.firing_groups_count > 32 ) { return -1; } // storage invariant
    if ( value.firing_groups_count > 0 )
    {
        const uint64_t ref_firing_groups = ids.ref( 0x260b8ca6b0c3db7full );
        int64_t body_firing_groups = 0;
        body_firing_groups += 1 + TableLebBytes( (uint64_t) ( value.firing_groups_count ) ); // the element kind byte and the count
        for ( int32_t elem_i = 0; elem_i < value.firing_groups_count; elem_i++ )
        {
            const int64_t elem_bytes = FiringGroupMeasureBody( ids, value.firing_groups[elem_i] );
            if ( elem_bytes < 0 ) { return -1; }
            body_firing_groups += TableLebBytes( (uint64_t) ( elem_bytes ) ) + ( elem_bytes );
        }
        bytes += TableLebBytes( ref_firing_groups ) + 1 + TableLebBytes( (uint64_t) ( body_firing_groups ) ) + ( body_firing_groups ); // firing_groups
    }
    if ( value.missile_groups_count < 0 || value.missile_groups_count > 4 ) { return -1; } // storage invariant
    if ( value.missile_groups_count > 0 )
    {
        const uint64_t ref_missile_groups = ids.ref( 0x3c99105aa087f6bcull );
        int64_t body_missile_groups = 0;
        body_missile_groups += 1 + TableLebBytes( (uint64_t) ( value.missile_groups_count ) ); // the element kind byte and the count
        for ( int32_t elem_i = 0; elem_i < value.missile_groups_count; elem_i++ )
        {
            const int64_t elem_bytes = FiringGroupMeasureBody( ids, value.missile_groups[elem_i] );
            if ( elem_bytes < 0 ) { return -1; }
            body_missile_groups += TableLebBytes( (uint64_t) ( elem_bytes ) ) + ( elem_bytes );
        }
        bytes += TableLebBytes( ref_missile_groups ) + 1 + TableLebBytes( (uint64_t) ( body_missile_groups ) ) + ( body_missile_groups ); // missile_groups
    }
    if ( value.reload_seconds != 0.0f ) { bytes += TableLebBytes( ids.ref( 0xad9b64728ea52486ull ) ) + 1 + 4; } // reload_seconds
    if ( value.gunner_id != 0 ) { bytes += TableLebBytes( ids.ref( 0xbd9be53180256e02ull ) ) + 1 + 4; } // gunner_id
    return bytes;
}

inline int64_t GunnerSettingsMeasure( const GunnerSettings & value )
{
    TableIds ids;
    const int64_t body = GunnerSettingsMeasureBody( ids, value );
    if ( body < 0 || ids.overflow ) { return -1; }
    return 1 + body + TableIdsBytes( ids );
}

BLOCKHOME_TABLE_INLINE bool GunnerSettingsSaveBody( TableWriter & w, TableIds & ids, const GunnerSettings & value )
{
    if ( value.firing_groups_count < 0 || value.firing_groups_count > 32 ) { return false; } // storage invariant
    if ( value.firing_groups_count > 0 )
    {
        const uint64_t ref_firing_groups = ids.ref( 0x260b8ca6b0c3db7full );
        int64_t body_firing_groups = 0;
        body_firing_groups += 1 + TableLebBytes( (uint64_t) ( value.firing_groups_count ) ); // the element kind byte and the count
        for ( int32_t elem_i = 0; elem_i < value.firing_groups_count; elem_i++ )
        {
            const int64_t elem_bytes = FiringGroupMeasureBody( ids, value.firing_groups[elem_i] );
            if ( elem_bytes < 0 ) { return false; }
            body_firing_groups += TableLebBytes( (uint64_t) ( elem_bytes ) ) + ( elem_bytes );
        }
        w.putleb( ref_firing_groups ); w.put8( 14 ); w.putleb( (uint64_t) body_firing_groups ); // firing_groups
        w.put8( 13 ); w.putleb( (uint64_t) ( value.firing_groups_count ) );
        for ( int32_t elem_i = 0; elem_i < value.firing_groups_count; elem_i++ )
        {
            {
                const int64_t elem_len = FiringGroupMeasureBody( ids, value.firing_groups[elem_i] );
                if ( elem_len < 0 ) return false;
                w.putleb( (uint64_t) elem_len );
                if ( !FiringGroupSaveBody( w, ids, value.firing_groups[elem_i] ) ) return false;
            }
        }
    }
    if ( value.missile_groups_count < 0 || value.missile_groups_count > 4 ) { return false; } // storage invariant
    if ( value.missile_groups_count > 0 )
    {
        const uint64_t ref_missile_groups = ids.ref( 0x3c99105aa087f6bcull );
        int64_t body_missile_groups = 0;
        body_missile_groups += 1 + TableLebBytes( (uint64_t) ( value.missile_groups_count ) ); // the element kind byte and the count
        for ( int32_t elem_i = 0; elem_i < value.missile_groups_count; elem_i++ )
        {
            const int64_t elem_bytes = FiringGroupMeasureBody( ids, value.missile_groups[elem_i] );
            if ( elem_bytes < 0 ) { return false; }
            body_missile_groups += TableLebBytes( (uint64_t) ( elem_bytes ) ) + ( elem_bytes );
        }
        w.putleb( ref_missile_groups ); w.put8( 14 ); w.putleb( (uint64_t) body_missile_groups ); // missile_groups
        w.put8( 13 ); w.putleb( (uint64_t) ( value.missile_groups_count ) );
        for ( int32_t elem_i = 0; elem_i < value.missile_groups_count; elem_i++ )
        {
            {
                const int64_t elem_len = FiringGroupMeasureBody( ids, value.missile_groups[elem_i] );
                if ( elem_len < 0 ) return false;
                w.putleb( (uint64_t) elem_len );
                if ( !FiringGroupSaveBody( w, ids, value.missile_groups[elem_i] ) ) return false;
            }
        }
    }
    if ( value.reload_seconds != 0.0f )
    {
        w.putleb( ids.ref( 0xad9b64728ea52486ull ) ); w.put8( 10 ); // reload_seconds
        w.put32( table_float_to_bits( value.reload_seconds ) );
    }
    if ( value.gunner_id != 0 )
    {
        w.putleb( ids.ref( 0xbd9be53180256e02ull ) ); w.put8( 8 ); // gunner_id
        w.put32( uint32_t( value.gunner_id ) );
    }
    w.put8( 0 ); // the ZERO REFERENCE that ends the body
    return !w.overflow;
}

inline int64_t GunnerSettingsSave( const GunnerSettings & value, uint8_t * buffer, int64_t capacity )
{
    TableWriter w( buffer, capacity );
    TableIds ids;
    w.put8( kTableWireForm ); // the FORM BYTE is the whole header (§3)
    if ( !GunnerSettingsSaveBody( w, ids, value ) || ids.overflow ) { return -1; }
    TableIdsWrite( w, ids ); // the ID TABLE is the last thing in the file
    if ( w.overflow ) { return -1; }
    return w.offset; // == GunnerSettingsMeasure( value )
}

BLOCKHOME_TABLE_INLINE bool GunnerSettingsLoadBody( TableReader & r, GunnerSettings & value )
{
    GunnerSettingsReset( value ); // prefill declared defaults in place, then overlay
    for ( ;; )
    {
        uint64_t field_ref = 0;
        if ( !r.getleb( field_ref ) ) { r.report->malformed = true; return false; }
        if ( field_ref == 0 ) return true; // the body ENDS AT ITS OWN ZERO REFERENCE
        if ( r.ids == NULL || field_ref > (uint64_t) r.ids->count ) { r.report->malformed = true; return false; } // a reference ABOVE the entry count
        const uint64_t field_id = r.ids->at( field_ref );
        if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
        uint8_t kind = r.get8();
        if ( field_id == kTableNodeTableFieldId && r.nested )
        {
            // THE RESERVED ID INSIDE A NESTED BODY IS MALFORMED
            // (docs/SPEC-TABLES.md §3.1), on the numbering's own rule: a
            // second numbering cannot exist, so a body claiming one is
            // damaged — that body stops and the parent reads on past its L.
            r.report->malformed = true;
            return false;
        }
        switch ( field_id )
        {
            case 0x260b8ca6b0c3db7full: // firing_groups
            {
                if ( kind != 14 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                uint64_t body_len = 0;
                if ( !r.getleb( body_len ) || !r.room( body_len ) ) { r.report->malformed = true; return false; }
                int64_t body_end = r.offset + (int64_t) body_len;
                // A BODY TOO SHORT FOR ITS OWN HEADER — the element kind byte and the
                // count, so fewer than two bytes — is INERT (§4): the field keeps the
                // value it has, no counter is raised, and the walk continues past L.
                if ( body_len >= 2 )
                {
                    uint8_t elem_kind = r.get8();
                    uint64_t count = 0;
                    const bool counted_ok = r.getleb( count );
                    // A DAMAGED COUNT stops the elements and nothing else: the field
                    // RODE, so an optional is still PRESENT (§2.3) — only a foreign
                    // ELEMENT KIND says the payload is not this array's at all.
                    if ( !counted_ok ) { r.report->malformed = true; }
                    else if ( elem_kind != 13 ) { r.report->kind_mismatch++; r.offset = body_end; break; }
                    else
                    {
                    uint64_t keep = count;
                    if ( keep > 32 ) { keep = 32; r.report->clamped++; }
                    // elements are BOUNDED by the field body: a count the length
                    // cannot cover keeps the decoded prefix, flags malformed, and
                    // the parent continues at the next field — following fields'
                    // bytes are never fabricated into elements
                    TableReader sub( r.buffer + r.offset, body_end - r.offset, r.report, r.ids );
                    uint64_t decoded = 0;
                    for ( uint64_t i = 0; i < keep; i++ )
                    {
                        uint64_t elem_len = 0;
                        if ( !sub.getleb( elem_len ) || !sub.room( elem_len ) ) { r.report->malformed = true; break; }
                        {
                            TableReader elem( sub.buffer + sub.offset, (int64_t) elem_len, r.report, r.ids );
                            FiringGroupLoadBody( elem, value.firing_groups[(int32_t) i] );
                        }
                        sub.offset += (int64_t) elem_len;
                        decoded = i + 1;
                    }
                    value.firing_groups_count = (int32_t) decoded;
                    }
                }
                r.offset = body_end; // excess elements and slack skip via the length
                break;
            }
            case 0x3c99105aa087f6bcull: // missile_groups
            {
                if ( kind != 14 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                uint64_t body_len = 0;
                if ( !r.getleb( body_len ) || !r.room( body_len ) ) { r.report->malformed = true; return false; }
                int64_t body_end = r.offset + (int64_t) body_len;
                // A BODY TOO SHORT FOR ITS OWN HEADER — the element kind byte and the
                // count, so fewer than two bytes — is INERT (§4): the field keeps the
                // value it has, no counter is raised, and the walk continues past L.
                if ( body_len >= 2 )
                {
                    uint8_t elem_kind = r.get8();
                    uint64_t count = 0;
                    const bool counted_ok = r.getleb( count );
                    // A DAMAGED COUNT stops the elements and nothing else: the field
                    // RODE, so an optional is still PRESENT (§2.3) — only a foreign
                    // ELEMENT KIND says the payload is not this array's at all.
                    if ( !counted_ok ) { r.report->malformed = true; }
                    else if ( elem_kind != 13 ) { r.report->kind_mismatch++; r.offset = body_end; break; }
                    else
                    {
                    uint64_t keep = count;
                    if ( keep > 4 ) { keep = 4; r.report->clamped++; }
                    // elements are BOUNDED by the field body: a count the length
                    // cannot cover keeps the decoded prefix, flags malformed, and
                    // the parent continues at the next field — following fields'
                    // bytes are never fabricated into elements
                    TableReader sub( r.buffer + r.offset, body_end - r.offset, r.report, r.ids );
                    uint64_t decoded = 0;
                    for ( uint64_t i = 0; i < keep; i++ )
                    {
                        uint64_t elem_len = 0;
                        if ( !sub.getleb( elem_len ) || !sub.room( elem_len ) ) { r.report->malformed = true; break; }
                        {
                            TableReader elem( sub.buffer + sub.offset, (int64_t) elem_len, r.report, r.ids );
                            FiringGroupLoadBody( elem, value.missile_groups[(int32_t) i] );
                        }
                        sub.offset += (int64_t) elem_len;
                        decoded = i + 1;
                    }
                    value.missile_groups_count = (int32_t) decoded;
                    }
                }
                r.offset = body_end; // excess elements and slack skip via the length
                break;
            }
            case 0xad9b64728ea52486ull: // reload_seconds
            {
                if ( kind != 10 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                value.reload_seconds = table_bits_to_float( r.get32() );
                break;
            }
            case 0xbd9be53180256e02ull: // gunner_id
            {
                if ( kind != 8 )
                {
                    // AT A POSITION THE READER DOES NAME, a field under
                    // kind 31 or kind 32 takes this same rule and no other (§3)
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                uint32_t decoded_v = uint32_t( r.get32( ) );
                value.gunner_id = decoded_v;
                break;
            }
            default:
            {
                r.report->unknown++;
                if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                break;
            }
        }
    }
}

// THE FORM BYTE IS READ FIRST, before the trailer and before any body, so a
// file that is both a newer form and damaged is a REFUSAL and never damage.
// A refusal moves none of the report's five counters, because nothing was
// decoded and there is nothing to count (docs/SPEC-TABLES.md §3).
inline TableOpenVerdict GunnerSettingsLoadVerdict( GunnerSettings & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    TableReport ignored;
    TableReport * to = report != NULL ? report : &ignored;
    TableIdTable table;
    int64_t body_bytes = 0;
    const TableOpenVerdict verdict = TableOpen( buffer, bytes, table, body_bytes );
    if ( verdict != TableOpenOk )
    {
        GunnerSettingsReset( value );
        if ( verdict == TableOpenDamaged ) { to->malformed = true; }
        else { to->refused = true; }
        return verdict;
    }
    // ANY BYTE BETWEEN THE ROOT'S TERMINATOR AND THE TABLE'S FIRST ENTRY IS
    // MALFORMED, because no field claims it and the two ends of the file
    // have met: nothing is decoded and one event is counted (§3).
    if ( TableBodyEndsEarly( buffer + 1, body_bytes, table ) )
    {
        GunnerSettingsReset( value );
        to->malformed = true;
        return TableOpenDamaged;
    }
    TableReader r( buffer + 1, body_bytes, to, &table );
    r.nested = false; // the ROOT body, the one that may carry a node table
    if ( !GunnerSettingsLoadBody( r, value ) ) { return TableOpenBodyStopped; }
    return TableOpenOk;
}

// The bool is the BODY reaching its own terminator, and it is what it has
// always been: framing damage inside a field keeps what it decoded, flags
// the report and reads on, so this answers true (docs/SPEC-TABLES.md §4).
// False is a wire nothing could be decoded from: a refusal, a table that
// cannot be read whole, or a root body the walk could not finish.
inline bool GunnerSettingsLoad( GunnerSettings & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    return GunnerSettingsLoadVerdict( value, buffer, bytes, report ) == TableOpenOk;
}

// ---- the cooked form: WRITE a cook (docs/SPEC-TABLES.md §7.6) ----
//
// The bytes are `schema cook`'s, and the tool stays the reference: the two
// writers are held to one file, byte for byte, in both byte orders. A cook is
// content-addressed by (asset hash, build version), so two writers of one
// instance produce ONE artifact or the pair means nothing.

inline void ArmorPlateCookBody( uint8_t * at, const ArmorPlate & value, TableByteOrder order );
inline void ArmorConfigCookBody( uint8_t * at, const ArmorConfig & value, TableByteOrder order );
inline void FiringGroupCookBody( uint8_t * at, const FiringGroup & value, TableByteOrder order );
inline void GunnerSettingsCookBody( uint8_t * at, const GunnerSettings & value, TableByteOrder order );

inline void ArmorPlateCookBody( uint8_t * at, const ArmorPlate & value, TableByteOrder order )
{
    { uint64_t bits = 0; memcpy( &bits, &value.thickness, 8 ); table_cook_put( at + 0, bits, 8, order ); }
    table_cook_put( at + 8, (uint64_t) value.material, 4, order );
    table_cook_put( at + 12, (uint64_t) value.layer, 1, order );
}

inline void ArmorConfigCookBody( uint8_t * at, const ArmorConfig & value, TableByteOrder order )
{
    ArmorPlateCookBody( at + 0, value.front, order );
    ArmorPlateCookBody( at + 16, value.rear, order );
    { uint32_t bits = 0; memcpy( &bits, &value.rating, 4 ); table_cook_put( at + 32, (uint64_t) bits, 4, order ); }
    table_cook_put( at + 36, (uint64_t) value.tier, 1, order );
}

inline void FiringGroupCookBody( uint8_t * at, const FiringGroup & value, TableByteOrder order )
{
    table_cook_put( at + 0, (uint64_t) value.barrel, 4, order );
    { uint32_t bits = 0; memcpy( &bits, &value.cooldown, 4 ); table_cook_put( at + 4, (uint64_t) bits, 4, order ); }
}

inline void GunnerSettingsCookBody( uint8_t * at, const GunnerSettings & value, TableByteOrder order )
{
    // all 32 slots: the storage is allocate-max, and a slot past the count rides as it lies (§7.2)
    for ( int32_t i = 0; i < 32; i++ )
    {
        FiringGroupCookBody( at + 0 + i * 8, value.firing_groups[ i ], order );
    }
    table_cook_put( at + 256, (uint64_t) (uint32_t) value.firing_groups_count, 4, order );
    // all 4 slots: the storage is allocate-max, and a slot past the count rides as it lies (§7.2)
    for ( int32_t i = 0; i < 4; i++ )
    {
        FiringGroupCookBody( at + 260 + i * 8, value.missile_groups[ i ], order );
    }
    table_cook_put( at + 292, (uint64_t) (uint32_t) value.missile_groups_count, 4, order );
    { uint32_t bits = 0; memcpy( &bits, &value.reload_seconds, 4 ); table_cook_put( at + 296, (uint64_t) bits, 4, order ); }
    table_cook_put( at + 300, (uint64_t) value.gunner_id, 4, order );
}

// ---- relocatability, enforced: the wire is a pure length-prefixed
// stream AND the decoded storage is pointer-free — every closure type
// must stay trivially copyable and standard-layout, so instances can be
// memcpy'd, mmap'd, shared across processes, and walked through
// descriptor offsets. A failure here means a pointer, virtual or
// non-trivial member crept into generated storage.
//
// They ask the COMPILER ITSELF, which is what every C++ standard library
// answers the same two questions with — and it costs this header no
// include at all.
static_assert( __is_trivially_copyable( ArmorPlate ), "ArmorPlate must stay relocatable" );
static_assert( __is_standard_layout( ArmorPlate ), "ArmorPlate must stay standard-layout for offsetof" );
static_assert( __is_trivially_copyable( ArmorConfig ), "ArmorConfig must stay relocatable" );
static_assert( __is_standard_layout( ArmorConfig ), "ArmorConfig must stay standard-layout for offsetof" );
static_assert( __is_trivially_copyable( FiringGroup ), "FiringGroup must stay relocatable" );
static_assert( __is_standard_layout( FiringGroup ), "FiringGroup must stay standard-layout for offsetof" );
static_assert( __is_trivially_copyable( GunnerSettings ), "GunnerSettings must stay relocatable" );
static_assert( __is_standard_layout( GunnerSettings ), "GunnerSettings must stay standard-layout for offsetof" );

// ---- the cook's layout contract (docs/SPEC-TABLES.md §20.3) ----
//
// The compiler derived every number below from the declaration and folded it
// into the BUILD VERSION; these asserts are this compiler saying whether it
// agrees. The model is not self-evidently right — on 32-bit System V
// alignof(uint64_t) is 4, not 8 — which is precisely why it is asserted
// rather than assumed.
static_assert( sizeof( ArmorPlate ) == 16, "ArmorPlate's sizeof moved: the build version was taken over 16, so a cook of it would not be this build's file (docs/SPEC-TABLES.md §20.3)" );
static_assert( alignof( ArmorPlate ) == 8, "ArmorPlate's alignof moved: the build version was taken over 8 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( ArmorPlate, thickness ) == 0, "ArmorPlate's field thickness moved: the build version was taken over offset 0 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( ArmorPlate, material ) == 8, "ArmorPlate's field material moved: the build version was taken over offset 8 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( ArmorPlate, layer ) == 12, "ArmorPlate's field layer moved: the build version was taken over offset 12 (docs/SPEC-TABLES.md §20.3)" );
static_assert( sizeof( ArmorConfig ) == 40, "ArmorConfig's sizeof moved: the build version was taken over 40, so a cook of it would not be this build's file (docs/SPEC-TABLES.md §20.3)" );
static_assert( alignof( ArmorConfig ) == 8, "ArmorConfig's alignof moved: the build version was taken over 8 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( ArmorConfig, front ) == 0, "ArmorConfig's field front moved: the build version was taken over offset 0 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( ArmorConfig, rear ) == 16, "ArmorConfig's field rear moved: the build version was taken over offset 16 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( ArmorConfig, rating ) == 32, "ArmorConfig's field rating moved: the build version was taken over offset 32 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( ArmorConfig, tier ) == 36, "ArmorConfig's field tier moved: the build version was taken over offset 36 (docs/SPEC-TABLES.md §20.3)" );
static_assert( sizeof( FiringGroup ) == 8, "FiringGroup's sizeof moved: the build version was taken over 8, so a cook of it would not be this build's file (docs/SPEC-TABLES.md §20.3)" );
static_assert( alignof( FiringGroup ) == 4, "FiringGroup's alignof moved: the build version was taken over 4 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( FiringGroup, barrel ) == 0, "FiringGroup's field barrel moved: the build version was taken over offset 0 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( FiringGroup, cooldown ) == 4, "FiringGroup's field cooldown moved: the build version was taken over offset 4 (docs/SPEC-TABLES.md §20.3)" );
static_assert( sizeof( GunnerSettings ) == 304, "GunnerSettings's sizeof moved: the build version was taken over 304, so a cook of it would not be this build's file (docs/SPEC-TABLES.md §20.3)" );
static_assert( alignof( GunnerSettings ) == 4, "GunnerSettings's alignof moved: the build version was taken over 4 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( GunnerSettings, firing_groups ) == 0, "GunnerSettings's field firing_groups moved: the build version was taken over offset 0 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( GunnerSettings, missile_groups ) == 260, "GunnerSettings's field missile_groups moved: the build version was taken over offset 260 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( GunnerSettings, reload_seconds ) == 296, "GunnerSettings's field reload_seconds moved: the build version was taken over offset 296 (docs/SPEC-TABLES.md §20.3)" );
static_assert( offsetof( GunnerSettings, gunner_id ) == 300, "GunnerSettings's field gunner_id moved: the build version was taken over offset 300 (docs/SPEC-TABLES.md §20.3)" );

// ---- reflection descriptors (tables only, docs/SPEC-TABLES.md) ----

inline const TableTypeInfo * ArmorPlateTableType();
inline const TableTypeInfo * ArmorConfigTableType();
inline const TableTypeInfo * FiringGroupTableType();
inline const TableTypeInfo * GunnerSettingsTableType();

inline const TableTypeInfo * ArmorPlateTableType()
{
    static const TableFieldInfo fields[] = {
        { "thickness", "thickness", "float64", 0xdbae65ca25b4f315ull, 11, false, false, false, 0, (uint32_t) offsetof( ArmorPlate, thickness ), (uint32_t) sizeof( ArmorPlate::thickness ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "material", "material", "uint32", 0x026f7568983161e0ull, 8, false, false, false, 0, (uint32_t) offsetof( ArmorPlate, material ), (uint32_t) sizeof( ArmorPlate::material ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "layer", "layer", "uint8", 0x84e39fec29768c56ull, 6, false, false, false, 0, (uint32_t) offsetof( ArmorPlate, layer ), (uint32_t) sizeof( ArmorPlate::layer ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
    };
    static const TableTypeInfo info = { "ArmorPlate", (uint32_t) sizeof( ArmorPlate ), 3, fields, +[]( void * p ) { ArmorPlateReset( *(ArmorPlate *) p ); } };
    return &info;
}

inline const TableTypeInfo * ArmorConfigTableType()
{
    static const TableFieldInfo fields[] = {
        { "front", "front", "ArmorPlate", 0x538b8c566e9e4b38ull, 13, false, false, false, 0, (uint32_t) offsetof( ArmorConfig, front ), (uint32_t) sizeof( ArmorConfig::front ), 0xffffffffu, 0xffffffffu, ArmorPlateTableType(), false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "rear", "rear", "ArmorPlate", 0x4ce65d1fbfdde703ull, 13, false, false, false, 0, (uint32_t) offsetof( ArmorConfig, rear ), (uint32_t) sizeof( ArmorConfig::rear ), 0xffffffffu, 0xffffffffu, ArmorPlateTableType(), false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "rating", "rating", "float32", 0x4e79ecbefe5ff4d0ull, 10, false, false, false, 0, (uint32_t) offsetof( ArmorConfig, rating ), (uint32_t) sizeof( ArmorConfig::rating ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "tier", "tier", "uint8", 0x1e6f84ef2eb65989ull, 6, false, false, false, 0, (uint32_t) offsetof( ArmorConfig, tier ), (uint32_t) sizeof( ArmorConfig::tier ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
    };
    static const TableTypeInfo info = { "ArmorConfig", (uint32_t) sizeof( ArmorConfig ), 4, fields, +[]( void * p ) { ArmorConfigReset( *(ArmorConfig *) p ); } };
    return &info;
}

inline const TableTypeInfo * FiringGroupTableType()
{
    static const TableFieldInfo fields[] = {
        { "barrel", "barrel", "uint32", 0x8ece059ad360b651ull, 8, false, false, false, 0, (uint32_t) offsetof( FiringGroup, barrel ), (uint32_t) sizeof( FiringGroup::barrel ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "cooldown", "cooldown", "float32", 0xdc2cbe6953343d48ull, 10, false, false, false, 0, (uint32_t) offsetof( FiringGroup, cooldown ), (uint32_t) sizeof( FiringGroup::cooldown ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
    };
    static const TableTypeInfo info = { "FiringGroup", (uint32_t) sizeof( FiringGroup ), 2, fields, +[]( void * p ) { FiringGroupReset( *(FiringGroup *) p ); } };
    return &info;
}

inline const TableTypeInfo * GunnerSettingsTableType()
{
    static const TableFieldInfo fields[] = {
        { "firing_groups", "firing_groups", "FiringGroup", 0x260b8ca6b0c3db7full, 13, true, true, false, 32, (uint32_t) offsetof( GunnerSettings, firing_groups ), (uint32_t) sizeof( GunnerSettings::firing_groups[0] ), (uint32_t) offsetof( GunnerSettings, firing_groups_count ), 0xffffffffu, FiringGroupTableType(), false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "missile_groups", "missile_groups", "FiringGroup", 0x3c99105aa087f6bcull, 13, true, true, false, 4, (uint32_t) offsetof( GunnerSettings, missile_groups ), (uint32_t) sizeof( GunnerSettings::missile_groups[0] ), (uint32_t) offsetof( GunnerSettings, missile_groups_count ), 0xffffffffu, FiringGroupTableType(), false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "reload_seconds", "reload_seconds", "float32", 0xad9b64728ea52486ull, 10, false, false, false, 0, (uint32_t) offsetof( GunnerSettings, reload_seconds ), (uint32_t) sizeof( GunnerSettings::reload_seconds ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "gunner_id", "gunner_id", "uint32", 0xbd9be53180256e02ull, 8, false, false, false, 0, (uint32_t) offsetof( GunnerSettings, gunner_id ), (uint32_t) sizeof( GunnerSettings::gunner_id ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, 0, NULL, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
    };
    static const TableTypeInfo info = { "GunnerSettings", (uint32_t) sizeof( GunnerSettings ), 4, fields, +[]( void * p ) { GunnerSettingsReset( *(GunnerSettings *) p ); } };
    return &info;
}

// ---- the text form (docs/SPEC-TABLES.md §16) ----

// ArmorPlate in and out of a JSON text — one instance, one text, the generic
// walk over this type's descriptors (docs/SPEC-TABLES.md §16). Defined in
// DataTable.cpp; link it to use them.
bool ArmorPlateFromJson( ArmorPlate & value, const char * text, int64_t bytes, TableReport * report );
int64_t ArmorPlateToJsonMeasure( const ArmorPlate & value );
int64_t ArmorPlateToJson( const ArmorPlate & value, char * buffer, int64_t capacity );

// ArmorConfig in and out of a JSON text — one instance, one text, the generic
// walk over this type's descriptors (docs/SPEC-TABLES.md §16). Defined in
// DataTable.cpp; link it to use them.
bool ArmorConfigFromJson( ArmorConfig & value, const char * text, int64_t bytes, TableReport * report );
int64_t ArmorConfigToJsonMeasure( const ArmorConfig & value );
int64_t ArmorConfigToJson( const ArmorConfig & value, char * buffer, int64_t capacity );

// FiringGroup in and out of a JSON text — one instance, one text, the generic
// walk over this type's descriptors (docs/SPEC-TABLES.md §16). Defined in
// DataTable.cpp; link it to use them.
bool FiringGroupFromJson( FiringGroup & value, const char * text, int64_t bytes, TableReport * report );
int64_t FiringGroupToJsonMeasure( const FiringGroup & value );
int64_t FiringGroupToJson( const FiringGroup & value, char * buffer, int64_t capacity );

// GunnerSettings in and out of a JSON text — one instance, one text, the generic
// walk over this type's descriptors (docs/SPEC-TABLES.md §16). Defined in
// DataTable.cpp; link it to use them.
bool GunnerSettingsFromJson( GunnerSettings & value, const char * text, int64_t bytes, TableReport * report );
int64_t GunnerSettingsToJsonMeasure( const GunnerSettings & value );
int64_t GunnerSettingsToJson( const GunnerSettings & value, char * buffer, int64_t capacity );

} // namespace blockhome
