// Code generated by the schema compiler from Data.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package blockhome — protocol id 0xb08615b7d62a9648 (packets only: tables version by field id, not by protocol id)
// The TABLE wire (evolution-tolerant, SPEC-TABLES.md): no serialize
// dependency — includable from any TU.

#pragma once

#include <cstdint>
#include <cstring>
#include <cstddef> // offsetof, for the reflection descriptors
#include <new> // in-place prefill (placement new): no giant stack temporaries
#include <type_traits> // the enforced relocatability asserts

#include "Data.h"

#ifndef BLOCKHOME_SCHEMA_TABLE_PRIMITIVES
#define BLOCKHOME_SCHEMA_TABLE_PRIMITIVES

namespace blockhome {

// The table-wire read report — the permissive contract's ledger. Silence
// (all zero) means the data matched this reader's schema exactly.
struct TableReport
{
    int32_t unknown = 0;       // unknown field ids skipped (newer data)
    int32_t kind_mismatch = 0; // known id, changed type — skipped, never misdecoded
    int32_t clamped = 0;       // out-of-range values clamped to declared bounds
    // a key the TEXT form saw twice: last wins, and the repeat is counted
    // (SPEC-TABLES.md §16.2). The wire never raises it — a body carrying an
    // id twice is legal input whose last occurrence wins, silently (§3).
    int32_t duplicate = 0;
    bool malformed = false;    // framing damage; decode stopped, partial result kept
};

// ---- reflection (tables only, SPEC-TABLES.md) ----
//
// Static field descriptors for every type in the table closure: name, wire
// id/kind, storage offset, bounds, ranges, enum names and branch guards —
// enough to walk, print, diff, edit or bind any table value at runtime with
// no RTTI and no schema files. TableType<X>() returns X's descriptor.

struct TableTypeInfo;

// One arm of a union field: where its payload sits inside the union's storage
// and what its payload looks like. The arm's NAME and its table-wire id come
// from the field's enum_name/variant_id functions at the same tag, so nothing
// is spelled twice (SPEC-TABLES.md §8).
struct TableUnionArmInfo
{
    uint32_t offset;             // offsetof the arm's payload within the union storage
    const TableTypeInfo * table; // the arm payload's descriptor
};

// A union field's shape: the tag, and the arms indexed by it. Arms run
// [0, enum_max]; index 0 is the EMPTY arm and carries no payload.
struct TableUnionInfo
{
    uint32_t tag_offset; // offsetof the tag within the union storage
    uint32_t tag_size;   // sizeof the tag
    const TableUnionArmInfo * arms;
};

struct TableFieldInfo
{
    const char * name;      // schema field name, e.g. "health"
    const char * json;      // the TEXT form's key: the json = "key" attribute, else name (§16.3)
    const char * type_name; // schema type name, e.g. "float32", "Grade"
    uint16_t id;            // table-wire field id (name hash; the was alias's hash after a rename)
    uint8_t kind;           // table-wire kind; for arrays/strings/bytes, the ELEMENT kind
    bool is_array;          // fixed or counted array (bytes included)
    bool counted;           // a _count/_length int32 companion exists (counted arrays, strings, bytes)
    bool optional;          // a ?T field: a _present bool companion decides whether it rides
    int32_t array_bound;    // array capacity / string max length; 0 for plain scalars
    uint32_t offset;        // offsetof the storage member
    uint32_t elem_size;     // sizeof the member (element size for arrays)
    uint32_t count_offset;  // offsetof the _count/_length companion, or 0xffffffff
    uint32_t present_offset; // offsetof the _present companion, or 0xffffffff
    const TableTypeInfo * table; // nested table's descriptor, or NULL
    bool has_range;         // a declared [min, max] (int or float)
    double range_min;       // NOTE: int64 ranges beyond 2^53 lose precision here
    double range_max;
    int64_t enum_max;       // enums: highest valid value (None = 0 always valid);
                            // unions: the arm count (tag range [0, enum_max]);
                            // flags: the highest declared BIT INDEX; else -1
    // the vocabulary's names, indexed the same way enum_max bounds: an enum's
    // value -> name, a union's tag -> arm name, a FLAGS field's bit index ->
    // variant name. NULL for every other kind.
    const char * (*enum_name)( uint64_t value );
    // the TABLE-WIRE id of one variant (SPEC-TABLES.md §5): for an enum, the
    // hash of the variant's name; for a union, the hash of the arm's name.
    // 0 is the reserved id — an enum's None, a union's empty. NULL for every
    // other kind — a FLAGS field's variants have no per-variant wire id (§4),
    // so a NULL here beside a non-NULL enum_name is what says "flags".
    // Walk [0, enum_max] to enumerate a vocabulary and its ids.
    uint16_t (*variant_id)( uint64_t value );
    // an ENUM-KEYED array (SPEC-TABLES.md §2.4): the array has one slot per
    // variant of key_type_name, indexed by the variant's value, and its slots
    // ride under variant ids rather than positions. key_name and key_id are
    // the key's vocabulary — walk [0, array_bound) to print slots by name.
    // NULL on every other field.
    const char * key_type_name;
    const char * (*key_name)( uint64_t value );
    uint16_t (*key_id)( uint64_t value );
    // union fields: the tag and its arms, behind a function so the whole
    // descriptor stays CONSTANT-INITIALISED (a captureless lambda converts to
    // a function pointer at compile time; the arms themselves are a static
    // inside it). NULL for every other kind.
    const TableUnionInfo * (*arms)();
    const char * guard;     // branch guard, e.g. "at_rest" or "!at_rest"; "" if unguarded
};

struct TableTypeInfo
{
    const char * name;   // schema type name
    uint32_t size;       // sizeof the storage struct
    int32_t num_fields;
    const TableFieldInfo * fields;
    // put one instance back at its declared defaults, in place. A generic
    // walker that fills a value has to be able to establish the defaults an
    // absent field takes, and it holds no type to spell — this is the one
    // thing the descriptors could not express without it. Placement-new
    // value-init, exactly what the wire's read path does, and no temporary.
    void (*reset)( void * storage );
};

struct TableWriter
{
    uint8_t * buffer;
    int64_t capacity;
    int64_t offset = 0;
    bool overflow = false;

    TableWriter( uint8_t * buffer, int64_t capacity ) : buffer( buffer ), capacity( capacity ) {}

    void raw( const void * data, int64_t bytes )
    {
        if ( offset + bytes > capacity ) { overflow = true; return; }
        memcpy( buffer + offset, data, (size_t) bytes );
        offset += bytes;
    }
    void put8( uint8_t v )   { raw( &v, 1 ); }
    void put16( uint16_t v ) { uint8_t b[2] = { uint8_t( v ), uint8_t( v >> 8 ) }; raw( b, 2 ); }
    void put32( uint32_t v ) { uint8_t b[4] = { uint8_t( v ), uint8_t( v >> 8 ), uint8_t( v >> 16 ), uint8_t( v >> 24 ) }; raw( b, 4 ); }
    void put64( uint64_t v ) { put32( uint32_t( v ) ); put32( uint32_t( v >> 32 ) ); }
    void patch32( int64_t at, uint32_t v )
    {
        if ( at + 4 > capacity ) { overflow = true; return; }
        buffer[at] = uint8_t( v ); buffer[at+1] = uint8_t( v >> 8 );
        buffer[at+2] = uint8_t( v >> 16 ); buffer[at+3] = uint8_t( v >> 24 );
    }
};

struct TableReader
{
    const uint8_t * buffer;
    int64_t size;
    int64_t offset = 0;
    TableReport * report;

    TableReader( const uint8_t * buffer, int64_t size, TableReport * report )
        : buffer( buffer ), size( size ), report( report ) {}

    bool has( int64_t bytes ) const { return offset + bytes <= size; }
    uint8_t get8()   { return buffer[offset++]; }
    uint16_t get16() { uint16_t v = uint16_t( buffer[offset] ) | uint16_t( buffer[offset+1] ) << 8; offset += 2; return v; }
    uint32_t get32() { uint32_t v = uint32_t( buffer[offset] ) | uint32_t( buffer[offset+1] ) << 8 | uint32_t( buffer[offset+2] ) << 16 | uint32_t( buffer[offset+3] ) << 24; offset += 4; return v; }
    uint64_t get64() { uint64_t lo = get32(); uint64_t hi = get32(); return lo | ( hi << 32 ); }

    // skip one payload by kind; false = framing damage
    bool skip( uint8_t kind )
    {
        switch ( kind )
        {
            case 1: case 2: case 6: return has( 1 ) ? ( offset += 1, true ) : false;
            case 3: case 7:         return has( 2 ) ? ( offset += 2, true ) : false;
            case 4: case 8: case 10: return has( 4 ) ? ( offset += 4, true ) : false;
            case 5: case 9: case 11: return has( 8 ) ? ( offset += 8, true ) : false;
            case 12: case 13: case 14: case 16:
            {
                if ( !has( 4 ) ) return false;
                uint32_t n = get32();
                return has( n ) ? ( offset += n, true ) : false;
            }
            case 15: // union: u16 arm id, then the arm length-prefixed (id 0 = empty, no body)
            {
                if ( !has( 2 ) ) return false;
                if ( get16() == 0 ) return true;
                if ( !has( 4 ) ) return false;
                uint32_t n = get32();
                return has( n ) ? ( offset += n, true ) : false;
            }
        }
        return false;
    }
};

inline float table_bits_to_float( uint32_t bits ) { float f; memcpy( &f, &bits, 4 ); return f; }
inline uint32_t table_float_to_bits( float f ) { uint32_t b; memcpy( &b, &f, 4 ); return b; }
inline double table_bits_to_double( uint64_t bits ) { double d; memcpy( &d, &bits, 8 ); return d; }
inline uint64_t table_double_to_bits( double d ) { uint64_t b; memcpy( &b, &d, 8 ); return b; }

} // namespace blockhome

#endif // BLOCKHOME_SCHEMA_TABLE_PRIMITIVES

namespace blockhome {

// ---- codecs: measure/save/load per closure member ----

inline int64_t ArmorPlateMeasure( const ArmorPlate & value );
inline bool ArmorPlateSaveBody( TableWriter & w, const ArmorPlate & value );
inline bool ArmorPlateLoadBody( TableReader & r, ArmorPlate & value );
inline int64_t ArmorConfigMeasure( const ArmorConfig & value );
inline bool ArmorConfigSaveBody( TableWriter & w, const ArmorConfig & value );
inline bool ArmorConfigLoadBody( TableReader & r, ArmorConfig & value );

inline int64_t ArmorPlateMeasure( const ArmorPlate & value )
{
    int64_t bytes = 2; // terminator
    if ( value.thickness != 0.0 ) { bytes += 3 + 8; } // thickness
    if ( value.material != 0 ) { bytes += 3 + 4; } // material
    if ( value.layer != 0 ) { bytes += 3 + 1; } // layer
    return bytes;
}

inline bool ArmorPlateSaveBody( TableWriter & w, const ArmorPlate & value )
{
    if ( value.thickness != 0.0 )
    {
        w.put16( 0xc81a ); w.put8( 11 ); // thickness
        w.put64( table_double_to_bits( value.thickness ) );
    }
    if ( value.material != 0 )
    {
        w.put16( 0x0284 ); w.put8( 8 ); // material
        w.put32( uint32_t( value.material ) );
    }
    if ( value.layer != 0 )
    {
        w.put16( 0x4750 ); w.put8( 6 ); // layer
        w.put8( uint8_t( value.layer ) );
    }
    w.put16( 0 ); // terminator
    return !w.overflow;
}

inline int64_t ArmorPlateSave( const ArmorPlate & value, uint8_t * buffer, int64_t capacity )
{
    TableWriter w( buffer, capacity );
    if ( !ArmorPlateSaveBody( w, value ) ) { return -1; }
    return w.offset; // == ArmorPlateMeasure( value )
}

inline bool ArmorPlateLoadBody( TableReader & r, ArmorPlate & value )
{
    new ( &value ) ArmorPlate{}; // prefill declared defaults in place, then overlay
    for ( ;; )
    {
        if ( !r.has( 2 ) ) { r.report->malformed = true; return false; }
        uint16_t field_id = r.get16();
        if ( field_id == 0 ) return true;
        if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
        uint8_t kind = r.get8();
        switch ( field_id )
        {
            case 0xc81a: // thickness
            {
                if ( kind != 11 )
                {
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 8 ) ) { r.report->malformed = true; return false; }
                value.thickness = table_bits_to_double( r.get64() );
                break;
            }
            case 0x0284: // material
            {
                if ( kind != 8 )
                {
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                uint32_t decoded_v = uint32_t( r.get32( ) );
                value.material = decoded_v;
                break;
            }
            case 0x4750: // layer
            {
                if ( kind != 6 )
                {
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
                uint8_t decoded_v = uint8_t( r.get8( ) );
                value.layer = decoded_v;
                break;
            }
            default:
            {
                r.report->unknown++;
                if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                break;
            }
        }
    }
}

inline bool ArmorPlateLoad( ArmorPlate & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    TableReport ignored;
    TableReader r( buffer, bytes, report != NULL ? report : &ignored );
    return ArmorPlateLoadBody( r, value );
}

inline int64_t ArmorConfigMeasure( const ArmorConfig & value )
{
    int64_t bytes = 2; // terminator
    {
        int64_t body_front = ArmorPlateMeasure( value.front );
        if ( body_front < 0 ) { return -1; }
        if ( body_front > 2 ) { bytes += 3 + 4 + body_front; } // front: all-default nested elides
    }
    {
        int64_t body_rear = ArmorPlateMeasure( value.rear );
        if ( body_rear < 0 ) { return -1; }
        if ( body_rear > 2 ) { bytes += 3 + 4 + body_rear; } // rear: all-default nested elides
    }
    if ( value.rating != 0.0f ) { bytes += 3 + 4; } // rating
    if ( value.tier != 0 ) { bytes += 3 + 1; } // tier
    return bytes;
}

inline bool ArmorConfigSaveBody( TableWriter & w, const ArmorConfig & value )
{
    {
        int64_t body_front = ArmorPlateMeasure( value.front );
        if ( body_front < 0 ) return false; // storage invariant, refused as measure refuses it
        if ( body_front > 2 ) // all-default nested elides
        {
            w.put16( 0x3aa1 ); w.put8( 13 ); // front
            w.put32( uint32_t( body_front ) );
            if ( !ArmorPlateSaveBody( w, value.front ) ) return false;
        }
    }
    {
        int64_t body_rear = ArmorPlateMeasure( value.rear );
        if ( body_rear < 0 ) return false; // storage invariant, refused as measure refuses it
        if ( body_rear > 2 ) // all-default nested elides
        {
            w.put16( 0x6b5c ); w.put8( 13 ); // rear
            w.put32( uint32_t( body_rear ) );
            if ( !ArmorPlateSaveBody( w, value.rear ) ) return false;
        }
    }
    if ( value.rating != 0.0f )
    {
        w.put16( 0xe2d9 ); w.put8( 10 ); // rating
        w.put32( table_float_to_bits( value.rating ) );
    }
    if ( value.tier != 0 )
    {
        w.put16( 0xe958 ); w.put8( 6 ); // tier
        w.put8( uint8_t( value.tier ) );
    }
    w.put16( 0 ); // terminator
    return !w.overflow;
}

inline int64_t ArmorConfigSave( const ArmorConfig & value, uint8_t * buffer, int64_t capacity )
{
    TableWriter w( buffer, capacity );
    if ( !ArmorConfigSaveBody( w, value ) ) { return -1; }
    return w.offset; // == ArmorConfigMeasure( value )
}

inline bool ArmorConfigLoadBody( TableReader & r, ArmorConfig & value )
{
    new ( &value ) ArmorConfig{}; // prefill declared defaults in place, then overlay
    for ( ;; )
    {
        if ( !r.has( 2 ) ) { r.report->malformed = true; return false; }
        uint16_t field_id = r.get16();
        if ( field_id == 0 ) return true;
        if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
        uint8_t kind = r.get8();
        switch ( field_id )
        {
            case 0x3aa1: // front
            {
                if ( kind != 13 )
                {
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                uint32_t body_len = r.get32();
                if ( !r.has( body_len ) ) { r.report->malformed = true; return false; }
                {
                    TableReader sub( r.buffer + r.offset, body_len, r.report );
                    ArmorPlateLoadBody( sub, value.front );
                }
                r.offset += body_len;
                break;
            }
            case 0x6b5c: // rear
            {
                if ( kind != 13 )
                {
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                uint32_t body_len = r.get32();
                if ( !r.has( body_len ) ) { r.report->malformed = true; return false; }
                {
                    TableReader sub( r.buffer + r.offset, body_len, r.report );
                    ArmorPlateLoadBody( sub, value.rear );
                }
                r.offset += body_len;
                break;
            }
            case 0xe2d9: // rating
            {
                if ( kind != 10 )
                {
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 4 ) ) { r.report->malformed = true; return false; }
                value.rating = table_bits_to_float( r.get32() );
                break;
            }
            case 0xe958: // tier
            {
                if ( kind != 6 )
                {
                    r.report->kind_mismatch++;
                    if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                    break;
                }
                if ( !r.has( 1 ) ) { r.report->malformed = true; return false; }
                uint8_t decoded_v = uint8_t( r.get8( ) );
                value.tier = decoded_v;
                break;
            }
            default:
            {
                r.report->unknown++;
                if ( !r.skip( kind ) ) { r.report->malformed = true; return false; }
                break;
            }
        }
    }
}

inline bool ArmorConfigLoad( ArmorConfig & value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    TableReport ignored;
    TableReader r( buffer, bytes, report != NULL ? report : &ignored );
    return ArmorConfigLoadBody( r, value );
}

// ---- relocatability, enforced: the wire is a pure length-prefixed
// stream AND the decoded storage is pointer-free — every closure type
// must stay trivially copyable and standard-layout, so instances can be
// memcpy'd, mmap'd, shared across processes, and walked through
// descriptor offsets. A failure here means a pointer, virtual or
// non-trivial member crept into generated storage.
static_assert( std::is_trivially_copyable<ArmorPlate>::value, "ArmorPlate must stay relocatable" );
static_assert( std::is_standard_layout<ArmorPlate>::value, "ArmorPlate must stay standard-layout for offsetof" );
static_assert( std::is_trivially_copyable<ArmorConfig>::value, "ArmorConfig must stay relocatable" );
static_assert( std::is_standard_layout<ArmorConfig>::value, "ArmorConfig must stay standard-layout for offsetof" );

// ---- reflection descriptors (tables only, SPEC-TABLES.md) ----

inline const TableTypeInfo * ArmorPlateTableType();
inline const TableTypeInfo * ArmorConfigTableType();

inline const TableTypeInfo * ArmorPlateTableType()
{
    static const TableFieldInfo fields[] = {
        { "thickness", "thickness", "float64", 0xc81a, 11, false, false, false, 0, (uint32_t) offsetof( ArmorPlate, thickness ), (uint32_t) sizeof( ArmorPlate{}.thickness ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "material", "material", "uint32", 0x0284, 8, false, false, false, 0, (uint32_t) offsetof( ArmorPlate, material ), (uint32_t) sizeof( ArmorPlate{}.material ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "layer", "layer", "uint8", 0x4750, 6, false, false, false, 0, (uint32_t) offsetof( ArmorPlate, layer ), (uint32_t) sizeof( ArmorPlate{}.layer ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
    };
    static const TableTypeInfo info = { "ArmorPlate", (uint32_t) sizeof( ArmorPlate ), 3, fields, +[]( void * p ) { new ( p ) ArmorPlate{}; } };
    return &info;
}

inline const TableTypeInfo * ArmorConfigTableType()
{
    static const TableFieldInfo fields[] = {
        { "front", "front", "ArmorPlate", 0x3aa1, 13, false, false, false, 0, (uint32_t) offsetof( ArmorConfig, front ), (uint32_t) sizeof( ArmorConfig{}.front ), 0xffffffffu, 0xffffffffu, ArmorPlateTableType(), false, 0.0, 0.0, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "rear", "rear", "ArmorPlate", 0x6b5c, 13, false, false, false, 0, (uint32_t) offsetof( ArmorConfig, rear ), (uint32_t) sizeof( ArmorConfig{}.rear ), 0xffffffffu, 0xffffffffu, ArmorPlateTableType(), false, 0.0, 0.0, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "rating", "rating", "float32", 0xe2d9, 10, false, false, false, 0, (uint32_t) offsetof( ArmorConfig, rating ), (uint32_t) sizeof( ArmorConfig{}.rating ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
        { "tier", "tier", "uint8", 0xe958, 6, false, false, false, 0, (uint32_t) offsetof( ArmorConfig, tier ), (uint32_t) sizeof( ArmorConfig{}.tier ), 0xffffffffu, 0xffffffffu, NULL, false, 0.0, 0.0, -1, NULL, NULL, NULL, NULL, NULL, NULL, "" },
    };
    static const TableTypeInfo info = { "ArmorConfig", (uint32_t) sizeof( ArmorConfig ), 4, fields, +[]( void * p ) { new ( p ) ArmorConfig{}; } };
    return &info;
}

// ---- the text form (SPEC-TABLES.md §16) ----

// ArmorPlate in and out of a JSON text — one instance, one text, the generic
// walk over this type's descriptors (SPEC-TABLES.md §16). Defined in
// DataTable.cpp; link it to use them.
bool ArmorPlateFromJson( ArmorPlate & value, const char * text, int64_t bytes, TableReport * report );
int64_t ArmorPlateToJsonMeasure( const ArmorPlate & value );
int64_t ArmorPlateToJson( const ArmorPlate & value, char * buffer, int64_t capacity );

// ArmorConfig in and out of a JSON text — one instance, one text, the generic
// walk over this type's descriptors (SPEC-TABLES.md §16). Defined in
// DataTable.cpp; link it to use them.
bool ArmorConfigFromJson( ArmorConfig & value, const char * text, int64_t bytes, TableReport * report );
int64_t ArmorConfigToJsonMeasure( const ArmorConfig & value );
int64_t ArmorConfigToJson( const ArmorConfig & value, char * buffer, int64_t capacity );

} // namespace blockhome
