// Generated by the schema compiler from Contexts.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package example — protocol id 0x39e4aa9c08faf8f8

#pragma once

#include <cstdint>

namespace example {

// contexts declared for this unit: client, server (SPEC §4.2).
// Contexts generate no standalone artifacts — where an object carries
// context-scoped [local] fields, its State struct is generated once per
// context (ClientShipState, ServerShipState, ...), each holding the `all`
// fields plus its own context's. No preprocessor in any target.

} // namespace example
