// Code generated by the schema compiler from Guarded.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package tabledemo — the TABLE wire (docs/SPEC-TABLES.md): evolution-tolerant, neutral
// bytes, no serialize dependency. Tables version by field id, never by the
// unit's protocol id.

using System;

namespace Tabledemo
{

    // table Patrol — TABLE-wire storage: public fields, every buffer allocated at
    // construction, declared defaults in the field initializers (docs/SPEC-TABLES.md)
    public sealed class Patrol
    {
        public bool Active;

        // active — guarded fields stay off the wire when the guard says so;
        // a read's restored defaults stand in for the untaken side
        public float Speed = 1.0f;
        public bool HasTarget;

        // active && has_target — guarded fields stay off the wire when the guard says so;
        // a read's restored defaults stand in for the untaken side
        public int TargetId = 0;

        // active && !has_target — guarded fields stay off the wire when the guard says so;
        // a read's restored defaults stand in for the untaken side
        public float Wander = 0.5f;

        // !active — guarded fields stay off the wire when the guard says so;
        // a read's restored defaults stand in for the untaken side
        public byte[] Note = new byte[8]; // string(8): max length, used length beside it
        public int NoteLength;
    }

    // Schema carries every generated function of the unit — C# has no
    // namespace-level functions, so the static class is their home; partial,
    // one slice per generated file.
    public static partial class Schema
    {
        // TableReset(Patrol) restores Patrol's declared defaults in place, reusing every
        // buffer the value already owns. The reader calls it before overlaying.
        public static void TableReset(Patrol value)
        {
            value.Active = false;
            value.Speed = 1.0f;
            value.HasTarget = false;
            value.TargetId = 0;
            value.Wander = 0.5f;
            Array.Clear(value.Note, 0, value.Note.Length);
            value.NoteLength = 0;
        }

        public static long PatrolMeasure(Patrol value)
        {
            Span<ulong> ids = stackalloc ulong[155];
            return TableWire.Save(value, PatrolTableType(), Span<byte>.Empty, ids, true);
        }

        public static long PatrolSave(Patrol value, Span<byte> buffer)
        {
            Span<ulong> ids = stackalloc ulong[155];
            return TableWire.Save(value, PatrolTableType(), buffer, ids, false);
        }

        public static TableWire.Verdict PatrolLoadVerdict(Patrol value, ReadOnlySpan<byte> bytes, TableReport report)
        {
            return TableWire.Load(value, PatrolTableType(), bytes, report);
        }

        public static bool PatrolLoad(Patrol value, ReadOnlySpan<byte> bytes, TableReport report)
        {
            return PatrolLoadVerdict(value, bytes, report) == TableWire.Verdict.Ok;
        }

        public static long PatrolMeasureMessages(Patrol[] values) { return TableWire.MessageSave(values, PatrolTableType(), Span<byte>.Empty, true); }
        public static long PatrolSaveMessages(Patrol[] values, Span<byte> bytes, TableReport report = null) { if (values.Length > 256 && report != null) { report.Refused = true; report.Reason = "batch_too_large"; report.Verdict = TableWire.Verdict.Refused; } return TableWire.MessageSave(values, PatrolTableType(), bytes, false); }
        public static TableWire.Verdict PatrolLoadMessages(Patrol[] values, ReadOnlySpan<byte> bytes, TableVocabulary vocabulary, TableReport report, out int count) { return TableWire.MessageLoad(values, PatrolTableType(), bytes, vocabulary, report, out count); }

        public static long PatrolCookMeasure(Patrol value) { return TableWire.Cook(value, PatrolTableType(), Span<byte>.Empty, TableByteOrder.Little, true); }
        public static bool PatrolCook(Patrol value, Span<byte> bytes, TableByteOrder order = TableByteOrder.Little) { return TableWire.Cook(value, PatrolTableType(), bytes, order, false) >= 0; }

        // ---- reflection descriptors (tables only, docs/SPEC-TABLES.md §8) ----

        private static TableTypeInfo PatrolTableInfo;
        public static TableTypeInfo PatrolTableType()
        {
            TableTypeInfo info = PatrolTableInfo;
            if (info != null) { return info; }
            info = new TableTypeInfo();
            info.Name = "Patrol";
            info.Id = 0x1c182e1c2529027bul;
            info.NumFields = 6;
            info.Create = delegate { return new Patrol(); };
            info.StorageSize = 36; info.StorageAlign = 4; info.RegionAlign = 8;
            info.Variable = false;
            info.PointerType = delegate(ulong id) { switch(id) { default: return null; } };
            info.PointerTypes = delegate { return new TableTypeInfo[] { }; };
            info.BytesEdge = false; info.StringEdge = false;
            info.Fields = new TableFieldInfo[]
            {
                new TableFieldInfo { Name = "active", Json = "active", TypeName = "bool", Id = 0x6580790b036f0c6f, Kind = 1, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, ElemWidth = 1, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "", TableRef = null, Arms = null, Doc = TableDocNone, NumTags = 0, Tags = null, GetRaw = delegate(object o, int i) { return ((Patrol)o).Active ? 1ul : 0ul; }, SetRaw = delegate(object o, int i, ulong r) { ((Patrol)o).Active = r != 0; }, MessageSlot = 32, Ordinal = 0, NativeOffset = 0, NativeElementSize = 1, NativeCountOffset = -1, NativePresentOffset = -1, ResetField = delegate(object o) { var value = (Patrol)o; value.Active = false; }, DefaultRaw = false ? 1ul : 0ul },
                new TableFieldInfo { Name = "speed", Json = "speed", TypeName = "float32", Id = 0x2281498aa0200e40, Kind = 10, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, ElemWidth = 4, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "active", TableRef = null, Arms = null, Doc = TableDocNone, NumTags = 0, Tags = null, GetRaw = delegate(object o, int i) { return (ulong)TableFloatToBits(((Patrol)o).Speed); }, SetRaw = delegate(object o, int i, ulong r) { ((Patrol)o).Speed = TableBitsToFloat(unchecked((uint)r)); }, MessageSlot = 33, Ordinal = 1, NativeOffset = 4, NativeElementSize = 4, NativeCountOffset = -1, NativePresentOffset = -1, NativeGuardOffsets = new int[] {0}, NativeGuardValues = new bool[] {true}, WireGuard = delegate(object o) { var value = (Patrol)o; return value.Active; }, ResetField = delegate(object o) { var value = (Patrol)o; value.Speed = 1.0f; }, DefaultRaw = (ulong)TableFloatToBits(1.0f), ClampRaw = delegate(ulong raw, TableReport r) { float v = TableBitsToFloat(unchecked((uint)raw)); return (ulong)TableFloatToBits(v); } },
                new TableFieldInfo { Name = "has_target", Json = "has_target", TypeName = "bool", Id = 0x247f0e7f55aacfbd, Kind = 1, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, ElemWidth = 1, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "active", TableRef = null, Arms = null, Doc = TableDocNone, NumTags = 0, Tags = null, GetRaw = delegate(object o, int i) { return ((Patrol)o).HasTarget ? 1ul : 0ul; }, SetRaw = delegate(object o, int i, ulong r) { ((Patrol)o).HasTarget = r != 0; }, MessageSlot = 34, Ordinal = 2, NativeOffset = 8, NativeElementSize = 1, NativeCountOffset = -1, NativePresentOffset = -1, NativeGuardOffsets = new int[] {0}, NativeGuardValues = new bool[] {true}, WireGuard = delegate(object o) { var value = (Patrol)o; return value.Active; }, ResetField = delegate(object o) { var value = (Patrol)o; value.HasTarget = false; }, DefaultRaw = false ? 1ul : 0ul },
                new TableFieldInfo { Name = "target_id", Json = "target_id", TypeName = "int32", Id = 0xb7bc9ac015a25050, Kind = 4, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, ElemWidth = 4, HasRange = true, RangeMin = 0.0, RangeMax = 1000.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "active && has_target", TableRef = null, Arms = null, Doc = TableDocNone, NumTags = 0, Tags = null, GetRaw = delegate(object o, int i) { return (ulong)(long)((Patrol)o).TargetId; }, SetRaw = delegate(object o, int i, ulong r) { ((Patrol)o).TargetId = unchecked((int)(long)r); }, MessageSlot = 35, MessageBounded = true, MessageSigned = true, MessageMin = unchecked((UInt128)(((UInt128)0x0ul << 64) | 0x0ul)), MessageMax = unchecked((UInt128)(((UInt128)0x0ul << 64) | 0x3e8ul)), Ordinal = 3, NativeOffset = 12, NativeElementSize = 4, NativeCountOffset = -1, NativePresentOffset = -1, NativeGuardOffsets = new int[] {0,8}, NativeGuardValues = new bool[] {true,true}, WireGuard = delegate(object o) { var value = (Patrol)o; return value.Active && value.HasTarget; }, ResetField = delegate(object o) { var value = (Patrol)o; value.TargetId = 0; }, DefaultRaw = (ulong)(long)0, ClampRaw = delegate(ulong raw, TableReport r) { int v = unchecked((int)(long)raw); if (v < 0) { r.Clamped++; v = 0; } if (v > 1000) { r.Clamped++; v = 1000; } return (ulong)(long)v; } },
                new TableFieldInfo { Name = "wander", Json = "wander", TypeName = "float32", Id = 0xb8c758d8bd1845d4, Kind = 10, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, ElemWidth = 4, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "active && !has_target", TableRef = null, Arms = null, Doc = TableDocNone, NumTags = 0, Tags = null, GetRaw = delegate(object o, int i) { return (ulong)TableFloatToBits(((Patrol)o).Wander); }, SetRaw = delegate(object o, int i, ulong r) { ((Patrol)o).Wander = TableBitsToFloat(unchecked((uint)r)); }, MessageSlot = 36, Ordinal = 4, NativeOffset = 16, NativeElementSize = 4, NativeCountOffset = -1, NativePresentOffset = -1, NativeGuardOffsets = new int[] {0,8}, NativeGuardValues = new bool[] {true,false}, WireGuard = delegate(object o) { var value = (Patrol)o; return value.Active && !value.HasTarget; }, ResetField = delegate(object o) { var value = (Patrol)o; value.Wander = 0.5f; }, DefaultRaw = (ulong)TableFloatToBits(0.5f), ClampRaw = delegate(ulong raw, TableReport r) { float v = TableBitsToFloat(unchecked((uint)raw)); return (ulong)TableFloatToBits(v); } },
                new TableFieldInfo { Name = "note", Json = "note", TypeName = "string", Id = 0x3bf8fbbad1587cdd, Kind = 12, IsArray = false, Counted = true, Optional = false, ArrayBound = 8, ElemWidth = 0, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "!active", TableRef = null, Arms = null, Doc = TableDocNone, NumTags = 0, Tags = null, GetBuffer = delegate(object o) { return ((Patrol)o).Note; }, GetCount = delegate(object o) { return ((Patrol)o).NoteLength; }, SetCount = delegate(object o, int n) { ((Patrol)o).NoteLength = n; }, MessageSlot = 37, Ordinal = 5, NativeOffset = 20, NativeElementSize = 9, NativeCountOffset = 32, NativePresentOffset = -1, NativeGuardOffsets = new int[] {0}, NativeGuardValues = new bool[] {false}, WireGuard = delegate(object o) { var value = (Patrol)o; return !value.Active; }, ResetField = delegate(object o) { var value = (Patrol)o; Array.Clear(value.Note, 0, value.Note.Length); value.NoteLength = 0; } },
            };
            info.Reset = delegate(object o) { TableReset((Patrol)o); };
            info.Doc = TableDocNone;
            info.NumTags = 0;
            info.Tags = null;
            PatrolTableInfo = info;
            return info;
        }

        // ---- the text form: JSON in and out of one table (docs/SPEC-TABLES.md §16) ----

        // Patrol in and out of a JSON text — one instance, one text, the generic
        // walk over this type's descriptors (docs/SPEC-TABLES.md §16).
        public static bool PatrolFromJson(Patrol value, ReadOnlySpan<byte> text, TableReport report)
        {
            return TableJson.Read(value, PatrolTableType(), text, report);
        }

        public static long PatrolToJsonMeasure(Patrol value)
        {
            return TableJson.Write(value, PatrolTableType(), Span<byte>.Empty, true);
        }

        public static long PatrolToJson(Patrol value, Span<byte> buffer)
        {
            return TableJson.Write(value, PatrolTableType(), buffer, false);
        }
    }

}
