// Code generated by the schema compiler from Enums.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package example — protocol id 0xcaa884d7062cccc8

#pragma once

#include <cstdint>

#include "Enums.h"

namespace example {


} // namespace example
