package cstable

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// §5.8 row 11 `unknown_census`, the ordinary ONE-record row every leg but cs
// already had: the NEW build reads `old_unknown_census.bin` through a
// HANDED-IN lineage entry (§5.1 refuses the removal, so no lock). One record,
// four `items` carrying `a` = 10..13 and the removed `drop`. `r.Unknown` is
// asserted EXACTLY `== 1` because `Item.drop` is one field of one peer, so the
// census is 1 however many elements carry it — `4` is the divergence this row
// exists to catch, and the exact defect rust, cpp and cs itself once carried.
func TestFixedVersioningUnknownCensus(t *testing.T) {
	corpus := csFixedCorpus(t)
	dir := t.TempDir()

	probe := csVersionProbe{
		name:   "unknown_census/new_reads_old",
		reader: "VNEW_unknown_census",
		older:  []string{"VOLD_unknown_census"},
		file:   "old_unknown_census.bin",
		body: `            byte[] data = System.IO.File.ReadAllBytes(System.IO.Path.Combine(corpus, @FILE@));
            @TABLE@[] back = new @TABLE@[8];
            for (int i = 0; i < back.Length; ++i) { back[i] = new @TABLE@(); }
            TableReport r = new TableReport();
            TableFixedEntry[] plan = new TableFixedEntry[8192];
            long n = Schema.@TABLE@FixedLoad(back, data, plan, r);
            if (n != 1)
            {
                bad += ProbeLog.Fail(@NAME@, "expected one record, not " + n);
            }
            if (r.Refused || r.Malformed || r.Reason != null)
            {
                bad += ProbeLog.Fail(@NAME@, "a clean read is not a refusal: reason=" + r.Reason + " malformed=" + r.Malformed);
            }
            if (r.Unknown != 1)
            {
                bad += ProbeLog.Fail(@NAME@, "the census is once per field per peer, not once per element: unknown=" + r.Unknown);
            }
            if (r.KindMismatch != 0 || r.Clamped != 0 || r.Duplicate != 0 || r.Widened != 0 || r.Retained != 0 || r.RetainLost != 0)
            {
                bad += ProbeLog.Fail(@NAME@, "only the unknown counter may move: kind=" + r.KindMismatch + " clamped=" + r.Clamped + " duplicate=" + r.Duplicate + " widened=" + r.Widened + " retained=" + r.Retained + " lost=" + r.RetainLost);
            }
            if (back[0].Lead != 1u || back[0].Trail != 2u)
            {
                bad += ProbeLog.Fail(@NAME@, "a neighbour moved: lead=" + back[0].Lead + " trail=" + back[0].Trail);
            }
            int[] wantA = { 10, 11, 12, 13 };
            for (int k = 0; k < 4; ++k)
            {
                if (back[0].Items[k].A != wantA[k])
                {
                    bad += ProbeLog.Fail(@NAME@, "item " + k + " did not land its own a: " + back[0].Items[k].A + " != " + wantA[k]);
                }
            }`,
	}

	ns, table, files := csVersionGenerate(t, probe)
	gen := filepath.Join(dir, "gen", "u000")
	csVersionWrite(t, gen, files)
	joined := ""
	for _, data := range files {
		joined += string(data)
	}
	body := strings.ReplaceAll(probe.body, "@JSON@", csVersionJSON(joined, table))
	body = strings.NewReplacer(
		"@NAME@", fmt.Sprintf("%q", probe.name),
		"@TABLE@", table,
		"@FILE@", fmt.Sprintf("%q", probe.file),
	).Replace(body)
	src := fmt.Sprintf(`// generated by internal/codegen/cstable's versioning harness: one probe per row per COLUMN
using System;

namespace %s
{
    static class Probe000
    {
        public static int Run(string corpus)
        {
            int bad = 0;
%s
            if (bad == 0) { Console.WriteLine("ROW " + %s + ": ok"); }
            return bad;
        }
    }
}
`, ns, body, fmt.Sprintf("%q", probe.name))
	if err := os.WriteFile(filepath.Join(dir, "Probe000.cs"), []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	main := fmt.Sprintf(`using System;

static class ProbeLog
{
    public static int Fail(string row, string what)
    {
        Console.WriteLine("ROW " + row + ": FAILED " + what);
        return 1;
    }
}

static class ProbeMain
{
    static int Main()
    {
        string corpus = Environment.GetEnvironmentVariable("SCHEMA_FIXEDFORM_CORPUS");
        int bad = 0;
        try
        {
            bad += %s.Probe000.Run(corpus);
        }
        catch (Exception e)
        {
            Console.WriteLine("ROW harness: FAILED " + e.ToString());
            return 1;
        }
        Console.WriteLine(bad == 0 ? "cs versioning: every row green" : "cs versioning: " + bad + " FAILED");
        return bad == 0 ? 0 : 1;
    }
}
`, ns)
	if err := os.WriteFile(filepath.Join(dir, "ProbeMain.cs"), []byte(main), 0o600); err != nil {
		t.Fatal(err)
	}

	runtime, err := filepath.Abs("../../../../serialize.cs")
	if err != nil {
		t.Fatal(err)
	}
	proj := fmt.Sprintf(`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>csversioning</AssemblyName>
    <NoWarn>CS0162;CS0168;CS0219;CS8600;CS8602;CS8604;CS8625</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="*.cs" />
    <Compile Include="gen/**/*.cs" />
    <Compile Include="%s/src/Serialize.cs" />
    <Compile Include="%s/src/Int128Pair.cs" />
  </ItemGroup>
</Project>
`, runtime, runtime)
	if err := os.WriteFile(filepath.Join(dir, "csversioning.csproj"), []byte(proj), 0o600); err != nil {
		t.Fatal(err)
	}

	dotnet := os.Getenv("DOTNET")
	if dotnet == "" {
		dotnet = "dotnet"
	}
	cmd := exec.Command(dotnet, "run", "--project", dir, "-v", "q", "--nologo")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "SCHEMA_FIXEDFORM_CORPUS="+corpus, "DOTNET_NOLOGO=1")
	out, runErr := cmd.CombinedOutput()

	csVersionAssert(t, out, runErr, "unknown_census/new_reads_old")
}
