// The Dart cross-language wire test for the fixed-point + 128-bit unit
// (examples128/): the generated Dart library writes the SAME pinned instance
// test/ludicrous_main.cpp pins in testdata/wire/ludicrous_state*.bin and
// byte-compares against those files — cross-language wire identity for the
// serialize-phase-1 families (fixed(I, F), ufixed(I, F), int128, uint128) is
// the §7.2 gate this leg carries. Plus round-trips, the §5 branch-zeroing
// check over a 128-bit field, the specified-defaults checks (one default no
// 64-bit literal can spell — the emitted pair composition), and the hostile
// reads (reject, never clamp — STANDARD.md).
//
// Prints OK and exits 0. Run from test/dart-ludicrous (the Makefile does).
// Both modes run in CI: JIT --enable-asserts and AOT release; the wire must
// be identical in both. Mirrors test/ludicrous_main.cpp block for block;
// 128-bit values ride the generated Int128/UInt128 pair.
import 'dart:io';
import 'dart:typed_data';

import '../../generated/dart-ludicrous/Int128.dart';
import '../../generated/dart-ludicrous/Ludicrous.dart';

var failed = false;

void check(bool ok, String what) {
  if (!ok) {
    print('FAILED: $what');
    failed = true;
  }
}

final bool assertsEnabled = () {
  var on = false;
  assert(on = true);
  return on;
}();

void expectAssert(void Function() fn, String what) {
  if (!assertsEnabled) {
    return;
  }
  try {
    fn();
    check(false, what);
  } on AssertionError {
    // the contract fired — expected
  }
}

bool bytesEqual(Uint8List a, Uint8List b) {
  if (a.length != b.length) {
    return false;
  }
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) {
      return false;
    }
  }
  return true;
}

Uint8List golden(String name) =>
    File('../../testdata/wire/$name.bin').readAsBytesSync();

final Uint8List writeBuf = Uint8List(256);
final ByteData writeView = ByteData.sublistView(writeBuf);

Uint8List written(int bytes) => Uint8List.sublistView(writeBuf, 0, bytes);

// setBits forces bits [pos, pos + n) of the stream image to 1 — the hostile
// reader's tool: smuggling an offset into the range's bit headroom, which a
// read must REJECT, never clamp (STANDARD.md).
void setBits(Uint8List data, int pos, int n) {
  for (var i = pos; i < pos + n; i++) {
    data[i >>> 3] |= 1 << (i & 7);
  }
}

// makeState is test/ludicrous_main.cpp's make_state — the values must stay
// mirrored on both sides.
LudicrousState makeState() {
  final inp = LudicrousState();
  inp.mode = DriveMode.ludicrous;
  inp.probe.angle = 2981888; // +45.5 * 2^16
  inp.probe.position = -809119744; // -12346.1875 * 2^16
  inp.probe.reach = Int128.fromInt(65536000000 - 1); // raw_max - 1
  inp.probe.ticks = 777777;
  inp.probe.samples[0] = -524288; // raw_min
  inp.probe.samples[1] = 524288; // raw_max
  inp.wide.entityId = const UInt128(0x0123456789abcdef, 0xfedcba9876543210);
  inp.wide.energy = Int128.fromInt(4999999999);
  inp.wide.flux = const Int128(1 << 35, 7); // 2^99 + 7
  // wide.bias and wide.seed stay at their SPECIFIED DEFAULTS (-250 and
  // 2^65) — construction installs them, and they ride the wire as written
  inp.keysCount = 2;
  inp.keys[0] = const UInt128(0, 1);
  inp.keys[1] = const UInt128(0x8000000000000000, 0); // 1 << 127
  inp.hasTarget = true;
  inp.targetId = const UInt128(0, 42);
  return inp;
}

void main() {
  // worst-case bounds, hand-derived (SPEC §6.1 item 4) — the same numbers
  // test/ludicrous_main.cpp static_asserts
  check(fixedProbeMaxBits == 156, 'FixedProbe worst case');
  check(wideProbeMaxBits == 403, 'WideProbe worst case');
  check(ludicrousStateMaxBits == 1205, 'LudicrousState worst case');
  check(protocolId != 0, 'the unit has a protocol id');

  // zero initialization with specified defaults (SPEC §4.2), sentinel-zero
  // composition: construction starts at DriveMode None — the null rides
  // in-band — and the two defaulted 128-bit fields construct to their
  // declared values, one of which no 64-bit literal can spell
  {
    final zero = LudicrousState();
    check(
      zero.mode == DriveMode.none,
      'a fresh state starts at DriveMode None',
    );
    check(zero.probe.reach == Int128.zero, 'reach starts zero');
    check(zero.wide.entityId == UInt128.zero, 'entity_id starts zero');
    check(zero.wide.bias == Int128.fromInt(-250), 'bias defaults -250');
    check(zero.wide.seed == const UInt128(2, 0), 'seed defaults 2^65');
    check(zero.keysCount == 0, 'keys start empty');
    check(zero.targetId == UInt128.zero, 'target_id starts zero');
    // zero* is the §5 zero form; construction alone installs the defaults
    zeroLudicrousState(zero);
    check(zero.wide.bias == Int128.zero, 'the §5 zero form stays zero');
  }

  // ---- the taken-branch wire: generated bytes == the C++-pinned golden ----
  late Uint8List takenWire;
  {
    final inp = makeState();
    final n = writeLudicrousState(inp, writeView);
    takenWire = Uint8List.fromList(written(n));
    final g = golden('ludicrous_state');
    check(
      bytesEqual(takenWire, g),
      'wire golden ludicrous_state — Dart bytes must equal the C++-pinned bytes',
    );
    check(
      (measureLudicrousState(inp) + 7) >>> 3 == n,
      'measure vs written bytes',
    );

    final out = LudicrousState();
    check(
      readLudicrousState(out, ByteData.sublistView(takenWire), n * 8),
      'read LudicrousState',
    );
    check(out.mode == DriveMode.ludicrous, 'mode round-trips');
    check(out.probe.angle == inp.probe.angle, 'angle round-trips');
    check(out.probe.position == inp.probe.position, 'position round-trips');
    check(out.probe.reach == inp.probe.reach, 'reach round-trips');
    check(out.probe.ticks == inp.probe.ticks, 'ticks round-trips');
    check(
      out.probe.samples[0] == -524288 && out.probe.samples[1] == 524288,
      'samples round-trip',
    );
    check(out.wide.entityId == inp.wide.entityId, 'entity_id round-trips');
    check(out.wide.energy == inp.wide.energy, 'energy round-trips');
    check(out.wide.flux == inp.wide.flux, 'flux round-trips');
    check(out.wide.bias == Int128.fromInt(-250), 'the bias default rides');
    check(out.wide.seed == const UInt128(2, 0), 'the seed default rides');
    check(out.keysCount == 2, 'keys_count round-trips');
    check(
      out.keys[0] == inp.keys[0] && out.keys[1] == inp.keys[1],
      'keys round-trip',
    );
    check(
      out.hasTarget && out.targetId == const UInt128(0, 42),
      'the taken branch round-trips',
    );

    final n2 = writeLudicrousState(out, writeView);
    check(
      n2 == n && bytesEqual(written(n), takenWire),
      'LudicrousState round-trips to identical bytes',
    );
  }

  // ---- the untaken branch: identical prefix, and the 128-bit field under
  // it reads back ZERO into a dirty object (SPEC §5) ----
  {
    final inp = makeState();
    inp.hasTarget = false;
    final n = writeLudicrousState(inp, writeView);
    check(
      bytesEqual(written(n), golden('ludicrous_state_untargeted')),
      'wire golden ludicrous_state_untargeted',
    );

    final out = LudicrousState();
    out.targetId = const UInt128(0, 0xdead); // dirty — the read must zero it
    check(
      readLudicrousState(out, ByteData.sublistView(written(n)), n * 8),
      'read LudicrousState untargeted',
    );
    check(!out.hasTarget, 'has_target reads false');
    check(
      out.targetId == UInt128.zero,
      'the untaken 128-bit field reads as zero (SPEC §5)',
    );
  }

  // ---- hostile reads REJECT, never clamp (STANDARD.md, SPEC §5) ----
  {
    // fixed: angle's 25 offset bits start at bit 2; all-ones = 33554431,
    // above the raw range 360 * 2^16 = 23592960
    final hostile = Uint8List.fromList(takenWire);
    setBits(hostile, 2, 25);
    final out = LudicrousState();
    check(
      !readLudicrousState(
        out,
        ByteData.sublistView(hostile),
        hostile.length * 8,
      ),
      'a smuggled fixed offset is REJECTED',
    );
  }
  {
    // int128: energy's 34 offset bits start at bit 286 (2+156+128);
    // all-ones = 2^34 - 1 = 17179869183, above the range 10^10
    final hostile = Uint8List.fromList(takenWire);
    setBits(hostile, 286, 34);
    final out = LudicrousState();
    check(
      !readLudicrousState(
        out,
        ByteData.sublistView(hostile),
        hostile.length * 8,
      ),
      'a smuggled int128 offset is REJECTED',
    );
  }
  {
    // truncation: running out of input mid-read is a read failure (SPEC §5)
    final out = LudicrousState();
    final t = Uint8List.sublistView(takenWire, 0, 4);
    check(
      !readLudicrousState(out, ByteData.sublistView(t), t.length * 8),
      'a truncated stream is a read failure',
    );
  }

  // ---- DegenerateProbe: min == max costs ZERO bits (SPEC §4.6) ----
  // The whole wire is the tail byte; a port that emits ANY bits for a
  // degenerate range shifts it and fails the golden compare.
  {
    check(
      degenerateProbeMaxBits == 8,
      'three degenerate fields cost zero bits',
    );

    final inp = DegenerateProbe();
    inp.lockedFixed = -196608; // -3 * 2^16, the ONE legal raw
    inp.lockedInt = 7;
    inp.lockedWide = Int128.fromInt(-12345678901234);
    inp.tail = 0xa5;

    final n = writeDegenerateProbe(inp, writeView);
    check(
      bytesEqual(written(n), golden('degenerate_probe')),
      'wire golden degenerate_probe',
    );
    check(measureDegenerateProbe(inp) == 8, 'the degenerate wire is one byte');

    final out = DegenerateProbe();
    check(
      readDegenerateProbe(out, ByteData.sublistView(written(n)), n * 8),
      'read DegenerateProbe',
    );
    check(
      out.lockedFixed == -196608 &&
          out.lockedInt == 7 &&
          out.lockedWide == Int128.fromInt(-12345678901234) &&
          out.tail == 0xa5,
      'DegenerateProbe round-trips — every value materialized from its range',
    );
  }

  // ---- UnsignedProbe: ufixed(I, F), the unsigned sibling (SPEC §4.3) ----
  // span's raw value fills uint64's HIGH HALF (above 2^63) — it rides
  // bit-transparently in int, and the C++-pinned golden is the gate.
  {
    check(unsignedProbeMaxBits == 196, 'UnsignedProbe worst case');

    final inp = UnsignedProbe();
    inp.angle = 2981888; // +45.5 * 2^16
    inp.span = 0xffffffffffff0000; // raw_max — the uint64 HIGH HALF
    inp.reach = UInt128.fromInt(131071999999); // raw_max - 1
    inp.ticks = 777777;
    inp.samples[0] = 0; // raw_min
    inp.samples[1] = 1048576; // raw_max
    inp.locked = 196608; // 3 * 2^16, the ONE legal raw
    inp.tail = 0xa5;

    final n = writeUnsignedProbe(inp, writeView);
    final uWire = Uint8List.fromList(written(n));
    check(
      bytesEqual(uWire, golden('unsigned_probe')),
      'wire golden unsigned_probe',
    );

    final out = UnsignedProbe();
    check(
      readUnsignedProbe(out, ByteData.sublistView(uWire), n * 8),
      'read UnsignedProbe',
    );
    check(
      out.span == 0xffffffffffff0000 &&
          out.reach == UInt128.fromInt(131071999999) &&
          out.locked == 196608,
      'UnsignedProbe round-trips — the uint64 high half bit-exact',
    );

    // the write-side degenerate contract: any raw but 3 * 2^16 trips the
    // writer assert (checked twin)
    expectAssert(() {
      final bad = UnsignedProbe();
      bad.angle = inp.angle;
      bad.span = inp.span;
      bad.reach = inp.reach;
      bad.ticks = inp.ticks;
      bad.samples[0] = 0;
      bad.samples[1] = 1048576;
      bad.locked = 196609;
      bad.tail = 0xa5;
      writeUnsignedProbe(bad, writeView);
    }, 'a wrong degenerate ufixed raw must trip the writer contract');

    // hostile: span's 64 offset bits (starting at bit 25) all-ones =
    // 2^64 - 1, above the raw range 0xFFFFFFFFFFFF0000 — the headroom is
    // exactly the low 16 bits, and the reject must fire in the UNSIGNED
    // domain (a signed compare would call the smuggled value negative)
    final hostile = Uint8List.fromList(uWire);
    setBits(hostile, 25, 64);
    final hOut = UnsignedProbe();
    check(
      !readUnsignedProbe(
        hOut,
        ByteData.sublistView(hostile),
        hostile.length * 8,
      ),
      'a smuggled ufixed high-half offset is REJECTED',
    );
  }

  if (failed) {
    exitCode = 1;
    return;
  }
  print('OK');
}
