/* Code generated by the schema compiler. DO NOT EDIT.
   SPDX-License-Identifier: NONE — this generated output is yours. */
#ifndef SCHEMA_LUDICROUS_VIEW_H
#define SCHEMA_LUDICROUS_VIEW_H
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include "Ludicrous.h"
#ifndef SCHEMA_LUDICROUS_TABLE_PRIMITIVES
#define SCHEMA_LUDICROUS_TABLE_PRIMITIVES

/* THE CODEC DOES NOT DEPEND ON THE COMPILER'S INLINING BUDGET. A table of a
   realistic field count emits one large body per type, and the cursor a body
   writes through lives in the caller's TableWriter: across a call boundary that
   cursor round-trips through memory, and a uint8_t * store may alias the writer
   itself, so every put reloads it. When a budget runs out mid-body the codec
   silently degrades to that shape. Forcing the primitives and the fixed-class
   bodies inline is what keeps the cursor in registers and lets adjacent
   constant framing bytes merge into one store.

   The spelling is FEATURE TESTED rather than assumed, exactly as the packet
   emitter's own inlining demand is (SPEC §6.1's C column).

   IT CARRIES THE PACKAGE for the reason every other name here does, and that
   reason is the LINKER rather than the preprocessor: two units of the same
   schema family link into one program — two generations of one schema is the
   case the conformance driver itself is — so nothing this backend emits may
   be spelled the same way by two packages. They do NOT share a translation
   unit and cannot: C has no namespace, so two units' headers in one TU
   redefine TableReport, TableWriter and every other runtime name, which is the
   packet emitter's standing limit (SPEC §6.1) and not something tables
   changed. A per-package macro is what keeps the LINK legal. */
#ifndef SCHEMA_LUDICROUS_TABLE_INLINE
#if defined( _MSC_VER )
#define SCHEMA_LUDICROUS_TABLE_INLINE __forceinline
#elif defined( __GNUC__ ) || defined( __clang__ )
#define SCHEMA_LUDICROUS_TABLE_INLINE inline __attribute__(( always_inline ))
#else
#define SCHEMA_LUDICROUS_TABLE_INLINE inline
#endif
#endif

/* A COMPILE-TIME assertion under -std=c99, which has none of its own. C11's
   _Static_assert carries the message into the build log verbatim and is used
   wherever the compiler has it; everywhere else the negative array bound is
   the same refusal with a tag a reader can find. The tag is unique per record
   and field, and each record is asserted by the ONE header that declares it,
   so no two of these ever meet. */
#ifndef SCHEMA_TABLE_STATIC_ASSERT
#if defined( __STDC_VERSION__ ) && __STDC_VERSION__ >= 201112L
#define SCHEMA_TABLE_STATIC_ASSERT( tag, cond, message ) _Static_assert( cond, message )
#elif defined( __cplusplus ) && __cplusplus >= 201103L
#define SCHEMA_TABLE_STATIC_ASSERT( tag, cond, message ) static_assert( cond, message )
#else
#define SCHEMA_TABLE_STATIC_ASSERT( tag, cond, message ) typedef char schema_table_assert_##tag[ ( cond ) ? 1 : -1 ]
#endif
#endif

/* A record's ALIGNMENT, which the cook's layout contract asserts and which the
   cook's Open compares the header's alignment word against (§7.1, §20.3).
   C99 has no alignof either; C11's _Alignof, the two GNU spellings and MSVC's
   cover every compiler this repo builds under, and the last form is the
   portable definition of the same number. */
#ifndef SCHEMA_TABLE_ALIGNOF
#if defined( __STDC_VERSION__ ) && __STDC_VERSION__ >= 201112L
#define SCHEMA_TABLE_ALIGNOF( T ) _Alignof( T )
#elif defined( __GNUC__ ) || defined( __clang__ )
#define SCHEMA_TABLE_ALIGNOF( T ) __alignof__( T )
#elif defined( _MSC_VER )
#define SCHEMA_TABLE_ALIGNOF( T ) __alignof( T )
#else
#define SCHEMA_TABLE_ALIGNOF( T ) ( (size_t) offsetof( struct { char schema_pad_; T schema_member_; }, schema_member_ ) )
#endif
#endif

/* The table-wire read report — the permissive contract's ledger. Silence
   (all zero) means the data matched this reader's schema exactly. */
typedef struct TableReport
{
    int32_t unknown;       /* unknown field ids skipped (newer data) */
    int32_t kind_mismatch; /* known id, changed type — skipped, never misdecoded */
    int32_t clamped;       /* out-of-range values clamped to declared bounds */
    /* a key the TEXT form saw twice: last wins, and the repeat is counted
       (docs/SPEC-TABLES.md §16.2). The wire never raises it — a body carrying an
       id twice is legal input whose last occurrence wins, silently (§3). */
    int32_t duplicate;
    int malformed;         /* framing damage; decode stopped, partial result kept */
    int32_t widened;        /* exact widening of a known kind */
    int refused;           /* unsupported file form, not framing damage */
    int reason;            /* SCHEMA_TABLE_REFUSAL_REASON */
} TableReport;

enum SCHEMA_TABLE_REFUSAL_REASON { SCHEMA_TABLE_NO_REFUSAL, SCHEMA_TABLE_NEWER_FORM, SCHEMA_TABLE_MESSAGE_FORM_AS_FILE };

/* ---- reflection (tables only, docs/SPEC-TABLES.md) ----

   Static field descriptors for every type in the table closure: name, wire
   id/kind, storage offset, bounds, ranges, enum names and branch guards —
   enough to walk, print, diff, edit or bind any table value at runtime with
   no schema files. <name>_table_type() returns <Name>'s descriptor. */

struct TableTypeInfo;
struct TableFieldInfo;

/* One arm of a union field: where its payload sits inside the union's storage
   and what its payload looks like. The arm's NAME and its table-wire id ride
   in the field's own vocabulary table at the same tag, so nothing is spelled
   twice (docs/SPEC-TABLES.md §8). */
typedef struct TableUnionArmInfo
{
    uint32_t offset;                    /* offsetof the arm's payload within the union storage */
    const struct TableTypeInfo * table; /* the arm payload's descriptor */
    const struct TableFieldInfo * field; /* non-body arm, relative to union storage */
    uint32_t size; /* bytes established when this arm is selected */
} TableUnionArmInfo;

/* A union field's shape: the tag, and the arms indexed by it. Arms run
   [0, enum_max]; index 0 is the EMPTY arm and carries no payload. */
typedef struct TableUnionInfo
{
    uint32_t tag_offset; /* offsetof the tag within the union storage */
    uint32_t tag_size;   /* sizeof the tag */
    const TableUnionArmInfo * arms;
} TableUnionInfo;

/* ONE ENTRY OF A VOCABULARY, and the whole of what C++ spells as a pair of
   captureless lambdas. An enum's values, a union's arms and a flags field's
   BITS are each a named set indexed by [0, enum_max], so the set rides as an
   ARRAY indexed the same way: no function per enum, and therefore no name per
   enum for a schema to collide with (docs/SPEC-TABLES.md §11).

   name is the variant's spelling, or NULL for a value the declared set does
   not name. id is the TABLE-WIRE id it rides under (§5) — the hash of the
   variant's name, 0 for the reserved None and for the empty union arm. A
   FLAGS field's variants are BIT POSITIONS and have no per-variant wire id
   (§4), so has_ids is 0 there and 1 for an enum and a union: a vocabulary
   with names and no ids is what says "flags". */
typedef struct TableVariantInfo
{
    const char * name;
    uint64_t id;
} TableVariantInfo;

/* THE SHARED EMPTY DOC (docs/SPEC-TABLES.md §8.1): a declaration with no ///
   block carries a doc column pointing at this one object, so absence costs a
   unit no string data and a printer concatenates doc columns with no null
   test. One definition per translation unit, and the descriptors of a unit
   are one, so every absent doc compares equal by address. */
static SCHEMA_UNUSED const char TableDocNone[1] = "";

typedef struct TableWideRange { uint64_t lo[2], hi[2]; } TableWideRange;

typedef struct TableFieldInfo
{
    const char * name;      /* schema field name, e.g. "health" */
    const char * json;      /* the TEXT form's key: the json = "key" attribute, else name (§16.3) */
    const char * type_name; /* schema type name, e.g. "float32", "Grade" */
    uint64_t id;            /* table-wire field id (name hash; the was alias's hash after a rename) */
    uint8_t kind;           /* table-wire kind; for arrays/strings/bytes, the ELEMENT kind */
    int is_array;           /* fixed or counted array (bytes included) */
    int counted;            /* a _count/_length int32 companion exists (counted arrays, strings, bytes) */
    int optional;           /* a ?T field: a _present companion decides whether it rides */
    int32_t array_bound;    /* array capacity / string max length; 0 for plain scalars */
    uint32_t offset;        /* offsetof the storage member */
    uint32_t elem_size;     /* sizeof the member (element size for arrays) */
    uint32_t count_offset;  /* offsetof the _count/_length companion, or 0xffffffff */
    uint32_t present_offset; /* offsetof the _present companion, or 0xffffffff */
    const struct TableTypeInfo * table; /* nested table's descriptor, or NULL */
    int has_range;          /* a declared [min, max] (int or float) */
    double range_min;       /* NOTE: int64 ranges beyond 2^53 lose precision here */
    double range_max;
    const TableWideRange * wide; /* exact raw range for wide/fixed storage */
    int32_t frac_bits;
    int64_t enum_max;       /* enums: highest valid value (None = 0 always valid);
                               unions: the arm count (tag range [0, enum_max]);
                               flags: the highest declared BIT INDEX; else -1 */
    /* the vocabulary, indexed the same way enum_max bounds: an enum's value ->
       (name, id), a union's tag -> (arm name, arm id), a FLAGS field's bit
       index -> (variant name, 0). NULL for every other kind. */
    const TableVariantInfo * variants;
    int has_variant_ids;    /* 1 for an enum or a union, 0 for flags (§4) */
    /* an ENUM-KEYED array (docs/SPEC-TABLES.md §2.4): the array has one slot per
       variant of key_type_name, the key k at index k-1, and its slots ride
       under variant ids rather than positions. keys is the key's vocabulary,
       indexed by the KEY — walk [0, array_bound) and ask about index + 1 to
       print slots by name. NULL on every other field. */
    const char * key_type_name;
    const TableVariantInfo * keys;
    int64_t key_max;        /* the key enum's highest value, bounding keys */
    /* union fields: the tag and its arms. NULL for every other kind. */
    const TableUnionInfo * arms;
    const char * guard;     /* branch guard, e.g. "at_rest" or "!at_rest"; "" if unguarded */
    /* what a PERSON wrote about the field (docs/SPEC-TABLES.md §8.1): the ///
       block above it, verbatim (SPEC §4.1). It is TableDocNone when there is
       none, never NULL. Its tags (SPEC §4.2) follow in declared order, and an
       untagged field is 0 beside NULL. Static, constant-initialized,
       allocating nothing. */
    const char * doc;
    int32_t num_tags;
    const char * const * tags;
    int sequence; /* 0 inline field, 1 unbounded list, 2 map */
    void * (*place)(void * worker,void * slot,const char * key,int32_t length,int64_t number);
} TableFieldInfo;

typedef struct TableTypeInfo
{
    const char * name;   /* schema type name */
    uint32_t size;       /* sizeof the storage struct */
    int32_t num_fields;
    const TableFieldInfo * fields;
    /* put one instance back at its declared defaults, in place. A generic
       walker that fills a value has to be able to establish the defaults an
       absent field takes, and it holds no type to spell — this is the one
       thing the descriptors could not express without it. It is the void *
       form of <name>_reset and the same code. */
    void (*reset)( void * storage );
    /* the declaration's own doc and tags, on the same terms as a field's
       (docs/SPEC-TABLES.md §8.1) */
    const char * doc;
    int32_t num_tags;
    const char * const * tags;
} TableTypeInfo;



static SCHEMA_UNUSED float table_bits_to_float( uint32_t bits ) { float f; memcpy( &f, &bits, 4 ); return f; }
static SCHEMA_UNUSED uint32_t table_float_to_bits( float f ) { uint32_t b; memcpy( &b, &f, 4 ); return b; }
static SCHEMA_UNUSED double table_bits_to_double( uint64_t bits ) { double d; memcpy( &d, &bits, 8 ); return d; }
static SCHEMA_UNUSED uint64_t table_double_to_bits( double d ) { uint64_t b; memcpy( &b, &d, 8 ); return b; }

#endif /* SCHEMA_LUDICROUS_TABLE_PRIMITIVES */

#ifdef __cplusplus
extern "C" {
#endif
typedef struct ViewConstant
{
    const char * name;
    const char * file;       // the declaring schema file's basename
    const char * type_name;  // declared storage: "int64", "float64", "int32", ...
    int is_float;
    int64_t int_value;       // the folded value; float_value when is_float
    double float_value;
    const char * doc;        // the `///` block above it, verbatim (SPEC §4.1);
                             // "" when there is none, never NULL (§8.1)
    int32_t num_tags;             // the declaration's tags (SPEC §4.2), in
    const char * const * tags;    // DECLARED order; 0 and NULL when there are none
} ViewConstant;

typedef struct ViewVariant          // one enum variant, one flags bit, one union arm
{
    uint64_t value;         // an enum's value, a flags BIT INDEX, a union's tag
    const char * name;
    uint64_t id;            // the table-wire id (§5). It is 0 for a flags bit,
                            // and throughout a vocabulary no table closure
                            // reaches (§8.2)
    const char * payload_name;      // a union arm's TYPE as declared — a record's
                                    // name, or a general arm's spelling
                                    // ("int32", "string(64)", "*Chunk"); NULL on
                                    // a payload-free arm and on every other row
    const TableTypeInfo * payload;  // that payload's descriptor — never NULL for
                                    // an arm naming a `type` or a `table` (§8.2);
                                    // NULL on a general arm, on a payload-free
                                    // arm, on tag 0, and on an enum or flags row
    const TableFieldInfo * field;   // a general arm's FIELD descriptor: its kind,
                                    // width, bounds, capacity, companions and the
                                    // offsets §8.1 takes within the union's
                                    // storage. NULL on an arm naming a `type` or
                                    // a `table`, on a payload-free arm, on tag 0,
                                    // and on an enum or flags row
    const char * doc;               // the `///` block above this variant, bit or
                                    // arm, verbatim; "" when there is none (§8.1)
    int32_t num_tags;               // this row's own tags, in DECLARED order;
    const char * const * tags;      // 0 and NULL when there are none. On a general
                                    // arm the `field` descriptor above carries the
                                    // same two values (§8.1)
} ViewVariant;

typedef struct ViewVocabulary       // an enum, a flags or a union declaration
{
    const char * name;
    const char * file;
    int64_t max;            // highest value / highest bit index / highest tag
    int32_t storage_bits;
    int32_t num_variants;
    const ViewVariant * variants;
    const char * doc;             // the declaration's own `///` block; "" when none
    int32_t num_tags;             // the declaration's own tags, in DECLARED order;
    const char * const * tags;    // 0 and NULL when there are none
} ViewVocabulary;

typedef struct ViewType             // one declaration: a type, or a table
{
    const char * name;
    const char * file;
    int table;                     // declared `table`
    const TableTypeInfo * type;     // §8.1's descriptor: the properties, and this
                                    // declaration's own doc and tags beside them
    const char * doc;               // the `///` block above it; "" when none. The
                                    // same text `type->doc` carries (§8.1)
    int32_t num_tags;               // the declaration's tags (SPEC §4.2), in
    const char * const * tags;      // DECLARED order; the same list `type` carries
} ViewType;

typedef struct UnitViewInfo
{
    const char * package;
    uint64_t protocol_id;
    int32_t num_types;      const ViewType * types;
    int32_t num_tables;     const ViewType * tables;
    int32_t num_enums;      const ViewVocabulary * enums;
    int32_t num_flags;      const ViewVocabulary * flags;
    int32_t num_unions;     const ViewVocabulary * unions;
    int32_t num_constants;  const ViewConstant * constants;
} UnitViewInfo;

/* ---- prefill: the declared defaults, in place (docs/SPEC-TABLES.md) ---- */

static SCHEMA_UNUSED void degenerate_probe_reset( DegenerateProbe * value );
static SCHEMA_UNUSED void schema_ludicrous_degenerate_probe_reset_raw_( void * storage );
static SCHEMA_UNUSED void fixed_probe_reset( FixedProbe * value );
static SCHEMA_UNUSED void schema_ludicrous_fixed_probe_reset_raw_( void * storage );
static SCHEMA_UNUSED void fixed_quat_reset( FixedQuat * value );
static SCHEMA_UNUSED void schema_ludicrous_fixed_quat_reset_raw_( void * storage );
static SCHEMA_UNUSED void fixed_vec_reset( FixedVec * value );
static SCHEMA_UNUSED void schema_ludicrous_fixed_vec_reset_raw_( void * storage );
static SCHEMA_UNUSED void ludicrous_state_reset( LudicrousState * value );
static SCHEMA_UNUSED void schema_ludicrous_ludicrous_state_reset_raw_( void * storage );
static SCHEMA_UNUSED void unsigned_probe_reset( UnsignedProbe * value );
static SCHEMA_UNUSED void schema_ludicrous_unsigned_probe_reset_raw_( void * storage );
static SCHEMA_UNUSED void wide_probe_reset( WideProbe * value );
static SCHEMA_UNUSED void schema_ludicrous_wide_probe_reset_raw_( void * storage );

static SCHEMA_UNUSED void degenerate_probe_reset( DegenerateProbe * value )
{
    value->locked_fixed = -196608;
    value->locked_int = 7;
    value->locked_wide = serialize_int128_make( 18446744073709551615ull, 18446731728030650382ull );
    value->tail = 0;
}

static SCHEMA_UNUSED void schema_ludicrous_degenerate_probe_reset_raw_( void * storage ) { degenerate_probe_reset( (DegenerateProbe *) storage ); }

extern const TableTypeInfo schema_ludicrous_degenerate_probe_info_;
static SCHEMA_UNUSED const TableTypeInfo * degenerate_probe_table_type(void) { return &schema_ludicrous_degenerate_probe_info_; }
static SCHEMA_UNUSED void fixed_probe_reset( FixedProbe * value )
{
    value->angle = 0;
    value->position = 0;
    value->reach = serialize_int128_make( 0ull, 0ull );
    value->ticks = 0;
    memset( value->samples, 0, sizeof( value->samples ) );
}

static SCHEMA_UNUSED void schema_ludicrous_fixed_probe_reset_raw_( void * storage ) { fixed_probe_reset( (FixedProbe *) storage ); }

extern const TableTypeInfo schema_ludicrous_fixed_probe_info_;
static SCHEMA_UNUSED const TableTypeInfo * fixed_probe_table_type(void) { return &schema_ludicrous_fixed_probe_info_; }
static SCHEMA_UNUSED void fixed_quat_reset( FixedQuat * value )
{
    value->x = 0;
    value->y = 0;
    value->z = 0;
    value->w = 1073741824;
}

static SCHEMA_UNUSED void schema_ludicrous_fixed_quat_reset_raw_( void * storage ) { fixed_quat_reset( (FixedQuat *) storage ); }

extern const TableTypeInfo schema_ludicrous_fixed_quat_info_;
static SCHEMA_UNUSED const TableTypeInfo * fixed_quat_table_type(void) { return &schema_ludicrous_fixed_quat_info_; }
static SCHEMA_UNUSED void fixed_vec_reset( FixedVec * value )
{
    value->x = 0;
    value->y = 0;
    value->z = 0;
}

static SCHEMA_UNUSED void schema_ludicrous_fixed_vec_reset_raw_( void * storage ) { fixed_vec_reset( (FixedVec *) storage ); }

extern const TableTypeInfo schema_ludicrous_fixed_vec_info_;
static SCHEMA_UNUSED const TableTypeInfo * fixed_vec_table_type(void) { return &schema_ludicrous_fixed_vec_info_; }
static SCHEMA_UNUSED void ludicrous_state_reset( LudicrousState * value )
{
    value->mode = DRIVE_MODE_NONE;
    fixed_probe_reset( &value->probe );
    wide_probe_reset( &value->wide );
    memset( value->keys, 0, sizeof( value->keys ) );
    value->keys_count = 0;
    value->has_target = 0;
    value->target_id = serialize_uint128_make( 0ull, 0ull );
}

static SCHEMA_UNUSED void schema_ludicrous_ludicrous_state_reset_raw_( void * storage ) { ludicrous_state_reset( (LudicrousState *) storage ); }

extern const TableTypeInfo schema_ludicrous_ludicrous_state_info_;
static SCHEMA_UNUSED const TableTypeInfo * ludicrous_state_table_type(void) { return &schema_ludicrous_ludicrous_state_info_; }
static SCHEMA_UNUSED void unsigned_probe_reset( UnsignedProbe * value )
{
    value->angle = 0;
    value->span = 0;
    value->reach = serialize_uint128_make( 0ull, 0ull );
    value->ticks = 0;
    memset( value->samples, 0, sizeof( value->samples ) );
    value->locked = 196608;
    value->tail = 0;
}

static SCHEMA_UNUSED void schema_ludicrous_unsigned_probe_reset_raw_( void * storage ) { unsigned_probe_reset( (UnsignedProbe *) storage ); }

extern const TableTypeInfo schema_ludicrous_unsigned_probe_info_;
static SCHEMA_UNUSED const TableTypeInfo * unsigned_probe_table_type(void) { return &schema_ludicrous_unsigned_probe_info_; }
static SCHEMA_UNUSED void wide_probe_reset( WideProbe * value )
{
    value->entity_id = serialize_uint128_make( 0ull, 0ull );
    value->energy = serialize_int128_make( 0ull, 0ull );
    value->flux = serialize_int128_make( 0ull, 0ull );
    value->bias = serialize_int128_make( 18446744073709551615ull, 18446744073709551366ull );
    value->seed = serialize_uint128_make( 2ull, 0ull );
}

static SCHEMA_UNUSED void schema_ludicrous_wide_probe_reset_raw_( void * storage ) { wide_probe_reset( (WideProbe *) storage ); }

extern const TableTypeInfo schema_ludicrous_wide_probe_info_;
static SCHEMA_UNUSED const TableTypeInfo * wide_probe_table_type(void) { return &schema_ludicrous_wide_probe_info_; }
const UnitViewInfo * schema_ludicrous_unit_view_(void);
static SCHEMA_UNUSED const UnitViewInfo * unit_view(void) { return schema_ludicrous_unit_view_(); }
#ifdef __cplusplus
}
#endif
#endif
