// Code generated by the schema compiler from Caption.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package wide — the BLOCK FORM (docs/SPEC-TABLES.md §19): the READ half.
//
// NOTHING DECLARES THIS FORM. Every fixed table has one, and it is emitted on
// the side: compile this file only if you read a block. The unit's
// <Base>Table.cs carries not one symbol of it.
//
// It is UNSAFE by nature, not by taste: a block is memory another language
// wrote, and pointing at it without a copy is the whole point (§12.1). A
// project that compiles this file sets AllowUnsafeBlocks.
//
// Every size and offset below is the MANAGED unmanaged-struct model — what
// Span and pointer arithmetic index with — never the interop marshalling
// model (§19.3). A bool in a row is ONE byte.

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Wide
{


    // The BLITTABLE records: one per record the block form touches, laid out to
    // the C ABI with GENERATED PADDING FIELDS wherever the layout has interior
    // padding and a Size that pins the trailing padding — both are needed
    // (docs/SPEC-TABLES.md §19.3). Explicit padding is chosen over LayoutKind.Explicit
    // because Sequential is the form every blittable path handles best, and over
    // relying on a padding-free field order because that is discipline, and
    // discipline is what this form exists to delete.
    //
    // They take a CLAIMED SUFFIX in the unit's own namespace — <Name>Row for a
    // row and <Table>BlockProjection for a projection — because the namespace
    // already holds a sealed CLASS of each declaration's name, which is the
    // table wire's storage, and one declaration cannot be two types.
    // Stamp — the block PROJECTION: the table's own instance as it sits at the
    // front of a block, opening with the generated PROLOGUE and carrying, per
    // out-of-line array, the triple that says where its rows are. It is a record
    // like any other and follows the same C ABI rule (docs/SPEC-TABLES.md §19.3).
    //
    // It is a SEPARATE record from <Table>Row: a table can be both a block root
    // and another block's row, and the two differ by the prologue.
    [StructLayout(LayoutKind.Sequential, Pack = 1, Size = 48)]
    public unsafe struct StampBlockProjection
    {
        public ulong Magic;        // generated: identifies a schema block
        public ulong BuildVersion; // generated: the unit's build version (docs/SPEC-TABLES.md §20)
        public ulong ByteOrder;    // generated: 1 little, 2 big
        public fixed char Label[5];
        private byte _pad34;
        private byte _pad35;
        public int LabelLength;
        public uint Seq;
        private byte _pad44;
        private byte _pad45;
        private byte _pad46;
        private byte _pad47;
    }
    // table Caption has NO block form: Caption.body is a union, and a block's blittable C# form is Sequential with generated padding, which cannot overlay arms (docs/SPEC-TABLES.md §19).
    // Its wire (§3) is unaffected — only this projection is absent, and it is
    // absent by construction rather than by refusal.

    public struct StampCounts
    {
    }

    public sealed class StampBlockStorage : TableBlockStorage
    {
        public StampBlockStorage(TableBlockAllocator allocator = null) : base(StampBlock.BlockMaxBytes, allocator) {}
    }

    // Stamp's block: a pointer and a length, and then rows in place. Opening one
    // is ONE check and no copy; reading a row is one add (docs/SPEC-TABLES.md §19.2).
    //
    // The bytes belong to the CONSUMER — a managed array it pinned, a NativeArray,
    // or memory the producer handed across. Nothing here allocates.
    public unsafe readonly struct StampBlock
    {
        // Begin settles the layout before workers fill disjoint rows. It touches
        // the prologue and triples only; use Clear on storage when byte stability matters.
        public static bool Begin(out StampBlock block, IntPtr pointer, long capacity, in StampCounts counts, out TableBlockRefusal refusal)
        {
            block = default; refusal = default;
            if (pointer == IntPtr.Zero || ((ulong)pointer & 63) != 0) { return false; }
            long at = 48;
            at = (at + 63) & ~63L; if (at > capacity) { return false; }
            StampBlockProjection* p = (StampBlockProjection*)pointer;
            p->Magic = Schema.TableBlockMagic; p->BuildVersion = Schema.BuildVersion; p->ByteOrder = Schema.TableBlockByteOrder;
            block = new StampBlock((byte*)pointer, at); return true;
        }

        public static bool Begin(out StampBlock block, StampBlockStorage storage, in StampCounts counts, out TableBlockRefusal refusal) { return Begin(out block, storage.Pointer, storage.Capacity, counts, out refusal); }
        public ref StampBlockProjection WritableProjection { get { return ref *(StampBlockProjection*)basePointer; } }
        private readonly byte* basePointer;
        private readonly long bytes;

        private StampBlock(byte* basePointer, long bytes)
        {
            this.basePointer = basePointer;
            this.bytes = bytes;
        }

        static StampBlock()
        {
            // the layout contract, run once before any static member of this type
            TableBlockLayout.Verify();
        }

        // The storage a PRODUCER of this block allocates, sized from the declared
        // maxima (docs/SPEC-TABLES.md §19.1). A C# consumer does not allocate a block —
        // the bytes are handed to it — but it caps by this: a playback buffer, a
        // recording, a scratch copy all size from the generated constant rather
        // than from a number a person wrote down beside it.
        public const long BlockMaxBytes = 64;

        public byte* Base { get { return basePointer; } }
        public long Bytes { get { return bytes; } }

        // the table's own declared fields, read where they lie
        public ref readonly StampBlockProjection Projection { get { return ref *(StampBlockProjection*) basePointer; } }

        // Open checks once and points, and this is the WHOLE check (docs/SPEC-TABLES.md
        // §19.2): the magic read bytewise, the BYTE ORDER the prologue carries
        // against this build's own, the BUILD VERSION against this build's own,
        // each array's pitch, its offset_of, its COUNT against the declared
        // maximum and its extent inside the block, the used extent
        // against the bytes the caller passed, and the base's alignment. On a
        // match the bytes are what a build with this layout wrote, so there is
        // nothing to validate and nothing to fix up. On any failure it returns
        // false and points at nothing.
        //
        // There is ONE entry point and no tolerant twin: the block form is
        // same-build by construction — both sides generated from one declaration
        // at one build — so a consumer older than its producer is not a case. A
        // mismatch is a refusal; regenerate both sides. Data that must outlive the
        // build that wrote it takes the wire, which this same table still has.
        public static bool Open(out StampBlock block, IntPtr pointer, long bytes) { return Open(out block, pointer, bytes, out _); }
        public static bool Open(out StampBlock block, IntPtr pointer, long bytes, out TableRefuseReason reason)
        {
            block = default; reason = TableRefuseReason.ok;
            TableBlockLayout.Verify();
            if (pointer == IntPtr.Zero) { reason = TableRefuseReason.unaligned_base; return false; }
            if (bytes < 48) { reason = TableRefuseReason.truncated; return false; }
            byte* at = (byte*) pointer;
            if (Schema.TableBlockRead64(at) != Schema.TableBlockMagic) { reason = Schema.TableBlockRead64(at) == System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(Schema.TableBlockMagic) ? TableRefuseReason.foreign_order : TableRefuseReason.not_a_cook; return false; }
            if (Schema.TableBlockRead64(at + 16) != Schema.TableBlockByteOrder) { reason = TableRefuseReason.not_a_cook; return false; }
            if (Schema.TableBlockRead64(at + 8) != Schema.BuildVersion) { reason = TableRefuseReason.wrong_build_version; return false; }
            long used = 48;
            // the used extent, rounded to 64 WITHOUT the rounding itself wrapping:
            // used is already inside bytes, and the padding is paid out of the slack
            // that is left rather than added and compared after.
            long padding = (64 - (used % 64)) % 64;
            if (padding > bytes - used) { reason = TableRefuseReason.truncated; return false; }
            used += padding;
            if (((ulong)pointer & 63) != 0) { reason = TableRefuseReason.unaligned_base; return false; }
            block = new StampBlock(at, used);
            return true;
        }

        // this table's block descriptors: constant data, so a reflective read
        // costs a lookup and not a parse. The row layouts hang off the element
        // column rather than taking names of their own, so a walker reaches every
        // record through the graph.
        private static readonly TableBlockInfo blockProjection = new TableBlockInfo
        {
            Name = "Stamp", BuildVersion = Schema.BuildVersion, Size = 48, Align = 8, NumFields = 2,
            Fields = new TableBlockFieldInfo[]
            {
                new TableBlockFieldInfo { Name = "label", Offset = 24, Size = 16, Kind = 33, OutOfLine = false, OffsetOfOffset = -1, CountOffset = 36, StrideOffset = -1, Stride = 0, IsArray = false, Counted = true, Optional = false, ArrayBound = 4, ElemSize = 2, PresentOffset = -1, ElementRef = null },
                new TableBlockFieldInfo { Name = "seq", Offset = 40, Size = 4, Kind = 8, OutOfLine = false, OffsetOfOffset = -1, CountOffset = -1, StrideOffset = -1, Stride = 0, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, ElemSize = 4, PresentOffset = -1, ElementRef = null },
            },
        };

        public static TableBlockInfo Type { get { return blockProjection; } }
    }

}
