// Code generated by the schema compiler from Clauses.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package example — protocol id 0xdd71ce8b50d78939

using System;
using System.Runtime.CompilerServices;
using Serialize;

namespace Example
{

    // type W13
    public sealed class W13
    {
        public ushort[] Items = new ushort[12]; // used count beside it; wire count in [0, 12]
        public int ItemsCount;
    }

    // type W17
    public sealed class W17
    {
        public uint[] Items = new uint[9]; // used count beside it; wire count in [0, 9]
        public int ItemsCount;
    }

    // type W26
    public sealed class W26
    {
        public uint[] Items = new uint[6]; // used count beside it; wire count in [0, 6]
        public int ItemsCount;
    }

    // type W1
    public sealed class W1
    {
        public byte[] Items = new byte[20]; // used count beside it; wire count in [0, 20]
        public int ItemsCount;
    }

    // type W52
    public sealed class W52
    {
        public ulong[] Items = new ulong[3]; // used count beside it; wire count in [0, 3]
        public int ItemsCount;
    }

    // type W50
    public sealed class W50
    {
        public ulong[] Items = new ulong[3]; // used count beside it; wire count in [0, 3]
        public int ItemsCount;
    }

    // type F13
    public sealed class F13
    {
        public ushort[] Items = new ushort[7]; // wire [0, 8191]
    }

    // type Tri3
    public sealed class Tri3
    {
        public uint A;
        public uint B;
    }

    // type ArrTri3
    public sealed class ArrTri3
    {
        public Tri3[] Items = new Tri3[10]; // used count beside it; wire count in [0, 10]
        public int ItemsCount;

        public ArrTri3()
        {
            for (int i = 0; i < Items.Length; i++)
            {
                Items[i] = new Tri3();
            }
        }
    }

    // type Eleven
    public sealed class Eleven
    {
        public uint A;
        public uint B;
    }

    // type ArrEleven
    public sealed class ArrEleven
    {
        public Eleven[] Items = new Eleven[9];

        public ArrEleven()
        {
            for (int i = 0; i < Items.Length; i++)
            {
                Items[i] = new Eleven();
            }
        }
    }

    // type EmptyA
    public sealed class EmptyA
    {
    }

    // type EmptyB
    public sealed class EmptyB
    {
    }

    // EmptyUnionType: union EmptyUnion's tag — None = 0, then each variant in declared order (SPEC §4.8)
    public enum EmptyUnionType : byte
    {
        None = 0,
        A = 1,
        B = 2,
        Max = 2, // the exported extent (SPEC §4.2)
    }

    // EmptyUnion — at most one of the arms; Type says which. Construction is the empty
    // union (None). A read zero-establishes exactly the selected arm before
    // decoding it (SPEC §5); unselected arms keep what they last held — the
    // MessageStorage reuse discipline. Consumers read the selected arm only.
    public sealed class EmptyUnion
    {
        public EmptyUnionType Type;
        public EmptyA A = new EmptyA();
        public EmptyB B = new EmptyB();
    }

    // type HoldsEmptyUnion
    public sealed class HoldsEmptyUnion
    {
        public uint Lead;
        public EmptyUnion U = new EmptyUnion();
        public uint Tail;
    }

    // type Strs
    public sealed class Strs
    {
        public uint Lead;
        public byte[] S = new byte[8]; // string(8): max length, used length beside it (SPEC §4.7)
        public int SLength;
        public byte[] B = new byte[8]; // bytes(8): fixed buffer, used length beside it (SPEC §4.7)
        public int BLength;
        public uint Tail;
    }

    // type ArrNested
    public sealed class ArrNested
    {
        public uint Lead;
        public Eleven[] Items = new Eleven[4]; // used count beside it; wire count in [0, 4]
        public int ItemsCount;
        public uint Tail;

        public ArrNested()
        {
            for (int i = 0; i < Items.Length; i++)
            {
                Items[i] = new Eleven();
            }
        }
    }

    // type Sole
    public sealed class Sole
    {
        public uint Only;
    }

    // Schema carries every generated function and constant of the unit — C# has
    // no namespace-level functions or constants, so the static class is their
    // home (SPEC §6.1 naming); partial, one slice per generated file.
    public static partial class Schema
    {
        // W13MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // W13MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long W13MaxBits = 160;
        public const long W13MaxBytes = 24;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroW13(W13 value)
        {
            Array.Clear(value.Items, 0, 12);
            value.ItemsCount = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteW13(WriteStream stream, W13 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteW13Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteW13Batch(ref WriteBatch batch, W13 value)
        {
            if (value.ItemsCount < 0 || value.ItemsCount > 12) // the count guards the loop (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.ItemsCount);
                if (!batch.SerializeBits(ref offsetValue, 4))
                {
                    return false;
                }
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (value.Items[i] > 8191)
                {
                    return false;
                }
                {
                    uint offsetValue = (uint)(value.Items[i]);
                    if (!batch.SerializeBits(ref offsetValue, 13))
                    {
                        return false;
                    }
                }
            }
            return true;
        }

        public static bool ReadW13(ReadStream stream, W13 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadW13Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadW13Batch(ref ReadBatch batch, W13 value)
        {
            if (!batch.SerializeInt(ref value.ItemsCount, 0, 12)) // the count guards the loop (§6.3)
            {
                return false;
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                {
                    int rangeValue = 0;
                    if (!batch.SerializeInt(ref rangeValue, 0, 8191))
                    {
                        return false;
                    }
                    value.Items[i] = (ushort)rangeValue;
                }
            }
            return true;
        }

        // W17MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // W17MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long W17MaxBits = 157;
        public const long W17MaxBytes = 24;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroW17(W17 value)
        {
            Array.Clear(value.Items, 0, 9);
            value.ItemsCount = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteW17(WriteStream stream, W17 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteW17Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteW17Batch(ref WriteBatch batch, W17 value)
        {
            if (value.ItemsCount < 0 || value.ItemsCount > 9) // the count guards the loop (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.ItemsCount);
                if (!batch.SerializeBits(ref offsetValue, 4))
                {
                    return false;
                }
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (value.Items[i] > 131071)
                {
                    return false;
                }
                {
                    uint offsetValue = (uint)(value.Items[i]);
                    if (!batch.SerializeBits(ref offsetValue, 17))
                    {
                        return false;
                    }
                }
            }
            return true;
        }

        public static bool ReadW17(ReadStream stream, W17 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadW17Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadW17Batch(ref ReadBatch batch, W17 value)
        {
            if (!batch.SerializeInt(ref value.ItemsCount, 0, 9)) // the count guards the loop (§6.3)
            {
                return false;
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                {
                    int rangeValue = 0;
                    if (!batch.SerializeInt(ref rangeValue, 0, 131071))
                    {
                        return false;
                    }
                    value.Items[i] = (uint)rangeValue;
                }
            }
            return true;
        }

        // W26MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // W26MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long W26MaxBits = 159;
        public const long W26MaxBytes = 24;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroW26(W26 value)
        {
            Array.Clear(value.Items, 0, 6);
            value.ItemsCount = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteW26(WriteStream stream, W26 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteW26Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteW26Batch(ref WriteBatch batch, W26 value)
        {
            if (value.ItemsCount < 0 || value.ItemsCount > 6) // the count guards the loop (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.ItemsCount);
                if (!batch.SerializeBits(ref offsetValue, 3))
                {
                    return false;
                }
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (value.Items[i] > 67108863)
                {
                    return false;
                }
                {
                    uint offsetValue = (uint)(value.Items[i]);
                    if (!batch.SerializeBits(ref offsetValue, 26))
                    {
                        return false;
                    }
                }
            }
            return true;
        }

        public static bool ReadW26(ReadStream stream, W26 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadW26Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadW26Batch(ref ReadBatch batch, W26 value)
        {
            if (!batch.SerializeInt(ref value.ItemsCount, 0, 6)) // the count guards the loop (§6.3)
            {
                return false;
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                {
                    int rangeValue = 0;
                    if (!batch.SerializeInt(ref rangeValue, 0, 67108863))
                    {
                        return false;
                    }
                    value.Items[i] = (uint)rangeValue;
                }
            }
            return true;
        }

        // W1MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // W1MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long W1MaxBits = 25;
        public const long W1MaxBytes = 8;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroW1(W1 value)
        {
            Array.Clear(value.Items, 0, 20);
            value.ItemsCount = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteW1(WriteStream stream, W1 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteW1Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteW1Batch(ref WriteBatch batch, W1 value)
        {
            if (value.ItemsCount < 0 || value.ItemsCount > 20) // the count guards the loop (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.ItemsCount);
                if (!batch.SerializeBits(ref offsetValue, 5))
                {
                    return false;
                }
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (value.Items[i] > 1)
                {
                    return false;
                }
                {
                    uint offsetValue = (uint)(value.Items[i]);
                    if (!batch.SerializeBits(ref offsetValue, 1))
                    {
                        return false;
                    }
                }
            }
            return true;
        }

        public static bool ReadW1(ReadStream stream, W1 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadW1Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadW1Batch(ref ReadBatch batch, W1 value)
        {
            if (!batch.SerializeInt(ref value.ItemsCount, 0, 20)) // the count guards the loop (§6.3)
            {
                return false;
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                {
                    int rangeValue = 0;
                    if (!batch.SerializeInt(ref rangeValue, 0, 1))
                    {
                        return false;
                    }
                    value.Items[i] = (byte)rangeValue;
                }
            }
            return true;
        }

        // W52MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // W52MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long W52MaxBits = 158;
        public const long W52MaxBytes = 24;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroW52(W52 value)
        {
            Array.Clear(value.Items, 0, 3);
            value.ItemsCount = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteW52(WriteStream stream, W52 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteW52Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteW52Batch(ref WriteBatch batch, W52 value)
        {
            if (value.ItemsCount < 0 || value.ItemsCount > 3) // the count guards the loop (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.ItemsCount);
                if (!batch.SerializeBits(ref offsetValue, 2))
                {
                    return false;
                }
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (value.Items[i] > 4503599627370495)
                {
                    return false;
                }
                {
                    ulong offsetValue = (ulong)(value.Items[i]);
                    if (!batch.SerializeBits64(ref offsetValue, 52))
                    {
                        return false;
                    }
                }
            }
            return true;
        }

        public static bool ReadW52(ReadStream stream, W52 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadW52Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadW52Batch(ref ReadBatch batch, W52 value)
        {
            if (!batch.SerializeInt(ref value.ItemsCount, 0, 3)) // the count guards the loop (§6.3)
            {
                return false;
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                {
                    long rangeValue = 0;
                    if (!batch.SerializeInt64(ref rangeValue, 0, 4503599627370495))
                    {
                        return false;
                    }
                    value.Items[i] = (ulong)rangeValue;
                }
            }
            return true;
        }

        // W50MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // W50MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long W50MaxBits = 152;
        public const long W50MaxBytes = 24;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroW50(W50 value)
        {
            Array.Clear(value.Items, 0, 3);
            value.ItemsCount = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteW50(WriteStream stream, W50 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteW50Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteW50Batch(ref WriteBatch batch, W50 value)
        {
            if (value.ItemsCount < 0 || value.ItemsCount > 3) // the count guards the loop (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.ItemsCount);
                if (!batch.SerializeBits(ref offsetValue, 2))
                {
                    return false;
                }
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (value.Items[i] > 1125899906842623)
                {
                    return false;
                }
                {
                    ulong offsetValue = (ulong)(value.Items[i]);
                    if (!batch.SerializeBits64(ref offsetValue, 50))
                    {
                        return false;
                    }
                }
            }
            return true;
        }

        public static bool ReadW50(ReadStream stream, W50 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadW50Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadW50Batch(ref ReadBatch batch, W50 value)
        {
            if (!batch.SerializeInt(ref value.ItemsCount, 0, 3)) // the count guards the loop (§6.3)
            {
                return false;
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                {
                    long rangeValue = 0;
                    if (!batch.SerializeInt64(ref rangeValue, 0, 1125899906842623))
                    {
                        return false;
                    }
                    value.Items[i] = (ulong)rangeValue;
                }
            }
            return true;
        }

        // F13MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // F13MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long F13MaxBits = 91;
        public const long F13MaxBytes = 16;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroF13(F13 value)
        {
            Array.Clear(value.Items, 0, 7);
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteF13(WriteStream stream, F13 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteF13Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteF13Batch(ref WriteBatch batch, F13 value)
        {
            for (int i = 0; i < 7; i++)
            {
                if (value.Items[i] > 8191)
                {
                    return false;
                }
                {
                    uint offsetValue = (uint)(value.Items[i]);
                    if (!batch.SerializeBits(ref offsetValue, 13))
                    {
                        return false;
                    }
                }
            }
            return true;
        }

        public static bool ReadF13(ReadStream stream, F13 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadF13Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadF13Batch(ref ReadBatch batch, F13 value)
        {
            for (int i = 0; i < 7; i++)
            {
                {
                    int rangeValue = 0;
                    if (!batch.SerializeInt(ref rangeValue, 0, 8191))
                    {
                        return false;
                    }
                    value.Items[i] = (ushort)rangeValue;
                }
            }
            return true;
        }

        // Tri3MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // Tri3MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long Tri3MaxBits = 3;
        public const long Tri3MaxBytes = 8;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroTri3(Tri3 value)
        {
            value.A = 0;
            value.B = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteTri3(WriteStream stream, Tri3 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteTri3Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteTri3Batch(ref WriteBatch batch, Tri3 value)
        {
            {
                // flat run: 3 bits in 1 chunk(s) — the field placement is folded
                ulong f0 = ((ulong)value.A) & 0x1UL;
                ulong f1 = ((ulong)value.B) & 0x3UL;
                uint w0 = (uint)(f0 | (f1 << 1));
                if (!batch.SerializeBits(ref w0, 3))
                {
                    return false;
                }
            }
            return true;
        }

        public static bool ReadTri3(ReadStream stream, Tri3 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadTri3Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadTri3Batch(ref ReadBatch batch, Tri3 value)
        {
            {
                // flat run: 3 bits in 1 chunk(s) — one bounds check per chunk,
                // one sticky-error test for the whole run
                ulong c0 = 0;
                batch.SerializeBits64(ref c0, 3);
                if (!batch.Ok)
                {
                    return false;
                }
                ulong v0 = c0 & 0x1UL;
                value.A = (uint)v0;
                ulong v1 = (c0 >> 1) & 0x3UL;
                value.B = (uint)v1;
            }
            return true;
        }

        // ArrTri3MaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // ArrTri3MaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long ArrTri3MaxBits = 34;
        public const long ArrTri3MaxBytes = 8;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroArrTri3(ArrTri3 value)
        {
            for (int i = 0; i < 10; i++)
            {
                ZeroTri3(value.Items[i]);
            }
            value.ItemsCount = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteArrTri3(WriteStream stream, ArrTri3 value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteArrTri3Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteArrTri3Batch(ref WriteBatch batch, ArrTri3 value)
        {
            if (value.ItemsCount < 0 || value.ItemsCount > 10) // the count guards the loop (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.ItemsCount);
                if (!batch.SerializeBits(ref offsetValue, 4))
                {
                    return false;
                }
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (!WriteTri3Batch(ref batch, value.Items[i]))
                {
                    return false;
                }
            }
            return true;
        }

        public static bool ReadArrTri3(ReadStream stream, ArrTri3 value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadArrTri3Batch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadArrTri3Batch(ref ReadBatch batch, ArrTri3 value)
        {
            if (!batch.SerializeInt(ref value.ItemsCount, 0, 10)) // the count guards the loop (§6.3)
            {
                return false;
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (!ReadTri3Batch(ref batch, value.Items[i]))
                {
                    return false;
                }
            }
            return true;
        }

        // ElevenMaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // ElevenMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long ElevenMaxBits = 11;
        public const long ElevenMaxBytes = 8;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroEleven(Eleven value)
        {
            value.A = 0;
            value.B = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteEleven(WriteStream stream, Eleven value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteElevenBatch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteElevenBatch(ref WriteBatch batch, Eleven value)
        {
            {
                // flat run: 11 bits in 1 chunk(s) — the field placement is folded
                ulong f0 = ((ulong)value.A) & 0x7UL;
                ulong f1 = ((ulong)value.B) & 0xffUL;
                uint w0 = (uint)(f0 | (f1 << 3));
                if (!batch.SerializeBits(ref w0, 11))
                {
                    return false;
                }
            }
            return true;
        }

        public static bool ReadEleven(ReadStream stream, Eleven value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadElevenBatch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadElevenBatch(ref ReadBatch batch, Eleven value)
        {
            {
                // flat run: 11 bits in 1 chunk(s) — one bounds check per chunk,
                // one sticky-error test for the whole run
                ulong c0 = 0;
                batch.SerializeBits64(ref c0, 11);
                if (!batch.Ok)
                {
                    return false;
                }
                ulong v0 = c0 & 0x7UL;
                value.A = (uint)v0;
                ulong v1 = (c0 >> 3) & 0xffUL;
                value.B = (uint)v1;
            }
            return true;
        }

        // ArrElevenMaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // ArrElevenMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long ArrElevenMaxBits = 99;
        public const long ArrElevenMaxBytes = 16;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroArrEleven(ArrEleven value)
        {
            for (int i = 0; i < 9; i++)
            {
                ZeroEleven(value.Items[i]);
            }
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteArrEleven(WriteStream stream, ArrEleven value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteArrElevenBatch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteArrElevenBatch(ref WriteBatch batch, ArrEleven value)
        {
            for (int i = 0; i < 9; i++)
            {
                if (!WriteElevenBatch(ref batch, value.Items[i]))
                {
                    return false;
                }
            }
            return true;
        }

        public static bool ReadArrEleven(ReadStream stream, ArrEleven value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadArrElevenBatch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadArrElevenBatch(ref ReadBatch batch, ArrEleven value)
        {
            for (int i = 0; i < 9; i++)
            {
                if (!ReadElevenBatch(ref batch, value.Items[i]))
                {
                    return false;
                }
            }
            return true;
        }

        // EmptyAMaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // EmptyAMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long EmptyAMaxBits = 0;
        public const long EmptyAMaxBytes = 0;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroEmptyA(EmptyA value)
        {
            _ = value; // empty body — nothing to reset (SPEC §4.6)
        }

        public static bool WriteEmptyA(WriteStream stream, EmptyA value)
        {
            // empty body — presence is the payload (SPEC §4.6)
            return true;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteEmptyABatch(ref WriteBatch batch, EmptyA value)
        {
            // empty body — presence is the payload (SPEC §4.6)
            return true;
        }

        public static bool ReadEmptyA(ReadStream stream, EmptyA value)
        {
            return true;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadEmptyABatch(ref ReadBatch batch, EmptyA value)
        {
            return true;
        }

        // EmptyBMaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // EmptyBMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long EmptyBMaxBits = 0;
        public const long EmptyBMaxBytes = 0;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroEmptyB(EmptyB value)
        {
            _ = value; // empty body — nothing to reset (SPEC §4.6)
        }

        public static bool WriteEmptyB(WriteStream stream, EmptyB value)
        {
            // empty body — presence is the payload (SPEC §4.6)
            return true;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteEmptyBBatch(ref WriteBatch batch, EmptyB value)
        {
            // empty body — presence is the payload (SPEC §4.6)
            return true;
        }

        public static bool ReadEmptyB(ReadStream stream, EmptyB value)
        {
            return true;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadEmptyBBatch(ref ReadBatch batch, EmptyB value)
        {
            return true;
        }

        // EmptyUnionMaxBits is the tag plus the largest arm; None costs the tag only (SPEC §4.8).
        // EmptyUnionMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long EmptyUnionMaxBits = 2;
        public const long EmptyUnionMaxBytes = 8;

        // ZeroEmptyUnion resets value to the §5 zero form — the empty union. The tag alone
        // resets: unselected arms are unspecified by rule (SPEC §4.8), and every arm
        // is unselected at None; an arm re-zeroes at its next selection.
        public static void ZeroEmptyUnion(EmptyUnion value)
        {
            value.Type = EmptyUnionType.None;
        }

        public static bool WriteEmptyUnion(WriteStream stream, EmptyUnion value)
        {
            uint tagValue = (uint)value.Type;
            if (tagValue > 2) // the tag validates BEFORE it rides (SPEC §4.8)
            {
                return false;
            }
            if (!stream.SerializeBits(ref tagValue, 2))
            {
                return false;
            }
            switch (value.Type)
            {
                case EmptyUnionType.A:
                    return WriteEmptyA(stream, value.A);
                case EmptyUnionType.B:
                    return WriteEmptyB(stream, value.B);
            }
            return true; // None — the tag is the whole wire (SPEC §4.8)
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteEmptyUnionBatch(ref WriteBatch batch, EmptyUnion value)
        {
            uint tagValue = (uint)value.Type;
            if (tagValue > 2) // the tag validates BEFORE it rides (SPEC §4.8)
            {
                return false;
            }
            if (!batch.SerializeBits(ref tagValue, 2))
            {
                return false;
            }
            switch (value.Type)
            {
                case EmptyUnionType.A:
                    return WriteEmptyABatch(ref batch, value.A);
                case EmptyUnionType.B:
                    return WriteEmptyBBatch(ref batch, value.B);
            }
            return true; // None — the tag is the whole wire (SPEC §4.8)
        }

        public static bool ReadEmptyUnion(ReadStream stream, EmptyUnion value)
        {
            int tagValue = 0;
            if (!stream.SerializeInt(ref tagValue, 0, 2)) // rejects a tag above the count (SPEC §4.8)
            {
                return false;
            }
            value.Type = (EmptyUnionType)tagValue;
            switch (value.Type)
            {
                case EmptyUnionType.A:
                    ZeroEmptyA(value.A); // the selected arm starts from the zero form (SPEC §5)
                    return ReadEmptyA(stream, value.A);
                case EmptyUnionType.B:
                    ZeroEmptyB(value.B); // the selected arm starts from the zero form (SPEC §5)
                    return ReadEmptyB(stream, value.B);
            }
            return true; // None
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadEmptyUnionBatch(ref ReadBatch batch, EmptyUnion value)
        {
            int tagValue = 0;
            if (!batch.SerializeInt(ref tagValue, 0, 2)) // rejects a tag above the count (SPEC §4.8)
            {
                return false;
            }
            value.Type = (EmptyUnionType)tagValue;
            switch (value.Type)
            {
                case EmptyUnionType.A:
                    ZeroEmptyA(value.A); // the selected arm starts from the zero form (SPEC §5)
                    return ReadEmptyABatch(ref batch, value.A);
                case EmptyUnionType.B:
                    ZeroEmptyB(value.B); // the selected arm starts from the zero form (SPEC §5)
                    return ReadEmptyBBatch(ref batch, value.B);
            }
            return true; // None
        }

        // HoldsEmptyUnionMaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // HoldsEmptyUnionMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long HoldsEmptyUnionMaxBits = 14;
        public const long HoldsEmptyUnionMaxBytes = 8;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroHoldsEmptyUnion(HoldsEmptyUnion value)
        {
            value.Lead = 0;
            ZeroEmptyUnion(value.U);
            value.Tail = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteHoldsEmptyUnion(WriteStream stream, HoldsEmptyUnion value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteHoldsEmptyUnionBatch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteHoldsEmptyUnionBatch(ref WriteBatch batch, HoldsEmptyUnion value)
        {
            if (!batch.SerializeBits(ref value.Lead, 5))
            {
                return false;
            }
            if (!WriteEmptyUnionBatch(ref batch, value.U))
            {
                return false;
            }
            if (!batch.SerializeBits(ref value.Tail, 7))
            {
                return false;
            }
            return true;
        }

        public static bool ReadHoldsEmptyUnion(ReadStream stream, HoldsEmptyUnion value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadHoldsEmptyUnionBatch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadHoldsEmptyUnionBatch(ref ReadBatch batch, HoldsEmptyUnion value)
        {
            if (!batch.SerializeBits(ref value.Lead, 5))
            {
                return false;
            }
            if (!ReadEmptyUnionBatch(ref batch, value.U))
            {
                return false;
            }
            if (!batch.SerializeBits(ref value.Tail, 7))
            {
                return false;
            }
            return true;
        }

        // StrsMaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // StrsMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long StrsMaxBits = 158;
        public const long StrsMaxBytes = 24;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroStrs(Strs value)
        {
            value.Lead = 0;
            Array.Clear(value.S, 0, 8);
            value.SLength = 0;
            Array.Clear(value.B, 0, 8);
            value.BLength = 0;
            value.Tail = 0;
        }

        public static bool WriteStrs(WriteStream stream, Strs value)
        {
            if (!stream.SerializeBits(ref value.Lead, 5))
            {
                return false;
            }
            if (value.SLength < 0 || value.SLength > 8) // the length guards the slice (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.SLength);
                if (!stream.SerializeBits(ref offsetValue, 4))
                {
                    return false;
                }
            }
            if (!stream.SerializeBytes(value.S.AsSpan(0, value.SLength)))
            {
                return false;
            }
            if (value.BLength < 0 || value.BLength > 8) // the length guards the slice (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.BLength);
                if (!stream.SerializeBits(ref offsetValue, 4))
                {
                    return false;
                }
            }
            if (!stream.SerializeBytes(value.B.AsSpan(0, value.BLength)))
            {
                return false;
            }
            if (!stream.SerializeBits(ref value.Tail, 3))
            {
                return false;
            }
            return true;
        }

        public static bool ReadStrs(ReadStream stream, Strs value)
        {
            if (!stream.SerializeBits(ref value.Lead, 5))
            {
                return false;
            }
            if (!stream.SerializeInt(ref value.SLength, 0, 8)) // the length guards the slice (§6.3)
            {
                return false;
            }
            if (!stream.SerializeBytes(value.S.AsSpan(0, value.SLength)))
            {
                return false;
            }
            for (int i = 0; i < value.SLength; i++)
            {
                if (value.S[i] == 0) // an interior null is content the read refuses (SPEC §4.7)
                {
                    return false;
                }
            }
            if (!stream.SerializeInt(ref value.BLength, 0, 8)) // the length guards the slice (§6.3)
            {
                return false;
            }
            if (!stream.SerializeBytes(value.B.AsSpan(0, value.BLength)))
            {
                return false;
            }
            if (!stream.SerializeBits(ref value.Tail, 3))
            {
                return false;
            }
            return true;
        }

        // ArrNestedMaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // ArrNestedMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long ArrNestedMaxBits = 55;
        public const long ArrNestedMaxBytes = 8;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroArrNested(ArrNested value)
        {
            value.Lead = 0;
            for (int i = 0; i < 4; i++)
            {
                ZeroEleven(value.Items[i]);
            }
            value.ItemsCount = 0;
            value.Tail = 0;
        }

        // batch form: stream state stays in registers across the body and End
        // publishes it — same wire bytes, same validation, same error model.
        public static bool WriteArrNested(WriteStream stream, ArrNested value)
        {
            WriteBatch batch = stream.BeginBatch();
            bool result = WriteArrNestedBatch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WriteArrNestedBatch(ref WriteBatch batch, ArrNested value)
        {
            if (!batch.SerializeBits(ref value.Lead, 5))
            {
                return false;
            }
            if (value.ItemsCount < 0 || value.ItemsCount > 4) // the count guards the loop (§6.3); out-of-contract writes are refused
            {
                return false;
            }
            {
                uint offsetValue = (uint)(value.ItemsCount);
                if (!batch.SerializeBits(ref offsetValue, 3))
                {
                    return false;
                }
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (!WriteElevenBatch(ref batch, value.Items[i]))
                {
                    return false;
                }
            }
            if (!batch.SerializeBits(ref value.Tail, 3))
            {
                return false;
            }
            return true;
        }

        public static bool ReadArrNested(ReadStream stream, ArrNested value)
        {
            ReadBatch batch = stream.BeginBatch();
            bool result = ReadArrNestedBatch(ref batch, value);
            batch.End();
            return result;
        }

        // inline-only batch core — a real call would address-expose the batch
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool ReadArrNestedBatch(ref ReadBatch batch, ArrNested value)
        {
            if (!batch.SerializeBits(ref value.Lead, 5))
            {
                return false;
            }
            if (!batch.SerializeInt(ref value.ItemsCount, 0, 4)) // the count guards the loop (§6.3)
            {
                return false;
            }
            for (int i = 0; i < value.ItemsCount; i++)
            {
                if (!ReadElevenBatch(ref batch, value.Items[i]))
                {
                    return false;
                }
            }
            if (!batch.SerializeBits(ref value.Tail, 3))
            {
                return false;
            }
            return true;
        }

        // SoleMaxBits is the longest wire path; align pads at worst case (SPEC §6.1).
        // SoleMaxBytes is rounded up to the 8-byte write-buffer granularity.
        public const long SoleMaxBits = 13;
        public const long SoleMaxBytes = 8;

        // The §5 zero form: all-zero storage; specified defaults live only in construction.
        public static void ZeroSole(Sole value)
        {
            value.Only = 0;
        }

        public static bool WriteSole(WriteStream stream, Sole value)
        {
            if (!stream.SerializeBits(ref value.Only, 13))
            {
                return false;
            }
            return true;
        }

        public static bool ReadSole(ReadStream stream, Sole value)
        {
            if (!stream.SerializeBits(ref value.Only, 13))
            {
                return false;
            }
            return true;
        }
    }

}
