// Code generated by the schema compiler from Frame.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package blockhome — the TABLE wire (SPEC-TABLES.md): evolution-tolerant, neutral
// bytes, no serialize dependency. Tables version by field id, never by the
// unit's protocol id.

using System;

namespace Blockhome
{

    // table PartRow — TABLE-wire storage: public fields, every buffer allocated at
    // construction, declared defaults in the field initializers (SPEC-TABLES.md)
    public sealed class PartRow
    {
        public ArmorConfig Armor = new ArmorConfig();
        public GunnerSettings Gunner = new GunnerSettings();
        public uint PartId;
        public byte Slot;
    }

    // table PartFrame — TABLE-wire storage: public fields, every buffer allocated at
    // construction, declared defaults in the field initializers (SPEC-TABLES.md)
    public sealed class PartFrame
    {
        public ulong Version;
        public PartRow[] Parts = new PartRow[32]; // used count beside it; count in [0, 32]
        public int PartsCount;

        public PartFrame()
        {
            for (int i = 0; i < Parts.Length; i++)
            {
                Parts[i] = new PartRow();
            }
        }
    }

    // Schema carries every generated function of the unit — C# has no
    // namespace-level functions, so the static class is their home; partial,
    // one slice per generated file.
    public static partial class Schema
    {
        // TableReset(PartRow) restores PartRow's declared defaults in place, reusing every
        // buffer the value already owns. The reader calls it before overlaying.
        public static void TableReset(PartRow value)
        {
            TableReset(value.Armor);
            TableReset(value.Gunner);
            value.PartId = 0;
            value.Slot = 0;
        }

        public static long PartRowMeasure(PartRow value)
        {
            long bytes = 2; // terminator
            {
                long body = ArmorConfigMeasure(value.Armor);
                if (body < 0) { return -1; }
                if (body > 2) { bytes += 3 + 4 + body; } // armor: all-default nested elides
            }
            {
                long body = GunnerSettingsMeasure(value.Gunner);
                if (body < 0) { return -1; }
                if (body > 2) { bytes += 3 + 4 + body; } // gunner: all-default nested elides
            }
            if (value.PartId != 0) { bytes += 3 + 4; } // part_id
            if (value.Slot != 0) { bytes += 3 + 1; } // slot
            return bytes;
        }

        public static bool PartRowSaveBody(ref TableWriter w, PartRow value)
        {
            {
                long body = ArmorConfigMeasure(value.Armor);
                if (body < 0) { return false; } // storage invariant, refused as measure refuses it
                if (body > 2) // all-default nested elides
                {
                    w.Put16(0x7c9d); w.Put8(13); // armor
                    w.Put32((uint)body);
                    if (!ArmorConfigSaveBody(ref w, value.Armor)) { return false; }
                }
            }
            {
                long body = GunnerSettingsMeasure(value.Gunner);
                if (body < 0) { return false; } // storage invariant, refused as measure refuses it
                if (body > 2) // all-default nested elides
                {
                    w.Put16(0x2bc9); w.Put8(13); // gunner
                    w.Put32((uint)body);
                    if (!GunnerSettingsSaveBody(ref w, value.Gunner)) { return false; }
                }
            }
            if (value.PartId != 0)
            {
                w.Put16(0x6deb); w.Put8(8); // part_id
                w.Put32(unchecked((uint)(value.PartId)));
            }
            if (value.Slot != 0)
            {
                w.Put16(0x37e4); w.Put8(6); // slot
                w.Put8(unchecked((byte)(value.Slot)));
            }
            w.Put16(0); // terminator
            return !w.Overflow;
        }

        public static long PartRowSave(PartRow value, Span<byte> buffer)
        {
            TableWriter w = new TableWriter(buffer);
            if (!PartRowSaveBody(ref w, value)) { return -1; }
            return w.Offset; // == PartRowMeasure(value)
        }

        public static bool PartRowLoadBody(ref TableReader r, PartRow value)
        {
            TableReset(value); // restore declared defaults in place, then overlay
            for (;;)
            {
                if (!r.Has(2)) { r.Report.Malformed = true; return false; }
                ushort fieldId = r.Get16();
                if (fieldId == 0) { return true; }
                if (!r.Has(1)) { r.Report.Malformed = true; return false; }
                byte kind = r.Get8();
                switch (fieldId)
                {
                    case 0x7c9d: // armor
                    {
                        if (kind != 13)
                        {
                            r.Report.KindMismatch++;
                            if (!r.Skip(kind)) { r.Report.Malformed = true; return false; }
                            break;
                        }
                        if (!r.Has(4)) { r.Report.Malformed = true; return false; }
                        uint bodyLen = r.Get32();
                        if (!r.Has(bodyLen)) { r.Report.Malformed = true; return false; }
                        {
                            TableReader sub = new TableReader(r.Buffer.Slice(r.Offset, (int)bodyLen), r.Report);
                            ArmorConfigLoadBody(ref sub, value.Armor);
                        }
                        r.Offset += (int)bodyLen;
                        break;
                    }
                    case 0x2bc9: // gunner
                    {
                        if (kind != 13)
                        {
                            r.Report.KindMismatch++;
                            if (!r.Skip(kind)) { r.Report.Malformed = true; return false; }
                            break;
                        }
                        if (!r.Has(4)) { r.Report.Malformed = true; return false; }
                        uint bodyLen = r.Get32();
                        if (!r.Has(bodyLen)) { r.Report.Malformed = true; return false; }
                        {
                            TableReader sub = new TableReader(r.Buffer.Slice(r.Offset, (int)bodyLen), r.Report);
                            GunnerSettingsLoadBody(ref sub, value.Gunner);
                        }
                        r.Offset += (int)bodyLen;
                        break;
                    }
                    case 0x6deb: // part_id
                    {
                        if (kind != 8)
                        {
                            r.Report.KindMismatch++;
                            if (!r.Skip(kind)) { r.Report.Malformed = true; return false; }
                            break;
                        }
                        if (!r.Has(4)) { r.Report.Malformed = true; return false; }
                        {
                            uint decodedV = unchecked((uint)r.Get32());
                            value.PartId = decodedV;
                        }
                        break;
                    }
                    case 0x37e4: // slot
                    {
                        if (kind != 6)
                        {
                            r.Report.KindMismatch++;
                            if (!r.Skip(kind)) { r.Report.Malformed = true; return false; }
                            break;
                        }
                        if (!r.Has(1)) { r.Report.Malformed = true; return false; }
                        {
                            byte decodedV = unchecked((byte)r.Get8());
                            value.Slot = decodedV;
                        }
                        break;
                    }
                    default:
                    {
                        r.Report.Unknown++;
                        if (!r.Skip(kind)) { r.Report.Malformed = true; return false; }
                        break;
                    }
                }
            }
        }

        public static bool PartRowLoad(PartRow value, ReadOnlySpan<byte> bytes, TableReport report)
        {
            TableReader r = new TableReader(bytes, report != null ? report : new TableReport());
            return PartRowLoadBody(ref r, value);
        }

        // TableReset(PartFrame) restores PartFrame's declared defaults in place, reusing every
        // buffer the value already owns. The reader calls it before overlaying.
        public static void TableReset(PartFrame value)
        {
            value.Version = 0;
            for (int i = 0; i < value.Parts.Length; i++)
            {
                TableReset(value.Parts[i]);
            }
            value.PartsCount = 0;
        }

        public static long PartFrameMeasure(PartFrame value)
        {
            long bytes = 2; // terminator
            if (value.Version != 0) { bytes += 3 + 8; } // version
            if (value.PartsCount < 0 || value.PartsCount > 32) { return -1; } // storage invariant
            if (value.PartsCount > 0)
            {
                bytes += 3 + 4 + 5; // parts
                for (int i = 0; i < value.PartsCount; i++)
                {
                    long elem = PartRowMeasure(value.Parts[i]);
                    if (elem < 0) { return -1; }
                    bytes += 4 + elem;
                }
            }
            return bytes;
        }

        public static bool PartFrameSaveBody(ref TableWriter w, PartFrame value)
        {
            if (value.Version != 0)
            {
                w.Put16(0xe8e6); w.Put8(9); // version
                w.Put64(unchecked((ulong)(value.Version)));
            }
            if (value.PartsCount < 0 || value.PartsCount > 32) { return false; } // storage invariant
            if (value.PartsCount > 0)
            {
                w.Put16(0xfc18); w.Put8(14); // parts
                int lenAt = w.Offset; w.Put32(0);
                w.Put8(13); w.Put32((uint)value.PartsCount);
                for (int i = 0; i < value.PartsCount; i++)
                {
                    {
                        int elemLenAt = w.Offset; w.Put32(0);
                        if (!PartRowSaveBody(ref w, value.Parts[i])) { return false; }
                        w.Patch32(elemLenAt, (uint)(w.Offset - elemLenAt - 4));
                    }
                }
                w.Patch32(lenAt, (uint)(w.Offset - lenAt - 4));
            }
            w.Put16(0); // terminator
            return !w.Overflow;
        }

        public static long PartFrameSave(PartFrame value, Span<byte> buffer)
        {
            TableWriter w = new TableWriter(buffer);
            if (!PartFrameSaveBody(ref w, value)) { return -1; }
            return w.Offset; // == PartFrameMeasure(value)
        }

        public static bool PartFrameLoadBody(ref TableReader r, PartFrame value)
        {
            TableReset(value); // restore declared defaults in place, then overlay
            for (;;)
            {
                if (!r.Has(2)) { r.Report.Malformed = true; return false; }
                ushort fieldId = r.Get16();
                if (fieldId == 0) { return true; }
                if (!r.Has(1)) { r.Report.Malformed = true; return false; }
                byte kind = r.Get8();
                switch (fieldId)
                {
                    case 0xe8e6: // version
                    {
                        if (kind != 9)
                        {
                            r.Report.KindMismatch++;
                            if (!r.Skip(kind)) { r.Report.Malformed = true; return false; }
                            break;
                        }
                        if (!r.Has(8)) { r.Report.Malformed = true; return false; }
                        {
                            ulong decodedV = unchecked((ulong)r.Get64());
                            value.Version = decodedV;
                        }
                        break;
                    }
                    case 0xfc18: // parts
                    {
                        if (kind != 14)
                        {
                            r.Report.KindMismatch++;
                            if (!r.Skip(kind)) { r.Report.Malformed = true; return false; }
                            break;
                        }
                        if (!r.Has(4)) { r.Report.Malformed = true; return false; }
                        uint bodyLen = r.Get32();
                        if (!r.Has(bodyLen)) { r.Report.Malformed = true; return false; }
                        int bodyEnd = r.Offset + (int)bodyLen;
                        if (bodyLen >= 5)
                        {
                            byte elemKind = r.Get8();
                            uint count = r.Get32();
                            if (elemKind != 13) { r.Report.KindMismatch++; r.Offset = bodyEnd; break; }
                            uint keep = count;
                            if (keep > 32) { keep = 32; r.Report.Clamped++; }
                            // elements are BOUNDED by the field body: a count the length
                            // cannot cover keeps the decoded prefix, flags malformed, and
                            // the parent continues at the next field — following fields'
                            // bytes are never fabricated into elements
                            TableReader sub = new TableReader(r.Buffer.Slice(r.Offset, bodyEnd - r.Offset), r.Report);
                            uint decoded = 0;
                            for (uint i = 0; i < keep; i++)
                            {
                                if (!sub.Has(4)) { r.Report.Malformed = true; break; }
                                uint elemLen = sub.Get32();
                                if (!sub.Has(elemLen)) { r.Report.Malformed = true; break; }
                                {
                                    TableReader elem = new TableReader(sub.Buffer.Slice(sub.Offset, (int)elemLen), r.Report);
                                    PartRowLoadBody(ref elem, value.Parts[i]);
                                }
                                sub.Offset += (int)elemLen;
                                decoded = i + 1;
                            }
                            value.PartsCount = (int)decoded;
                        }
                        r.Offset = bodyEnd; // excess elements and slack skip via the length
                        break;
                    }
                    default:
                    {
                        r.Report.Unknown++;
                        if (!r.Skip(kind)) { r.Report.Malformed = true; return false; }
                        break;
                    }
                }
            }
        }

        public static bool PartFrameLoad(PartFrame value, ReadOnlySpan<byte> bytes, TableReport report)
        {
            TableReader r = new TableReader(bytes, report != null ? report : new TableReport());
            return PartFrameLoadBody(ref r, value);
        }

        // ---- reflection descriptors (tables only, SPEC-TABLES.md §8) ----

        private static TableTypeInfo PartRowTableInfo;
        public static TableTypeInfo PartRowTableType()
        {
            TableTypeInfo info = PartRowTableInfo;
            if (info != null) { return info; }
            info = new TableTypeInfo();
            info.Name = "PartRow";
            info.NumFields = 4;
            info.Fields = new TableFieldInfo[]
            {
                new TableFieldInfo { Name = "armor", TypeName = "ArmorConfig", Id = 0x7c9d, Kind = 13, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "", TableRef = delegate { return ArmorConfigTableType(); } },
                new TableFieldInfo { Name = "gunner", TypeName = "GunnerSettings", Id = 0x2bc9, Kind = 13, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "", TableRef = delegate { return GunnerSettingsTableType(); } },
                new TableFieldInfo { Name = "part_id", TypeName = "uint32", Id = 0x6deb, Kind = 8, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "", TableRef = null },
                new TableFieldInfo { Name = "slot", TypeName = "uint8", Id = 0x37e4, Kind = 6, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "", TableRef = null },
            };
            PartRowTableInfo = info;
            return info;
        }

        private static TableTypeInfo PartFrameTableInfo;
        public static TableTypeInfo PartFrameTableType()
        {
            TableTypeInfo info = PartFrameTableInfo;
            if (info != null) { return info; }
            info = new TableTypeInfo();
            info.Name = "PartFrame";
            info.NumFields = 2;
            info.Fields = new TableFieldInfo[]
            {
                new TableFieldInfo { Name = "version", TypeName = "uint64", Id = 0xe8e6, Kind = 9, IsArray = false, Counted = false, Optional = false, ArrayBound = 0, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "", TableRef = null },
                new TableFieldInfo { Name = "parts", TypeName = "PartRow", Id = 0xfc18, Kind = 13, IsArray = true, Counted = true, Optional = false, ArrayBound = 32, HasRange = false, RangeMin = 0.0, RangeMax = 0.0, EnumMax = -1, EnumName = null, VariantId = null, KeyTypeName = null, KeyName = null, KeyId = null, Guard = "", TableRef = delegate { return PartRowTableType(); } },
            };
            PartFrameTableInfo = info;
            return info;
        }
    }

}
