// Generated by the schema compiler from Wire.schema. DO NOT EDIT.
// SPDX-License-Identifier: NONE — this generated output is yours, under terms of
// your choice. See the LICENSE exception in the schema compiler; the compiler is
// AGPL-3.0, its output is not.
// package example — protocol id 0x311b2f6c84685619
// The TABLE wire (evolution-tolerant, notes/table-wire.md).

#![allow(clippy::needless_range_loop)]

use crate::*;

/// Returns `value`'s table-wire encoding in a fresh buffer.
pub fn table_write_probe_sample(value: &ProbeSample) -> Vec<u8> {
    append_table_probe_sample(Vec::new(), value)
}

/// Appends `value`'s table-wire encoding to `dst` and returns the extended
/// buffer — the zero-allocation write path: hand it a buffer you reuse
/// (`v.clear()` then pass `v`) and steady-state writes never touch the heap.
pub fn append_table_probe_sample(dst: Vec<u8>, value: &ProbeSample) -> Vec<u8> {
    let mut w = TableWriter { buf: dst };
    table_write_probe_sample_into(&mut w, value);
    w.buf
}

fn table_write_probe_sample_into(w: &mut TableWriter, value: &ProbeSample) {
    if value.active != true {
        w.u16(0x405a); // active
        w.u8(1);
        w.u8(if value.active { 1 } else { 0 });
    }
    if value.orientation != 0.0 {
        w.u16(0x7964); // orientation
        w.u8(10);
        w.u32(f32::to_bits(value.orientation));
    }
    if value.raw_delta != 0 {
        w.u16(0x933d); // raw_delta
        w.u8(4);
        w.u32(value.raw_delta as u32);
    }
    if value.big_delta != 0 {
        w.u16(0x078b); // big_delta
        w.u8(5);
        w.u64(value.big_delta as u64);
    }
    if value.active {
        if value.weapon != Weapon::NONE {
            w.u16(0x4f72); // weapon
            w.u8(6);
            w.u8(value.weapon.0 as u8);
        }
    }
    if value.active {
        if value.has_target != false {
            w.u16(0xb0a7); // has_target
            w.u8(1);
            w.u8(if value.has_target { 1 } else { 0 });
        }
    }
    if value.active && value.has_target {
        if value.target_id != 0 {
            w.u16(0xdf6a); // target_id
            w.u8(7);
            w.u16(value.target_id as u16);
        }
    }
    if !value.active {
        if value.idle_ticks != 0 {
            w.u16(0x9555); // idle_ticks
            w.u8(8);
            w.u32(value.idle_ticks as u32);
        }
    }
    if value.samples_count > 0 {
        w.u16(0xaf9a); // samples
        w.u8(14);
        let len_at = w.buf.len();
        w.u32(0);
        w.u8(7);
        w.u16(value.samples_count as u16);
        for i in 0..value.samples_count as usize {
            w.u16(value.samples[i] as u16);
        }
        let body = (w.buf.len() - len_at - 4) as u32;
        w.patch32(len_at, body);
    }
    w.u16(0); // terminator
}

/// Decodes a table-wire buffer under the permissive contract: declared
/// defaults prefill, known fields overlay, unknown ids and kind mismatches
/// skip and count, out-of-range values clamp and count. `false` means
/// malformed — the partial decode up to that point is kept.
pub fn table_read_probe_sample(data: &[u8], value: &mut ProbeSample, report: &mut TableReport) -> bool {
    let mut r = TableReader { buf: data, off: 0 };
    table_read_probe_sample_from(&mut r, value, report)
}

fn table_read_probe_sample_from(r: &mut TableReader, value: &mut ProbeSample, report: &mut TableReport) -> bool {
    *value = ProbeSample::new(); // prefill declared defaults, then overlay
    loop {
        if !r.has(2) { report.malformed = true; return false; }
        let field_id = r.get16();
        if field_id == 0 { return true; }
        if !r.has(1) { report.malformed = true; return false; }
        let kind = r.get8();
        match field_id {
            0x405a => { // active
                if kind != 1 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    value.active = r.get8() != 0;
                }
            }
            0x7964 => { // orientation
                if kind != 10 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = f32::from_bits(r.get32());
                    let mut v = raw;
                    if v < -180 as f32 { v = -180 as f32; report.clamped += 1; }
                    if v > 180 as f32 { v = 180 as f32; report.clamped += 1; }
                    value.orientation = v;
                }
            }
            0x933d => { // raw_delta
                if kind != 4 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = r.get32() as i32;
                    value.raw_delta = raw as i32;
                }
            }
            0x078b => { // big_delta
                if kind != 5 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(8) { report.malformed = true; return false; }
                    let raw = r.get64() as i64;
                    value.big_delta = raw as i64;
                }
            }
            0x4f72 => { // weapon
                if kind != 6 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    let raw = r.get8();
                    let mut v = raw;
                    if v as u64 > 15 { v = 0; report.clamped += 1; }
                    value.weapon = Weapon(v as u8);
                }
            }
            0xb0a7 => { // has_target
                if kind != 1 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    value.has_target = r.get8() != 0;
                }
            }
            0xdf6a => { // target_id
                if kind != 7 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(2) { report.malformed = true; return false; }
                    let raw = r.get16();
                    value.target_id = raw as u16;
                }
            }
            0x9555 => { // idle_ticks
                if kind != 8 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = r.get32();
                    value.idle_ticks = raw as u32;
                }
            }
            0xaf9a => { // samples
                if kind != 14 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let body_len = r.get32() as usize;
                    if !r.has(body_len) { report.malformed = true; return false; }
                    let body_end = r.off + body_len;
                    if body_len >= 3 {
                        let elem_kind = r.get8();
                        let count = r.get16() as usize;
                        if elem_kind != 7 {
                            report.kind_mismatch += 1;
                        } else {
                            let mut keep = count;
                            if keep > 8 { keep = 8; report.clamped += 1; }
                            for i in 0..keep {
                                if !r.has(2) { report.malformed = true; return false; }
                                let raw = r.get16();
                                value.samples[i] = raw as u16;
                            }
                            value.samples_count = keep as i32;
                        }
                    }
                    r.off = body_end; // excess elements and slack skip via the length
                }
            }
            _ => {
                report.unknown += 1;
                if !r.skip(kind) { report.malformed = true; return false; }
            }
        }
    }
}

/// Returns `value`'s table-wire encoding in a fresh buffer.
pub fn table_write_probe_config(value: &ProbeConfig) -> Vec<u8> {
    append_table_probe_config(Vec::new(), value)
}

/// Appends `value`'s table-wire encoding to `dst` and returns the extended
/// buffer — the zero-allocation write path: hand it a buffer you reuse
/// (`v.clear()` then pass `v`) and steady-state writes never touch the heap.
pub fn append_table_probe_config(dst: Vec<u8>, value: &ProbeConfig) -> Vec<u8> {
    let mut w = TableWriter { buf: dst };
    table_write_probe_config_into(&mut w, value);
    w.buf
}

fn table_write_probe_config_into(w: &mut TableWriter, value: &ProbeConfig) {
    if value.retries != -1 {
        w.u16(0x460c); // retries
        w.u8(4);
        w.u32(value.retries as u32);
    }
    if value.preferred != Weapon::RAILGUN {
        w.u16(0x3982); // preferred
        w.u8(6);
        w.u8(value.preferred.0 as u8);
    }
    w.u16(0); // terminator
}

/// Decodes a table-wire buffer under the permissive contract: declared
/// defaults prefill, known fields overlay, unknown ids and kind mismatches
/// skip and count, out-of-range values clamp and count. `false` means
/// malformed — the partial decode up to that point is kept.
pub fn table_read_probe_config(data: &[u8], value: &mut ProbeConfig, report: &mut TableReport) -> bool {
    let mut r = TableReader { buf: data, off: 0 };
    table_read_probe_config_from(&mut r, value, report)
}

fn table_read_probe_config_from(r: &mut TableReader, value: &mut ProbeConfig, report: &mut TableReport) -> bool {
    *value = ProbeConfig::new(); // prefill declared defaults, then overlay
    loop {
        if !r.has(2) { report.malformed = true; return false; }
        let field_id = r.get16();
        if field_id == 0 { return true; }
        if !r.has(1) { report.malformed = true; return false; }
        let kind = r.get8();
        match field_id {
            0x460c => { // retries
                if kind != 4 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = r.get32() as i32;
                    value.retries = raw as i32;
                }
            }
            0x3982 => { // preferred
                if kind != 6 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    let raw = r.get8();
                    let mut v = raw;
                    if v as u64 > 15 { v = 0; report.clamped += 1; }
                    value.preferred = Weapon(v as u8);
                }
            }
            _ => {
                report.unknown += 1;
                if !r.skip(kind) { report.malformed = true; return false; }
            }
        }
    }
}

/// Returns `value`'s table-wire encoding in a fresh buffer.
pub fn table_write_probe_array(value: &ProbeArray) -> Vec<u8> {
    append_table_probe_array(Vec::new(), value)
}

/// Appends `value`'s table-wire encoding to `dst` and returns the extended
/// buffer — the zero-allocation write path: hand it a buffer you reuse
/// (`v.clear()` then pass `v`) and steady-state writes never touch the heap.
pub fn append_table_probe_array(dst: Vec<u8>, value: &ProbeArray) -> Vec<u8> {
    let mut w = TableWriter { buf: dst };
    table_write_probe_array_into(&mut w, value);
    w.buf
}

fn table_write_probe_array_into(w: &mut TableWriter, value: &ProbeArray) {
    {
        w.u16(0xaf9a); // samples (fixed [2])
        w.u8(14);
        let len_at = w.buf.len();
        w.u32(0);
        w.u8(13);
        w.u16(2);
        for i in 0..2 {
            {
                let len_at = w.buf.len();
                w.u32(0);
                table_write_probe_sample_into(w, &value.samples[i]);
                let body = (w.buf.len() - len_at - 4) as u32;
                w.patch32(len_at, body);
            }
        }
        let body = (w.buf.len() - len_at - 4) as u32;
        w.patch32(len_at, body);
    }
    {
        let field_at = w.buf.len();
        w.u16(0x4538); // config
        w.u8(13);
        let len_at = w.buf.len();
        w.u32(0);
        table_write_probe_config_into(w, &value.config);
        if w.buf.len() - len_at - 4 <= 2 {
            w.buf.truncate(field_at); // all-default nested elides
        } else {
            let body = (w.buf.len() - len_at - 4) as u32;
            w.patch32(len_at, body);
        }
    }
    w.u16(0); // terminator
}

/// Decodes a table-wire buffer under the permissive contract: declared
/// defaults prefill, known fields overlay, unknown ids and kind mismatches
/// skip and count, out-of-range values clamp and count. `false` means
/// malformed — the partial decode up to that point is kept.
pub fn table_read_probe_array(data: &[u8], value: &mut ProbeArray, report: &mut TableReport) -> bool {
    let mut r = TableReader { buf: data, off: 0 };
    table_read_probe_array_from(&mut r, value, report)
}

fn table_read_probe_array_from(r: &mut TableReader, value: &mut ProbeArray, report: &mut TableReport) -> bool {
    *value = ProbeArray::new(); // prefill declared defaults, then overlay
    loop {
        if !r.has(2) { report.malformed = true; return false; }
        let field_id = r.get16();
        if field_id == 0 { return true; }
        if !r.has(1) { report.malformed = true; return false; }
        let kind = r.get8();
        match field_id {
            0xaf9a => { // samples
                if kind != 14 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let body_len = r.get32() as usize;
                    if !r.has(body_len) { report.malformed = true; return false; }
                    let body_end = r.off + body_len;
                    if body_len >= 3 {
                        let elem_kind = r.get8();
                        let count = r.get16() as usize;
                        if elem_kind != 13 {
                            report.kind_mismatch += 1;
                        } else {
                            let mut keep = count;
                            if keep > 2 { keep = 2; report.clamped += 1; }
                            for i in 0..keep {
                                if !r.has(4) { report.malformed = true; return false; }
                                let elem_len = r.get32() as usize;
                                if !r.has(elem_len) { report.malformed = true; return false; }
                                {
                                    let mut sub = TableReader { buf: &r.buf[r.off..r.off + elem_len], off: 0 };
                                    table_read_probe_sample_from(&mut sub, &mut value.samples[i], report);
                                }
                                r.off += elem_len;
                            }
                        }
                    }
                    r.off = body_end; // excess elements and slack skip via the length
                }
            }
            0x4538 => { // config
                if kind != 13 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let body_len = r.get32() as usize;
                    if !r.has(body_len) { report.malformed = true; return false; }
                    {
                        let mut sub = TableReader { buf: &r.buf[r.off..r.off + body_len], off: 0 };
                        table_read_probe_config_from(&mut sub, &mut value.config, report);
                    }
                    r.off += body_len;
                }
            }
            _ => {
                report.unknown += 1;
                if !r.skip(kind) { report.malformed = true; return false; }
            }
        }
    }
}

/// Returns `value`'s table-wire encoding in a fresh buffer.
pub fn table_write_test_data(value: &TestData) -> Vec<u8> {
    append_table_test_data(Vec::new(), value)
}

/// Appends `value`'s table-wire encoding to `dst` and returns the extended
/// buffer — the zero-allocation write path: hand it a buffer you reuse
/// (`v.clear()` then pass `v`) and steady-state writes never touch the heap.
pub fn append_table_test_data(dst: Vec<u8>, value: &TestData) -> Vec<u8> {
    let mut w = TableWriter { buf: dst };
    table_write_test_data_into(&mut w, value);
    w.buf
}

fn table_write_test_data_into(w: &mut TableWriter, value: &TestData) {
    if value.a != 0 {
        w.u16(0xcd20); // a
        w.u8(4);
        w.u32(value.a as u32);
    }
    if value.b != 0 {
        w.u16(0xcae9); // b
        w.u8(4);
        w.u32(value.b as u32);
    }
    if value.c != 0 {
        w.u16(0xca5e); // c
        w.u8(4);
        w.u32(value.c as u32);
    }
    if value.d != 0 {
        w.u16(0xc57f); // d
        w.u8(6);
        w.u8(value.d as u8);
    }
    if value.e != 0 {
        w.u16(0xc2ec); // e
        w.u8(6);
        w.u8(value.e as u8);
    }
    if value.f != 0 {
        w.u16(0xc495); // f
        w.u8(6);
        w.u8(value.f as u8);
    }
    if value.g != false {
        w.u16(0xc40a); // g
        w.u8(1);
        w.u8(if value.g { 1 } else { 0 });
    }
    if value.items_count > 0 {
        w.u16(0x09f6); // items
        w.u8(14);
        let len_at = w.buf.len();
        w.u32(0);
        w.u8(4);
        w.u16(value.items_count as u16);
        for i in 0..value.items_count as usize {
            w.u32(value.items[i] as u32);
        }
        let body = (w.buf.len() - len_at - 4) as u32;
        w.patch32(len_at, body);
    }
    if value.float_value != 0.0 {
        w.u16(0xbbaf); // float_value
        w.u8(10);
        w.u32(f32::to_bits(value.float_value));
    }
    if value.compressed_float_value != 0.0 {
        w.u16(0x8aa5); // compressed_float_value
        w.u8(10);
        w.u32(f32::to_bits(value.compressed_float_value));
    }
    if value.double_value != 0.0 {
        w.u16(0x6a50); // double_value
        w.u8(11);
        w.u64(f64::to_bits(value.double_value));
    }
    if value.int8_value != 0 {
        w.u16(0x6592); // int8_value
        w.u8(2);
        w.u8(value.int8_value as u8);
    }
    if value.int16_value != 0 {
        w.u16(0x68f3); // int16_value
        w.u8(3);
        w.u16(value.int16_value as u16);
    }
    if value.uint8_value != 0 {
        w.u16(0x5645); // uint8_value
        w.u8(6);
        w.u8(value.uint8_value as u8);
    }
    if value.uint16_value != 0 {
        w.u16(0xd185); // uint16_value
        w.u8(7);
        w.u16(value.uint16_value as u16);
    }
    if value.uint32_value != 0 {
        w.u16(0x3ba7); // uint32_value
        w.u8(8);
        w.u32(value.uint32_value as u32);
    }
    if value.uint64_value != 0 {
        w.u16(0xc4d6); // uint64_value
        w.u8(9);
        w.u64(value.uint64_value as u64);
    }
    if value.int64_full != 0 {
        w.u16(0xc2b7); // int64_full
        w.u8(5);
        w.u64(value.int64_full as u64);
    }
    if value.int64_range != 0 {
        w.u16(0xab05); // int64_range
        w.u8(5);
        w.u64(value.int64_range as u64);
    }
    {
        let mut all_default = true;
        for i in 0..17 {
            if value.fixed_bytes[i] != 0 { all_default = false; break; }
        }
        if !all_default {
            w.u16(0x14fc); // fixed_bytes (fixed [17])
            w.u8(14);
            let len_at = w.buf.len();
            w.u32(0);
            w.u8(6);
            w.u16(17);
            for i in 0..17 {
                w.u8(value.fixed_bytes[i] as u8);
            }
            let body = (w.buf.len() - len_at - 4) as u32;
            w.patch32(len_at, body);
        }
    }
    if value.text_length > 0 {
        w.u16(0xf3d8); // text
        w.u8(12);
        w.u16(value.text_length as u16);
        w.raw(&value.text[..value.text_length as usize]);
    }
    w.u16(0); // terminator
}

/// Decodes a table-wire buffer under the permissive contract: declared
/// defaults prefill, known fields overlay, unknown ids and kind mismatches
/// skip and count, out-of-range values clamp and count. `false` means
/// malformed — the partial decode up to that point is kept.
pub fn table_read_test_data(data: &[u8], value: &mut TestData, report: &mut TableReport) -> bool {
    let mut r = TableReader { buf: data, off: 0 };
    table_read_test_data_from(&mut r, value, report)
}

fn table_read_test_data_from(r: &mut TableReader, value: &mut TestData, report: &mut TableReport) -> bool {
    *value = TestData::default(); // prefill (all-zero defaults), then overlay
    loop {
        if !r.has(2) { report.malformed = true; return false; }
        let field_id = r.get16();
        if field_id == 0 { return true; }
        if !r.has(1) { report.malformed = true; return false; }
        let kind = r.get8();
        match field_id {
            0xcd20 => { // a
                if kind != 4 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = r.get32() as i32;
                    let mut v = raw;
                    if (v as i128) < -100i128 { v = -100i128 as _; report.clamped += 1; }
                    if (v as i128) > 100i128 { v = 100i128 as _; report.clamped += 1; }
                    value.a = v as i32;
                }
            }
            0xcae9 => { // b
                if kind != 4 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = r.get32() as i32;
                    let mut v = raw;
                    if (v as i128) < -100i128 { v = -100i128 as _; report.clamped += 1; }
                    if (v as i128) > 100i128 { v = 100i128 as _; report.clamped += 1; }
                    value.b = v as i32;
                }
            }
            0xca5e => { // c
                if kind != 4 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = r.get32() as i32;
                    let mut v = raw;
                    if (v as i128) < -100i128 { v = -100i128 as _; report.clamped += 1; }
                    if (v as i128) > 150i128 { v = 150i128 as _; report.clamped += 1; }
                    value.c = v as i32;
                }
            }
            0xc57f => { // d
                if kind != 6 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    let raw = r.get8();
                    value.d = raw as u32;
                }
            }
            0xc2ec => { // e
                if kind != 6 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    let raw = r.get8();
                    value.e = raw as u32;
                }
            }
            0xc495 => { // f
                if kind != 6 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    let raw = r.get8();
                    value.f = raw as u32;
                }
            }
            0xc40a => { // g
                if kind != 1 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    value.g = r.get8() != 0;
                }
            }
            0x09f6 => { // items
                if kind != 14 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let body_len = r.get32() as usize;
                    if !r.has(body_len) { report.malformed = true; return false; }
                    let body_end = r.off + body_len;
                    if body_len >= 3 {
                        let elem_kind = r.get8();
                        let count = r.get16() as usize;
                        if elem_kind != 4 {
                            report.kind_mismatch += 1;
                        } else {
                            let mut keep = count;
                            if keep > 16 { keep = 16; report.clamped += 1; }
                            for i in 0..keep {
                                if !r.has(4) { report.malformed = true; return false; }
                                let raw = r.get32() as i32;
                                let mut v = raw;
                                if (v as i128) < 0i128 { v = 0i128 as _; report.clamped += 1; }
                                if (v as i128) > 255i128 { v = 255i128 as _; report.clamped += 1; }
                                value.items[i] = v as i32;
                            }
                            value.items_count = keep as i32;
                        }
                    }
                    r.off = body_end; // excess elements and slack skip via the length
                }
            }
            0xbbaf => { // float_value
                if kind != 10 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = f32::from_bits(r.get32());
                    value.float_value = raw;
                }
            }
            0x8aa5 => { // compressed_float_value
                if kind != 10 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = f32::from_bits(r.get32());
                    let mut v = raw;
                    if v < 0 as f32 { v = 0 as f32; report.clamped += 1; }
                    if v > 10 as f32 { v = 10 as f32; report.clamped += 1; }
                    value.compressed_float_value = v;
                }
            }
            0x6a50 => { // double_value
                if kind != 11 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(8) { report.malformed = true; return false; }
                    let raw = f64::from_bits(r.get64());
                    value.double_value = raw;
                }
            }
            0x6592 => { // int8_value
                if kind != 2 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    let raw = r.get8() as i8;
                    value.int8_value = raw as i8;
                }
            }
            0x68f3 => { // int16_value
                if kind != 3 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(2) { report.malformed = true; return false; }
                    let raw = r.get16() as i16;
                    value.int16_value = raw as i16;
                }
            }
            0x5645 => { // uint8_value
                if kind != 6 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(1) { report.malformed = true; return false; }
                    let raw = r.get8();
                    value.uint8_value = raw as u8;
                }
            }
            0xd185 => { // uint16_value
                if kind != 7 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(2) { report.malformed = true; return false; }
                    let raw = r.get16();
                    value.uint16_value = raw as u16;
                }
            }
            0x3ba7 => { // uint32_value
                if kind != 8 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let raw = r.get32();
                    value.uint32_value = raw as u32;
                }
            }
            0xc4d6 => { // uint64_value
                if kind != 9 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(8) { report.malformed = true; return false; }
                    let raw = r.get64();
                    value.uint64_value = raw as u64;
                }
            }
            0xc2b7 => { // int64_full
                if kind != 5 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(8) { report.malformed = true; return false; }
                    let raw = r.get64() as i64;
                    value.int64_full = raw as i64;
                }
            }
            0xab05 => { // int64_range
                if kind != 5 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(8) { report.malformed = true; return false; }
                    let raw = r.get64() as i64;
                    let mut v = raw;
                    if (v as i128) < -1000000000000i128 { v = -1000000000000i128 as _; report.clamped += 1; }
                    if (v as i128) > 1000000000000i128 { v = 1000000000000i128 as _; report.clamped += 1; }
                    value.int64_range = v as i64;
                }
            }
            0x14fc => { // fixed_bytes
                if kind != 14 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(4) { report.malformed = true; return false; }
                    let body_len = r.get32() as usize;
                    if !r.has(body_len) { report.malformed = true; return false; }
                    let body_end = r.off + body_len;
                    if body_len >= 3 {
                        let elem_kind = r.get8();
                        let count = r.get16() as usize;
                        if elem_kind != 6 {
                            report.kind_mismatch += 1;
                        } else {
                            let mut keep = count;
                            if keep > 17 { keep = 17; report.clamped += 1; }
                            for i in 0..keep {
                                if !r.has(1) { report.malformed = true; return false; }
                                let raw = r.get8();
                                value.fixed_bytes[i] = raw as u8;
                            }
                        }
                    }
                    r.off = body_end; // excess elements and slack skip via the length
                }
            }
            0xf3d8 => { // text
                if kind != 12 {
                    report.kind_mismatch += 1;
                    if !r.skip(kind) { report.malformed = true; return false; }
                } else {
                    if !r.has(2) { report.malformed = true; return false; }
                    let length = r.get16() as usize;
                    if !r.has(length) { report.malformed = true; return false; }
                    let mut keep = length;
                    if keep > 255 { keep = 255; report.clamped += 1; }
                    value.text[..keep].copy_from_slice(&r.buf[r.off..r.off + keep]);
                    value.text_length = keep as i32;
                    r.off += length;
                }
            }
            _ => {
                report.unknown += 1;
                if !r.skip(kind) { report.malformed = true; return false; }
            }
        }
    }
}

// ---- reflection descriptors (tables only, notes/table-wire.md) ----
//
// Descriptors are 'static data, so table_type_* costs nothing per instance
// and needs no lazy initialization: Rust resolves the cross-type links at
// compile time, which is the one place this is simpler than the C#/Go
// backends, where the same links are wired at startup.

static TABLE_TYPE_PROBE_SAMPLE_FIELDS: &[TableFieldInfo] = &[
    TableFieldInfo {
        name: "active",
        type_name: "bool",
        id: 0x405a,
        kind: 1,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "orientation",
        type_name: "float32",
        id: 0x7964,
        kind: 10,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: true,
        range_min: -180.0,
        range_max: 180.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "raw_delta",
        type_name: "int32",
        id: 0x933d,
        kind: 4,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "big_delta",
        type_name: "int64",
        id: 0x078b,
        kind: 5,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "weapon",
        type_name: "Weapon",
        id: 0x4f72,
        kind: 6,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: 15,
        enum_name: Some(enum_name_weapon_dyn),
        guard: "active",
    },
    TableFieldInfo {
        name: "has_target",
        type_name: "bool",
        id: 0xb0a7,
        kind: 1,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "active",
    },
    TableFieldInfo {
        name: "target_id",
        type_name: "uint16",
        id: 0xdf6a,
        kind: 7,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "active && has_target",
    },
    TableFieldInfo {
        name: "idle_ticks",
        type_name: "uint32",
        id: 0x9555,
        kind: 8,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "!active",
    },
    TableFieldInfo {
        name: "samples",
        type_name: "uint16",
        id: 0xaf9a,
        kind: 7,
        is_array: true,
        counted: true,
        array_bound: 8,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
];

static TABLE_TYPE_PROBE_SAMPLE: TableTypeInfo = TableTypeInfo {
    name: "ProbeSample",
    fields: TABLE_TYPE_PROBE_SAMPLE_FIELDS,
};

/// Returns `ProbeSample`'s reflection descriptor — field names, wire ids/kinds,
/// bounds, ranges, enum names and branch guards. Static data: no
/// per-instance cost and no lazy initialization.
pub fn table_type_probe_sample() -> &'static TableTypeInfo { &TABLE_TYPE_PROBE_SAMPLE }

static TABLE_TYPE_PROBE_CONFIG_FIELDS: &[TableFieldInfo] = &[
    TableFieldInfo {
        name: "retries",
        type_name: "int32",
        id: 0x460c,
        kind: 4,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "preferred",
        type_name: "Weapon",
        id: 0x3982,
        kind: 6,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: 15,
        enum_name: Some(enum_name_weapon_dyn),
        guard: "",
    },
];

static TABLE_TYPE_PROBE_CONFIG: TableTypeInfo = TableTypeInfo {
    name: "ProbeConfig",
    fields: TABLE_TYPE_PROBE_CONFIG_FIELDS,
};

/// Returns `ProbeConfig`'s reflection descriptor — field names, wire ids/kinds,
/// bounds, ranges, enum names and branch guards. Static data: no
/// per-instance cost and no lazy initialization.
pub fn table_type_probe_config() -> &'static TableTypeInfo { &TABLE_TYPE_PROBE_CONFIG }

static TABLE_TYPE_PROBE_ARRAY_FIELDS: &[TableFieldInfo] = &[
    TableFieldInfo {
        name: "samples",
        type_name: "ProbeSample",
        id: 0xaf9a,
        kind: 13,
        is_array: true,
        counted: false,
        array_bound: 2,
        table: Some(&TABLE_TYPE_PROBE_SAMPLE),
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "config",
        type_name: "ProbeConfig",
        id: 0x4538,
        kind: 13,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: Some(&TABLE_TYPE_PROBE_CONFIG),
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
];

static TABLE_TYPE_PROBE_ARRAY: TableTypeInfo = TableTypeInfo {
    name: "ProbeArray",
    fields: TABLE_TYPE_PROBE_ARRAY_FIELDS,
};

/// Returns `ProbeArray`'s reflection descriptor — field names, wire ids/kinds,
/// bounds, ranges, enum names and branch guards. Static data: no
/// per-instance cost and no lazy initialization.
pub fn table_type_probe_array() -> &'static TableTypeInfo { &TABLE_TYPE_PROBE_ARRAY }

static TABLE_TYPE_TEST_DATA_FIELDS: &[TableFieldInfo] = &[
    TableFieldInfo {
        name: "a",
        type_name: "int32",
        id: 0xcd20,
        kind: 4,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: true,
        range_min: -100.0,
        range_max: 100.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "b",
        type_name: "int32",
        id: 0xcae9,
        kind: 4,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: true,
        range_min: -100.0,
        range_max: 100.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "c",
        type_name: "int32",
        id: 0xca5e,
        kind: 4,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: true,
        range_min: -100.0,
        range_max: 150.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "d",
        type_name: "bits8",
        id: 0xc57f,
        kind: 6,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "e",
        type_name: "bits8",
        id: 0xc2ec,
        kind: 6,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "f",
        type_name: "bits8",
        id: 0xc495,
        kind: 6,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "g",
        type_name: "bool",
        id: 0xc40a,
        kind: 1,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "items",
        type_name: "int32",
        id: 0x09f6,
        kind: 4,
        is_array: true,
        counted: true,
        array_bound: 16,
        table: None,
        has_range: true,
        range_min: 0.0,
        range_max: 255.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "float_value",
        type_name: "float32",
        id: 0xbbaf,
        kind: 10,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "compressed_float_value",
        type_name: "float32",
        id: 0x8aa5,
        kind: 10,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: true,
        range_min: 0.0,
        range_max: 10.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "double_value",
        type_name: "float64",
        id: 0x6a50,
        kind: 11,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "int8_value",
        type_name: "int8",
        id: 0x6592,
        kind: 2,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "int16_value",
        type_name: "int16",
        id: 0x68f3,
        kind: 3,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "uint8_value",
        type_name: "uint8",
        id: 0x5645,
        kind: 6,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "uint16_value",
        type_name: "uint16",
        id: 0xd185,
        kind: 7,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "uint32_value",
        type_name: "uint32",
        id: 0x3ba7,
        kind: 8,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "uint64_value",
        type_name: "uint64",
        id: 0xc4d6,
        kind: 9,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "int64_full",
        type_name: "int64",
        id: 0xc2b7,
        kind: 5,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "int64_range",
        type_name: "int64",
        id: 0xab05,
        kind: 5,
        is_array: false,
        counted: false,
        array_bound: 0,
        table: None,
        has_range: true,
        range_min: -1e+12,
        range_max: 1e+12,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "fixed_bytes",
        type_name: "uint8",
        id: 0x14fc,
        kind: 6,
        is_array: true,
        counted: false,
        array_bound: 17,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
    TableFieldInfo {
        name: "text",
        type_name: "string",
        id: 0xf3d8,
        kind: 12,
        is_array: false,
        counted: true,
        array_bound: 255,
        table: None,
        has_range: false,
        range_min: 0.0,
        range_max: 0.0,
        enum_max: -1,
        enum_name: None,
        guard: "",
    },
];

static TABLE_TYPE_TEST_DATA: TableTypeInfo = TableTypeInfo {
    name: "TestData",
    fields: TABLE_TYPE_TEST_DATA_FIELDS,
};

/// Returns `TestData`'s reflection descriptor — field names, wire ids/kinds,
/// bounds, ranges, enum names and branch guards. Static data: no
/// per-instance cost and no lazy initialization.
pub fn table_type_test_data() -> &'static TableTypeInfo { &TABLE_TYPE_TEST_DATA }

