/* Code generated by the schema compiler from Guarded.schema. DO NOT EDIT.
   SPDX-License-Identifier: NONE — this generated output is yours, under terms of
   your choice. See the LICENSE exception in the schema compiler; the compiler is
   AGPL-3.0, its output is not.
   package tabledemo — protocol id 0x91df5fddd8edc184 (packets only: tables version by field id, not by protocol id)
   The TABLE wire (evolution-tolerant, docs/SPEC-TABLES.md): no serialize
   dependency — includable from any TU. Compile the .c beside this header
   to use the reflection descriptors or the text form. */

#ifndef SCHEMA_TABLEDEMO_GUARDEDTABLE_H
#define SCHEMA_TABLEDEMO_GUARDEDTABLE_H

#include <stdint.h>
#include <stddef.h> /* offsetof, for the reflection descriptors */
#include <string.h> /* memcpy, memset — the prefill and the wire's raw moves */
#include <assert.h> /* the keyed accessor's None refusal, in a debug build */
#include <stdlib.h> /* and its abort, which NDEBUG does not remove */

#include "Guarded.h"

#ifndef SCHEMA_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define SCHEMA_UNUSED __attribute__((unused))
#else
#define SCHEMA_UNUSED
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifndef SCHEMA_TABLEDEMO_TABLE_PRIMITIVES
#define SCHEMA_TABLEDEMO_TABLE_PRIMITIVES

/* THE CODEC DOES NOT DEPEND ON THE COMPILER'S INLINING BUDGET. A table of a
   realistic field count emits one large body per type, and the cursor a body
   writes through lives in the caller's TableWriter: across a call boundary that
   cursor round-trips through memory, and a uint8_t * store may alias the writer
   itself, so every put reloads it. When a budget runs out mid-body the codec
   silently degrades to that shape. Forcing the primitives and the fixed-class
   bodies inline is what keeps the cursor in registers and lets adjacent
   constant framing bytes merge into one store.

   The spelling is FEATURE TESTED rather than assumed, exactly as the packet
   emitter's own inlining demand is (SPEC §6.1's C column).

   IT CARRIES THE PACKAGE for the reason every other name here does, and that
   reason is the LINKER rather than the preprocessor: two units of the same
   schema family link into one program — two generations of one schema is the
   case the conformance driver itself is — so nothing this backend emits may
   be spelled the same way by two packages. They do NOT share a translation
   unit and cannot: C has no namespace, so two units' headers in one TU
   redefine TableReport, TableWriter and every other runtime name, which is the
   packet emitter's standing limit (SPEC §6.1) and not something tables
   changed. A per-package macro is what keeps the LINK legal. */
#ifndef SCHEMA_TABLEDEMO_TABLE_INLINE
#if defined( _MSC_VER )
#define SCHEMA_TABLEDEMO_TABLE_INLINE __forceinline
#elif defined( __GNUC__ ) || defined( __clang__ )
#define SCHEMA_TABLEDEMO_TABLE_INLINE inline __attribute__(( always_inline ))
#else
#define SCHEMA_TABLEDEMO_TABLE_INLINE inline
#endif
#endif

/* A COMPILE-TIME assertion under -std=c99, which has none of its own. C11's
   _Static_assert carries the message into the build log verbatim and is used
   wherever the compiler has it; everywhere else the negative array bound is
   the same refusal with a tag a reader can find. The tag is unique per record
   and field, and each record is asserted by the ONE header that declares it,
   so no two of these ever meet. */
#ifndef SCHEMA_TABLE_STATIC_ASSERT
#if defined( __STDC_VERSION__ ) && __STDC_VERSION__ >= 201112L
#define SCHEMA_TABLE_STATIC_ASSERT( tag, cond, message ) _Static_assert( cond, message )
#elif defined( __cplusplus ) && __cplusplus >= 201103L
#define SCHEMA_TABLE_STATIC_ASSERT( tag, cond, message ) static_assert( cond, message )
#else
#define SCHEMA_TABLE_STATIC_ASSERT( tag, cond, message ) typedef char schema_table_assert_##tag[ ( cond ) ? 1 : -1 ]
#endif
#endif

/* A record's ALIGNMENT, which the cook's layout contract asserts and which the
   cook's Open compares the header's alignment word against (§7.1, §20.3).
   C99 has no alignof either; C11's _Alignof, the two GNU spellings and MSVC's
   cover every compiler this repo builds under, and the last form is the
   portable definition of the same number. */
#ifndef SCHEMA_TABLE_ALIGNOF
#if defined( __STDC_VERSION__ ) && __STDC_VERSION__ >= 201112L
#define SCHEMA_TABLE_ALIGNOF( T ) _Alignof( T )
#elif defined( __GNUC__ ) || defined( __clang__ )
#define SCHEMA_TABLE_ALIGNOF( T ) __alignof__( T )
#elif defined( _MSC_VER )
#define SCHEMA_TABLE_ALIGNOF( T ) __alignof( T )
#else
#define SCHEMA_TABLE_ALIGNOF( T ) ( (size_t) offsetof( struct { char schema_pad_; T schema_member_; }, schema_member_ ) )
#endif
#endif

/* The table-wire read report — the permissive contract's ledger. Silence
   (all zero) means the data matched this reader's schema exactly. */
typedef struct TableReport
{
    int32_t unknown;       /* unknown field ids skipped (newer data) */
    int32_t kind_mismatch; /* known id, changed type — skipped, never misdecoded */
    int32_t clamped;       /* out-of-range values clamped to declared bounds */
    /* a key the TEXT form saw twice: last wins, and the repeat is counted
       (docs/SPEC-TABLES.md §16.2). The wire never raises it — a body carrying an
       id twice is legal input whose last occurrence wins, silently (§3). */
    int32_t duplicate;
    int malformed;         /* framing damage; decode stopped, partial result kept */
} TableReport;

/* ---- reflection (tables only, docs/SPEC-TABLES.md) ----

   Static field descriptors for every type in the table closure: name, wire
   id/kind, storage offset, bounds, ranges, enum names and branch guards —
   enough to walk, print, diff, edit or bind any table value at runtime with
   no schema files. <name>_table_type() returns <Name>'s descriptor. */

struct TableTypeInfo;

/* One arm of a union field: where its payload sits inside the union's storage
   and what its payload looks like. The arm's NAME and its table-wire id ride
   in the field's own vocabulary table at the same tag, so nothing is spelled
   twice (docs/SPEC-TABLES.md §8). */
typedef struct TableUnionArmInfo
{
    uint32_t offset;                    /* offsetof the arm's payload within the union storage */
    const struct TableTypeInfo * table; /* the arm payload's descriptor */
} TableUnionArmInfo;

/* A union field's shape: the tag, and the arms indexed by it. Arms run
   [0, enum_max]; index 0 is the EMPTY arm and carries no payload. */
typedef struct TableUnionInfo
{
    uint32_t tag_offset; /* offsetof the tag within the union storage */
    uint32_t tag_size;   /* sizeof the tag */
    const TableUnionArmInfo * arms;
} TableUnionInfo;

/* ONE ENTRY OF A VOCABULARY, and the whole of what C++ spells as a pair of
   captureless lambdas. An enum's values, a union's arms and a flags field's
   BITS are each a named set indexed by [0, enum_max], so the set rides as an
   ARRAY indexed the same way: no function per enum, and therefore no name per
   enum for a schema to collide with (docs/SPEC-TABLES.md §11).

   name is the variant's spelling, or NULL for a value the declared set does
   not name. id is the TABLE-WIRE id it rides under (§5) — the hash of the
   variant's name, 0 for the reserved None and for the empty union arm. A
   FLAGS field's variants are BIT POSITIONS and have no per-variant wire id
   (§4), so has_ids is 0 there and 1 for an enum and a union: a vocabulary
   with names and no ids is what says "flags". */
typedef struct TableVariantInfo
{
    const char * name;
    uint16_t id;
} TableVariantInfo;

typedef struct TableFieldInfo
{
    const char * name;      /* schema field name, e.g. "health" */
    const char * json;      /* the TEXT form's key: the json = "key" attribute, else name (§16.3) */
    const char * type_name; /* schema type name, e.g. "float32", "Grade" */
    uint16_t id;            /* table-wire field id (name hash; the was alias's hash after a rename) */
    uint8_t kind;           /* table-wire kind; for arrays/strings/bytes, the ELEMENT kind */
    int is_array;           /* fixed or counted array (bytes included) */
    int counted;            /* a _count/_length int32 companion exists (counted arrays, strings, bytes) */
    int optional;           /* a ?T field: a _present companion decides whether it rides */
    int32_t array_bound;    /* array capacity / string max length; 0 for plain scalars */
    uint32_t offset;        /* offsetof the storage member */
    uint32_t elem_size;     /* sizeof the member (element size for arrays) */
    uint32_t count_offset;  /* offsetof the _count/_length companion, or 0xffffffff */
    uint32_t present_offset; /* offsetof the _present companion, or 0xffffffff */
    const struct TableTypeInfo * table; /* nested table's descriptor, or NULL */
    int has_range;          /* a declared [min, max] (int or float) */
    double range_min;       /* NOTE: int64 ranges beyond 2^53 lose precision here */
    double range_max;
    int64_t enum_max;       /* enums: highest valid value (None = 0 always valid);
                               unions: the arm count (tag range [0, enum_max]);
                               flags: the highest declared BIT INDEX; else -1 */
    /* the vocabulary, indexed the same way enum_max bounds: an enum's value ->
       (name, id), a union's tag -> (arm name, arm id), a FLAGS field's bit
       index -> (variant name, 0). NULL for every other kind. */
    const TableVariantInfo * variants;
    int has_variant_ids;    /* 1 for an enum or a union, 0 for flags (§4) */
    /* an ENUM-KEYED array (docs/SPEC-TABLES.md §2.4): the array has one slot per
       variant of key_type_name, the key k at index k-1, and its slots ride
       under variant ids rather than positions. keys is the key's vocabulary,
       indexed by the KEY — walk [0, array_bound) and ask about index + 1 to
       print slots by name. NULL on every other field. */
    const char * key_type_name;
    const TableVariantInfo * keys;
    int64_t key_max;        /* the key enum's highest value, bounding keys */
    /* union fields: the tag and its arms. NULL for every other kind. */
    const TableUnionInfo * arms;
    const char * guard;     /* branch guard, e.g. "at_rest" or "!at_rest"; "" if unguarded */
} TableFieldInfo;

typedef struct TableTypeInfo
{
    const char * name;   /* schema type name */
    uint32_t size;       /* sizeof the storage struct */
    int32_t num_fields;
    const TableFieldInfo * fields;
    /* put one instance back at its declared defaults, in place. A generic
       walker that fills a value has to be able to establish the defaults an
       absent field takes, and it holds no type to spell — this is the one
       thing the descriptors could not express without it. It is the void *
       form of <name>_reset and the same code. */
    void (*reset)( void * storage );
} TableTypeInfo;

typedef struct TableWriter
{
    uint8_t * buffer;
    int64_t capacity;
    int64_t offset;
    int overflow;
} TableWriter;

static SCHEMA_UNUSED TableWriter table_writer_make( uint8_t * buffer, int64_t capacity )
{
    TableWriter w;
    w.buffer = buffer;
    w.capacity = capacity;
    w.offset = 0;
    w.overflow = 0;
    return w;
}

static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE void table_writer_raw( TableWriter * w, const void * data, int64_t bytes )
{
    if ( w->offset + bytes > w->capacity ) { w->overflow = 1; return; }
    memcpy( w->buffer + w->offset, data, (size_t) bytes );
    w->offset += bytes;
}
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE void table_writer_put8( TableWriter * w, uint8_t v ) { table_writer_raw( w, &v, 1 ); }
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE void table_writer_put16( TableWriter * w, uint16_t v )
{
    uint8_t b[2];
    b[0] = (uint8_t) v; b[1] = (uint8_t) ( v >> 8 );
    table_writer_raw( w, b, 2 );
}
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE void table_writer_put32( TableWriter * w, uint32_t v )
{
    uint8_t b[4];
    b[0] = (uint8_t) v; b[1] = (uint8_t) ( v >> 8 ); b[2] = (uint8_t) ( v >> 16 ); b[3] = (uint8_t) ( v >> 24 );
    table_writer_raw( w, b, 4 );
}
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE void table_writer_put64( TableWriter * w, uint64_t v )
{
    table_writer_put32( w, (uint32_t) v );
    table_writer_put32( w, (uint32_t) ( v >> 32 ) );
}
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE void table_writer_patch32( TableWriter * w, int64_t at, uint32_t v )
{
    if ( at + 4 > w->capacity ) { w->overflow = 1; return; }
    w->buffer[at] = (uint8_t) v; w->buffer[at+1] = (uint8_t) ( v >> 8 );
    w->buffer[at+2] = (uint8_t) ( v >> 16 ); w->buffer[at+3] = (uint8_t) ( v >> 24 );
}

typedef struct TableReader
{
    const uint8_t * buffer;
    int64_t size;
    int64_t offset;
    TableReport * report;
} TableReader;

static SCHEMA_UNUSED TableReader table_reader_make( const uint8_t * buffer, int64_t size, TableReport * report )
{
    TableReader r;
    r.buffer = buffer;
    r.size = size;
    r.offset = 0;
    r.report = report;
    return r;
}

static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE int table_reader_has( const TableReader * r, int64_t bytes ) { return r->offset + bytes <= r->size; }
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE uint8_t table_reader_get8( TableReader * r ) { return r->buffer[r->offset++]; }
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE uint16_t table_reader_get16( TableReader * r )
{
    uint16_t v = (uint16_t) ( (uint16_t) r->buffer[r->offset] | ( (uint16_t) r->buffer[r->offset+1] << 8 ) );
    r->offset += 2;
    return v;
}
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE uint32_t table_reader_get32( TableReader * r )
{
    uint32_t v = (uint32_t) r->buffer[r->offset] | ( (uint32_t) r->buffer[r->offset+1] << 8 )
               | ( (uint32_t) r->buffer[r->offset+2] << 16 ) | ( (uint32_t) r->buffer[r->offset+3] << 24 );
    r->offset += 4;
    return v;
}
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE uint64_t table_reader_get64( TableReader * r )
{
    uint64_t lo = table_reader_get32( r );
    uint64_t hi = table_reader_get32( r );
    return lo | ( hi << 32 );
}

/* skip one payload by kind; 0 = framing damage */
static SCHEMA_UNUSED int table_reader_skip( TableReader * r, uint8_t kind )
{
    switch ( kind )
    {
        case 1: case 2: case 6:
            if ( !table_reader_has( r, 1 ) ) { return 0; }
            r->offset += 1; return 1;
        case 3: case 7:
            if ( !table_reader_has( r, 2 ) ) { return 0; }
            r->offset += 2; return 1;
        /* 17 is a NODE INDEX (docs/SPEC-TABLES.md 3.1): four bytes, so it costs
           one row here and a reader without the kind still skips a pointer field */
        case 4: case 8: case 10: case 17:
            if ( !table_reader_has( r, 4 ) ) { return 0; }
            r->offset += 4; return 1;
        case 5: case 9: case 11:
            if ( !table_reader_has( r, 8 ) ) { return 0; }
            r->offset += 8; return 1;
        case 12: case 13: case 14: case 16:
        {
            uint32_t n;
            if ( !table_reader_has( r, 4 ) ) { return 0; }
            n = table_reader_get32( r );
            if ( !table_reader_has( r, n ) ) { return 0; }
            r->offset += n;
            return 1;
        }
        case 15: /* union: u16 arm id, then the arm length-prefixed (id 0 = empty, no body) */
        {
            uint32_t n;
            if ( !table_reader_has( r, 2 ) ) { return 0; }
            if ( table_reader_get16( r ) == 0 ) { return 1; }
            if ( !table_reader_has( r, 4 ) ) { return 0; }
            n = table_reader_get32( r );
            if ( !table_reader_has( r, n ) ) { return 0; }
            r->offset += n;
            return 1;
        }
        default: break;
    }
    return 0;
}

/* The storage index a key names, with the None refusal that stands in EVERY
   build. The storage shifts left and holds no slot for None, so a build that
   skipped this compare would index one element BEFORE the array — undefined
   behaviour in the configuration a game ships. */
static SCHEMA_UNUSED int32_t table_keyed_slot( int32_t key )
{
    if ( key == 0 )
    {
        assert( 0 && "None is the null key of an enum-keyed array: it keys no slot" );
        abort();
    }
    return key - 1;
}

/* keyed[key] — the slot a variant owns, as an LVALUE. The key is evaluated
   once. ITERATION is the surface a consumer of the whole array wants: walk
   1..E_MAX and index with the key, so a call site writes no shift. */
#define SCHEMA_TABLE_KEYED_AT( array, key ) ( (array)[ table_keyed_slot( (int32_t) ( key ) ) ] )


static SCHEMA_UNUSED float table_bits_to_float( uint32_t bits ) { float f; memcpy( &f, &bits, 4 ); return f; }
static SCHEMA_UNUSED uint32_t table_float_to_bits( float f ) { uint32_t b; memcpy( &b, &f, 4 ); return b; }
static SCHEMA_UNUSED double table_bits_to_double( uint64_t bits ) { double d; memcpy( &d, &bits, 8 ); return d; }
static SCHEMA_UNUSED uint64_t table_double_to_bits( double d ) { uint64_t b; memcpy( &b, &d, 8 ); return b; }

#endif /* SCHEMA_TABLEDEMO_TABLE_PRIMITIVES */

#ifndef SCHEMA_TABLEDEMO_BUILD_VERSION
#define SCHEMA_TABLEDEMO_BUILD_VERSION

/* THE BUILD VERSION (docs/SPEC-TABLES.md §20): one digest over every fact the bytes
   this build produces depend on — the type wire's protocol id, every record's
   layout as the compiler's own C ABI model computes it, and the facts that
   decide what a load PUTS in those slots. It is the number a cook's header
   carries and the number Open compares, and the number a block's prologue
   carries and BlockOpen compares: a build version answers "which build?" and
   not "which form?", and what separates the two forms is their MAGIC.

   There are TWO ids in the design and they are not interchangeable: the
   PROTOCOL ID is the type wire's and nothing else, and the BUILD VERSION is
   what everything cooked or blocked is keyed by. A table edit moves this and
   never the protocol id; a type edit moves both. */
#define SCHEMA_TABLEDEMO_BUILD_VERSION_VALUE 0x913551e66dc67157ull

#endif /* SCHEMA_TABLEDEMO_BUILD_VERSION */

#ifndef SCHEMA_TABLEDEMO_TABLE_COOK
#define SCHEMA_TABLEDEMO_TABLE_COOK

/* ---- the cooked form (docs/SPEC-TABLES.md §7) ----

   A cooked file is a HEADER, a DATA part and an ATTRIBUTION part, in that
   order. Every word of the header is a u64 written in the byte order the cook
   was produced in, and the header is 64 bytes:

       0  magic               0x4b4f4f434d484353, read BYTEWISE before anything else
       8  build_version       the unit's id (docs/SPEC-TABLES.md §20)
      16  byte_order          1 little, 2 big — the order that WROTE the file
      24  data_length         the region's bytes, rounded up to alignment
      32  attribution_length  the directory's bytes, or 0
      40  alignment           the region's alignment, never below eight
      48  reserved            zero
      56  reserved            zero

   The DATA part is Lock's region written verbatim (§7.2) — the root at its
   base — and it is what a runtime points at. The ATTRIBUTION part is the node
   directory (§6.3), and NOTHING THAT READS THE STRUCTURE TOUCHES IT: it is
   written beside the data for schema cook-check, so a build that ships no
   tooling need not carry it at all. */
static SCHEMA_UNUSED const int64_t table_cook_header_bytes = 64;

/* THE MAGIC'S VALUE, and a consumer written from the page needs the constant
   rather than a description of one. It is "SCHMCOOK" read as ASCII in the byte
   order a little-endian store produces — the same shape the block form's
   SCHMABLK takes, so a hex dump of a little-endian cook is legible and the two
   accelerators sit in one vocabulary.

   IT IS STORED IN THE PRODUCER'S ORDER, which is what makes it the byte-order
   check as well as the form check: a consumer reads back this build's
   constant, or that constant byte-reversed — which identifies a cook of the
   OTHER order — or something that is not a cook. All three answers but the
   first refuse, and a cook and a BLOCK are separated here too, because a
   form's identity belongs in its magic rather than in a second digest. */
static SCHEMA_UNUSED const uint64_t table_cook_magic = 0x4b4f4f434d484353ull;

/* THIS BUILD's byte order, as the header's own word carries it. The magic is
   what REFUSES a foreign order; this word is what RECORDS which order wrote
   the file, so a refusal names the order rather than inferring it and a tool
   dumping a cook reads the fact. A file whose magic matched and whose order
   word did not is corrupt, and there is no reading that recovers it.

   The BUILD VERSION cannot do either job: §20.1 digests byteorder as a
   GENERATION input, little for every target schema generates for today, so
   two builds of one schema for two orders emit the same id. */
#if defined( __BYTE_ORDER__ ) && defined( __ORDER_BIG_ENDIAN__ ) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
static SCHEMA_UNUSED const uint64_t table_cook_byte_order = 2; /* big */
#else
static SCHEMA_UNUSED const uint64_t table_cook_byte_order = 1; /* little */
#endif

/* The greatest region alignment a cooked file may name. The DATA part begins
   at align_up( 64, alignment ), which is 64 for every unit this language can
   declare — the largest alignment it has is sixteen — so a word past this cap
   describes a file no build of this schema wrote (docs/SPEC-TABLES.md §7.1). */
static SCHEMA_UNUSED const uint64_t table_cook_max_align = 64;

/* The header read, BYTEWISE. memcpy is the portable spelling of "these eight
   bytes, in this machine's order"; every compiler this repo builds under folds
   it to one load, and it is the only read in the whole of Open that is not a
   comparison. */
static SCHEMA_UNUSED uint64_t table_cook_read64( const uint8_t * p )
{
    uint64_t v;
    memcpy( &v, p, sizeof( v ) );
    return v;
}

/* table_cook_open: THE WHOLE CHECK, in one place, because §7 states the
   enumeration once and every generated <name>_open is that one enumeration plus
   its own root's two layout facts.

   THE CHECK, in order: the magic read bytewise, the byte order it establishes,
   the build version against this build's own, both RESERVED words zero, the
   region alignment the header names, the two part lengths against the length
   the caller passed — a truncated file and a file with trailing bytes are the
   same refusal — the root's own storage inside the data part, and the
   alignment of the base.

   AND THAT IS ALL OF IT. On a match the bytes ARE what this build wrote, in
   this build's layout and this build's byte order, so there is nothing to
   validate and nothing to fix up: the caller gets the root. Nothing per node
   happens here, which is what makes open O(1) in the file's size.

   EVERY NUMBER BELOW COMES OUT OF THE FILE, so the arithmetic is unsigned and
   each term is BOUNDED BEFORE IT IS ADDED: a forged length near 2^64 must
   refuse, and an addition that wrapped would be the defect the comparison
   after it was supposed to catch. Nothing past length is read on any path,
   including every refusing one. */
static SCHEMA_UNUSED const uint8_t * table_cook_open( const void * bytes, uint64_t length, uint64_t root_size, uint64_t root_align )
{
    const uint8_t * raw;
    uint64_t data_length, attribution_length, alignment, data_offset;
    const uint8_t * base;
    if ( bytes == NULL ) { return NULL; }
    if ( length < (uint64_t) table_cook_header_bytes ) { return NULL; }
    raw = (const uint8_t *) bytes;
    /* the MAGIC, bytewise and first: it is what establishes the byte order
       every other header word is read in, so nothing else may be read before
       it. A byte-reversed constant is a cook of the other order and refuses
       here, which is why the order never reaches a fix-up pass. */
    if ( table_cook_read64( raw ) != table_cook_magic ) { return NULL; }
    if ( table_cook_read64( raw + 16 ) != table_cook_byte_order ) { return NULL; }
    if ( table_cook_read64( raw + 8 ) != SCHEMA_TABLEDEMO_BUILD_VERSION_VALUE ) { return NULL; }
    /* the RESERVED words: a non-zero one means a writer used a form this build
       does not understand, and Open refuses rather than ignoring it. */
    if ( table_cook_read64( raw + 48 ) != 0 ) { return NULL; }
    if ( table_cook_read64( raw + 56 ) != 0 ) { return NULL; }
    data_length = table_cook_read64( raw + 24 );
    attribution_length = table_cook_read64( raw + 32 );
    alignment = table_cook_read64( raw + 40 );
    /* THE ALIGNMENT WORD IS DATA, and it is the one header field the rest of
       the check does arithmetic WITH rather than only comparison against. A
       region's alignment is a power of two, never below eight (the floor that
       puts the attribution part on an eight-byte boundary without a second
       padding rule) and never past the cap above; a word that is none of those
       rounds nothing and aligns nothing, so it is refused before it is used. */
    if ( alignment < 8 || alignment > table_cook_max_align ) { return NULL; }
    if ( ( alignment & ( alignment - 1 ) ) != 0 ) { return NULL; }
    /* and it must be an alignment THE ROOT CAN SIT AT, since the root is at
       the region's base: both are powers of two, so "at least the root's"
       is one division. */
    if ( ( alignment % root_align ) != 0 ) { return NULL; }
    /* The DATA part begins at align_up( 64, alignment ). It is DERIVED and not
       a header field, because a fact a reader computes is a fact two writers
       cannot disagree about. */
    data_offset = ( (uint64_t) table_cook_header_bytes + alignment - 1 ) & ~( alignment - 1 );
    if ( length < data_offset ) { return NULL; }
    /* the two part lengths against the length the caller passed. The whole
       file is data_offset + data_length + attribution_length, and a length
       that is not EXACTLY that refuses — truncation and trailing bytes are one
       refusal, and both terms are subtracted rather than added so no sum can
       carry. */
    if ( data_length > length - data_offset ) { return NULL; }
    if ( attribution_length != length - data_offset - data_length ) { return NULL; }
    /* the ROOT sits at the region's base, so the region has to hold it: a
       shorter data part describes a root partly outside the file, which is the
       one way a match-and-point reader could hand back storage it never
       received. */
    if ( data_length < root_size ) { return NULL; }
    base = raw + data_offset;
    /* the alignment of the BASE. The header pads the data part to the region's
       alignment, so a base an allocator or mmap gave you is already aligned —
       mmap gives page alignment for free — and a base that is not is a caller's
       buffer this form cannot be read out of. */
    if ( ( (uintptr_t) base % (uintptr_t) alignment ) != 0 ) { return NULL; }
    return base;
}

#endif /* SCHEMA_TABLEDEMO_TABLE_COOK */

/* table Patrol — TABLE-wire storage: relocatable, bounded. C has no member
   initializers, so the declared defaults live in patrol_reset and nowhere
   else — one definition of what a default is (docs/SPEC-TABLES.md) */
typedef struct Patrol {
    uint8_t active;

    /* active — guarded fields stay off the wire when the guard says so;
       a read's prefilled defaults stand in for the untaken side */
    float speed;
    uint8_t has_target;

    /* active && has_target — guarded fields stay off the wire when the guard says so;
       a read's prefilled defaults stand in for the untaken side */
    int32_t target_id;

    /* active && !has_target — guarded fields stay off the wire when the guard says so;
       a read's prefilled defaults stand in for the untaken side */
    float wander;

    /* !active — guarded fields stay off the wire when the guard says so;
       a read's prefilled defaults stand in for the untaken side */
    char note[8 + 1]; /* string(8): N + 1 for the terminator the wire does not carry */
    int32_t note_length;
} Patrol;

/* ---- prefill: the declared defaults, in place (docs/SPEC-TABLES.md) ---- */

static SCHEMA_UNUSED void patrol_reset( Patrol * value );
static SCHEMA_UNUSED void schema_tabledemo_patrol_reset_raw_( void * storage );

static SCHEMA_UNUSED void patrol_reset( Patrol * value )
{
    value->active = 0;
    value->speed = 1.0f;
    value->has_target = 0;
    value->target_id = 0;
    value->wander = 0.5f;
    memset( value->note, 0, sizeof( value->note ) );
    value->note_length = 0;
}

static SCHEMA_UNUSED void schema_tabledemo_patrol_reset_raw_( void * storage ) { patrol_reset( (Patrol *) storage ); }

/* ---- codecs: measure/save/load per closure member ---- */

static SCHEMA_UNUSED int64_t patrol_measure( const Patrol * value );
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE int patrol_save_body( TableWriter * w, const Patrol * value );
static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE int patrol_load_body( TableReader * r, Patrol * value );

static SCHEMA_UNUSED int64_t patrol_measure( const Patrol * value )
{
    int64_t bytes = 2; /* terminator */
    if ( value->active != 0 ) { bytes += 3 + 1; } /* active */
    if ( value->active )
    {
        if ( value->speed != 1.0f ) { bytes += 3 + 4; } /* speed */
    }
    if ( value->active )
    {
        if ( value->has_target != 0 ) { bytes += 3 + 1; } /* has_target */
    }
    if ( value->active && value->has_target )
    {
        if ( value->target_id != 0 ) { bytes += 3 + 4; } /* target_id */
    }
    if ( value->active && !value->has_target )
    {
        if ( value->wander != 0.5f ) { bytes += 3 + 4; } /* wander */
    }
    if ( !value->active )
    {
        if ( value->note_length < 0 || value->note_length > 8 ) { return -1; } /* storage invariant */
        if ( value->note_length > 0 ) { bytes += 3 + 4 + value->note_length; } /* note */
    }
    return bytes;
}

static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE int patrol_save_body( TableWriter * w, const Patrol * value )
{
    if ( value->active != 0 )
    {
        table_writer_put16( w, 0x405a ); table_writer_put8( w, 1 ); /* active */
        table_writer_put8( w, value->active ? 1 : 0 );
    }
    if ( value->active )
    {
        if ( value->speed != 1.0f )
        {
            table_writer_put16( w, 0xbc00 ); table_writer_put8( w, 10 ); /* speed */
            table_writer_put32( w, table_float_to_bits( value->speed ) );
        }
    }
    if ( value->active )
    {
        if ( value->has_target != 0 )
        {
            table_writer_put16( w, 0xb0a7 ); table_writer_put8( w, 1 ); /* has_target */
            table_writer_put8( w, value->has_target ? 1 : 0 );
        }
    }
    if ( value->active && value->has_target )
    {
        if ( value->target_id != 0 )
        {
            table_writer_put16( w, 0xdf6a ); table_writer_put8( w, 4 ); /* target_id */
            table_writer_put32( w, (uint32_t) ( value->target_id ) );
        }
    }
    if ( value->active && !value->has_target )
    {
        if ( value->wander != 0.5f )
        {
            table_writer_put16( w, 0x832f ); table_writer_put8( w, 10 ); /* wander */
            table_writer_put32( w, table_float_to_bits( value->wander ) );
        }
    }
    if ( !value->active )
    {
        if ( value->note_length < 0 || value->note_length > 8 ) { return 0; } /* storage invariant */
        if ( value->note_length > 0 )
        {
            table_writer_put16( w, 0x9da7 ); table_writer_put8( w, 12 ); /* note */
            table_writer_put32( w, (uint32_t) value->note_length );
            table_writer_raw( w, value->note, value->note_length );
        }
    }
    table_writer_put16( w, 0 ); /* terminator */
    return !w->overflow;
}

static SCHEMA_UNUSED int64_t patrol_save( const Patrol * value, uint8_t * buffer, int64_t capacity )
{
    TableWriter w = table_writer_make( buffer, capacity );
    if ( !patrol_save_body( &w, value ) ) { return -1; }
    return w.offset; /* == patrol_measure( value ) */
}

static SCHEMA_UNUSED SCHEMA_TABLEDEMO_TABLE_INLINE int patrol_load_body( TableReader * r, Patrol * value )
{
    patrol_reset( value ); /* prefill declared defaults in place, then overlay */
    for ( ;; )
    {
        uint16_t field_id;
        uint8_t kind;
        if ( !table_reader_has( r, 2 ) ) { r->report->malformed = 1; return 0; }
        field_id = table_reader_get16( r );
        if ( field_id == 0 ) { return 1; }
        if ( !table_reader_has( r, 1 ) ) { r->report->malformed = 1; return 0; }
        kind = table_reader_get8( r );
        switch ( field_id )
        {
            case 0x405a: /* active */
            {
                if ( kind != 1 )
                {
                    r->report->kind_mismatch++;
                    if ( !table_reader_skip( r, kind ) ) { r->report->malformed = 1; return 0; }
                    break;
                }
                if ( !table_reader_has( &(*r), 1 ) ) { r->report->malformed = 1; return 0; }
                value->active = table_reader_get8( &(*r) ) != 0;
                break;
            }
            case 0xbc00: /* speed */
            {
                if ( kind != 10 )
                {
                    r->report->kind_mismatch++;
                    if ( !table_reader_skip( r, kind ) ) { r->report->malformed = 1; return 0; }
                    break;
                }
                if ( !table_reader_has( &(*r), 4 ) ) { r->report->malformed = 1; return 0; }
                value->speed = table_bits_to_float( table_reader_get32( &(*r) ) );
                break;
            }
            case 0xb0a7: /* has_target */
            {
                if ( kind != 1 )
                {
                    r->report->kind_mismatch++;
                    if ( !table_reader_skip( r, kind ) ) { r->report->malformed = 1; return 0; }
                    break;
                }
                if ( !table_reader_has( &(*r), 1 ) ) { r->report->malformed = 1; return 0; }
                value->has_target = table_reader_get8( &(*r) ) != 0;
                break;
            }
            case 0xdf6a: /* target_id */
            {
                if ( kind != 4 )
                {
                    r->report->kind_mismatch++;
                    if ( !table_reader_skip( r, kind ) ) { r->report->malformed = 1; return 0; }
                    break;
                }
                if ( !table_reader_has( &(*r), 4 ) ) { r->report->malformed = 1; return 0; }
                {
                    int32_t decoded_v = (int32_t) table_reader_get32( &(*r) );
                    if ( decoded_v < 0 ) { decoded_v = 0; r->report->clamped++; }
                    else if ( decoded_v > 1000 ) { decoded_v = 1000; r->report->clamped++; }
                    value->target_id = decoded_v;
                }
                break;
            }
            case 0x832f: /* wander */
            {
                if ( kind != 10 )
                {
                    r->report->kind_mismatch++;
                    if ( !table_reader_skip( r, kind ) ) { r->report->malformed = 1; return 0; }
                    break;
                }
                if ( !table_reader_has( &(*r), 4 ) ) { r->report->malformed = 1; return 0; }
                value->wander = table_bits_to_float( table_reader_get32( &(*r) ) );
                break;
            }
            case 0x9da7: /* note */
            {
                if ( kind != 12 )
                {
                    r->report->kind_mismatch++;
                    if ( !table_reader_skip( r, kind ) ) { r->report->malformed = 1; return 0; }
                    break;
                }
                uint32_t len;
                uint32_t keep;
                if ( !table_reader_has( r, 4 ) ) { r->report->malformed = 1; return 0; }
                len = table_reader_get32( r );
                if ( !table_reader_has( r, len ) ) { r->report->malformed = 1; return 0; }
                keep = len;
                if ( keep > 8 ) { keep = 8; r->report->clamped++; }
                memcpy( value->note, r->buffer + r->offset, keep );
                value->note[keep] = 0;
                value->note_length = (int32_t) keep;
                r->offset += len;
                break;
            }
            default:
            {
                r->report->unknown++;
                if ( !table_reader_skip( r, kind ) ) { r->report->malformed = 1; return 0; }
                break;
            }
        }
    }
}

static SCHEMA_UNUSED int patrol_load( Patrol * value, const uint8_t * buffer, int64_t bytes, TableReport * report )
{
    TableReport ignored;
    TableReader r;
    memset( &ignored, 0, sizeof( ignored ) );
    r = table_reader_make( buffer, bytes, report != NULL ? report : &ignored );
    return patrol_load_body( &r, value );
}

/* ---- the cooked form: point at a cook (docs/SPEC-TABLES.md §7) ---- */

/* patrol_open: match the header and POINT. On a match the bytes ARE what this
   build wrote, in this build's layout and this build's byte order, so there
   is nothing to validate and nothing to fix up and the root comes back as it
   lies. On ANY refusal it returns NULL and the caller falls back to a wire
   load, which is the path that carries every version.

   It is O(1) IN THE FILE'S SIZE — the header and nothing per node — so a one
   megabyte cook and a one gigabyte cook open in the same time, and a mapped
   file's pages are touched only as they are used.

   Patrol IS FIXED-SIZE, so its cook is ONE REGION OF ONE NODE and not a second
   shape (§7): one struct behind the header, at the region's base, which is
   what this returns. There is no graph below it and nothing to resolve.

   There is ONE entry point and no tolerant twin: a build either wrote this
   file or it did not, and the build version is what says which. Validating a
   file whose provenance a person doubts is schema cook-check, offline, over
   the ATTRIBUTION part beside the data — a person's decision, never a
   parameter on a load. */
static SCHEMA_UNUSED const Patrol * patrol_open( const void * bytes, uint64_t length )
{
    return (const Patrol *) table_cook_open( bytes, length, (uint64_t) sizeof( Patrol ), (uint64_t) SCHEMA_TABLE_ALIGNOF( Patrol ) );
}

/* ---- relocatability: the wire is a pure length-prefixed stream AND the
   decoded storage is pointer-free — every closure type is a plain C struct
   of scalars and arrays, so instances can be memcpy'd, mmap'd, shared
   across processes, and walked through descriptor offsets. C has no way to
   put a pointer, a vtable or a non-trivial member in one of these, which is
   why the property is a fact of the language here rather than an assert.
   What IS asserted is the layout the build version was taken over. */

/* ---- the cook's layout contract (docs/SPEC-TABLES.md §20.3) ----

   The compiler derived every number below from the declaration and folded it
   into the BUILD VERSION; these asserts are this compiler saying whether it
   agrees. The model is not self-evidently right — on 32-bit System V
   alignof(uint64_t) is 4, not 8 — which is precisely why it is asserted
   rather than assumed. */
SCHEMA_TABLE_STATIC_ASSERT( Patrol_sizeof, sizeof( Patrol ) == 36, "Patrol's sizeof moved: the build version was taken over 36, so a cook of it would not be this build's file (docs/SPEC-TABLES.md §20.3)" );
SCHEMA_TABLE_STATIC_ASSERT( Patrol_alignof, SCHEMA_TABLE_ALIGNOF( Patrol ) == 4, "Patrol's alignof moved: the build version was taken over 4 (docs/SPEC-TABLES.md §20.3)" );
SCHEMA_TABLE_STATIC_ASSERT( Patrol_active_offset, offsetof( Patrol, active ) == 0, "Patrol's field active moved: the build version was taken over offset 0 (docs/SPEC-TABLES.md §20.3)" );
SCHEMA_TABLE_STATIC_ASSERT( Patrol_speed_offset, offsetof( Patrol, speed ) == 4, "Patrol's field speed moved: the build version was taken over offset 4 (docs/SPEC-TABLES.md §20.3)" );
SCHEMA_TABLE_STATIC_ASSERT( Patrol_has_target_offset, offsetof( Patrol, has_target ) == 8, "Patrol's field has_target moved: the build version was taken over offset 8 (docs/SPEC-TABLES.md §20.3)" );
SCHEMA_TABLE_STATIC_ASSERT( Patrol_target_id_offset, offsetof( Patrol, target_id ) == 12, "Patrol's field target_id moved: the build version was taken over offset 12 (docs/SPEC-TABLES.md §20.3)" );
SCHEMA_TABLE_STATIC_ASSERT( Patrol_wander_offset, offsetof( Patrol, wander ) == 16, "Patrol's field wander moved: the build version was taken over offset 16 (docs/SPEC-TABLES.md §20.3)" );
SCHEMA_TABLE_STATIC_ASSERT( Patrol_note_offset, offsetof( Patrol, note ) == 20, "Patrol's field note moved: the build version was taken over offset 20 (docs/SPEC-TABLES.md §20.3)" );

/* ---- reflection descriptors (tables only, docs/SPEC-TABLES.md) ----

   The descriptors are CONSTANT data DEFINED in GuardedTable.c: a translation
   unit that includes this header for the wire codecs pays nothing for
   them, and one definition per program means one address per type. The
   whole reflection surface is immutable — read it from any thread, any
   time. */

extern const TableTypeInfo schema_tabledemo_patrol_info_;

static SCHEMA_UNUSED const TableTypeInfo * patrol_table_type( void ) { return &schema_tabledemo_patrol_info_; }

/* ---- the text form (docs/SPEC-TABLES.md §16) ---- */

/* Patrol in and out of a JSON text — one instance, one text, the generic
   walk over this type's descriptors (docs/SPEC-TABLES.md §16). Defined in
   GuardedTable.c; compile it to use them. */
int schema_tabledemo_patrol_from_json_( Patrol * value, const char * text, int64_t bytes, TableReport * report );
int64_t schema_tabledemo_patrol_to_json_( const Patrol * value, char * buffer, int64_t capacity );
static SCHEMA_UNUSED int patrol_from_json( Patrol * value, const char * text, int64_t bytes, TableReport * report )
{
    return schema_tabledemo_patrol_from_json_( value, text, bytes, report );
}
static SCHEMA_UNUSED int64_t patrol_to_json_measure( const Patrol * value ) { return schema_tabledemo_patrol_to_json_( value, NULL, 0 ); }
static SCHEMA_UNUSED int64_t patrol_to_json( const Patrol * value, char * buffer, int64_t capacity )
{
    return schema_tabledemo_patrol_to_json_( value, buffer, capacity );
}


#ifdef __cplusplus
}
#endif

#endif /* SCHEMA_TABLEDEMO_GUARDEDTABLE_H */
